grommet/grommet

test/components/RadioButton-test.js

Hi Grommet Team,
I've added tests for the RadioButton.

Added tests for RadioButton.

---

README.md

Adding code Climate badge to readme: [![Code Climate](https://codeclimate.com/github/HewlettPackard/grommet/badges/gpa.svg)](https://codeclimate.com/github/HewlettPackard/grommet)
Code Climate provide useful code analysis to the project. It can help improving the quality of the code. :)

Adding public code-climate badge to readme.

---

src/js/components/Login.js

Check if this.props.background is truthy before adding event listener for 'resize' event
Signed-off-by: Tobias Kahse <tobias.kahse@hp.com>

Solve issue #51

---

docs/gulpfile.js
docs/src/Home.js
docs/src/downloads/Content.htm
examples/server/server.js

I'm submitting this as a PR to make sure the express config is done in an optimal way...being an express newb.
Tested the results of all download files in Safari and Chrome on Mac.

Moved design files into separate folder and improved ai downloads

---

.travis.yml
e2e/docs-assets-test.js
gulpfile.js

added working e2e to travis. Still need to integrate sauce labs though.

Travis e2 e integration

---

docs/src/documentation/GetStarted.htm

Updated the documentation with the correct minimal version for Node and some more few tips on the installation process.

Update on Get Started documentation page.

---

src/scss/hpe/_hpe.defaults.scss
src/scss/hpinc/_hpinc.defaults.scss

This PR aims to add path variables on where to download the fonts.
Also, this PR also changes the font path of HPinc from local to CDN.

Added font paths variable and CDN for hpinc.

---

src/js/components/icons/status/Disabled.js
src/js/components/icons/status/ErrorStatus.js
src/js/components/icons/status/OK.js
src/js/components/icons/status/Unknown.js
src/js/components/icons/status/Warning.js
test/components/icons/Status-test.js

Added titles and web aria roles for improved accessibility of status icons.

Added titles to status icons for accessibility

---

src/js/components/Table.js

This patch adds a property onSelect. If you select a row, then the
callback function gets called with the react row node as first argument.

issue #99: Table does not handle onSelection property as documented

---

src/js/mixins/KeyboardAccelerators.js

This PR refactors the KeyboardAccelerators so we have better control on the keyboard events. The previous implementation added multiple listeners to keyup and keydown on window. As we don't have control on the order that the browser call the listeners, it was not possible to manage the same key event on different components.
This implementation adds only one listener and the multiple components are managed on the KeyboardAccelerators itself.
Improvements to this PR are welcome =)
More information on: [Bubbling and capturing](http://javascript.info/tutorial/bubbling-and-capturing)

Refactoring on KeyboardAccelerators to avoid multiple keypress events.

---

docs/src/develop/components/TableDoc.js
src/js/components/Table.js

The onSelect callback is only called if the table is selectable.
The doc now mentions all available options.

Table: onClick honors selectable; fixed doc

---

src/js/components/Menu.js
src/js/mixins/KeyboardAccelerators.js
src/scss/grommet-core/_objects.menu.scss

Added keyboard navigation (up and down arrow keys) to the Menu drop window.

Added keyboard navigation to Menu component.

---

docs/src/develop/Accessibility.js
docs/src/develop/Develop.js

Added accessibility information about Icons, Lang attr, Menu and Skip Links in documentation.

Accessibility documentation.

---

docs/src/develop/components/CheckBoxDoc.js
src/js/components/CheckBox.js
src/js/components/Menu.js
src/js/components/icons/Filter.js
src/js/components/index/IndexFilters.js
src/js/messages/en-US.js
src/js/messages/pt-BR.js
src/scss/grommet-core/_objects.index.scss

This PR improves the screen reader support for the Menu component.
- the 'menu' and 'menuitem' roles were added.
- aria-expanded, aria-selected and aria-activedescendant attributes added

Added aria attributes to Menu component to support screen readers.

---

src/js/components/Footer.js
src/scss/grommet-core/_objects.article.scss
src/scss/grommet-core/_objects.footer.scss

Adding support to float Footer component similar to the way we float header.

Added float support for footer

---

docs/src/develop/components/LoginFormDoc.js
src/js/components/LoginForm.js

Please note, I am having build issues locally with scss-lint so I only made it past the jslint checks.

Enabled input type configuration on login form

---

docs/README.md
docs/aruba/gulpfile.js
docs/gulpfile.js
docs/src/Home.js
docs/src/index.js
docs/src/scss/index-aruba.scss
gulpfile-grommet-dist.js
server/docs.js
src/scss/aruba/_aruba.defaults.scss
src/scss/aruba/index.scss

Signed-off-by: Bryan Jacquot <jacquot@hp.com>

Added theme for Aruba.

---

bin/grommet.js
docs/src/develop/GetStarted.htm

Signed-off-by: Ioan Eugen Stan <ieugen@apache.org>

Added information about NODE_PATH issue

---

examples/todo-app-modular/src/js/components/TodoAddTaskForm.js
src/js/components/Button.js

Signed-off-by: Bryan Jacquot <jacquot@hp.com>

Changed propTypes for button type to use oneOf and update example

---

docs/src/develop/components/BoxDoc.js
docs/src/develop/components/MenuDoc.js
src/js/components/Box.js

Signed-off-by: Bryan Jacquot <jacquot@hp.com>

Cleaned up docs for alignment of menus and fixed align props on Box

---

docs/src/DocsSplit.js
docs/src/design/Showcase.htm

Fixes the hashtag references and the login.png reference

Link Fixes

---

test/components/Checkbox-test.js
test/components/RadioButton-test.js
test/components/Search-test.js

I've added basic tests for RadioButton, CheckBox, and Search. The following test cases are covered:
* RadioButton
* Check disabled state
* Check assignment of custom class
* CheckBox
* Check disabled state
* Check assignment of custom class (this is just a fix for the existing test case which didn't check for the assigned custom class)
* Search
* Check basic initialization (including that the `inline` property is `false` by default)
* Check assignment of custom class
* Check large search
* Check inline search

Added tests

---

src/utils/gulp/gulp-tasks-linters.js

Linters should print all the issues found instead of failing out at the first one.

Linters should fail at end

---

docs/src/develop/GetStarted.htm

Fix #200 Signed-off-by:Ben Harris <benjamin.d.harris@Hp.com>

Add windows dependencies to GetStarted page.

---

src/js/components/Button.js

button component will now have the disabled attribute added to the button element it when styled as disabled.

Added html disabled attribute to the button element.

---

src/js/components/Calendar.js

The prev logic was a XOR operation using two 'if' statements, but in the first one it as always passing undefined to activation function. It was replaced to use only one if statement to have the same XOR operation and now it's passing the not undefined value to the activation function.

prevState was never being passed to the activation function

---

src/js/components/Menu.js
src/scss/grommet-core/_objects.drop.scss
src/scss/grommet-core/_objects.menu.scss

https://trello.com/c/Bk5CZPJ5/326-drop-alignment-with-header-containing-menu
I believe I've addressed the requested fixes. I'm having a hard time testing this from within the grommet repo since the docs are moved out - is there a good way to do this @alansouzati?
@ericsoderberghp: let me know if this is what you had in mind

Drop alignment with Header containing Menu

---

src/js/components/Layer.js

Signed-off-by: Primoz Susa <primoz.susa@gmail.com>

React router needs history object. #234.

---

src/js/components/Chart.js

Fix issue #266: Bar Charts xAxis ({ Placement: Bottom }) not working correctly
Issue:
Fix:
Signed-off-by: Stephane Bochet s.bochet1@gmail.com

Fix issue #266: Bar Charts xAxis ({ Placement: Bottom }) not working correctly

---

.codeclimate.yml

medium-app no longer exists in this repo since 7953b12cf722cd1e7da33675fd07cc88d59be0e5

Remove path referencing medium-app

---

src/js/utils/Locale.js

Can you check and give some feedback?

Locale refactoring

---

package.json
src/utils/gulp/gulp-tasks.js

Fix problem with Hot Reload #275

Fix problem with Hot Reload #275

---

src/js/components/FormattedMessage.js
src/js/components/LoginForm.js

Fix `Uncaught Invariant Violation: [React Intl] An `id` must be provided to format a message.`

---

src/js/components/CheckBox.js
src/js/components/LoginForm.js
src/scss/grommet-core/_objects.check-box.scss

Enable to get the value of remember me field on submit

---

src/js/components/LoginForm.js

Add `defaultValues` prop to LoginForm component to populate username and remember me fields

---

src/js/components/Tag.js
src/js/components/Tags.js
src/scss/grommet-core/_objects.scss
src/scss/grommet-core/_objects.tag.scss

- Adds Tags and Tag components as an easy and user-friendly way to quickly generate a list of tags
- Tags component mainly wraps the Box component
- Tag component mainly wraps the Anchor component

Tags/Tag Components

---

package.json
src/js/components/Anchor.js

Also adds `classnames` package to make `className` generation more easier and cleaner.

Convert Anchor to a stateless function

---

src/js/components/Attribute.js

Convert Attribute to a stateless function

---

src/js/components/Brick.js
src/js/components/Bricks.js

Convert Brick to a stateless function

---

src/js/components/Button.js
src/js/components/Menu.js
src/js/components/Search.js

Convert Button to a stateless function

---

src/js/components/Anchor.js

Allows developer to set different icons for the Primary anchor. (Based on icon names in index-icons).

adding customIcon prop to Anchor component

---

src/js/components/Carousel.js
src/scss/grommet-core/_objects.carousel.scss

Fixes Carousel component for phone size.

Responsive fixes for the Carousel component

---

src/js/components/Footer.js
src/js/utils/Props.js

Convert Footer to a stateless function

---

src/js/components/Form.js
src/js/components/FormFields.js

Convert Form to a stateless function

---

src/js/components/FormattedMessage.js

Convert FormattedMessage to a stateless function

---

src/js/components/Headline.js

Convert Headline to a stateless function

---

src/js/components/Image.js

Convert Image to a stateless function

---

src/js/components/ListItem.js

Convert ListItem to a stateless function

---

src/js/components/Notification.js

Convert Notification to a stateless function

---

src/js/components/Paragraph.js

Convert Paragraph to a stateless function

---

src/js/components/RadioButton.js

Convert RadioButton to a stateless function

---

src/js/components/Section.js

Convert Section to a stateless function

---

src/js/components/Sidebar.js

Convert Sidebar to a stateless function

---

src/js/components/SkipLinkAnchor.js

Convert SkipLinkAnchor to a stateless function

---

src/js/components/TableRow.js

Convert TableRow to a stateless function

---

src/js/components/Anchor.js
src/scss/grommet-core/_objects.anchor.scss

Updating anchor so if icon + label props are used (without primary prop), anchor gets styled appropriately, without primary anchor hover transition.

Anchor updates

---

src/js/components/Box.js
src/js/utils/KeyboardAccelerators.js

adding sanity check for keyboardaccelerators, and 'none' as option for box separator prop

Quelching BC Console Errors: Box Separator + KeyboardAccelerators

---

src/js/components/Menu.js

If child is null or a builtin component, type is either undefined or string, not a function:
```
Uncaught TypeError: Cannot read property 'type' of null
```
```
Uncaught TypeError: Cannot read property '_renderMenuDrop' of undefined
```

Better child.type detection when putting nested menus inline

---

src/js/components/SearchInput.js

highlighted selected suggestion drop: https://github.com/grommet/grommet/issues/396

SearchInput: highlighting selected suggestion drop, and converting to use classnames/string templates

---

src/scss/grommet-core/_objects.search-input.scss

issue: https://github.com/grommet/grommet/issues/418

SearchInput icon/input text overlap

---

src/js/components/Image.js
src/scss/grommet-core/_objects.image.scss
src/utils/gulp/gulp-tasks-dev.js

Proposed approach to add support for caption for Image component.

Image caption support

---

src/scss/grommet-core/_base.text.scss

For PR: https://github.com/grommet/grommet-docs/pull/37 (Issue: https://github.com/grommet/hpe-design/issues/19)

making top and bottom margins for blockquote tags even

---

src/js/components/Anchor.js
src/scss/grommet-core/_objects.anchor.scss

Adds animateIcon prop to Anchor component to allow anchors to have the `primary` style with no icon transition animation.

Adds animateIcon prop to Anchor component.

---

src/scss/grommet-core/_objects.form-field.scss

Issue: https://github.com/grommet/grommet-estories/issues/41

Changing border color of form fields to lighter color when in a dark bg context

---

src/js/components/SocialShare.js

Supports Facebook, Twitter, LinkedIn, and Google Plus social media sharing.

Adds social media share icon button component

---

src/js/components/FormField.js
src/scss/grommet-core/_objects.form-field.scss

* styling input/anchor inside FormField when wrapped in Box (removing outlines from input, removing underline from anchor)
* adding strong (font-weight) option to FormField

FormField strong option + styling

---

src/js/components/Article.js

Fixes an issue where the last page in the set of articles cannot be navigated to by clicking on the next button.
@ericsoderberghp As far as I know everything works, however since I'm not as familiar with the expected functionalities of the Article component, could you please let me know if anything doesn't work as expected?  Thanks!

Article Component last page navigation

---

gulpfile.babel.js

Updated the gulpfile.babel.js and removed reference to docs folder in core repo.

Updated gulpfile "gulp dev" console message

---

src/scss/grommet-core/_objects.video.scss
src/scss/grommet-core/_settings.color.scss

…ects.video) + (2) removing variable-exists conditional (settings.color) to bypass node-sass errors

node-sass errors with objects.video and settings.color

---

src/js/components/Article.js
src/js/utils/DOM.js

Proposed version to manage hidden focusable elements for article

Avoid focus on hidden elements for Article control step

---

src/js/components/Box.js
src/js/utils/Props.js

I would find it very convenient to be able to use style property on Box or related components. 
What do you think?
Cheers

Transfer props to Box

---

src/js/components/Meter.js
src/scss/grommet-core/_objects.meter.scss
src/scss/grommet-core/_settings.defaults.scss
src/scss/grommet-core/_settings.font.scss

* also adding responsive option so large and xlarge Meters can shrink to medium size on mobile.
Issue: https://github.com/grommet/grommet-estories/issues/160

X-Large Meter Option

---

src/js/components/Heading.js
src/scss/grommet-core/_objects.heading.scss

Adds uppercase property to heading to handle use case if user wants to transform heading into all uppercase. Adds heading--uppercase class to tag if property is true

Adds uppercase property to Heading component

---

src/js/components/ListItem.js
src/js/components/TableRow.js
src/js/components/Tile.js

For ListItem, TableRow, & Tile.

Change console.log -> console.warn

---

src/scss/grommet-core/_objects.box.scss

Signed-off-by: Michael Gilley <michaelgilley@gmail.com>
ref: #600

Fixes IE11 aligning content in center

---

src/scss/grommet-core/_objects.header.scss

Signed-off-by: Michael Gilley <michaelgilley@gmail.com>
Fix for #614

Vertically center fix for IE11

---

src/js/components/SearchInput.js

When click the search icon, alert error message as below, cause there is no props.suggestions
SearchInput.js:161 Uncaught TypeError: Cannot read property 'map' of undefined

Check if props.suggestions exist

---

src/scss/grommet-core/_base.text.scss
src/scss/grommet-core/_settings.font.scss

https://github.com/grommet/grommet/issues/575

Update css font stack for code snippets

---

src/js/components/Split.js

This closes #460
Signed-off-by: Oscar Linde <lindeoscar@gmail.com>

Fixes Split causing remount on responsive event

---

test/components/Tabs-test.js

Added tests for tabs.

---

src/js/components/CheckBox.js

transfer props for CheckBox #467

---

src/js/components/Video.js

Docs: https://github.com/grommet/grommet-docs/pull/60

Enhances Video component with new props: autoPlay, loop, muted, showControls

---

package.json
src/js/components/Accordion.js
src/js/components/AccordionPanel.js
src/js/components/Collapsible.js
src/js/utils/CSSClassnames.js
src/scss/grommet-core/_objects.accordion-panel.scss
src/scss/grommet-core/_objects.accordion.scss
src/scss/grommet-core/_objects.collapsible.scss
src/scss/grommet-core/_objects.scss

Add Accordion component.
Check out `Accordion`, then `AccordionPanel`, then `Collapsible`.
Tested on grommet-docs https://github.com/grommet/grommet-docs
Fire up grommet-docs & test in Accordion component doc page
Already did. See grommet/grommet-docs#62. 😄 
Sure.

Proposing Accordion component

---

src/scss/grommet-core/_objects.carousel.scss

Fixes #703.
Cross-browser & responsive.
Set up Layer with Carousel component inside it. 
```
<Layer> 
<Carousel>
</Carousel>
</Layer> 
```
#703.

Fix Carousel not showing up in Layer

---

package.json
src/js/components/Animate.js
src/scss/grommet-core/_base.animation.scss

This will allow components to transition in & out.
Examples can be found at grommet/grommet-docs#59.

Proposing Animate component

---

src/js/components/Accordion.js
src/js/components/Collapsible.js
test/components/Accordion-test.js

Fix for active Accordion not starting opened
components/Accordion.js
Started some basic Accordion tests
Create an Accordion with tag active
Yes, will submit another PR

Fix for active Accordion not starting opened

---

src/js/components/Tabs.js

Add ability to programmatically change the active Tab
Tabs.js

Add ability to programmatically change the active Tab

---

src/js/components/Article.js

Adds onProgress property to Article component. This property expects a function to which it will return a percentage value of how far the user has scrolled in the Article.
Tested row and column directional layouts with their corresponding mobile responds.
Manually testing this in a basic Grommet app would look like the following: 
```
// In your component class.
_onProgress(progressPercent) {
console.log(`Article Progress: ${progressPercent}`);
}
// In your render method.
<App>
<Article scrollStep={false} onProgress={this._onProgress}>
<Box full={true} />
<Box full={true} />
</Article>
</App>
```
Tracking progress has been an integral component in our infographic work, this feeds directly to a progress bar which generally lives in the infographic's header.
The Article must be the main …

Added progress functionality to Article.

---

src/scss/grommet-core/_objects.box.scss

Resolves #759 
See repro steps in issue

add flex-shrink to justify-center box

---

src/js/components/Box.js

Allows Box to use values with or without url() for the texture prop

---

package.json
test/components/Anchor-test.js
test/components/Attribute-test.js
test/components/Search-test.js
test/components/Tabs-test.js

Enzyme is a JavaScript Testing utility for React that makes it easier to assert, manipulate, and traverse your React Components' output.

Adding Enzyme as testing utility

---

src/scss/grommet-core/_objects.icon.scss

Removes pointer cursor for icons that are not within another component such as Anchor or Button that will cause the cursor to change to a pointer.
Tested in local dev environment with grommet-docs.  Before change, cursor changes to pointer.  After change, cursor does not change.   Cursor does change on Icon page when used in conjunction with a Button, as intended.
With Grommet docs or in any other app that uses icons.
#803 
No
No
Signed-off-by: Bryan Jacquot <jacquot@hpe.com>

Removed pointer cursor

---

src/js/components/Card.js
src/scss/grommet-core/_base.text.scss
src/scss/grommet-core/_objects.card.scss
src/scss/grommet-core/_objects.label.scss
src/scss/grommet-core/_objects.paragraph.scss

Merge Stack component with Card component.
#810 
Yes, will submit another PR to grommet-docs for that.
Yes.

Merge Stack with Card component

---

__tests__/components/Card-test.js
__tests__/components/__snapshots__/Card-test.js.snap
__tests__/components/__snapshots__/SocialShare-test.js.snap

It adds a Test for the Card component and it fixes a minor test issue from #819 
__tests__/components/Card-test.js
and
__tests__/components/__snapshots__/Card-test.js.snap
and
__tests__/components/__snapshots__/SocialShare-test.js.snap
Ran the entire test suite.  There is still one failing test, the Carousel test. Hopefully that can be fixed by someone more familiar with the project.
Not needed, just need to run the test suite once pulled into Master.
I have volunteered to write tests and was asked by @alansouzati to do them one at a time as to not overlap with his test writing.
N/A
N/A
N/A
N/A

Card test and small fix for SocialShare tests

---

__tests__/components/Animate-test.js
__tests__/components/Bricks-test.js
__tests__/components/__snapshots__/Animate-test.js.snap
__tests__/components/__snapshots__/Bricks-test.js.snap

It adds a component test for the Animate component, including 4 test cases.
It also adds a component test for Bricks / Brick components, with 4 test cases.
Note: these were seperate commits, but github is adding them together into one PR.
_tests__/components/Animate-test.js
and
__tests__/components/Bricks-test.js
Ran the unit tests before and after creating the snapshots to ensure that they passed with the new snapshots.
Running the unit tests, or CI.
N/A
N/A
N/A
N/A
No

Test: add test for Animate component with multiple test cases and snaps

---

__tests__/components/__snapshots__/Carousel-test.js.snap

Fixed Carousel component test's snapshot

Fixed Carousel component test's snapshot

---

__tests__/components/__snapshots__/Card-test.js.snap
src/js/components/Card.js
src/scss/grommet-core/_objects.card.scss
src/scss/grommet-core/_objects.columns.scss

Simplifies the implementation of Card and uses more standard Grommet styling.
Card.js.
See the card-diet branch of grommet-docs. Visual comparison between the new Card docs and the old ones.
Eventually with BrandCentral and eStories.
Yes
Yes.

Refactored Card to be simpler and use more standard Grommet styling.

---

src/js/components/meter/Circle.js
src/js/components/meter/Graphic.js

Fixes #789. This fix will get rid of the gap & perfectly fill the circle all the way around.
[CodePen](http://codepen.io/alansouzati/pen/vXOxvB?editors=1010#0)
#789

Fix #789, gap in circle meter component

---

src/js/components/Video.js
src/js/components/video/Controls.js
src/js/components/video/Overlay.js
src/js/components/video/ProgressBar.js
src/js/components/video/Time.js
src/js/utils/FormatTime.js

Make suggested changes from Alan in PR #863.
Bring back old props & add deprecation messages #845
Tested on grommet-docs https://grommet.github.io/docs/video/examples/#4
PR #863 
Issue #845 & #809
Yes.
Yes.

Video component updates & deprecated props

---

src/js/utils/DOM.js
src/scss/grommet-core/_objects.layer.scss
src/scss/grommet-core/_objects.tile.scss

Fix Tiles infinite scroll in Layer component.
Resolves #799. 
This bug happens when you're using Tiles infinite scroll in a Layer component. When Tiles is not in a Layer component, infinite scroll works perfectly. The problem is Tiles height doesn't grow within Layer.
http://codepen.io/epilande/pen/gwrGGy?editors=0110
http://codepen.io/epilande/pen/LRkzLm?editors=0110
#799.

Fix Tiles infinite scroll in Layer component

---

src/scss/grommet-core/_objects.pulse.scss

Fixed a typo in the Pulse scss which was not in the original commit.

Fixed typo in Pulse scss.

---

__tests__/components/Timestamp-test.js
__tests__/components/__snapshots__/Timestamp-test.js.snap
src/js/components/Timestamp.js

This PR adds seconds to the Timestamp component as well as a test for the seconds property. This PR references issue [#59] (https://github.com/grommet/grommet-index/issues/59) on grommet-index.

Added seconds to Timestamp.

---

__tests__/components/Article-test.js
__tests__/components/__snapshots__/Article-test.js.snap
src/js/components/Article.js

This PR adds `classnames` to the Article component and updates the Article component's tests to include a test for microdata properties and custom class names.

Updated Article component with classnames

---

__tests__/components/Carousel-test.js
__tests__/components/__snapshots__/Carousel-test.js.snap
src/js/components/Carousel.js

This PR updates the Carousel component to transfer properties to the DOM element which refers to issue #85. The PR also adds additional tests and brings the Carousel in line with our consistent component structure.

Transfer Carousel component props.

---

src/scss/grommet-core/_objects.chart.scss

Fixes a bug in the Axis component which was not allowing tick marks to render properly on dark backgrounds.

Updated Axis dark context.

---

src/js/utils/Announcer.js

Fix exceptions when using Toast without having App

---

__tests__/components/Collapsible-test.js
__tests__/components/__snapshots__/Collapsible-test.js.snap

Add test
Test files
Collapsible component
No UI changes
No
No
No

Collapsible: added tests.

---

src/js/components/Anchor.js

Anchor: Fix onClick to only work if the anchor is not disabled #1072

---

src/js/components/TextInput.js

See Issue #1095 for more details

Fix Issue #1095 : TextInput suggestions appears on unfocused TextInput

---

src/js/components/Topology.js

Signed-off-by: Sorin Davidoi <sorin.davidoi@gmail.com>
Fix a crash in the `Topology` component (#1194).
Made the same change to my local grommet installation (in `node_modules`), which fixed the issue.
I guess it should be build and then check if the new bundled version does no longer crash the Codepen mentioned in the issue.
No,
#1194
No.
Yes.

fix(components/topology): Undefined variable

---

src/js/components/Tabs.js

Resolves #1159 
`src/components/Tabs.js`
Manual UI testing
Try to render something with a conditional tab. eg,
```jsx
<Tabs>
{ false && <Tab title="Conditionally rendered">Content</Tab> }
<Tab title="Always rendered">Content</Tab>
</Tabs>
```
#1159

bail on processing Tab props if child is falsey (#1159)

---

src/js/components/WorldMap.js
src/scss/grommet-core/_objects.world-map.scss

Adds `places` to WorldMap.
Really need to look at all of how WorldMap was changed.
Enhanced WorldMapExamplesDoc.
Use documentation site.
Added for a new HPE product.
Yes.
Yes.

Added places to WorldMap.

---

__tests__/components/__snapshots__/Carousel-test.js.snap
src/js/components/Carousel.js
src/scss/grommet-core/_objects.carousel.scss

Changed class on creation and added at first user interaction
Solves the issue #1374
See the issue
Automated testing updated and  manual testing
Yes, for autoplay
No, it's just a fix
It's just a fix
Backward compatible

Fix for #1374

---

package.json
src/js/components/Animate.js
src/js/components/Collapsible.js
yarn.lock

Deprecated package react-addons-transition-group replaced with new one

---

src/js/components/TextInput.js

Related to #1409 
Fix the caret position bug described in #1409 
https://github.com/grommet/grommet/issues/1409
None, local testing.
I can provide test case.
See https://github.com/grommet/grommet/issues/1409
https://github.com/grommet/grommet/issues/1409
No

fix: temporarily fix TextInput due to react bug

---

__tests__/components/__snapshots__/RadioButton-test.js.snap
__tests__/components/__snapshots__/Select-test.js.snap
src/js/components/RadioButton.js

Fixing clicking issues with radio button
The label has been moved to wrap the component and it respect the wcag requirement.
Fix a clicking issue when click directly on the radiobutton
Distribution build and test locally plus the coverage test
Compatible

Fixing clicking issues with radio button

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/box/Box.js
src/js/components/box/StyledBox.js
src/js/components/box/__tests__/Box-test.js
src/js/components/box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/box/doc.js
src/js/components/box/index.js
src/js/components/index.js
yarn.lock

Initial Box

---

src/js/components/box/Box.js
src/js/components/box/StyledBox.js
src/js/components/box/__tests__/Box-test.js
src/js/components/box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/box/doc.js
src/js/themes/vanilla.js

Adds alignContent, alignSelf, basis, and reverse properties to Box.

Added more to Box.

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/components/mixins.js
src/js/components/text-input/StyledTextInput.js
src/js/components/text-input/TextInput.js
src/js/components/text-input/__tests__/TextInput-test.js
src/js/components/text-input/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/text-input/doc.js
src/js/components/text-input/index.js
src/js/themes/vanilla.js

Added initial version of text input

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/index.js
src/js/components/meter/Bar.js
src/js/components/meter/Circle.js
src/js/components/meter/Meter.js
src/js/components/meter/__tests__/Meter-test.js
src/js/components/meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/meter/doc.js
src/js/components/meter/index.js
src/js/components/paragraph/doc.js
src/js/components/utils/colors.js
src/js/components/utils/graphics.js
src/js/components/utils/mixins.js
src/js/components/utils/styles.js
src/js/themes/vanilla.js

Adds Meter.
Probably with components/meter/doc.js.
Updated next-sample.
Via next-sample.
no
none
next-sample
yes
breaking vs. 1.0.

Next meter

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/components/stack/Stack.js
src/js/components/stack/StyledStack.js
src/js/components/stack/__tests__/Stack-test.js
src/js/components/stack/__tests__/__snapshots__/Stack-test.js.snap
src/js/components/stack/doc.js
src/js/components/stack/index.js

Adds a Stack component to Grommet 2.0.
components/stack/doc.js
Via next-sample
Via next-sample
This allows doing things like putting a Value in the center of a Meter.
none
yes
yes
compatible, new component

Added Stack

---

__tests__/components/WorldMap-test.js
__tests__/components/__snapshots__/WorldMap-test.js.snap
src/js/components/WorldMap.js
src/scss/grommet-core/_objects.world-map.scss

Enhanced WorldMap to support latitude and longitude coordinates for places, added zoom property, added flag and onHover to series objects.
WorldMap.js
Enhanced grommet-docs examples for WorldMap.
Same as above.
no
none
Yes.
Yes.

Enhanced WorldMap

---

src/js/components/WorldMap.js

Adds latitude and longitude to WorldMap onSelectPlace()
WorldMap.js
Interactive with grommet-docs
same
no
none

Enhanced WorldMap onSelectPlace to also return latitude,longitude

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/index.js
src/js/components/text/StyledText.js
src/js/components/text/Text.js
src/js/components/text/__tests__/Text-test.js
src/js/components/text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/text/doc.js
src/js/components/text/index.js
src/js/themes/vanilla.js

Adds Text component
Text.js
next-sample
See next-sample
no
none
yes
yes

Added Text

---

package.json
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/components/markdown/Markdown.js
src/js/components/markdown/__tests__/Markdown-test.js
src/js/components/markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/components/markdown/doc.js
src/js/components/markdown/index.js
yarn.lock

Adds Markdown component
Markdown.js
next-sample
next-sample
no
none
yes
yes

Next markdown

---

src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/chart/Bar.js
src/js/components/chart/Chart.js
src/js/components/chart/Line.js
src/js/components/chart/__tests__/Chart-test.js
src/js/components/chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/chart/doc.js
src/js/components/chart/index.js
src/js/components/index.js
src/js/components/meter/Bar.js
src/js/components/meter/Circle.js
src/js/components/meter/Meter.js
src/js/components/meter/__tests__/Meter-test.js
src/js/components/meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/meter/doc.js
src/js/components/utils/colors.js

Adds Chart to grommet 2.0
components/chart/doc.js
next-sample
next-sample
no
none
yes
yes

Added Chart

---

src/js/components/box/__tests__/Box-test.js
src/js/components/box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/utils/colors.js
src/js/components/utils/styles.js

Adds `status-*` as a possible Box background color.

Allow status colors as Box background.

---

src/scss/grommet-core/_objects.meter.scss

[MeterClipping.pdf](https://github.com/grommet/grommet/files/1267982/MeterClipping.pdf)

fix meter crop - 1227

---

src/js/components/layer/LayerContainer.js
src/js/components/layer/StyledLayer.js
src/js/components/layer/__tests__/Layer-test.js
src/js/components/layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/layer/doc.js

Removed closer, renamed onClose to `onEsc`. added size prop.

Simplifying layer to remove closer

---

src/js/components/Image/Image.js
src/js/components/Image/StyledImage.js
src/js/components/Image/__tests__/Image-test.js
src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
src/js/components/Image/doc.js
src/js/components/Image/index.js
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js

Adds Image component
Image/doc.js
next-sample
next-sample
no
no
yes
yes
breaking

Next image

---

src/js/components/Anchor/Anchor.js
src/js/components/Anchor/StyledAnchor.js
src/js/components/Box/Box.js
src/js/components/Grommet/Grommet.js

Track background darkness in grommet context via Box. Use in Anchor to set text color.
Box.js
grommet-people-finder
same
no
none
no
no
compatible

Added dark background to context in Box

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Text/doc.js
src/js/components/utils/colors.js
src/js/components/utils/styles.js
src/js/themes/vanilla.js
yarn.lock

Added opacity and radius support to Box. Added dark to icons.

Add opacity

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/CheckBox-test.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBox/doc.js
src/js/components/CheckBox/index.js
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/themes/vanilla.js

Adds CheckBox
CheckBox/doc.js
next-sample
next-sample
no
yes
compatible

Added CheckBox

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/StyledBox.js
src/js/components/Box/doc.js
src/js/components/Button/Button.js
src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Button/doc.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/themes/vanilla.js

See summary
read the code
next-simple
yes
no
compatible

Removed 'box' and 'centered' from Button.

---

src/js/components/Text/StyledText.js
src/js/components/Text/__tests__/Text-test.js
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/Text/doc.js

Adds `color` to Text.
Text/doc.js
next-sample
next-sample
yes
yes
compatible

Added color to Text

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
src/js/components/Keyboard/__tests__/__snapshots__/Keyboard-test.js.snap
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
src/js/components/Responsive/Responsive.js
src/js/components/Responsive/__tests__/Responsive-test.js
src/js/components/Responsive/__tests__/__snapshots__/Responsive-test.js.snap
src/js/components/Responsive/doc.js
src/js/components/Responsive/index.js
src/js/components/Stack/__tests__/__snapshots__/Stack-test.js.snap
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/components/utils/mixins.js
src/js/themes/vanilla.js

Adds Responsive component
Responsive/doc.js
next-sample

Added Responsive

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/themes/vanilla.js

Adds `animation` property to Box.
Box/doc.js
next-sample
next-sample
yes
yes
compatible

Added animation to Box

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/StyledRadioButton.js
src/js/components/RadioButton/__tests__/RadioButton-test.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/components/RadioButton/doc.js
src/js/components/RadioButton/index.js
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/themes/vanilla.js

Adds RadioButton
RadioButton/doc.js
next-sample
yes
yes
compatible

Added RadioButton

---

src/js/components/Video/StyledVideo.js
src/js/components/Video/Video.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Fixed an issue with Video controls positioning
Video.js
next-sample
next-sample

Fixed an issue with Video when fit=contain and controls=over

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/RadioButton/StyledRadioButton.js
src/js/themes/vanilla.js
src/js/utils/object.js

Also fixed issues when changing the theme for CheckBox and RadioButton

Object assign removal

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/TextInput/TextInput.js
src/js/themes/vanilla.js

Updated use of brand color in vanilla theme

---

src/js/components/TextArea/README.md
src/js/components/TextArea/StyledTextArea.js
src/js/components/TextArea/TextArea.js
src/js/components/TextArea/__tests__/TextArea-test.js
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextArea/doc.js
src/js/components/TextArea/index.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/utils/DOM.js
yarn.lock

Adds the TextArea component.
TextArea/doc.js
grommet-site

Added TextArea

---

src/js/components/Search.js

Fix Search exception on mobile-1707

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Anchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
src/js/components/Grommet/StyledGrommet.js
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
src/js/components/Keyboard/__tests__/__snapshots__/Keyboard-test.js.snap
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
src/js/components/Responsive/__tests__/__snapshots__/Responsive-test.js.snap
src/js/components/Stack/__tests__/__snapshots__/Stack-test.js.snap
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
yarn.lock

Removed layout from the styling for the `Grommet` component so it can be used within an app.

Removed layout styling from Grommet component

---

src/js/components/WorldMap.js
src/scss/grommet-core/_base.input.scss
yarn.lock

Fixed an issue with WorldMap when places have the same location. Fixed an issue with generic input styling.
files changed
internal project

Fixed issues with WorldMap and generic input styling.

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/StyledMeter.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap

styled bar Meter to have outer rounding
StyledMeter.js
next-sample
next-sample

Round bar Meter edges when rounded

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap

Improves Meter when there are small values and `round={true}`.
Bar.js
next-sample
next-sample

Improve Meter when rounded

---

.gitignore
package.json
tools/pack.js
yarn.lock

This is useful because it creates two things:
1) A zip with all the dependencies bundled
2) A map of licenses for all the dependencies that grommet ships

Added pack task

---

src/js/components/Layer.js

Adds `overlayClose` to Layer.
Layer.js
Enhanced grommet-docs to include property in example.
grommet-docs
See issue.
https://github.com/grommet/grommet/issues/1183
Yes. PR coming.
Yes.

Added overlayClose to Layer

---

src/js/components/Button/README.md
src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/Button-test.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Button/doc.js
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap

See Title.
Button/doc.js
grommet-site whitebox testing
same as above
automatic
Most definitely.
This is a breaking change for 2.0.

BREAKING CHANGE. Removed accent, critical, and secondary from Button. Added color to Button.

---

package.json
src/js/utils/Cookies.js
yarn.lock

See title.
src/js/utils/Cookies.js
jest tests
Whitebox testing using grommet-docs
Same as above.
Avoid GPL.
No.
Yes.
Should be backwards compatible.

Re-implemented Cookies to avoid license issues

---

src/js/components/SearchInput.js
src/js/components/Select.js
src/js/components/TextInput.js
src/scss/grommet-core/_base.input.scss
src/scss/grommet-core/_objects.button.scss
src/scss/grommet-core/_objects.form-field.scss

Simplifies styling of FormField input elements. Improved layout.
The CSS files have the interesting changes.
All browsers + grommet-docs.
grommet-docs
no
yes

Restyled FormField input elements

---

src/js/components/chart/Graph.js

See Title
Graph.js
grommet-docs
grommet-docs
no
yes

Fixed an issue with Chart graphics when there is only one value

---

src/js/utils/DOM.js

Fixes snapshot testing, bug reported in: https://github.com/grommet/grommet/issues/1806
Thanks to @atanasster

Fix snapshot testing \#1806

---

src/js/components/Layer.js

This PR is related to #1806, however, it fixes a similar issue inside the Layer component.

Fixed snapshot testing in Layer #1806

---

src/js/components/Diagram/Diagram.js
src/js/components/Diagram/README.md
src/js/components/Diagram/StyledDiagram.js
src/js/components/Diagram/__tests__/Diagram-test.js
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Diagram/doc.js
src/js/components/Diagram/index.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js

Adds Diagram component.
Diagram/doc.js
grommet-site
grommet-site
Replaced Map and Topology from v1.
Yes. Done.
Yes.
backwards compatible with v2.

Added Diagram

---

src/js/utils/DOM.js
src/js/utils/Drop.js

if the drop control is hidden, find first visible parent
#1812

fix for #1812

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Diagram/Diagram.js
src/js/components/Diagram/__tests__/Diagram-test.js
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/WorldMap/README.md
src/js/components/WorldMap/StyledWorldMap.js
src/js/components/WorldMap/WorldMap.js
src/js/components/WorldMap/__tests__/WorldMap-test.js
src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.js.snap
src/js/components/WorldMap/doc.js
src/js/components/WorldMap/index.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/themes/vanilla.js

Adds WorldMap component
WorldMap/doc.js
grommet-site
grommet-site
yes
yes
This is new for v2 and not backwards compatible with v1.

Added WorldMap

---

package.json
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Calendar/Calendar.js
src/js/components/Calendar/README.md
src/js/components/Calendar/StyledCalendar.js
src/js/components/Calendar/__tests__/Calendar-test.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/doc.js
src/js/components/Calendar/index.js
src/js/components/Chart/Chart.js
src/js/components/Clock/Clock.js
src/js/components/Diagram/Diagram.js
src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/RangeInput/StyledRangeInput.js
src/js/components/WorldMap/WorldMap.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/themes/vanilla.js
src/js/utils/mixins.js
src/js/utils/styles.js
yarn.lock

Adds a Calendar component.
Calendar/doc.js
grommet-site
wait for grommet-site?
The design approach is to decouple this from an input control, drop containers, layers, etc. to allow the caller to have more flexibility in how it is used.
Yes
Yes

Added Calendar

---

package.json

Updated to the latest version of grommet-icons to support styled components

Styled Components V3 support

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/utils/DOM.js

Drop hidden control

---

src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
yarn.lock

Fixes RadioButton to set correct input type.
RadioButton.js
snapshot
jest
https://github.com/grommet/grommet/issues/1850
no
no

Fixed an issue where RadioButton was setting the incorrect input type

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/Meter.js
src/js/components/Meter/__tests__/Meter-test.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Meter/doc.js
src/js/components/Meter/utils.js
src/js/components/Stack/Stack.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/utils/prop-types.js

Enhance Meter to support opacity of the background
Meter/doc.js
grommet-site
grommet-site
automatic
sure

Enhance Meter to support opacity of the background

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/themes/vanilla.js

Changes the default text color on dark backgrounds to full white.
One line change.
grommet-site
grommet-site
no
no

Change text color on dark backgrounds to full white

---

package.json
src/js/components/Calendar/Calendar.js
src/js/components/Calendar/README.md
src/js/components/Calendar/__tests__/Calendar-test.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/doc.js
src/js/components/Calendar/utils.js
src/js/components/Meter/README.md
src/js/components/Select/README.md
src/js/components/__tests__/__snapshots__/README-test.js.snap
yarn.lock

Removes dependency on momentjs for Calendar. Adds `firstDayOfWeek` property to Calendar.
Calendar/doc.js
grommet-site and grommet-sandbox
momentjs is large. We don't need it all.
automatic
Yes

Removed dependency on momentjs for Calendar

---

src/js/components/Box/Box.js
src/js/components/Box/README.md
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/CheckBox/README.md
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/RadioButton/README.md
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Stack/README.md
src/js/components/__tests__/__snapshots__/README-test.js.snap

Adds the `gap` property to Box.
Box/doc.js
grommet-site
grommet-site
The term 'gap' aligns better with the same property in Grid.
yes
yes

Added Box gap

---

src/js/components/Box/README.md
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Button/StyledButton.js
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/DropButton/DropButton.js
src/js/components/DropButton/README.md
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/DropButton/doc.js
src/js/components/Grommet/README.md
src/js/components/Grommet/StyledGrommet.js
src/js/components/Grommet/__tests__/Grommet-test.js
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Grommet/doc.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap

Added Grommet full. Removed Box full. Added Box fill.
This aligns Box `fill` with Button `fill` and uses `full` in only the outer Grommet context.
Added DropButton align.
Grommet/doc.js
Box/doc.js
grommet-site
grommet-ferret with grommet-v1
grommet-site
yes
YES
BREAKING CHANGE

Added Grommet full. Removed Box full. Added Box fill. Added DropButton align.

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Anchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Distribution/Distribution.js
src/js/components/Distribution/README.md
src/js/components/Distribution/__tests__/Distribution-test.js
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Distribution/doc.js
src/js/components/Distribution/index.js
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
yarn.lock

Adds Distribution component. It both renders and is implemented differently than v1. See doc.js.
Distribution/doc.js
grommet-site
Nothing available yet.
yes
yes

Added Distribution

---

src/js/components/RadioButton/README.md
src/js/components/RadioButton/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed RadioButton to require `name`.
RadioButton/doc.js
unit tests
unit tests
no
no
backwards compatible in v2

Changed RadioButton to require 'name'

---

src/js/components/RangeInput/README.md
src/js/components/RangeInput/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Enhances documentation of RangeInput
RangeInput/doc.js
grommet-site
grommet-site
automatic
no

Enhanced documentation of RangeInput

---

src/js/components/WorldMap/WorldMap.js

Fixed GitHub issue #1852.
WorldMap.js
none
somehow
https://github.com/grommet/grommet/issues/1852
no
no

Changed WorldMap to use spaces in americas names. Fixed GitHub issue #1852.

---

src/js/components/Button/Button.js
src/js/components/Button/StyledButton.js

Fixed an issue with Button label color when in a dark background context
no
no

Fixed an issue with Button label color when in a dark background context

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/StyledRadioButton.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/utils/object.js

Changed CheckBox and RadioButton to have a unique style when disabled
CheckBox/StyledCheckBox.js
unit tests
unit tests
https://github.com/grommet/grommet/issues/1920
https://github.com/grommet/grommet/issues/1921
no
no

Changed CheckBox and RadioButton to have a unique style when disabled

---

src/js/components/Select/Select.js

Fix Select component that was closing unexpectedly.
Select
Yes
Open the select with search, manually search something. the select should not close
No
Yes

Fixed select closing on search change

---

src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/Carousel.js
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Allow the main carousel box to receive focus .
Carousel.
Updated snapshots.
Open carousel example page (probably grommet-sandbox) and navigate to the carousel and 
No
No.

Added accessibility to carousel. Allowed box to receive focus.

---

src/js/components/Box/StyledBox.js
src/js/components/Menu/README.md
src/js/components/RangeSelector/EdgeControl.js
src/js/components/RangeSelector/README.md
src/js/components/RangeSelector/RangeSelector.js
src/js/components/RangeSelector/__tests__/RangeSelector-test.js
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/components/RangeSelector/doc.js
src/js/components/RangeSelector/index.js
src/js/components/Select/README.md
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js

Added RangeSelector
RangeSelector/doc.js
unit tests
This can be used to control selection over a chart range. For example, a Google finance style low resolution chart with range selection linked to a high resolution chart for the selected range.
yes
yes

Added RangeSelector

---

src/js/components/Select/README.md
src/js/components/Select/Select.js
src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed Select to add `multiple`.
Select/doc.js
unit tests
HTML5 spec allows multiple selection
https://github.com/grommet/grommet/issues/1868
automatic
yes

Changed Select to add multiple

---

src/js/components/DropButton/DropButton.js
src/js/components/DropButton/README.md
src/js/components/DropButton/__tests__/DropButton-test.js
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/DropButton/doc.js
src/js/components/Menu/Menu.js
src/js/components/Menu/README.md
src/js/components/Menu/__tests__/Menu-test.js
src/js/components/Menu/doc.js
src/js/components/Select/README.md
src/js/components/Select/Select.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed DropButton, Menu, and Select to add `disabled`.
DropButton/doc.js
unit test
https://github.com/grommet/grommet/issues/1951
https://github.com/grommet/grommet/issues/1952
https://github.com/grommet/grommet/issues/1953
automatic
yes

 Changed DropButton, Menu, and Select to add disabled

---

package.json
src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/README.md
src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
src/js/components/InfiniteScroll/doc.js
src/js/components/InfiniteScroll/index.js
src/js/components/Menu/README.md
src/js/components/Select/README.md
src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
yarn.lock

Added InfiniteScroll
InfiniteScroll/doc.js
unit test
https://github.com/grommet/grommet/issues/1914
yes
yes

Added InfiniteScroll

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/FormField/FormField.js
src/js/themes/vanilla.js

Changed FormField to fix focus color issue
FormField.js
https://github.com/grommet/grommet/issues/1973
Will evaluate https://github.com/grommet/grommet/issues/1974 later.
no
no

Changed FormField to fix focus color issue

---

src/js/components/Video/Video.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
yarn.lock

Changed Video to remove findDOMNode usage from render
Video.js
grommet-site
https://github.com/grommet/grommet/issues/1911
no
yes

Changed Video to remove findDOMNode usage from render

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Button/StyledButton.js
src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/themes/dark.js
src/js/themes/index.js
src/js/themes/vanilla.js
src/js/utils/styles.js

Added dark theme and necessary related changes.
dark.js
grommet-site
grommet-site
https://github.com/grommet/grommet/issues/1933
no
yes

Added dark theme

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Drop/DropContainer.js
src/js/components/Drop/StyledDrop.js
src/js/themes/dark.js
src/js/themes/vanilla.js

Fixed an issue with drop shadows on dark backgrounds
vanilla.js
grommet-site
https://github.com/grommet/grommet/issues/1988
no
yes

Fixed an issue with drop shadows on dark backgrounds

---

src/js/components/Box/README.md
src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/README.md
src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
src/js/components/InfiniteScroll/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed InfiniteScroll to add renderMarker.
InfiniteScroll/doc.js
automatic
yes

Changed InfiniteScroll to add renderMarker

---

src/js/components/Distribution/Distribution.js

Changed Distribution to fix an issue with zero values
Distribution.js
no
yes

Changed Distribution to fix an issue with zero values

---

src/js/components/Box/StyledBox.js
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap

Changed Box to fix an issue with gap styling
StyledBox.js
unit testing
unit testing
no
yes

Changed Box to fix an issue with gap styling

---

src/js/components/Heading/StyledHeading.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/Text/StyledText.js

Changed Text and Heading to fix an issue with color styling
StyledText.js
no
yes

Changed Text and Heading to fix an issue with color styling

---

src/js/components/Table/StyledTable.js
src/js/components/Table/TableCell.js
src/js/components/Table/__tests__/Table-test.js
src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
src/js/components/Table/doc.js

Changed TableCell to add verticalAlign
Table/doc.js
automatic
yes

Changed TableCell to add verticalAlign

---

src/js/components/Meter/Circle.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap

Fixed an issue with Meter circle cap rendering
Meter/Circle.js
no
yes

Fixed an issue with Meter circle cap rendering

---

src/js/components/FocusedContainer.js
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/__tests__/__snapshots__/FocusedContainer-test.js.snap

Fix for #2001
#2001 
no
sure
compatible

Fix for v2 Layer causing unexpected Scrollbars upon being closed #2001

---

src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/doc.js

Changed InfiniteScroll to add `scrollableAncestor`.
InfiniteScroll/doc.js
Cruiser project
no
yes

Changed InfiniteScroll to add scrollableAncestor.

---

src/js/components/Grid/StyledGrid.js
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap

Fixed an issue with Grid justify not using the correct CSS property.
StyledGrid.js
grommet-site
grommet-site
no
yes

Fixed an issue with Grid justify

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Calendar/Calendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Tabs/Tab.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/themes/vanilla.js

Fixed an issue with vanilla font face loading.
vanilla.js
grommet-site
grommet-site
no
yes

Fixed an issue with vanilla font face loading

---

src/js/components/Grid/README.md
src/js/components/Grid/StyledGrid.js
src/js/components/Grid/__tests__/Grid-test.js
src/js/components/Grid/doc.js
src/js/components/Grid/index.js
src/js/components/InfiniteScroll/README.md
src/js/components/__tests__/__snapshots__/README-test.js.snap

Added Grid.available so callers can determine whether the Grid is available (it isn't on ie11) so they can create a reasonable fallback.
Grid/doc.js
grommet-site
grommet-site
automatic
yes

[Breaking Change] Added Grid.available. Changed Grid to remove horizontal and vertical gap values

---

src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
yarn.lock

Changed TextInput to fix an issue with suggestion labels
TextInput.js
https://github.com/grommet/grommet/issues/2028
no
yes

Changed TextInput to fix an issue with suggestion labels

---

src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Box to fix an issue with properties leaking into the DOM
Box.js
https://github.com/grommet/grommet/issues/2017
no
yes

Changed Box to fix an issue with properties leaking into the DOM

---

src/js/components/Box/Box.js
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap

Changed Box to fix an issue with gap
Box.js
https://github.com/grommet/grommet/issues/2040
no
no

Changed Box to fix an issue with gap

---

.github/stale.yml

Add Github stale bot to handle inactive issues.

Add Github Stale bot

---

src/js/components/Accordion.js

This change will fix the following issue:
Unable to conditionally render an AccordionPanel component
https://github.com/grommet/grommet/issues/2064

FIX https://github.com/grommet/grommet/issues/2064

---

src/js/themes/dark.js
src/js/themes/hpe.js

Fixed an issue with theme color overriding
hpe.js
storybook
storybook
no
yes

Fixed an issue with theme color overriding

---

src/js/components/TextInput/TextInput.js
src/js/components/TextInput/textinput.stories.js
src/js/components/hocs.js

Fixed an issue with forward ref on withAnnounce
withAnnounce
storybook
storybook
no
no

Fixed an issue with forward ref on withAnnounce

---

src/js/components/Button/StyledButton.js
src/js/components/Button/button.stories.js
src/js/themes/vanilla.js

Fixed bug where specifying a custom primary color inside button theme would still use the brand color.

Fixed button color to allow for custom primary colorl

---

src/js/components/Button/Button.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Fixed an issue with icon only Button padding
Button.js
storybook
storybook
no
no

Fixed an issue with icon only Button padding

---

src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/README.md
src/js/components/TextInput/StyledTextInput.js
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/TextInput/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed TextInput to support node placeholder
TextInput.js
storybook
storybook
This is being done to support column level search/filter in the upcoming DataTable component.
automatic
yes

Changed TextInput to support node placeholder

---

src/js/components/WorldMap/WorldMap.js
src/js/components/WorldMap/worldmap.stories.js

Changed WorldMap to fix an issue with updating props
WorldMap.js
storybook
storybook
no
yes

Changed WorldMap to fix an issue with updating props

---

src/js/components/Diagram/Diagram.js
src/js/components/Diagram/README.md
src/js/components/Diagram/StyledDiagram.js
src/js/components/Diagram/__tests__/Diagram-test.js
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Diagram/diagram.stories.js
src/js/components/Diagram/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/vanilla.js
tools/generate-readme.js

Changed Diagram to reduce dependence on Stack, add more `thickness` options, add `anchor`.
Diagram.js
Diagram storybook
Diagram storybook
https://github.com/grommet/grommet/issues/2036
https://github.com/grommet/grommet/issues/2037
https://github.com/grommet/grommet/issues/2038
automatic
yes

Changed Diagram to reduce dependence on Stack, add more `thickness` options, add `anchor`.

---

src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Fix erroneous  quotes in css value for smooth scrolling in Select
SelectContainer
manual
open Select stories
no
yes

Fixed wrong smooth scroll value

---

package.json
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Anchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/stories/components/icons/ArrowDown.js
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
yarn.lock

Fixed a problem running storybook locally due to a wrong export icon.
Also updated yarn.lock.
`npm run storybook`
manual
try to run storybook
no
no
backwards

Fixed arrow down export. Updated dependencies

---

src/js/components/Button/Button.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Button to fix an issue with label alignment when fill={true}. Fixes GitHub issue #2097.
Button.js
storybook
storybook
https://github.com/grommet/grommet/issues/2097
no
yes

Changed Button to fix an issue with label alignment when fill={true}. Fixes GitHub issue #2097.

---

.babelrc
.eslintrc
package.json
src/js/components/TextInput.js
yarn.lock

Issue 2109: TextInput - remove keyboard handlers when unmounting.

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/Header.js
src/js/components/DataTable/Resizer.js
src/js/components/DataTable/Searcher.js
src/js/components/DataTable/Sorter.js
src/js/components/DataTable/StyledDataTable.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/datatable.stories.js

Changed DataTable to fix some issues with Header controls
Header.js
storybook with Opera, Firefox, Edge, IE11
storybook
no
yes

Changed DataTable to fix some issues with Header controls

---

src/js/components/Box/Box.js
src/js/components/Box/box.stories.js
src/js/components/Calendar/Calendar.js
src/js/components/Calendar/StyledCalendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/calendar.stories.js
src/js/components/RangeSelector/__tests__/RangeSelector-test.js
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/themes/vanilla.js
src/js/utils/styles.js

Changed Box to not change darkness with weak opacity. Changed Calendar to fix an IE11 issue.
Box.js
StyledCalendar.js
storybook: Opera, Firefox, Edge, IE11
storybook
https://github.com/grommet/grommet/issues/2119
no
yes

Changed Box to not change darkness with weak opacity. Changed Calendar to fix an IE11 issue. Fixes #2119

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/StyledDrop.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/Select.js
src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/stories/select.stories.js
src/js/components/Select/stories/theme.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/themes/vanilla.js

Changed Select to fix an issue with drop height. Fixes GitHub issue #2121.
storybook: Opera, Firefox, Edge
storybook
https://github.com/grommet/grommet/issues/2121
no
yes

Changed Select to fix an issue with drop height. Fixes GitHub issue #2121.

---

src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap

Changed TextInput to fix an issue with scrolling when there are lots of suggestions
TextInput.js
storybook
storybook
no
yes

Changed TextInput to fix an issue with scrolling when there are lots of suggestions

---

src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/__tests__/__snapshots__/hocs-test.js.snap
src/js/components/hocs.js

Changed withFocus to fix GitHub issue #2126
hocs.js
storybook
storybook
https://github.com/grommet/grommet/issues/2126
no
no

Changed withFocus to fix GitHub issue #2126

---

src/js/components/Select/stories/components/SearchBorderBox.js

Change Select Custom Search story to fix animation issue
select stories
manual
open storybook
no
nope

Fixed select story animation

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/calendar.stories.js
src/js/components/DropButton/dropbutton.stories.js

Changed Calendar to fix an issue with heading padding
Calendar.js
storybook
storybook
no
yes

Changed Calendar to fix an issue with heading padding

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Button/RoutedButton.js
src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Button to fix an issue with anchor element buttons
RoutedButton.js
storybook
storybook
https://github.com/grommet/grommet/issues/2116
no
yes

Changed Button to fix an issue with anchor element buttons

---

src/js/components/FormField/FormField.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/FormField/formfield.stories.js
src/js/components/TextInput/TextInput.js

Changed FormField and TextInput focus processing
FormField.js
storybook on Opera, Firefox, Chrome, Edge, IE11
storybook
https://github.com/grommet/grommet/issues/2048
no
no

Changed FormField and TextInput focus processing

---

src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/README.md
src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
src/js/components/InfiniteScroll/doc.js
src/js/components/InfiniteScroll/infinitescroll.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed InfiniteScroll to add show. Fixes GitHub issue #2123.
added storybook stories
storybook
https://github.com/grommet/grommet/issues/2123
automatic
yes

Changed InfiniteScroll to add show. Fixes GitHub issue #2123.

---

src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/utils.js

Changed Calendar to fix issue #2142
Calendar/utils.js
storybook
storybook
https://github.com/grommet/grommet/issues/2142
no
no

Changed Calendar to fix issue #2142

---

src/js/components/Grid/StyledGrid.js
src/js/components/Grid/grid.stories.js

Changed Grid to pass through non-formalized sizes, like 0 or 'auto'. This aligns with how Box handles sizes.
Also added a storybook story for Grid.
StyledGrid.js
storybook
storybook
automatic
yes

Changed Grid to pass through non-formalized sizes, like 0 or 'auto'

---

src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/components/TextInput/textinput.stories.js
src/js/components/__tests__/__snapshots__/hocs-test.js.snap
src/js/components/__tests__/hocs-test.js
src/js/components/hocs.js

Changed TextInput and withFocus to address timing issues.
hocs.js
TextInput.js
storybook in Opera, Firefox, ie11
storybook
https://github.com/grommet/grommet/issues/2154
no
yes

Changed TextInput and withFocus to address timing issues. Fixes GitHub issue #2154.

---

src/js/components/DataTable/Searcher.js
src/js/components/DataTable/StyledDataTable.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap

Changed DataTable to fix an issue with size
StyledDataTable.js
storybook on Opera, Firefox, Chrome, Edge, IE11
storybook
no
no

Changed DataTable to fix an issue with size

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/Header.js
src/js/components/DataTable/README.md
src/js/components/DataTable/buildState.js
src/js/components/DataTable/datatable.stories.js
src/js/components/DataTable/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed DataTable to add onSearch
doc.js
storybook
storybook
automatic
yes

Changed DataTable to add onSearch

---

src/js/components/Tabs/Tabs.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/Tabs/doc.js
src/js/components/Tabs/tabs.stories.js

Changed Tabs to fix uncontrolled behavior. Fixes GitHub issue #2158
Tabs.js
storybook
storybook
https://github.com/grommet/grommet/issues/2158
yes, to include documentation for Tab
yes

Changed Tabs to fix uncontrolled behavior. Fixes GitHub issue #2158

---

src/js/components/Grommet/StyledGrommet.js
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap

Fixes Grommet with full prop to avoid scroll issues in Drop
StyledGrommet
storybook
storybook
#2172
no
yes!

Grommet: added overflow auto to full styles to avoid drop scroll issues. Fixes 2172

---

src/js/components/Paragraph/README.md
src/js/components/Paragraph/StyledParagraph.js
src/js/components/Paragraph/doc.js
src/js/components/Paragraph/paragraph.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Fixes paragraph to add support for color prop
StyledParagraph
storybook
storybook
#2171 
yes
yes

Added support for Paragraph color. Fixes #2171

---

src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/utils/styles.js

Fixes invalid css for hover logic
StyledButton
storybook
open Button Active new example
no
yes
backwards

Fix hover indicator

---

.eslintrc
package.json
src/js/components/Accordion/AccordionPanel.js
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Accordion/accordion.stories.js
src/js/components/Collapsible/Collapsible.js
src/js/components/Collapsible/CollapsibleContext.js
src/js/components/Collapsible/collapsible.stories.js
src/js/components/Collapsible/index.js
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/themes/base.js

Removed collapsible context, now reset is done automatically internally.
Changes collapsible to allow for nested elements within itself.
storybook
manual
open collapsible.stories.js
no (currently we dont have docs for collapsible, we should add one)
yes
breaking change since we are removing CollapsibleContext.

Collpasible: fix to allow nested collapsible elements. 

---

src/js/components/Collapsible/Collapsible.js

Fixes a small bump when closing the collapsible panel
collapsible.js
manual
storybook
no
no

Collapsible: fixed bump issue when closing panel.

---

src/js/components/Menu/Menu.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap

Changed Menu to fix an issue on IE11.
Menu.js
storybook with Opera, Firefox, Edge, IE11
storybook
https://github.com/grommet/grommet/issues/2183
no
yes

Changed Menu to fix an issue on IE11.

---

src/js/components/Button/Button.js
src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Button to not leak icon into the DOM.
Button.js
storybook
storybook
https://github.com/grommet/grommet/issues/2180
no
yes

Changed Button to not leak icon into the DOM. Issue #2180.

---

package.json
webpack.config.babel.js

Adds clean webpack plugin to make sure we delete dist before running build
webpack config
manual
`npm run dist`
no
no
backwards

Added clean webpack plugin

---

src/js/components/Menu/Menu.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap

Changed Menu to allow a long list of items that might scroll
Menu.js
storybook
storybook
no
yes

Changed Menu to allow a long list of items that might scroll

---

package.json

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
package.json
manual
no
no
backwards

Added sideEffects false for better tree shaking support.

---

src/js/components/Accordion/README.md
src/js/components/Accordion/doc.js
src/js/components/Accordion/index.d.ts
src/js/components/Box/README.md
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/Button/README.md
src/js/components/Button/doc.js
src/js/components/Button/index.d.ts
src/js/components/Carousel/Carousel.js
src/js/components/DataTable/README.md
src/js/components/DataTable/doc.js
src/js/components/DataTable/index.d.ts
src/js/components/Grid/README.md
src/js/components/Grid/doc.js
src/js/components/Grid/index.d.ts
src/js/components/Heading/README.md
src/js/components/Heading/doc.js
src/js/components/Heading/index.d.ts
src/js/components/Stack/Stack.js
src/js/components/Stack/StyledStack.js
src/js/components/Stack/__tests__/__snapshots__/Stack-test.js.snap
src/js/components/Tabs/README.md
src/js/components/Tabs/doc.js
src/js/components/Tabs/index.d.ts
src/js/components/Text/text.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/components/components.stories.js

Fixed prop type warnings
storybook
storybook
no
no

Fixed prop type warnings

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Anchor/Anchor.js
src/js/components/Anchor/StyledAnchor.js
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Button/Button.js
src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Heading/Heading.js
src/js/components/Heading/StyledHeading.js
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Heading/heading.stories.js
src/js/components/RoutedAnchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/Text/StyledText.js
src/js/components/Text/Text.js
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/components/Text/text.stories.js

Fixed some properties leaking into the DOM
anywhere
storybook, unit test, snapshot pattern search
storybook
https://github.com/grommet/grommet/issues/2228
https://github.com/grommet/grommet/issues/2227
https://github.com/grommet/grommet/issues/2226
https://github.com/grommet/grommet/issues/2225
https://github.com/grommet/grommet/issues/2224
no
yes

Fixed some properties leaking into the DOM

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/__tests__/Meter-test.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Meter/utils.js

Changed Meter to fix an issue with many values using default colors
Bar.js
storybook, enhanced unit tests
storybook
https://github.com/grommet/grommet/issues/2230
no
yes

Changed Meter to fix an issue with many values using default colors

---

src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Layer/layer.stories.js
src/js/themes/base.js
yarn.lock

Fixes margin on layer.
Improves responsive.
Removes unused border variable.
layer.stories.js
manual 
open layer examples, especially Margin example.
Fixes https://github.com/grommet/grommet/issues/2281 and https://github.com/grommet/grommet/issues/2282
no
yes
this can be a breaking change because we removed the unused `border` code and folks maybe using that outside grommet space.

Layer: fixed issues with margin and responsive.

---

src/js/components/Box/README.md
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/box.stories.js
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
yarn.lock

Changed Box to allow more flexibility with rounding.
Box/doc.js
storybook
storybook
https://github.com/grommet/grommet/issues/2275
automatic
yes

Changed Box to allow more flexibility with rounding

---

src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/box.stories.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/utils/background.js

Changed Box to allow the background to specify both an image and color
utils/background.js
storybook
storybook
It's all background :)
https://github.com/grommet/grommet/issues/2212
no
yes

Changed Box to allow the background to specify both an image and color

---

src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap

Changed Box to support custom width and height
StyledBox.js
storybook
storybook
https://github.com/grommet/grommet/issues/2277
no
yes

Changed Box to support custom width and height

---

src/js/themes/hpe.js

Changed hpe theme to fix an issue with Anchor text color on dark backgrounds
hpe.js
grommet-ldap
storybook
no
no

Changed hpe theme to fix an issue with Anchor text color on dark backgrounds

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/calendar.stories.js
src/js/components/Calendar/utils.js
src/js/themes/base.js

Changed Calendar to fix some issues with bounds and quick navigation
Calendar.js
storybook
storybook
https://github.com/grommet/grommet/issues/2298
https://github.com/grommet/grommet/issues/2299
no
yes

Changed Calendar to fix some issues with bounds and quick navigation

---

package.json
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
yarn.lock

updates package json and test to use the latest grommet-icons
package.json
manual
run tests and storybook
no
no

Updated to the latest grommet-icons

---

src/js/components/Anchor/Anchor.js
src/js/components/Anchor/StyledAnchor.js
src/js/components/Grommet/Grommet.js
src/js/components/Grommet/grommet.stories.js
src/js/components/typography.stories.js
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/__tests__/theme-test.js

Changed Grommet to fix an issue with the generation of grommet-icons theme.
Grommet.js
storybook
storybook
https://github.com/grommet/grommet/issues/2278
no
yes

Changed Grommet to fix an issue with the generation of grommet-icons theme

---

src/js/components/Button/__tests__/Button-test.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/utils/colors.js

Fixed an issue with short hex colors. e.g. #000
added story and test
colors.js
storybook
storybook
https://github.com/grommet/grommet/issues/2258
no
yes

Fixed an issue with short hex colors. e.g. #000

---

src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/box.stories.js

Changed Box to fix an issue with elevation
StyledBox.js
storybook, added story
storybook
https://github.com/grommet/grommet/issues/2361
no
yes

Changed Box to fix an issue with elevation

---

src/js/components/Box/README.md
src/js/components/Box/doc.js
src/js/components/Calendar/README.md
src/js/components/Calendar/doc.js
src/js/components/Layer/doc.js
src/js/components/Stack/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Improved some documentation, mostly default values
grommet-site
yes
no

Improved some documentation, mostly default values

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Heading/README.md
src/js/components/Heading/StyledHeading.js
src/js/components/Heading/doc.js
src/js/components/Heading/heading.stories.js
src/js/components/Heading/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Changes Heading to allow custom heading levels.
StyledHeading.js
manual
open custom level storybook example
yes
yes
backwards

Heading: Allowing custom heading levels.

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBox/checkbox.stories.js
src/js/components/Clock/StyledClock.js
src/js/components/Menu/Menu.js
src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/StyledRadioButton.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/components/RadioButton/radiobutton.stories.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/themes/base.js
src/js/themes/grommet.js
src/js/utils/styles.js

Changes Menu and RadioButton to add better theming support
Menu.js and StyledRadioButton.js
manual
open storybook
https://github.com/grommet/grommet/issues/2336
no
sure
small breaking change. Had to move `radioButton.border.radius` to `radioButton.check.radius` to align better with CheckBox.

Menu, RadioButton: added better theming support.

---

src/js/components/Tab/README.md
src/js/components/Tab/StyledTab.js
src/js/components/Tab/Tab.js
src/js/components/Tab/doc.js
src/js/components/Tab/index.d.ts
src/js/components/Tabs/StyledTabs.js
src/js/components/Tabs/Tabs.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/Tabs/tabs.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/themes/base.js

Changes tab and tabs to allow customizable inner components
Tabs.js and Tab.js
manual
open storybook examples for tabs. especially custom theme one.
https://github.com/grommet/grommet/issues/2336
yes
yes
backwards

Tabs: make inner components customizable.

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBox/checkbox.stories.js
src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/components/RadioButton/radiobutton.stories.js
src/js/components/Select/stories/select.stories.js
src/js/components/Select/stories/theme.js

Changes CheckBox and RadioButton to fix an issue with rendering it inside a Button.
CheckBox.js and RadioButton.js
manual
open storybook examples `inside button` for both checkbox and radiobutton
no
yes

Fixed checkbox placed inside a button.

---

src/js/components/Distribution/Distribution.js
src/js/components/Distribution/README.md
src/js/components/Distribution/distribution.stories.js
src/js/components/Distribution/doc.js
src/js/components/Distribution/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
storybook/preview-head.html

Changed Distribution to add fill and improve documentation
Distribution/doc.js
storybook
storybook
https://github.com/grommet/grommet/issues/2383
yes
yes

Changed Distribution to add fill

---

src/js/components/Notification.js
src/js/components/Table.js

Notification banner: Allow the message parameter to be a node or a string.

---

package.json
src/js/components/AccordionPanel/AccordionPanel.js
src/js/components/Heading/README.md
src/js/components/Heading/__tests__/Heading-test.js
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Heading/doc.js
src/js/components/Heading/index.d.ts
src/js/components/Meter/meter.stories.js
src/js/components/Paragraph/README.md
src/js/components/Paragraph/__tests__/Paragraph-test.js
src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
src/js/components/Paragraph/doc.js
src/js/components/Paragraph/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/components/components.stories.js
src/js/themes/base.js
src/js/themes/grommet.js
yarn.lock

Changed Paragraph and Heading to add xlarge size.
Changed `grommet` theme to use Helvetica.
Fixed an console warning in AccordionPanel.
Added `grommet-theme-v1` to storybook example.
Added a richer story for Meter.
base.js
storybook, upcoming `grommet-site` refactor
storybook
no
yes

Changed Paragraph and Heading to add xlarge size

---

src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/utils/background.js
yarn.lock

Changes button to fix an issue where the theme color was being overwritten by the text color
StyledButton
manual
open Themed Color storybook example in
Fixes https://github.com/grommet/grommet/issues/2396
no
yes
backwards

Button: make sure buttont color takes precedence over text color.

---

src/js/components/Anchor/Anchor.js
src/js/components/Anchor/README.md
src/js/components/Anchor/StyledAnchor.js
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Anchor/anchor.stories.js
src/js/components/Anchor/doc.js
src/js/components/Anchor/index.d.ts
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/RoutedAnchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Text/StyledText.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
yarn.lock

Changed Anchor to add `size` property and remove unused `primary` property.
Note that this change ties the Anchor sizes to the size values of Text in the theme `global.text.size`. This is typically what you want to both from an aesthetic standpoint and to avoid confusion.
Anchor/doc.js
storybook
storybook
https://github.com/grommet/grommet/issues/2404
yes
yes
backwards compatible, since `primary` didn't affect anything.

Changed Anchor to add size property.

---

src/js/components/Anchor/README.md
src/js/components/Anchor/doc.js
src/js/components/Box/README.md
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

Changed base theme elevation values.
Also fixed some minor issues in theme documentation.
base.js
grommet-site/redesign
grommet-site/redesign
@L0ZZI (Grommet Chief Designer) wanted to tweak the elevations.
no
no

Changed base theme elevation values

---

src/js/components/Calendar/calendar.stories.js
src/js/components/Calendar/utils.js

Changed Calendar to fix an issue crossing daylight savings time
Calendar.js
storybook
storybook
https://github.com/grommet/grommet/issues/2422
no
yes

Changed Calendar to fix an issue crossing daylight savings time

---

src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Layer/layer.stories.js

Changes layer on mobile to make sure it takes full width and height
StyledLayer
manual
open full example on layer stories
no
yes
backwards

Fixed layer on mobile to take full width and height

---

src/js/components/Tab/StyledTab.js
src/js/components/Tab/Tab.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/themes/base.js

Changed Tabs base themeing
base.js
storybook
storybook
https://github.com/grommet/grommet/issues/2403
no
yes

Changed Tabs base themeing

---

src/js/components/Layer/layer.stories.js
src/js/components/TextArea/TextArea.js
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextInput/TextInput.js

Changed TextInput and TextArea to absorb Esc when focused
TextArea.js
storybook Layer Form
storybook Layer Form
https://github.com/grommet/grommet/issues/2409
no
yes

Changed TextInput and TextArea to absorb Esc when focused

---

src/js/components/Text/StyledText.js
src/js/components/Text/text.stories.js

Changed Text to fix an issue with arbitrary size
StyledText.js
storybook
storybook
https://github.com/grommet/grommet/issues/2435
no
yes

Changed Text to fix an issue with arbitrary size

---

src/js/components/AccordionPanel/doc.js
src/js/components/Anchor/doc.js
src/js/components/Box/doc.js
src/js/components/Button/README.md
src/js/components/Button/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed Button to add theme documentation
Button/doc.js
grommet-site
read
yes
yes

Changed Button to add theme documentation

---

src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/DataTable/Cell.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/datatable.stories.js

Changed DataTable to fix an issue with falsey values
DataTable/Cell.js
storybook
storybook
https://github.com/grommet/grommet/issues/2453
no
yes

Changed DataTable to fix an issue with falsey values

---

package.json
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
yarn.lock

updates local dev styled components dependency
package.json
unit testing / storybooks
unit testing / storybooks
no
no

update styled components dev dependency to 4.1.1

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/utils/styles.js
yarn.lock

Adding font weight styling to the theme
styles.js
storybook (using grommet.js)
sandbox for reproducing the problem https://codesandbox.io/s/j491nm309v
storybook (using grommet.js)
#2472 
Yes
No

font-weight styling in theme

---

src/js/components/Grid/grid.stories.js

Fix Grid App story to take full vertical area.
grid.stories.js
storybook
storybook
no
no
backwards compatible, no change to grommet proper.

Fix Grid story

---

src/js/components/Select/SelectContainer.js
src/js/themes/base.js
src/js/utils/debounce.js

Select - extracting debounce timer to global theme
src/js/components/Select/SelectContainer.js
storybook. verify the filter and timer are intact.
go to storybook->Select->Search and start typing.
one can change the debounceTimer values to see how it affects the search time. 
nope
#2451 
N/A
yes
no

Select - extracting debounce timer to global theme

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Drop/drop.stories.js
src/js/components/DropButton/dropbutton.stories.js

Changes drop container to have correct height when using bottom align
DropContainer place function
manual
open storybook UserMenu dropbutton example. also make sure the examples for dropbutton and drop dont regress.
Closes #2479 
no
yes

Fixed drop container height.

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/README.md
src/js/components/CheckBox/__tests__/CheckBox-test.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBox/checkbox.stories.js
src/js/components/CheckBox/doc.js
src/js/components/CheckBox/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/themes/base.js

Add indeterminate state to the CheckBox component
I would say the storybook for the rendering part. Maybe the color of the line should be neutral?
* it renders correctly
* warning when used with toggle checkboxes
* warning when both checked and indeterminate state is activated
#1323
Covered in the PR

Add indeterminate state for checkbox

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/README.md
src/js/components/Drop/__tests__/Drop-test.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Drop/doc.js
src/js/components/Drop/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Closes: #2376
Lets user control Drop elevation
Tested renders of default, theme and props elevation 
#2376 
covered in PR
compatible

Add elevation to available props of Drop component

---

package.json
src/js/components/Grommet/Grommet.js
src/js/components/Grommet/README.md
src/js/components/Grommet/__tests__/Grommet-test.js
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Grommet/doc.js
src/js/components/Grommet/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/themes/base.js
src/js/utils/responsive.js
yarn.lock

Alright this is more like an RFC process at the moment. There are a lot of things to consider which i'll try to list:
* should we use mobile-detect for this one. Seems like a great lib, but not sure if you feel ok including it in the dependencies of Grommet since it will only be used on SSR
* Haven't tested other libs for that matter. If anyone has something else to pitch in here
* How should this be done, for the moment i experimented with the headers being passed on as props, @atanasster suggested some other solutions here https://github.com/grommet/grommet/issues/2311#issuecomment-442768382 Plus maybe we should only receive the user-agent?
* I had to introduce a new value in the theme here `ssrBreakpoints`. Since the lib is only …

Improve SSR by trying to guess device width using mobile-detect

---

src/js/components/TextInput/README.md
src/js/components/TextInput/StyledTextInput.js
src/js/components/TextInput/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Adding doc for TextInput
doc.js
verification
verifying with the styled component
missing docs
Took care of that
no

TextInput doc theme

---

src/js/components/InfiniteScroll/InfiniteScroll.js

Fixed an issue with InfiniteScroll replace indexing
storybook
storybook
no
no

Fixed an issue with InfiniteScroll replace indexing

---

src/js/components/Box/Box.js
src/js/components/hocs.js

fix an unexpected issue with storybook after changing the require statement in box
manual
run storybook
no issue
no
no
backwards

Fixed storybook complaning about missing path.

---

src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Layer/layer.stories.js

properly center layer with margin
StyledLayer.js
manual
run new margin examples in storybook for layer
https://github.com/grommet/grommet/issues/2533
no
yes
backwards

Fixed regression with Layer margin.

---

src/js/components/Markdown/Markdown.js
src/js/components/Markdown/__tests__/Markdown-test.js
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap

Closes: #2515
Sorry i know this is nice for newcomers but i am needing it :/
IMHO the problem expands to #2522 but i ll let that for later
Adds the anchor component to the tag overrides in markdown.
storybook
storybook
compatible

[Markdown] Style anchors

---

src/js/components/Select/README.md
src/js/components/Select/Select.js
src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/Select/stories/select.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Closes: #2426
Add height option to the select component which is forwarded to the drop container
Modified the lots options of the storybook to include a height
storybook
#2426
did it
compatible

[Select] Add option to limit height of the drop container

---

src/js/components/Select/stories/select.stories.js

Applying search by label to Select - Object Multiple story
select.stories.js
storybook 
storybook Select - Object Multiple
#2549 
no
np

Select - Object Multiple story

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap

Closes #2531 helps with #2521 
Changes checkbox to fix an issue with accessibility. also passes the themeable props down to the theme object extend function.
Checkbox
manual
storybook checkbox examples
#2531 
no
yes
backwards

Fixed accessibility for Checkbox

---

src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/base.js

Fixed some incorrect color values
base.js
storybook
storybook
no
no

Fixed some incorrect color values

---

package.json
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Collapsible/Collapsible.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Drop/DropContainer.js
src/js/components/Grommet/Grommet.js
src/js/components/Layer/LayerContainer.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/RangeSelector/RangeSelector.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Video/Video.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/hocs.js
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/base.js
yarn.lock

Moves to grommet icons v4
everywhere?
manual storybook
open every storybook story
no
no
yes!!!!!
backwards, but you need to install `grommet-styles` peer dependency

move to grommet-icons v4

---

src/js/components/InfiniteScroll/infinitescroll.stories.js

Added onMore story for InfiniteScroll.
No changes to production grommet code, documentation, or tests.

Added onMore story for InfiniteScroll

---

src/js/components/Anchor/anchor.stories.js
src/js/components/Button/button.stories.js
src/js/components/Calendar/calendar.stories.js
src/js/components/Carousel/carousel.stories.js
src/js/components/Chart/chart.stories.js
src/js/components/CheckBox/checkbox.stories.js
src/js/components/Clock/clock.stories.js
src/js/components/DataTable/datatable.stories.js
src/js/components/Diagram/diagram.stories.js
src/js/components/DropButton/dropbutton.stories.js
src/js/components/FormField/formfield.stories.js
src/js/components/Markdown/markdown.stories.js
src/js/components/MaskedInput/maskedinput.stories.js
src/js/components/Menu/menu.stories.js
src/js/components/Meter/meter.stories.js
src/js/components/RadioButton/radiobutton.stories.js
src/js/components/RangeInput/rangeinput.stories.js
src/js/components/RangeSelector/rangeselector.stories.js
src/js/components/Table/table.stories.js
src/js/components/TextArea/textarea.stories.js
src/js/components/TextInput/textinput.stories.js
src/js/components/Video/video.stories.js
src/js/components/WorldMap/worldmap.stories.js

Cleaned up stories to be more visually appealing.
No production code, documentation, or test changes, just story updates.

Cleaned up stories to be more visually appealing

---

src/js/components/MaskedInput/__tests__/MaskedInput-test.js
src/js/components/Select/SelectContainer.js
src/js/components/Select/StyledSelect.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

manual
open lots of options story select example
no issue
no
yes
backwards

Added fix for dropHeight in Select to use max height instead of height.

---

src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/Menu/README.md
src/js/components/Menu/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Adding docs for Menu theme
doc.js
improving docs
done
no

Menu - theme docs

---

src/js/components/Markdown/Markdown.js
src/js/components/Markdown/README.md
src/js/components/Markdown/doc.js
src/js/components/Markdown/index.d.ts
src/js/components/Markdown/markdown.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Closes: #2574
Adds an example and documentation on markdown component overrides
stoirybook
#2574
no code changes here. only doc and storybook

Added an example and doc of component overrides in markdown

---

src/js/components/Layer/README.md
src/js/components/Layer/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

add docs for theme layer
doc.js
improving docs
no

Layer -  theme docs

---

src/js/components/Accordion/index.d.ts
src/js/components/Anchor/index.d.ts
src/js/components/Button/index.d.ts
src/js/components/Calendar/index.d.ts
src/js/components/Chart/index.d.ts
src/js/components/CheckBox/index.d.ts
src/js/components/Clock/index.d.ts
src/js/components/DataTable/index.d.ts
src/js/components/Distribution/index.d.ts
src/js/components/Drop/index.d.ts
src/js/components/DropButton/index.d.ts
src/js/components/InfiniteScroll/index.d.ts
src/js/components/Keyboard/index.d.ts
src/js/components/Layer/index.d.ts
src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/MaskedInput/index.d.ts
src/js/components/Meter/index.d.ts
src/js/components/RadioButton/index.d.ts
src/js/components/RangeInput/index.d.ts
src/js/components/RangeSelector/index.d.ts
src/js/components/Select/index.d.ts
src/js/components/Tabs/index.d.ts
src/js/components/TextArea/index.d.ts
src/js/components/TextInput/index.d.ts
src/js/components/WorldMap/index.d.ts
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
yarn.lock

Updates typescript autogenerated files
any file changed
fresh clone of grommet core
`yarn test`
(fresh clone of grommet core, and run `yarn test` you'll see these file updated.)
recently updated react-desc
none
n/a
no
no

typescript updates

---

src/js/components/Select/README.md
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/TextInput/README.md
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/TextInput/doc.js
src/js/components/TextInput/index.d.ts
src/js/components/TextInput/textinput.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Changed TextInput to add dropHeight.
TextInput/doc.js
storybook
storybook
For the same reasons that Select has it.
automatic
yes

Changed TextInput to add dropHeight

---

src/js/components/Layer/README.md
src/js/components/Layer/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

adds background doc to Layer theme
doc.js
verifying with the styled file
you can see it here https://codesandbox.io/s/5k8rr2l21k
#2594
done
no

Layer - add theme background

---

src/js/components/Box/Box.js
src/js/components/Box/box.stories.js
src/js/components/Carousel/Carousel.js
src/js/components/Diagram/Diagram.js
src/js/components/Drop/drop.stories.js
src/js/components/Form/README.md
src/js/components/Form/doc.js
src/js/components/Menu/Menu.js
src/js/components/Select/SelectContainer.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
yarn.lock

Changed Form to improve documentation.
Updated dependencies.
Fixed some new lint issues.
Form/doc.js
storybook
storybook
automatic
no

Changed Form to improve documentation

---

src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/themes/base.js

Intermediately addressing Heading issues
base.js
storybook
storybook
not for this PR
no

Heading sizing

---

src/js/components/DataTable/Body.js
src/js/components/DataTable/Cell.js
src/js/components/DataTable/DataTable.js
src/js/components/DataTable/Footer.js
src/js/components/DataTable/README.md
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/buildState.js
src/js/components/DataTable/doc.js
src/js/components/DataTable/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap

Changed DataTable to add primaryKey.
Added documentation for DataTable `columns` `primary`.
DataTable/doc.js
storybook
storybook
https://github.com/grommet/grommet/issues/2616
automatic
yes

Changed DataTable to add primaryKey

---

src/js/components/Markdown/Markdown.js
src/js/components/Markdown/__tests__/Markdown-test.js
src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
src/js/components/Markdown/markdown.stories.js

Changed Markdown to use Image and Table
Markdown.js
storybook
storybook
https://github.com/grommet/grommet/issues/2573
no
yes

Changed Markdown to use Image and Table

---

netlify.toml

publish-storybook

---

src/js/index.d.ts

Fixes ts definitions to add Form
components/index.d.ts
manual
run test
https://twitter.com/bruno_cardosor/status/1083177993294569472
no
yes
backwards

Added Form to the typescript definition.

---

src/js/components/Chart/README.md
src/js/components/Chart/doc.js
src/js/components/Chart/index.d.ts
src/js/components/Meter/README.md
src/js/components/Meter/doc.js
src/js/components/Meter/index.d.ts
src/js/components/Select/README.md
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/__tests__/__snapshots__/typescript-test.js.snap
src/js/contexts/ThemeContext/index.d.ts

Fix intrinsic type issues with Meter, Chart, and Select.
no
yes

Fix intrinsic type issues

---

src/js/contexts/ResponsiveContext/doc.js
yarn.lock

responsive - update docs

---

src/js/components/TextInput/index.d.ts
src/js/index.d.ts

This PR adds the missing export of the `<MaskedInput />` typings.

Export MaskedInput typings

---

src/js/components/Grommet/README.md
src/js/components/Grommet/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

adding theme doc for Grommet component
doc.js
grommet-site and verify with StyledGrommet.js theme usage
improving docs
#2690 
done + auto
no

Grommet - theme doc

---

src/js/components/Video/README.md
src/js/components/Video/StyledVideo.js
src/js/components/Video/Video.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/Video/doc.js
src/js/components/Video/video.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js
yarn.lock

adding theme docs for the video component
@MikeWalrath let's tag this one on the issue you are filing
done + auto
nop

Video - adding theme doc

---

src/js/components/Meter/StyledMeter.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Meter/meter.stories.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Meter to fix an issue with animation on Chrome.
StyledMeter.js
storybook
storybook
https://github.com/grommet/grommet/issues/2683
no
yes

Changed Meter to fix  an issue with animation on Chrome, #2683

---

src/js/components/Video/StyledVideo.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Video to fix scrubber issue #2666
StyledVideo.js
storybook
storybook
https://github.com/grommet/grommet/issues/2666
no
yes

Changed Video to fix scrubber issue #2666

---

src/js/components/Diagram/Diagram.js
src/js/components/Diagram/diagram.stories.js

Changed Diagram to re-place when connections change.
Diagram.js
storybook
storybook
https://github.com/grommet/grommet/issues/2677
no
yes

Changed Diagram to re-place when connections change. Fixes #2677

---

src/js/components/Collapsible/README.md
src/js/components/Collapsible/doc.js
src/js/components/Diagram/Diagram.js
src/js/components/Diagram/README.md
src/js/components/Diagram/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js
yarn.lock

adding theme doc for Diagram
doc.js
storybook and verifying with StyledDiagram
storybook and verifying with StyledDiagram
#2690 
auto + done
nope

Diagram - theme doc

---

src/js/components/RadioButtonGroup/RadioButtonGroup.js
src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap

Change RadioButtonGroup to fix an issue on Chrome
This was a remaining change from the original addition of RadioButtonGroup.
RadioButtonGroup.js
storybook on Safari, Firefox, Chrome
storybook on Safari, Firefox, Chrome
no
no

Change RadioButtonGroup to fix an issue on Chrome

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap

Changed CheckBox to fix z-index issue #2653 
CheckBox.js
storybook
storybook
https://github.com/grommet/grommet/issues/2653
no
yes

Changed CheckBox to fix z-index issue #2653

---

src/js/components/TextInput/StyledTextInput.js

Changed TextInput to fix node placeholder issue #2584
StyledTextInput.js
storybook
storybook
https://github.com/grommet/grommet/issues/2584
no
yes

Changed TextInput to fix node placeholder issue #2584

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/README.md
src/js/components/Meter/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

adding theme docs to Meter
doc.js
verification with the styled meter components
verification with the styled meter components
#2690 
nope
no

Meter - theme doc

---

storybook/manager-head.html

Use grommet font for storybook manager
local storybook
local storybook
https://github.com/grommet/grommet/issues/2715
no
no

Use grommet font for storybook manager

---

src/js/components/TextInput/index.d.ts

Changed TextInput to fix type for size
TextInput/index.d.ts
new typescript app I'm working on
no
yes

Changed TextInput to fix type for size

---

src/js/components/Chart/README.md
src/js/components/Chart/doc.js
src/js/components/Heading/README.md
src/js/components/Heading/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

adding theme docs for Heading and Chart
doc.js
verify with the components impl
done + auto
no

theme docs for Heading and Chart

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap

Fixes the toggle mode of the checkbox
CheckBox.js
storybook
storybook - all examples that are related to toggling specifically 
#2742 
no
yes

Fixes CheckBox toggle

---

src/js/components/InfiniteScroll/InfiniteScroll.js

Changed InfiniteScroll to fix initial load issue #2644
storybook with Simple test tuned down to step={3}
same as above
https://github.com/grommet/grommet/issues/2644
no
yes

Changed InfiniteScroll to fix initial load issue #2644

---

src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/infinitescroll.stories.js

Changed InfiniteScroll to fix grid issue #2646.
new storybook story
new storybook story, and verify old ones still work too
Prior to these changes, InfiniteScroll was only able to handle single column items layout.
With these changes, InfiniteScroll can now handle items being laid out in a grid.
https://github.com/grommet/grommet/issues/2646
no
yes

Changed InfiniteScroll to fix grid issue #2646

---

src/js/components/Box/README.md
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

This will add to the documentation to the Box component
props
#2752
#2753
box/doc.js
Verification 
#2752
#2753
Its been auto updated 
no

Update missing documentation for Box component

---

src/js/components/Box/Box.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/box.stories.js

Changed Box to fix elevation darkness issue #2361
Box.js
storybook Box - Elevation
storybook Box - Elevation
https://github.com/grommet/grommet/issues/2361
no
yes

Changed Box to fix elevation darkness issue #2361

---

src/js/components/Button/StyledButton.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Button to fix icon align issue #2728
storybook
storybook
https://github.com/grommet/grommet/issues/2728
no
yes

Changed Button to fix icon align issue #2728

---

src/js/components/CheckBox/StyledCheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap

Fix : #2772
storybook
c/p the codesandbox in storybook to verify
#2772
no
yes
compatible

Fix issue with checkbox box shrinking

---

src/js/components/RangeSelector/EdgeControl.js
src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap

Changed RangeSelector to add theme edge type
RangeSelector.js
nineties theme
eventually, when RangeSelector theme documentation is created.
yes

Changed RangeSelector to add theme edge type

---

src/js/components/Drop/__tests__/Drop-test.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Grid/__tests__/Grid-test.js
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
src/js/components/Menu/__tests__/Menu-test.js
src/js/components/RoutedAnchor/__tests__/RoutedAnchor-test.js
src/js/components/RoutedButton/__tests__/RoutedButton-test.js

Fix tests errors and warnings
any test file
`yarn test-update`
`yarn test-update`
no
no

Fix tests errors and warnings

---

src/js/components/Box/README.md
src/js/components/Box/doc.js
src/js/components/Heading/heading.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

fixes the docs for Box and adding custom theme for heading
doc.js
`yarn-test-update`
`yarn-test-update` not throwing error
storybook for heading -> custom theme
discussions with Eric
done
no

fixes follow-up

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Button/Button.js
src/js/components/Button/__tests__/Button-test.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/Button/button.stories.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Changed Button to pass interactive state to children render function.
Button.js
storybook Button - Sidebar
storybook Button - Sidebar
https://github.com/grommet/grommet/issues/2554
yes
yes

Changed Button to pass interactive state to children render function.

---

src/js/components/Anchor/README.md
src/js/components/Anchor/doc.js
src/js/components/Carousel/README.md
src/js/components/Carousel/doc.js
src/js/components/Grid/README.md
src/js/components/Grid/doc.js
src/js/components/Heading/README.md
src/js/components/Heading/doc.js
src/js/components/Text/README.md
src/js/components/Text/doc.js
src/js/components/TextArea/README.md
src/js/components/TextArea/doc.js
src/js/components/TextInput/README.md
src/js/components/TextInput/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Fix a bunch of issues with the docs
related issues:
#2803 #2801 #2797 #2798 #2799 #2792 #2793

Fix issues in components documentation

---

src/js/components/Button/README.md
src/js/components/Button/doc.js
src/js/components/Menu/Menu.js
src/js/components/Menu/README.md
src/js/components/Menu/doc.js
src/js/components/Menu/menu.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Menu to allow child render function, issue #2310
Menu.js
Added story for Menu Custom
storybook
#2310 
yes, automatic
yes

Changed Menu to allow child render function, issue #2310

---

src/js/components/Menu/Menu.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Menu/menu.stories.js

Fix: #2766
Add disable property on menu items
storybook
#2766 
right now the items are not documented. wonder whether we should
yes
yes

Add disabled property on menu items

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Button/Button.js

Changed Button to fix Select issue #2809
Button.js
storybook
storybook
https://github.com/grommet/grommet/issues/2809
no
yes

Changed Button to fix Select issue #2809

---

.circleci/config.yml

Try releasing stable on circleci

---

.travis.yml

Turn off testing and release-stable with TravisCI

---

.circleci/config.yml

Add the build command to the release stage

---

src/js/components/RoutedButton/__tests__/RoutedButton-test.js
src/js/components/TextArea/textarea.stories.js
src/js/themes/base.js

* enhance story for TextArea to include theme
* test warning clean-ups
story and then test files
* `yarn test-update`
* storybook
* `yarn test-update`
* storybook
#2819 
no
no

TextArea story to include custom theme and tests cleanups

---

src/js/components/FormField/FormField.js

FormField.js
storybook
open storybook Form example, once you click update you should see the required field working now
Closes #2838 
no
yes
backwards

Fixed formfield validate to handle required fields.

---

.circleci/config.yml

Release on npm with git tags.
In order for this to work we would need to set the variable `NPM_TOKEN`

Release using git tags

---

.circleci/config.yml

Adding checkout filter to CircleCI config

Adding checkout filter to CircleCI config

---

src/js/components/Accordion/accordion.stories.js
src/js/components/AccordionPanel/AccordionPanel.js
src/js/components/AccordionPanel/README.md
src/js/components/AccordionPanel/doc.js
src/js/components/Box/StyledBox.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

This PR  moves accordion border into theme for the border colors which is related to issue #2722 
This PR also provides an example in storybook for the custom colors.
src/js/components/AccordionPanel/AccordionPanel.js
none
#2722 
automatic
no

Added theme to change color on border accordion & example for storybook

---

src/js/components/Form/__tests__/Form-test.js
src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap

Follow up on recent Prs fixing formfield issues to add tests
#2838 
#2813 
tests
nope
nope
yes

Add tests for required and regex validation

---

src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/dark.js

Changed dark theme to fix light background context issue #2781 
dark.js
storybook, all components, dark theme, change backgrounds
storybook, all components, dark theme, change backgrounds
#2781 
no
yes

Changed dark theme to fix light background context issue #2781

---

src/js/themes/dark.js

Changed dark theme to fix an issue with input border on light backgrounds.
Just removed the theme border color to fall back on the base one, which is fine.
dark.js
storybook - All Components + theme selector + background selector
storybook - All Components + theme selector + background selector
#2781 
no
no

Changed dark theme to fix an issue with input border on light backgrounds

---

src/js/components/Drop/drop.stories.js

Added Drop Tooltip story
Related to #2660

Added Drop Tooltip story

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Grommet/README.md
src/js/components/Grommet/StyledGrommet.js
src/js/components/Grommet/__tests__/Grommet-test.js
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/components/Grommet/doc.js
src/js/components/Grommet/grommet.stories.js
src/js/components/Grommet/index.d.ts
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap

Grommet component to allow css vars, fixes #2582
doc.js
storybook -> Grommet -> Vars
Go to storybook -> Grommet -> Vars, the rest of the directions is there
#2582
done
Yes

Grommet component to allow css vars, fixes #2582

---

src/js/components/TextInput/textinput.stories.js

Adds a passwordinput in the storybook.
It came 2-3 times already the last month so maybe exposing one directly could help.
- Not entirely happy with my choice of icons. 
storybook
storybook
storybook
no
no
compat

Add password input in stories

---

package.json

Just noticed a sudden drop in percentage and didn't understand why until i saw the files.

Don't include stories in coverage reporting

---

src/js/components/Box/README.md
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/Button/README.md
src/js/components/Button/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Closes: #2800 #2790 #2751
Various doc improvements:

Various theme doc improvements

---

src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap

Fix CheckBox snapshots
unit
unit
no
no

Fix CheckBox snapshots

---

src/js/components/Clock/README.md
src/js/components/Clock/clock.stories.js
src/js/components/Clock/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

The PR adds the themes to the documentation for clock 
Also adds an example for a custom clock in storybook
Clock/doc.js
#2690
auto
No

added to clock docs which adds to the issue #2690

---

src/js/utils/styles.js

adding control.border.color to input style
#2900  
Yes, in https://github.com/grommet/grommet/pull/2899
no

adding control.border.color to input style

---

src/js/components/Tabs/README.md
src/js/components/Tabs/doc.js
src/js/components/Tabs/tabs.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Adds to the tabs documentation 
src/components/tabs/docs.js
#2817 
auto 
no

Added to tabs docs

---

.circleci/config.yml
package.json
yarn.lock

Fix: #2921
Adds a ci test for bundlesize to keep an eye on growing size 
#2917 
#2921 
no
no
compatible

Add bundlesize test

---

src/js/components/Tab/README.md
src/js/components/Tab/doc.js
src/js/components/Tabs/README.md
src/js/components/Tabs/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

fix missing types of Tab/s docs. (and some more types along the way)
doc.js
https://github.com/grommet/grommet-docs/issues/318
done
no

Fix Tabs on grommet-site

---

src/js/components/Diagram/diagram.stories.js

Changes the Storybook story of Diagram to not draw a swastika.
Run `npm run storybook` and look at the Diagram story
Tested new story
Some people aren't big fans of swastikas
Before:
After:
No
No

Changed diagram story to remove swastika

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/README.md
src/js/components/Calendar/__tests__/Calendar-test.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/doc.js
src/js/components/Calendar/index.d.ts
src/js/components/Calendar/stories/CustomHeader.js
src/js/components/Calendar/stories/DaylightSavings.js
src/js/components/Calendar/stories/Dual.js
src/js/components/Calendar/stories/Range.js
src/js/components/Calendar/stories/Simple.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Allows seeing days of the week on Calendar
doc.js
storybook
storybook, specifically the Simple Calendar example
this PR approach derived from https://github.com/grommet/grommet/pull/2929
closes: #2919
done
yes

Calendar - adding days of week

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBox/checkbox.stories.js

changes checkbox to skip adding margin right if there is not label
CheckBox.js
manual
open storybook examples for checkbox and make sure nothing breaks. I also added a new example of a checkbox without a label.
no
yes
backwards

Changed CheckBox to apply gap only when there is label.
