src/js/components/Button/stories/Sidebar.js

Changed Button Sidebar story to include active state
storybook
storybook
no
no

Changed Button Sidebar story to include active state

---

src/js/components/Select/README.md
src/js/components/Select/Select.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/Select/stories/select.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

changes Select to add a new prop called `icon`.
Select.js
manual
open storybook Select examples and make sure nothing breaks. also make sure the new ones allow for a custom icon or no icon.
Closes #2935 
yes
yes
backwards

Added select icon prop to replace the Select icon on the fly.

---

src/js/components/Box/box.stories.js

Fixes storybook 
storybook
storybook
#2959
Docs are ok, grommet-site has an issue
no
yes

Fix storybook border style

---

src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

adds doc to FormField theme
#2690 
no

FormField - add theme doc

---

src/js/components/Select/SelectContainer.js

- Store initial values in state in order to handle selection values and indexes based on that
- Reworked the selection handler to reason based on value instead of soon to be deprecated selected. 
played a lot on storybook. also verified that no regression is present when user uses `selected` prop with this component in storybook
```
<Select
id="mult"
name="mult"
placeholder="Select"
multiple
selected={selected}
options={options}
onChange={({ selected: nextSelected }) =>
this.setState({ selected: nextSelected })
}
{...rest}
/>
```
storybook. Paths i already checked:
- simple selection
- searching and then select stores correct values
- multiple select with/without searching
- selecting already selected in multiple select removes the selection
#2961 
no
yes
compatible

Refactor selection handling

---

src/js/components/DropButton/README.md
src/js/components/DropButton/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

DropButton - docs

---

src/js/components/AccordionPanel/README.md
src/js/components/AccordionPanel/doc.js
src/js/components/DataTable/README.md
src/js/components/DataTable/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

DataTable - adding theme doc

---

src/js/components/MaskedInput/maskedinput.stories.js

Example story for timeMaskedInput inside drop button
Added a story for using MaskedTextInput inside a drop button. 
maskedinput.stories.js
storybook
storybook
#2918 
No
Yes
Yes

Example story for timeMaskedInput inside drop button

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap

DropContainer height calculations handled.
Changed maxHeight for container as user scrolls through page after opening dropdown.
Storybook
Storybook
#2994 
No.
Yes
Yes

DropContainer height calculation modified

---

src/js/components/RadioButtonGroup/index.d.ts

* Fixes #2958
Not sure if this needs to be documented too.

add Box props to RadioButtonGroup typings

---

src/js/components/FormField/FormField.js
src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/FormField/formfield.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Fixes `component` prop of <FormField /> component.
Fixes: https://github.com/grommet/grommet/issues/2981

Changed propType's to object for `component` prop

---

src/js/components/FormField/FormField.js
src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/FormField/formfield.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Revert "Changed propType's to object for `component` prop"

---

src/js/components/Button/index.d.ts

add typescript support for Button gap
index.d.ts
TS tests
completing PR #3054 
#3015 
N/A
no
no

[TS] - add typescript support for Button gap

---

src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/utils/colors.js

Added support for hsl() background color
colors.js
Box unit test
white box testing with storybook
#3009 
no?
yes

Added support for hsl() background color

---

src/js/components/Heading/index.d.ts

fixes typescript of Heading level
index.d.ts
https://codesandbox.io/s/l0z8ply9l
https://codesandbox.io/s/l0z8ply9l
N/A
#2981 - On its sandbox example I noticed the level issue on Heading
N/A
no
no

[TS] fixes Heading level types

---

src/js/components/Form/form.stories.js
src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

extending the info and requirements for FormField component
doc.js
no
no

FormField - refine docs

---

src/js/components/FormField/index.d.ts

Patches the typings for component prop for formfield
https://github.com/grommet/grommet/pull/3027
This is a patch so there are no breaking changes.

[TS] type refinement for FormField - any patch

---

src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/__tests__/Meter-test.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap

Closes: #3094 
Fixes a bug when setting size value in the meter component 
Any of Bar or Circle. fix is identical
added unit-test &  tested manually 
#3094 
Screenshots (if appropriate)
nope
Is this change backwards compatible or is it a breaking change?
compatible

Added to size for meter to take into account a string also provided test

---

src/js/components/TextInput/stories/textinput.stories.js

fix issue #3097 
textinput.stories.js
manual 
storybook
#3097 
no
no
compatible

Fixed password showing to fit with icon

---

src/js/components/Form/Form.js

Fixed an issue with Form not delivering onChange.
Form.js
Integrated this change into a new internal HPE product.
storybook?
#3104 
no
yes

Fixed an issue with Form not delivering onChange.

---

src/js/components/Distribution/README.md
src/js/components/__tests__/__snapshots__/README-test.js.snap
yarn.lock

Updated dependencies.
yarn.lock
unit
unit
no
no

Updated dependencies

---

src/js/components/TextArea/README.md
src/js/components/TextArea/StyledTextArea.js
src/js/components/TextArea/__tests__/TextArea-test.js
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextArea/doc.js
src/js/components/TextArea/index.d.ts
src/js/components/TextInput/StyledTextInput.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed TextArea to add size
StyledTextArea.js
unit
unit
#2819 
yes
yes

Changed TextArea to add size

---

src/js/components/Select/README.md
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/Text/index.d.ts
src/js/components/TextInput/README.md
src/js/components/TextInput/doc.js
src/js/components/TextInput/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Fix: #3139, #3169, #3167
Fixes a few typescript issues
for the element in placeholder i tried this in sandbox
#3139, #3169, #3167
done
just ts improvement mention
yes

Fix some typescript definitions issues

---

src/js/components/Carousel/Carousel.js
src/js/components/Carousel/README.md
src/js/components/Carousel/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

…nd duration of the carousel animation
Add the ability to set the color/disabled color for carousel Next, Previous icons,
Add the ability to set the duration of the carousel animation
#3175 
use the storybook
#3175 
yes
yes
non-breaking

Addition configuration for Carousel theme

---

src/js/components/DataTable/Searcher.js
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap

fix DataTable's bug
Searcher.js
If #3121 is merged, I can write an unit test.
Storybook
backword compatible

fix(DataTable): focus input on search 

---

src/js/components/Layer/README.md
src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/Layer-test.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/Layer/doc.js
src/js/components/Layer/index.d.ts
src/js/components/Layer/layer.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed Layer to add animation property
doc.js
unit
storybook (Full)
same
This was motivated by needing something less rich than sliding but a bit more than nothing for grommet-designer layers that are frequently used.
yes
yes

Changed Layer to add animation property

---

src/js/components/Select/README.md
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Select to allow more types of options
doc.js
automatic
yes

Changed Select to allow more types of options

---

src/js/components/Carousel/carousel.stories.js
src/js/components/Heading/heading.stories.js
src/js/components/Layer/layer.stories.js
src/js/components/Markdown/markdown.stories.js
src/js/components/RadioButton/radiobutton.stories.js
src/js/components/Stack/stack.stories.js
src/js/components/TextInput/stories/Tag.js
src/js/components/TextInput/stories/textinput.stories.js
src/js/components/WorldMap/worldmap.stories.js

Inspired by #3212  , but there is still more work to be done there.
This PR is removing redundancy from the stories title. start with any story file.

Refine Stories

---

src/js/components/RadioButton/README.md
src/js/components/RadioButton/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

This PR updates the documentation for RadioButton
RadioButton/doc.js
yarn update-tests
#2690 
auto
no

Update RadioButton documentation

---

src/js/components/Button/README.md
src/js/components/Button/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

attempting to solve misunderstanding occurred on  #3202

Button - adding active style docs to theme

---

src/js/components/RangeSelector/RangeSelector.js

PR fixes "React state update on an unmounted component" error. No impact on any existing functionality.
Tested fix locally to ensure memory leak is fixed and there are no regressions.

fix(RangeSelector): fixes mouseup event handler cleanup

---

src/js/components/Grid/stories/App.js
src/js/components/Grid/stories/NColumn.js
src/js/components/Grid/stories/Percentages.js
src/js/components/Grid/stories/Responsive.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/stories/textinput.stories.js
yarn.lock

1. Decouple stories of Grid
2. Replacing stories with hook
3. Fix icon reference
anywhere
storybook
relevant stories
3097
no
no

Clean ups - hooks, decoupling stories and icon fix

---

src/js/contexts/ResponsiveContext/responsive-context.stories.js

Quick refactor to show usage of ResponsiveContext using hooks
the responsive grid story
the responsive grid story
the responsive grid story
#2556 
nope
no

ResponsiveContext - hooks example

---

src/js/components/WorldMap/index.d.ts

Added ColorType to WorldMap index.d.ts
js/components/WorldMap/index.d.ts
Manually tested by branching out to a typescript project.
Issue #3237

Add ColorType to WorldMap index.d.ts

---

src/js/components/Carousel/README.md
src/js/components/Carousel/carousel.stories.js
src/js/components/Carousel/doc.js
src/js/components/Carousel/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/utils/index.d.ts

Compliments #3176 
doc.js
storybook
storybook
#2629 
done
part of #3176 

Carousel - refine docs, types and stories

---

src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
src/js/components/DataTable/Body.js
src/js/components/DataTable/DataTable.js
src/js/components/DataTable/README.md
src/js/components/DataTable/StyledDataTable.js
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/doc.js
src/js/components/DataTable/stories/datatable.stories.js
src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/TableBody/TableBody.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/themes/base.js
src/js/utils/styles.js

Changed DataTable to add `onClickRow`
doc.js
unit test, added storybook, used with grommet-data
storybook
should be automatic?
yes

Changed DataTable to add onClickRow

---

src/js/components/Box/index.d.ts

TS fix
index.d.ts
Resulted from a slack conversation
None
no
As a general TS fix 
yes

Added missing type for Box justify

---

src/js/components/Accordion/index.d.ts
src/js/components/Calendar/index.d.ts
src/js/components/Layer/index.d.ts
src/js/utils/index.d.ts

Please the commit message for your changes. Lines starting
Extracts animate type 
utils/index.d.ts
manually
#3237 
no
no

Extract animate type

---

src/js/components/Form/index.d.ts

Update onSubmit type to be more specific to the event 
Form/index.d.ts
manually 
write onSubmit function in TS app 
Since we are using ``` JSX.IntrinsicElements['form'] ``` this includes the 
HTML form elements so we just need to add the react event handling
#3165 
no
no

Changed onSubmit type

---

src/js/components/MaskedInput/stories/Date.js
src/js/components/MaskedInput/stories/DateTimeDrop.js
src/js/components/MaskedInput/stories/Email.js
src/js/components/MaskedInput/stories/Filtered.js
src/js/components/MaskedInput/stories/IPv4Address.js
src/js/components/MaskedInput/stories/Phone.js
src/js/components/MaskedInput/stories/Time.js

Changed MaskedInput stories to use hooks.
Added "Filtered" MaskedInput story
stories
storybook
storybook
#3344
no
no

Changed MaskedInput stories to use hooks

---

src/js/components/Image/Image.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Image to support ref
Image.js
photofeed
no
yes

Changed Image to support ref

---

README.md

grammatical mistake

---

src/js/components/Box/index.d.ts

This PR is a follow up of a comment made by @oorestisime on @shabtaisharon PR. 
https://github.com/grommet/grommet/pull/3362
https://github.com/grommet/grommet/pull/3362/files#r326857694

TypeScript Box border - Adding reusable types

---

src/js/components/Accordion/README.md
src/js/components/Accordion/doc.js
src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/Heading/README.md
src/js/components/Heading/doc.js
src/js/components/Markdown/README.md
src/js/components/Markdown/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Fix spelling in `doc.js` files and correct the corresponding `README.md` files
`src/js/components/Accordion/doc.js`
No code changes in this PR
No code changes in this PR
N/A
N/A
Yes
No

Fix spelling in doc.js files and correct the corresponding README.md

---

src/js/components/Image/stories/Fallback.js
src/js/components/Image/stories/Fit.js
src/js/components/Image/stories/Opacity.js
src/js/components/Image/stories/Simple.js

Split the Image stories
Image section in storybook
No code change in this PR
Image section in storybook
N/A
#3212 
No
No
Backward compatible

Split Image stories

---

src/js/components/FormField/stories/Select.js

Refactor `src/js/components/FormField/stories/Select.js` using Hooks
`src/js/components/FormField/stories/Select.js`
https://github.com/grommet/grommet/issues/3394
N/A
No
No

Refactored Select story in FormField using Hooks

---

src/js/components/FormField/stories/Select.js
src/js/components/FormField/stories/TextInput.js

Refactor `src/js/components/FormField/stories/TextInput.js` using Hooks
`src/js/components/FormField/stories/TextInput.js`
N/A
https://github.com/grommet/grommet/issues/3394
N/A
No
No

Refactored TextInput story in FormField using Hooks

---

src/js/components/CheckBox/stories/CheckBoxInsideButton.js

Refactor `src/js/components/CheckBox/stories/CheckBoxInsideButton.js` using Hooks
`src/js/components/CheckBox/stories/CheckBoxInsideButton.js`
Running `yarn test` and `yarn storybook` and tested the component behavior.
N/A
#3394 
N/A
No
No

Refactor CheckBoxInsideButton story in CheckBox using Hooks

---

src/js/components/RangeInput/RangeInput.js

Refactor `src/js/components/RangeInput/RangeInput.js` to be functional
`src/js/components/RangeInput/RangeInput.js`
Running `yarn test` and `yarn storybook` and tested the component behavior.
N/A
#3394
N/A
No
No

Refactor RangeInput to be a functional component

---

src/js/components/CheckBox/stories/Basics.js

Refactor `src/js/components/CheckBox/stories/Basics.js` using Hooks
`src/js/components/CheckBox/stories/Basics.js`
Regression using `yarn test`
Through storybook.
#3394
N/A
No
No

Refactor Simple Checkbox Story to Use Hooks

---

src/js/components/DataTable/stories/ControlledGrouped.js

Refactor `src/js/components/DataTable/stories/ControlledGrouped.js` using Hooks
`src/js/components/DataTable/stories/ControlledGrouped.js`
Running `yarn test` and `yarn storybook` and tested the component behavior.
N/A
#3394 
N/A
No
No

Refactor ControlledGroupedDataTable story in DataTable using Hooks

---

src/js/components/RadioButton/RadioButton.js

Refactor `src/js/components/RadioButton/RadioButton.js` to be functional
`src/js/components/RadioButton/RadioButton.js`
Running `yarn test` and `yarn storybook` to test its behaviour
Run `yarn test`
No
#3394 
N/A
No
No
No

Refactor RadioButton Component to be functional

---

src/js/components/RangeSelector/stories/Custom.js

Refactor `src/js/components/RangeSelector/stories/Custom.js` to be functional and use Hooks
`src/js/components/RangeSelector/stories/Custom.js`
Running `yarn storybook` to check its behaviour
Run `yarn storybook`
No
#3394
N/A
No
No
No

Refactor RangeSelector Custom Story to use Hooks

---

src/js/components/Drop/stories/Tooltip.js

Refactor `src/js/components/Drop/stories/Tooltip.js` using Hooks.
`src/js/components/Drop/stories/Tooltip.js`
Running `yarn test` and `yarn storybook` and tested the component behavior.
N/A
#3394 
N/A
No
No

Refactor TooltipDrop using Hooks

---

src/js/components/RangeSelector/stories/Basics.js

Refactor `src/js/components/RangeSelector/stories/Basics.js` to be functional and use Hooks!
`src/js/components/RangeSelector/stories/Basics.js`
Running `yarn storybook` to test its behaviour
Run `yarn storybook` and check if everything is ok
No
#3394 
N/A
No
No
No

Refactor RangeSelector Basic Story to use Hooks

---

src/js/contexts/ResponsiveContext/doc.js

Updates component documentation
ResponsiveContext/doc.js
#3394 
Yes

Updated ResponsiveContext doc to use hooks.

---

src/js/components/SkipLinks/SkipLinks.js

Convert SkipLinks Component to Hooks
`src/js/components/SkipLinks/SkipLinks.js`
`yarn test`
`yarn test`
N/A
#3394
N/A
No
No
Backward compatible

Convert SkipLinks component to Hooks

---

src/js/components/RangeSelector/EdgeControl.js

Refactor stories at `src/js/components/Select` to be functional components
The order doesnt matter
I tested the components with the storybook
Using `yarn storybook` and checking its behaviour
No
#3394 
N/A
No
No
No

Refactor RangeSelector EdgeControl to be functional

---

CONTRIBUTING.md

update contribution docs
contributing docs doesn't really show how to run/see our local changes. I got this info from one of my reviewers till then I could not figure out how to run my changes. so this should help the future contributors.
no
no

update contribution docs

---

src/js/components/Markdown/Markdown.js

Markdown component was a class component. Now is functional component. Issue #3394

Refactor markdown component

---

src/js/components/Diagram/stories/Animated.js
src/js/components/Diagram/stories/Progressing.js

It refactor `src/js/components/Diagram/stories/` to be functional components
No particular order required.
Tested with the storybook checking if its behaviour was as expected
Testing with `yarn storybook`
No
#3394 
N/A
No
No
No

Refactor Diagram Stories to be functional components

---

src/js/components/Box/Box.js

Refactor `src/js/components/Box/Box.js` to be functional
`src/js/components/Box/Box.js`
Running `yarn test` and checking it behaviour with `yarn storybook`
Running `yarn storybook`
No
#3394 
N/A
No
No
No

Refactor Box component to be functional

---

src/js/components/Calendar/stories/CustomHeader.js
src/js/components/Calendar/stories/CustomSizeHeading.js
src/js/components/Calendar/stories/Dual.js
src/js/components/Calendar/stories/Simple.js
src/js/components/TextInput/stories/Custom.js

Refactor the Calendar stories to be functional with React Hooks.
`src/js/components/Calendar/stories`
Running yarn test and checking its behavior with yarn storybook.
No.
#3394
N/A
No.
No.
No.

Refactor Calendar stories and Custom TextInput to use Hooks

---

src/js/components/Select/stories/Basics.js

This PR adds to the Select custom theme storybook example
select/storybook
storybook
storybook
There has been questions on how to change the color of a selected choice in the select 
component. 
#3341 
no
no

custom color for selected

---

src/js/components/Select/stories/components/SearchBorderBox.js

Refactor component with React Hooks. Related to issue #3394

Refactor <SearchBorderBox/> to be functional

---

src/js/components/DataTable/README.md
src/js/components/DataTable/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Enhanced DataTable documentation
automatic
no

Enhanced DataTable documentation

---

src/js/components/List/stories/typescript/theme.tsx
src/js/index.d.ts

I noticed an error while trying to run a List with typescript. attached is the fix.
Tested with storybook new story for List on TS.
@ericsoderberghp  I wanted to get this fix into the release today. hence merging, but feel free to drop feedback.

Update List typings

---

src/js/components/DataTable/Header.js

Fixed an issue with DataTable search overflow. Issue #3539
Storybook
Storybook
#3539 
no
no

Fixed an issue with DataTable search overflow. Issue #3539

---

src/js/components/Accordion/index.d.ts
src/js/components/Accordion/stories/typescript/Rich.tsx
src/js/components/Anchor/Anchor.js
src/js/components/Diagram/Diagram.js

Some of the clean-ups we discussed.
All tested with ts build, storybook and jest.
#3458 #3549

PRs cleanups

---

src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/README.md
src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
src/js/components/InfiniteScroll/stories/OnMore.js
src/js/components/InfiniteScroll/stories/Replace.js
src/js/components/List/__tests__/List-test.js
src/js/components/List/__tests__/__snapshots__/List-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed InfiniteScroll to use hooks.
unit + storybook
added story for "onMore step"
same
#3477 
no
yes

Changed InfiniteScroll to use hooks. Fixed issue #3447.

---

src/js/components/List/List.js

Changed List to fix an issue when onClickItem is used without data
List.js
no
no

Changed List to fix an issue when onClickItem is used without data

---

src/js/components/DataTable/Body.js

Changed DataTable to pass index to onClickRow
aligns with List onClickItem
Body.js
no
yes

Changed DataTable to pass index to onClickRow

---

src/js/components/RadioButton/RadioButton.js
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
src/js/components/RadioButtonGroup/README.md
src/js/components/RadioButtonGroup/RadioButtonGroup.js
src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
src/js/components/RadioButtonGroup/doc.js
src/js/components/RadioButtonGroup/stories/Children.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed RadioButtonGroup to support children rendering.
This is the second pull request in this area. The first was https://github.com/grommet/grommet/pull/3548
RadioButtonGroup/doc.js
storybook and unit
storybook
yes
yes

Changed RadioButtonGroup to support children rendering

---

src/js/components/Chart/Chart.js

Changed Chart to fix an issue with re-rendering when no values are provided.
Also fixes an issue with `size="full"`.
Chart.js
no
yes

Changed Chart to fix an issue with re-rendering when no values are provided

---

src/js/components/Chart/Chart.js
src/js/components/Chart/README.md
src/js/components/Chart/__tests__/Chart-test.js
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/Chart/doc.js
src/js/components/Chart/index.d.ts
src/js/components/Chart/stories/Simple.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Chart to add 'point' type
Chart/doc.js
Storybook Point story
Storybook
automatic
yes

Changed Chart to add 'point' type

---

src/js/components/Meter/README.md
src/js/components/Meter/doc.js
src/js/components/Meter/index.d.ts
src/js/components/Meter/stories/typescript/MultipleValues.tsx
src/js/components/__tests__/__snapshots__/README-test.js.snap

Tested with a new Type script story.
Added `max` prop to docs and types.

Meter - typescript improvements 

---

src/js/components/Main/Main.js
src/js/components/Main/README.md
src/js/components/Main/doc.js
src/js/components/Main/index.d.ts
src/js/components/Main/index.js
src/js/components/Main/stories/Simple.js
src/js/components/Main/stories/typescript/Simple.tsx
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/index.d.ts

Added Main component

---

src/js/utils/colors.js

Fixed an issue with empty string colors
colors.js
theme designer
storybook
no
no

Fixed an issue with empty string colors

---

src/js/components/Footer/Footer.js
src/js/components/Footer/README.md
src/js/components/Footer/doc.js
src/js/components/Footer/index.d.ts
src/js/components/Footer/index.js
src/js/components/Footer/stories/DoubleFooter.js
src/js/components/Footer/stories/Simple.js
src/js/components/Footer/stories/Sitemap.js
src/js/components/Footer/stories/Social.js
src/js/components/Footer/stories/data.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/index.d.ts
yarn.lock

#3580
Let's discuss it more tomorrow.
I want to add one more story example of a sitemap.

Added Footer Component

---

src/js/components/Box/README.md
src/js/components/Box/StyledBox.js
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Box to add focusIndicator. Fixes issue #3577
Box/doc.js
automatic
yes

Changed Box to add focusIndicator. Fixes issue #3577

---

src/js/components/Main/Main.js

Changed Main to defult to flex='grow'
Main.js
designer
no
yes
since we haven't released Main yet, it's not a breaking change

Changed Main to defult to flex='grow'

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/README.md
src/js/components/DataTable/buildState.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed DataTable to use hooks, specifically, DataTable.js. The other DataTable component files were already using hooks.
DataTable.js
storybook
storybook
This is in preparation for some updates to DataTable to add more functionality.
no
yes

Changed DataTable to use hooks

---

src/js/components/Form/Form.js
src/js/components/Form/README.md
src/js/components/Form/doc.js
src/js/components/Form/index.d.ts
src/js/components/Form/stories/ValidateOnBlur.js
src/js/components/FormField/FormField.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed Form to add validate
index.d.ts
New storybook story
new storybook story
automatic
yes

Changed Form to add validate

---

src/js/components/FormField/FormField.js

Changed FormField to set aria-invalid when validation fails
FormField.js
Form Storybook stories "All" and "Validate on blur"
Form Storybook stories "All" and "Validate on blur"
no
yes

Changed FormField to set aria-invalid when validation fails

---

src/js/components/TextArea/TextArea.js

Changed TextArea to remove hocs
TextArea.js
Storybook + unit
Storybook
no
no

Changed TextArea to remove hocs

---

src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap

Changed TextInput to use hooks
TextInput.js
Storybook
Storybook
no
yes

Changed TextInput to use hooks

---

src/js/components/Nav/stories/CollapsableNav.js
yarn.lock

added storybook example of a collapsable nav

added storybook example of a collapsable nav

---

src/js/components/Form/Form.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Form to use hooks
Form.js
storybook
storybook
no
yes

Changed Form to use hooks

---

src/js/components/MaskedInput/stories/DateRange.js
src/js/components/MaskedInput/stories/IPV4Range.js
src/js/components/MaskedInput/stories/SizeUnits.js

Added MaskedInput stories
anywhere
storybook
storybook
no
yes

Added MaskedInput stories

---

src/js/components/Form/Form.js
src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/Form/stories/CustomTheme.js
src/js/components/FormField/FormField.js
src/js/components/FormField/README.md
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/FormField/doc.js
src/js/components/FormField/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/themes/base.d.ts
src/js/themes/base.js

Changed FormField to support background styling tied to error and disabled states
FormField/doc.js
storybook, theme designer
storybook
no
yes

Changed FormField to support background styling tied to error and disabled states

---

src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/themes/base.js

Enhancing the theme with  'active-background' and 'selected-background' colors.
Took a similar approach to HPE theme.

Added 'active-background' and 'selected-background'

---

package.json
yarn.lock

Changed @testing-* lib to be a dev dependency instead of dependency.
package.json
yarn test
jest + storybook
clean-ups
no
no
no

Changed @testing-* lib to be a devDependency

---

src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/Form/stories/All.js
src/js/components/Form/stories/AllChildren.js
src/js/components/Form/stories/CustomTheme.js
src/js/components/FormField/FormField.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/Select/Select.js

Changed FormField to use hooks
FormField.js
Storybook
Storybook
no
yes

Changed FormField to use hooks

---

src/js/components/DropButton/DropButton.js
src/js/components/DropButton/README.md
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Converted DropButton to use hooks
DropButton.js
storybook
storybook
no
yes

Converted DropButton to use hooks

---

src/js/components/RangeInput/RangeInput.js
src/js/components/Select/Select.js

Changed Select and RangeInput to fix an issue with setting the value
Select.js
storybook
storybook
no
no

Changed Select and RangeInput to fix an issue with setting the value

---

src/js/components/Box/index.d.ts
src/js/components/FormField/FormField.js
src/js/components/FormField/README.md
src/js/components/FormField/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.d.ts
src/js/themes/base.js
src/js/utils/index.d.ts

Changed FormField to add 'round' to theme
FormField/index.d.ts
theme designer
manually
automatic
yes

Changed FormField to add 'round' to theme

---

src/js/components/Layer/Layer.js

Addresses issue #3623 
added this.layerContainer.remove() when the component unmounts to completely remove the container.

Removes layer container from dom

---

src/js/components/Select/Select.js

Changed Select to fix an issue with setting value with FormContext
Select.js
storybook
storybook
no
no

Changed Select to fix an issue with setting value with FormContext

---

src/js/components/Drop/stories/Custom.js
src/js/components/Drop/stories/Lazy.js
src/js/components/Drop/stories/Overflow.js
src/js/components/Drop/stories/Plain.js
src/js/components/Drop/stories/Progressive.js
src/js/components/Drop/stories/Simple.js

Signed-off-by: Sivakar Sithamparanathan <sivakar12@outlook.com>
Replaces class components in stories of Drop and used functional components and hooks
src/js/components/Drop/stories/
Manual testing of Storybook
Open storybook by running yarn storybook
Check if the stories of Drop has changed 
Issue #3394 
No
No

Use hooks in stories of Drop (#3394)

---

src/js/components/Chart/Chart.js
src/js/components/Chart/README.md
src/js/components/Chart/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Chart to allow onClick to work for bar and point types
Chart.js
hmm???
automatic
yes

Changed Chart to allow onClick to work for bar and point types

---

src/js/components/RangeInput/index.d.ts
src/js/components/RangeInput/stories/typescript/CustomRange.tsx
src/js/components/RangeInput/stories/typescript/SimpleRange.tsx

This PR adjusts the onChange type definition for RangeInput
src/js/components/RangeInput/index.d.ts
#3165 
No
No
Yes

[TS] fix: rangeInput onChange prop type

---

src/js/components/Chart/stories/Rich.js
src/js/components/Chart/stories/Scan.js
src/js/components/Chart/stories/Window.js
src/js/components/Chart/stories/Zoom.js

Changes the stories of the Chart component to use hooks instead of class components
src/js/components/Chart/stories
Manual comparison of story renders
By inspecting the relevant stories
#3394 
No
No

Change Chart's stories to use Hooks

---

src/js/components/RangeInput/stories/CustomRange.js
src/js/components/RangeInput/stories/SimpleRange.js

Split the RangeInput stories
RangeInput section in storybook
No code change in this PR
RangeInput section in storybook
#3212 
No
No
Yes

Split RangeInput stories

---

src/js/components/Layer/Layer.js

Fixed an issue with Layer for server side rendering.
no
yes

Fixed an issue with Layer for static sites

---

src/js/components/Drop/Drop.js
src/js/components/Layer/Layer.js

Changed Drop and Layer to fix server side rendering issues.
Drop.js
Layer.js
built grommet, copied to local grommet-site, `yarn build-static`
no
no

Changed Drop and Layer to fix server side rendering issues

---

src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/FormField/FormField.js
src/js/components/FormField/__tests__/FormField-test.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap

… element. Fixes issue #3810
Changed FormField to propagate disabled and required to created input element.
FormField.js
added unit tests
#3810 
#3791 
no
yes

Changed FormField to propagate disabled and required to created input element.

---

src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/InfiniteScroll/InfiniteScroll.js
src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.js.snap
src/js/components/List/__tests__/__snapshots__/List-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap

Fixes issue #3665 by changing lastPage to use Math.floor instead of Math.ceil
Infinitescroll.js
Tested with storybook by changing the values for select with lots of options story.
#3665
No

select flicker fix

---

src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/Form/stories/All.js
src/js/components/FormField/FormField.js
src/js/components/FormField/__tests__/FormField-test.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap

Changed FormField to fix an issue with `onChange()` for custom `component`
FormField.js
add Custom field in storybook Form - All story
^^^
no
yes

Changed FormField to fix an issue with `onChange()` for custom `component`

---

src/js/components/Text/stories/All.js
src/js/components/Text/stories/Color.js
src/js/components/Text/stories/WordBreak.js

Split the Text stories
Text section in storybook
No code change in this PR
Text section in storybook
#3212 
No
No
Yes

Split Text Stories

---

src/js/components/DataTable/buildState.js

Changed DataTable to handle empty column definition
no
no

Changed DataTable to handle empty column definition

---

src/js/components/Form/stories/AggregateValidation.js

Added a story to demonstrate aggregate form validation
new story
new story
new story
no
no

Added a story to demonstrate aggregate form validation

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/README.md
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/buildState.js
src/js/components/DataTable/doc.js
src/js/components/DataTable/index.d.ts
src/js/components/DataTable/stories/Sort.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed DataTable to add sort and onSort
DataTable/doc.js
Added DataTable Sort story
DataTable Sort story
automatic
yes

Changed DataTable to add sort and onSort

---

src/js/components/Form/Form.js
src/js/components/Form/__tests__/Form-test.js
src/js/components/Form/stories/DynamicFields.js
src/js/components/FormField/FormField.js

Changed FormField to remove validation when unmounted.
FormField.js
Added Form -> Dynamic fields
above story
#3834 
no
yes

Changed FormField to remove validation when unmounted. Fixes issue #3834

---

src/js/components/Accordion/Accordion.js
src/js/components/Accordion/stories/Rich.js
src/js/components/AccordionPanel/AccordionPanel.js

Changed Accordion and AccordionPanel to use hooks
Accordion.js
unit + storybook
storybook
no
no?

Changed Accordion and AccordionPanel to use hooks

---

src/js/components/Chart/Chart.js
src/js/components/Chart/README.md
src/js/components/Chart/__tests__/Chart-test.js
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/Chart/doc.js
src/js/components/Chart/index.d.ts
src/js/components/Chart/stories/Dash.js
src/js/components/InfiniteScroll/stories/ClassChildren.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Chart to add dash
Chart/doc.js
Add unit test and Chart -> Dash story
Chart -> Dash story
automatic
yes

Changed Chart to add dash

---

src/js/components/DataTable/Cell.js
src/js/components/DataTable/Header.js
src/js/components/DataTable/README.md
src/js/components/DataTable/doc.js
src/js/components/DataTable/index.d.ts
src/js/components/TableCell/TableCell.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed DataTable to add verticalAlign under columns
doc.js
none
automatic
yes

Changed DataTable to add verticalAlign under columns

---

src/js/components/Box/StyledBox.js
src/js/components/Image/README.md
src/js/components/Image/StyledImage.js
src/js/components/Image/__tests__/Image-test.js
src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
src/js/components/Image/doc.js
src/js/components/Image/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/utils/styles.js

Changed Image to allow fill to be horizontal or vertical only
Image/doc.js
unit tests
unit
automatic
yes

Changed Image to allow fill to be horizontal or vertical only

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/__tests__/CheckBox-test.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/Form/Form.js
src/js/components/Form/FormContext.js
src/js/components/Form/stories/CheckBox.js
src/js/components/MaskedInput/__tests__/MaskedInput-test.js

Changed Form and FormContext to fix an issue with controlled components
FormContext.js
Added unit test
Several manual tests
unit test
#3855 
no
yes

Changed Form and FormContext to fix an issue with controlled components

---

src/js/components/Grid/StyledGrid.js

Changed Grid to fix an issue with flex columns and numeric count.
StyledGrid.js
no
yes

Changed Grid to fix an issue with flex columns and numeric count

---

src/js/components/Form/FormContext.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Changed non-Form FormContext to fix an issue with preserving caret location
FormContext.js
storybook
storybook
no
yes

Changed non-Form FormContext to fix an issue with preserving caret location - DONT MERGE YET

---

src/js/components/Form/Form.js
src/js/components/Form/__tests__/Form-test.js
src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/Form/stories/Controlled.js
src/js/components/Form/stories/ControlledInput.js

Changed Form FormContext to fix an issue with caret positioning.
Form.js
Added three unit tests to cover the three flavors of value control: controlled at the Form level, controlled at the Input level, and uncontrolled.
Also added two stories for additional coverage as well.
new Form stories
no
yes

Changed Form FormContext to fix an issue with caret positioning

---

src/js/components/CheckBox/CheckBox.js
src/js/components/Form/Form.js
src/js/components/Form/__tests__/Form-test.js
src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
src/js/components/Form/stories/CheckBox.js
src/js/components/Form/stories/ControlledInput.js
src/js/components/Form/stories/ControlledInputLazy.js
src/js/components/Form/stories/ControlledLazy.js
src/js/components/Form/stories/Uncontrolled.js
src/js/components/FormField/FormField.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/MaskedInput/MaskedInput.js
src/js/components/RadioButtonGroup/RadioButtonGroup.js
src/js/components/RangeInput/RangeInput.js
src/js/components/Select/Select.js
src/js/components/TextArea/TextArea.js
src/js/components/TextInput/TextInput.js

Changed Form to fix some issues with various control patterns.
Form.js
Added two new tests and two more stories to cover more control patterns
storybook
#3894
#3896
no
yes

Changed Form to fix some issues with various control patterns

---

src/js/components/Select/Select.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Changed Select to fix an issue with clearing multiple
Select -> Multiple story
Select -> Unselect story
Select -> Multiple story
Select -> Unselect story
no
yes

Changed Select to fix an issue with clearing multiple

---

src/js/components/Avatar/README.md
src/js/components/Avatar/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Noticed this one while updating the site https://github.com/grommet/grommet-site/pull/157

Changed Avatar docs

---

src/js/components/Form/stories/CheckBox.js
src/js/components/FormField/FormField.js

Changed FormField to fix an issue with required CheckBoxes
FormField.js
Enhanced Form CheckBox story to cover required case
storybook
#3891
no
yes

Changed FormField to fix an issue with required CheckBoxes

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/__tests__/Calendar-test.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/Calendar/stories/Multiple.js

Changed Calendar to fix an issue with selecting multiple dates.
Added Calendar -> Multiple story.
Added unit tests. Added `animate={false}` to the unit tests to avoid complaints about calling setState() in useEffect() without act().
Calendar.js
storybook
storybook
#3893 
no
yes

Changed Calendar to fix an issue with selecting multiple dates

---

src/js/components/WorldMap/WorldMap.js
src/js/components/WorldMap/stories/Color.js
src/js/components/WorldMap/stories/Continents.js
src/js/components/WorldMap/stories/Places.js
src/js/components/WorldMap/stories/SelectPlace.js

Changed WorldMap to use hooks
WorldMap.js
Added stories
Storybook
no
yes

Changed WorldMap to use hooks

---

src/js/components/Paragraph/Paragraph.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Paragraph to support forward ref
Paragraph.js
blackbox
write some code
no
yes

Changed Paragraph to support forward ref

---

src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap

Adds in tests for more complicated margin/pad combinations on Box.

Create pad and margin tests on Box

---

src/js/components/Chart/Chart.js

Changed Chart to fix an issue with strict refs
#3928
no
yes

Changed Chart to fix an issue with strict refs. Fixed issue #3928

---

src/js/components/Button/__tests__/Button-test.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap

Adding various combinations of disabled and active button tests to be able to use as a baseline in the disabled button and primary button border PRs.

Add Button tests

---

src/js/components/Button/__tests__/Button-test.js
src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap

To ensure backward compatibility on #3877

Added tests for Button disabled plain

---

src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Added a test for Select onChange without valueKey.
test file
added a test
go over snapshot and test flow
#3934 
no
no

Added a test for Select onChange without valueKey

---

src/js/components/Select/README.md
src/js/components/Select/Select.js
src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/doc.js
src/js/components/Select/index.d.ts
src/js/components/Select/stories/ObjectMultiple.js
src/js/components/Select/stories/ObjectOptions.js
src/js/components/Select/utils.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Select to fix an issue with onChange value.
Added the ability of `valueKey` to be an object with `{ key, reduce }`.
See the details in the issue comments for a description.
Read the issue comments.
Review the changes in doc.js and index.d.ts.
Added two new unit tests and cleaned up two stories.
storybook
#3934
yes, automatic
yes
backwards compatible with 2.11.0
fixes a compatibility issue with 2.12.0

Changed Select to fix an issue with onChange value.

---

src/js/components/Sidebar/README.md
src/js/components/Sidebar/Sidebar.js
src/js/components/Sidebar/__tests__/Sidebar-test.js
src/js/components/Sidebar/__tests__/__snapshots__/Sidebar-test.js.snap
src/js/components/Sidebar/doc.js
src/js/components/Sidebar/index.d.ts
src/js/components/Sidebar/index.js
src/js/components/Sidebar/stories/Labels.js
src/js/components/Sidebar/stories/Simple.js
src/js/components/Sidebar/stories/Tooltips.js
src/js/components/Sidebar/stories/typescript/Simple.tsx
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/components/index.js
src/js/index.d.ts

Added Sidebar component to the core library
doc.js
added 3 storybook examples plus one for typescript.
added a test file to test props.
storybook -> Sidebar
#3697 
#3489 
done
Yes

NEW Sidebar component

---

src/js/components/Avatar/index.d.ts
src/js/components/Avatar/stories/typescript/All.tsx
src/js/components/Box/index.d.ts
src/js/components/Sidebar/index.d.ts

Changed types of Avatar and Sidebar to include IntrinsicElements.
index.d.ts
tsx file change
tsx file change
fix #3968 
no
yes

[TS] Changed types of Avatar and Sidebar to include IntrinsicElements

---

src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/utils.js

Changed Select to fix an issue with having 0 for the value.
utlls.js
added a unit test specific to this
#3985
no
yes

Changed Select to fix an issue with having 0 for the value.

---

src/js/components/Clock/Analog.js
src/js/components/Clock/Clock.js
src/js/components/Clock/Digital.js
src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
src/js/components/Clock/stories/Countdown.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Clock to use hooks and fixed countdown run issue #3246
Clock.js
Storybook, added Clock -> Countdown
unit tests, snapshot change is due to prior run test not running
Storybook
#3246 
no
yes

Changed Clock to use hooks and fixed countdown run issue #3246

---

src/js/components/DataTable/Cell.js
src/js/components/DataTable/ExpanderCell.js
src/js/components/DataTable/Footer.js
src/js/components/DataTable/Header.js
src/js/components/DataTable/Resizer.js
src/js/components/DataTable/Searcher.js
src/js/components/DataTable/Sorter.js
src/js/components/Diagram/Diagram.js
src/js/components/Diagram/README.md
src/js/components/Image/Image.js
src/js/components/Menu/Menu.js
src/js/components/Menu/README.md
src/js/components/Meter/Bar.js
src/js/components/Meter/Circle.js
src/js/components/Meter/Meter.js
src/js/components/RangeSelector/EdgeControl.js
src/js/components/TableBody/TableBody.js
src/js/components/TableCell/TableCell.js
src/js/components/Tabs/Tabs.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed DataTable, Diagram, Image, Menu, Meter, TableBody, TableCell, Tabs to remove hocs and fix some missing forwardRefs.
anywhere
unit
storybook
cleaning up some more, eventually we'll be able to get rid of all higher order components and the `recompose` dependency.
no
yes

Changed DataTable, Diagram, Image, Menu, Meter, TableBody, TableCell, Tabs

---

src/js/components/RadioButtonGroup/README.md
src/js/components/RadioButtonGroup/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Simple documentation changes I applied while going over the component functionalities.

Refined docs for RadioButtonGroup

---

src/js/all/stories/AllComponents.js

Cleaned up temporary HPE theme story check
no
no

Cleaned up temporary HPE theme story check

---

src/js/components/Layer/stories/Center.js
yarn.lock

Relevant issue #3964 
Reverts the center layer example to its previous iteration.

reverted layer changes

---

src/js/components/Drop/DropContainer.js
src/js/components/MaskedInput/MaskedInput.js
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/stories/Suggestion.js
yarn.lock

Changed Drop, TextInput, and MaskedInput to fix scrolling issues with TextInput
anywhere
Changed TextInput -> Suggestion story to remove fixed drop height
TextInput -> Suggestion
#3854
no
yes

Changed Drop and TextInput to fix scrolling issues with TextInput

---

src/js/components/DropButton/DropButton.js
src/js/components/Select/Select.js
src/js/utils/DOM.js

Changed DOM utility to fix console error.
The other two changes are to reduce re-rendering.
DOM.js
Select -> Simple story
Select -> Simple story
#3994
no
yes

Changed DOM utility to fix console error

---

src/js/components/Form/stories/typescript/Submit.tsx

Fixes storybook rendering, that is currently broken.
the tsx file
storybook
storybook
https://github.com/grommet/grommet/pull/4037/files
no
no

Updated Form TS example

---

src/js/components/Select/SelectContainer.js

Changed SelectContainer to use hooks.
unit and some storybook
storybook!
#4019
no
yes

Changed SelectContainer to use hooks.

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Collapsible/Collapsible.js

Changed Collapsible to use hooks.
Collapsible.js
storybook, unit
storybook
no
yes

Changed Collapsible to use hooks

---

src/js/components/Menu/Menu.js
src/js/components/Select/Select.js

Changed Select to fix an issue with callback hooks
Select.js
Storybook, unit tests, grommet-designer on Windows + Chrome via BrowserStack
Storybook
no
yes

Changed Select & Menu to fix an issue with callback hooks

---

src/js/components/Button/StyledButtonKind.js
src/js/components/DataTable/ExpanderCell.js
src/js/components/MaskedInput/MaskedInput.js
src/js/components/Select/SelectContainer.js
src/js/components/TextInput/TextInput.js

Changed Button to fix some styling issues when plain
StyledButtonKind.js
storybook
storybook, with hpe-next theme
#4077
no
no

Changed Button to fix some styling issues when plain

---

src/js/components/Chart/Chart.js
src/js/components/Chart/__tests__/Chart-test.js
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/Chart/calcs.js
src/js/components/Chart/utils.js
src/js/components/DataChart/DataChart.js

Changed Chart and DataChart to fix some issues with undefined data points.
This addresses some issues with being more resilient to property values being built up over time, as the designer does.
Chart.js
storybook, added unit test, designer
storybook
no
no

Changed Chart and DataChart to fix some issues with undefined data points

---

src/js/components/DataChart/DataChart.js

Changed DataChart to fix an issue with empty data
DataChart.js
custom app
don't worry
no
no

Changed DataChart to fix an issue with empty data

---

src/js/components/Chart/calcs.js

Changed Chart calcs() to improve handling of single value cases
calcs.js
single value in designer
single value in designer
no
no

Changed Chart calcs() to improve handling of single value cases

---

src/js/components/Button/StyledButtonKind.js
src/js/components/Select/Select.js

Changed Button so kind styling can have radius and base border can be omitted.
StyledButtonKind.js
custom app
no
yes

Changed Button so kind styling can have radius and base border can be omitted

---

src/js/components/RadioButtonGroup/README.md
src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
src/js/components/RadioButtonGroup/doc.js
src/js/components/RadioButtonGroup/index.d.ts
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed RadioButtonGroup to support boolean options.
doc.js
Added unit test.
Whitebox in custom app.
storybook
automatic
yes

Changed RadioButtonGroup to support boolean options

---

src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Changed Select to fix an issue with showing focus on the options drop
no
no

Changed Select to fix an issue with showing focus on the options drop

---

src/js/components/Grid/Grid.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Grid to support ref
Grid.js
none
no
yes

Changed Grid to support ref

---

src/js/components/Video/README.md
src/js/components/Video/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

Changed video docs to include video icons
doc.js
jest
Fixes #4190 
done
maybe as doc improvement

Changed video docs to include video icons

---

src/js/components/Form/__tests__/Form-test-controlled.js
src/js/components/Form/__tests__/Form-test-uncontrolled.js
src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap

No changes were made to the tests, the Form tests are just being separated into two different testing files, one for uncontrolled and one for controlled.
I also had to break up some lines that were flagged as being too long, but no code was changed.
Form-test-controlled.js and Form-test-uncontrolled.js
`yarn test`
No
No

Organized Form tests by controlled and uncontrolled

---

src/js/components/Chart/Chart.js
src/js/components/Chart/README.md
src/js/components/Chart/__tests__/Chart-test.js
src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
src/js/components/Chart/doc.js
src/js/components/Chart/index.d.ts
src/js/components/Chart/stories/Point.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Chart to add point flavors
doc.js
Added Chart -> Point story
Added unit test
Chart -> Point story
Driven off of the great accessibility research Matt did.
automatic
yes

Changed Chart to add point flavors

---

src/js/components/Form/Form.js
src/js/components/Form/__tests__/Form-test-uncontrolled.js

Closes https://github.com/grommet/grommet/issues/4259
- Form.js
Storybook + Added Jest tests
Storybook
https://github.com/grommet/grommet/issues/4259
https://github.com/grommet/grommet/issues/4259
No.

Changed Form to fix runtime Error on validate

---

src/js/all/stories/Colors.js

Following-up on some questions that were raised on Stackoverflow regarding colors. This PR is providing an extensive example of Theme coloring.

Added theme colors examples to storybook

---

src/js/components/Accordion/__tests__/Accordion-test.js
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Anchor/__tests__/Anchor-test.js
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap

Adds accessibility tests for Accordion and Anchor components
`yarn test`
#4284 
No
No

Anchor and Accordion accessibility tests

---

src/js/components/FormField/__tests__/FormField-test.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap

Adds accessibility test to the FormField component
FormField-test.js
`yarn test`
#4284 
No
No

FormField accessibility test

---

src/js/components/Menu/__tests__/Menu-test.js
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Tabs/__tests__/Tabs-test.js
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap

Adds accessibility test to Menu and Tabs components
`yarn test`
#4284 
No
No

Added accessibility tests for Menu and Tabs

---

src/js/components/Drop/__tests__/Drop-test.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Nav/__tests__/Nav-test.js
src/js/components/Nav/__tests__/__snapshots__/Nav-test.js.snap

Adds accessibility tests for Nav and Drop
`yarn test`
#4284 
No
No
Breaking change

Accessibility tests for Nav and Drop components

---

src/js/components/Card/stories/Clickable.js
src/js/components/Drop/stories/Custom.js
src/js/components/Drop/stories/Lazy.js
src/js/components/Form/stories/FieldSpacingOptions.js
src/js/components/Form/stories/FieldStatesCustom.js
src/js/components/Grid/stories/ResponsiveCards.js
src/js/components/Menu/stories/Themed.js

Going over story examples I ran into these story changes:
1. Once the gradient issue for Chart was fixed #4322 I was able to allow modular view on cards.
2. imports of deepMerge refinement.
3. Moving the Card responsive example to Grid.

Stories cleanups

---

src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
src/js/components/MaskedInput/StyledMaskedInput.js
src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
src/js/components/TextArea/StyledTextArea.js
src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
src/js/components/TextInput/StyledTextInput.js
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/utils/styles.js

Puts code shared by `MaskedInput`, `TextInput`, and `TextArea` into `inputStyles` utils function.
src/js/utils/styles.js
Snapshots updated.
Look at storybook deploy.
There was code repeated across all of these that could be placed in a single utils function.
No.
No.

Refactor input styles

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap

Fix calendar crashing
`src/js/components/Calendar/Calendar.js`
With storybook in range component of DateInput
#4351

Fix: calendar crashing with three clicks

---

src/js/components/Header/stories/Simple.js
src/js/components/Header/stories/typescript/Simple.tsx
src/js/components/Nav/stories/NavOnHeader.js

Changed stories to leverage the usage of existing components (such as Nav and Avatar).

Simplify stories of Header and Nav

---

src/js/components/Heading/README.md
src/js/components/Heading/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap

This PR creates more transparency into the responsive behavior of heading styling. There have been questions around this in [Slack](https://grommet.slack.com/archives/C04LMHN59/p1595978603020300?thread_ts=1591199883.206300&cid=C04LMHN59), so it seems fitting to enhance the site documentation.
src/js/components/Heading/doc.js
Closes #4373 
No.

Enhance heading.level documentation

---

src/js/components/Select/Select.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap

Fix a bug that `onOpen` is called twice
`src/js/components/Select/Select.js`
Unit
Storybook
#4283 
no
yes

Select: fix onOpen called twice

---

src/js/components/Header/stories/Responsive.js

Added the header from the grommet tools site as a storybook example
Storybook
Issue #4385 
No
No

Added Grommet Tools header example in storybook

---

src/js/components/Card/README.md
src/js/components/Card/doc.js
src/js/components/CardBody/README.md
src/js/components/CardBody/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Elaborates on the Card and Card Body documentations.

Changed Card docs

---

src/js/components/Text/README.md
src/js/components/Text/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Adds clarification to the Text documentation for truncate
Closes #4462 
Updated in this PR
No

Updated docs for Text truncate

---

package.json
src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/__tests__/theme-test.js
yarn.lock

Changed hpe theme dependency to 2.0.0
package.json
storybook All - hpe theme
unit test changes - approved since the theme has a breaking change release
storybook All - hpe theme
A release to the new HPE theme
No 
No
backward compatible for grommet. the theme itself is a major release change.

Changed hpe theme dependency

---

src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
src/js/components/Anchor/Anchor.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/stories/Border.js
src/js/components/Button/Button.js
src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
src/js/components/List/__tests__/__snapshots__/List-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
src/js/utils/border.js

Replaces PR #3922
Changed Box to fix an issue with row-responsive border between
StyledBox.js
Enhanced Box -> Border story
Box -> Border story, especially responsive behavior
#3788
no
yes

Created a new branch on tot master with the content of fix/box-border

---

src/js/components/CheckBox/stories/Form.js
src/js/components/TextArea/stories/Form-Placeholder.js
src/js/components/TextInput/stories/Form.js

Form has a lot of stories under it. 
Moved:
Form/CheckBox story to CheckBox component and renamed story to Form
Form/TextArea story to TextArea component and renamed story to Form with placeholder (Form story already existed)
Form/TextInput story to TestInput component and renamed story to Form
storybook
No
No

Moved some stories away from Form

---

src/js/components/Drop/README.md
src/js/components/Drop/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Improved docs accuracy while working on the Tip component.

Updated drop docs

---

src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/DataTable/buildState.js

Closes #4486
Adds support for nested object in aggregate of `DataTable`
`src/js/components/DataTable/buildState.js `
Unit
Storybook
#4486
Yes

feat(DataTable): Add support for nested object in aggregate

---

src/js/components/Drop/__tests__/Drop-test.js

Signed-off-by: Aravind Reddy <reddy.aravind178@gmail.com>
part of #3394 
refactored TestInput class component in drop-test.js to functional component
yarn test

"chore: refactor class comp to functional component"

---

src/js/themes/base.d.ts

Updated theme.global.active typing.
Fixes grommet-theme-designer issue #11.
no
yes

Updated theme.global.active typing

---

src/js/components/Button/Button.js
src/js/components/Button/README.md
src/js/components/Button/__tests__/Button-kind-test.js
src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
src/js/components/Button/doc.js
src/js/components/Button/stories/Custom.js
src/js/components/Button/stories/Plain.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Kind Button set to `plain` when it has children
doc.js
storybook + jest
storybook
This PR is a resolution from discussions around the kind button.
Done.
Yes.
backward compatible.

Kind Button set to `plain` when it has children

---

src/js/components/Grid/StyledGrid.js

Remove unreachable code and improve test coverage
`src/js/components/Grid/__tests__/Grid-test.js`
`yarn test`
`yarn test`
No
#4539 
No
No

Remove unreachable code and improve test coverage

---

src/js/components/Text/doc.js

Clean up Text size description.
Doc.js
None
Automatic
No

Clean up Text size description.

---

src/js/components/Video/__tests__/Video-test.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Signed-off-by: Aravind Reddy <reddy.aravind178@gmail.com>
part of #4539 
improve the test coverage for the video component
video tests
yarn test
#4539 
before:
after:
No
Yes

"test: improved test coverage for video component"

---

src/js/components/Grid/__tests__/Grid-test.js
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap

Improved test coverage for Grid
`src/js/components/Grid/__tests__/Grid-test.js`
`yarn test`
`yarn test`
No
#4539 
No
No

Improved test coverage for Grid

---

src/js/components/Accordion/__tests__/Accordion-test.js
src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap

Signed-off-by: Aravind Reddy <reddy.aravind178@gmail.com>
part of #4539 
improved the coverage of accordion-panel
accordion tests
yarn test
#4539 
before:
after:
no
yes

"tests: improve coverage of accordian-panel"

---

src/js/components/Chart/__tests__/utils-test.js
src/js/components/Chart/utils.js

Added tests for Chart utils
`src/js/components/Chart/__tests__/utils-test.js`
`yarn test`
`yarn test`
No
#4539
No
No

Added tests for Chart utils

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Axis.js

Fixes an issue with DataChart in how it determines how many x-axis labels to render for `medium` granularity.
DataChart.js
white box testing across various data lengths
#4602
no
yes

Changed DataChart to fix an issue with x-axis medium granularity.

---

src/js/components/DateInput/DateInput.js
src/js/components/MaskedInput/stories/Form.js
src/js/components/TextInput/stories/Form.js

Changed DateInput to fix an issue with resetting Forms
DateInput.js
Added DateInput -> Form story
Storybook
https://grommet.slack.com/archives/C09QQEG69/p1603198508120400
no
yes

Changed DateInput to fix an issue with resetting Forms

---

src/js/components/DataChart/DataChart.js

Changed DataChart to fix an issue with chart definitions without properties
one file, one line
This is needed to fix an issue with building DataCharts in grommet-designer
no
no

Changed DataChart to fix an issue with chart definitions without properties

---

src/js/components/Accordion/stories/Accordion.stories.js
src/js/components/Accordion/stories/Custom.js
src/js/components/Accordion/stories/CustomHeader.js
src/js/components/Accordion/stories/Simple.js
src/js/components/Accordion/stories/typescript/Rich.tsx
storybook/main.js
storybook/preview.js

Updates the stories in Accordion/stroies/simple.js to use the new structure.
yarn storybook
#4651 
No
No

Accordion Simple stories changed to new structure

---

src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
src/js/components/Card/__tests__/__snapshots__/Card-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/themes/base.js

Changed background-* colors to support dark and light more accurately.
base.js
codesandbox examples.
Review.
no
yes

Changed background colors to support dark/light mode

---

storybook/main.js

Adding to loader missing stories such as Focus.tsx #4651

Added tsx loader for All stories

---

src/js/components/Anchor/stories/Anchor.stories.js
src/js/components/Anchor/stories/Color.js
src/js/components/Anchor/stories/Default.js
src/js/components/Anchor/stories/Disabled.js
src/js/components/Anchor/stories/Inline.js
src/js/components/Anchor/stories/Size.js
src/js/components/Anchor/stories/Weight.js

- Update Anchor stories to Controls/Anchor.
- Rename `Colors` to `Color` to match other components' stories with the same name.
`components/Anchor/stories/Anchor.stories.js`
Storybook
Storybook
#4651 
No.

Update Anchor stories to new Format

---

src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/__tests__/theme-test.js

Improve test coverage of the grommet theme.
theme-test.js
Jest
review
#4539 
no
no
b/c

Added a test for the grommet theme

---

src/js/themes/__tests__/__snapshots__/theme-test.js.snap
src/js/themes/__tests__/theme-test.js

Added test to ThemeContext
test file
Jest
Jest
#4539 
no
no
b/c

Added test to ThemeContext

---

src/js/components/Button/__tests__/Button-kind-test.js
src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap

Added tests for Button kind events and icon colors
test file
Jest
Jest
Updated:
#4539 
no
no
b/c

Added tests for Button kind events and icon colors

---

src/js/components/Avatar/stories/Avatar.stories.js
src/js/components/Avatar/stories/Basic.js
src/js/components/Avatar/stories/Round.js
src/js/components/Avatar/stories/Sizes.js
src/js/components/Avatar/stories/Themed.js
src/js/components/Avatar/stories/typescript/Stacked.tsx

Updates the stories in Avatar/stories to use the new structure.
Avatar.stories.js
storybook
No
#4651
No
No

Refactor Avatar stories to the new structure

---

src/js/components/Accordion/stories/Simple.js
src/js/components/Anchor/stories/Default.js
src/js/components/Drop/stories/Lazy.js
src/js/components/Drop/stories/Multiple.js
src/js/components/Drop/stories/Overflow.js
src/js/components/Drop/stories/Plain.js
src/js/components/Drop/stories/Progressive.js
src/js/components/Drop/stories/Simple.js
src/js/components/Drop/stories/Tooltip.js
src/js/components/WorldMap/stories/Color.js
src/js/components/WorldMap/stories/Continents.js
src/js/components/WorldMap/stories/Places.js
src/js/components/WorldMap/stories/SelectPlace.js
src/js/components/WorldMap/stories/Simple.js
src/js/components/WorldMap/stories/WorldMap.stories.js

Updates the stories in WorldMap/stories to use the new structure.
WorldMap.stories.js
storybook
No
#4651
No
No

Refactor WorldMap stories to the new structure

---

src/js/components/Diagram/stories/Animated.js
src/js/components/Diagram/stories/Diagram.stories.js
src/js/components/Diagram/stories/Progressing.js
src/js/components/Diagram/stories/typescript/Connections.tsx

Updates the stories in Diagram/stories to use the new structure.
Diagram.stories.js
storybook
No
#4651
No
No

Refactor Diagram stories to the new structure

---

src/js/components/Distribution/stories/Distribution.stories.js
src/js/components/Distribution/stories/typescript/Simple.tsx

Updates the stories in Distribution/stories to use the new structure.
Distribution.stories.js
storybook
No
#4651
No
No

Refactor Distribution stories to the new structure

---

src/js/components/Clock/stories/Analog.js
src/js/components/Clock/stories/Clock.stories.js
src/js/components/Clock/stories/Countdown.js
src/js/components/Clock/stories/Digital.js
src/js/components/Clock/stories/typescript/CustomAnalog.tsx

Updates the stories in Clock/stories to use the new structure.
Clock.stories.js
storybook
No
#4651
No
No

Refactor Clock stories to the new structure

---

src/js/components/Meter/stories/Bar.js
src/js/components/Meter/stories/Circle.js
src/js/components/Meter/stories/Labelled.js
src/js/components/Meter/stories/Meter.sotries.js
src/js/components/Meter/stories/typescript/MultipleValues.tsx

Updates the stories in Meter/stories to use the new structure.
Meter.stories.js
storybook
No
#4651
No
No

Refactor Meter stories to the new structure

---

src/js/components/Footer/stories/DoubleFooter.js
src/js/components/Footer/stories/Footer.stories.js
src/js/components/Footer/stories/Simple.js
src/js/components/Footer/stories/Sitemap.js
src/js/components/Footer/stories/Social.js

Organized the `Footer/stories` by type of its component which is Layout.
`src/js/components/Footer/stories/Footer.stories.js`
- `yarn test`
- `yarn lint`
No
#4651 
No
No

Organized Footer stories structure

---

src/js/components/Nav/stories/Collapsable.js
src/js/components/Nav/stories/CustomAnchor.js
src/js/components/Nav/stories/Nav.stories.js
src/js/components/Nav/stories/OnHeader.js
src/js/components/Nav/stories/Sidebar.js
src/js/components/Nav/stories/Simple.js

Update Nav stories to Controls/Nav.
`components/Nav/stories/Nav.stories.js`
Storybook
Visit storybook using PR's branch and check Controls/Nav.
#4651
No.

Nav stories changed to new structure

---

src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
src/js/themes/base.js

Previously the background for Drop and Layer was always set to white. This PR changes the theme so that there is dark and light for the Drop and Layer background.
themes/base.js
Tested with the following stories:
```javascript
import { storiesOf } from '@storybook/react';
import { Box, Grommet, Layer, Text } from 'grommet';
defaultMode: "dark",
global: { ...grommet.global }
};
const NotificationLayer = () => {
return (
<Grommet theme={customTheme} full>
<Layer margin="medium">
<Box pad="large" border={{ color: 'accent-1', size: 'large' }}>
<Text color="accent-2">Text</Text>
</Box>
</Layer>
</Grommet>
);
};
storiesOf('Layer', module).add('TEST', () => <NotificationLayer />);
```
```javascript
import …
```

Added dark and light to Drop and Layer in theme

---

src/js/components/WorldMap/WorldMap.js
src/js/components/WorldMap/__tests__/WorldMap-test.js
src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.js.snap

* Added tests to cover events of places and continents on WorldMap
* Enable continents to accept rest props
WorldMap.js
Jest
Jest
Nop
#4539 
no
no
b/c

Added tests to cover events of places and continents on WorldMap

---

src/js/components/Video/Video.js
src/js/components/Video/__tests__/Video-test.js
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap

Added tests for Video
video.js
Jest
Jest + review
#4539 
Nope
Nope
b/c

Added tests for Video

---

src/js/components/Carousel/__tests__/Carousel-test.js
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap

Added tests for Carousel events
test file
Events testing
Review
#4539 
no
no

Added tests for Carousel events

---

CONTRIBUTING.md

Fixes the Slack invite link in CONTRIBUTING.md

Fix Slack link

---

src/js/components/Collapsible/stories/Collapsible.stories.js
src/js/components/Collapsible/stories/Horizontal.js
src/js/components/Collapsible/stories/Nested.js
src/js/components/Collapsible/stories/Simple.js
src/js/components/Grommet/stories/Background.js
src/js/components/Grommet/stories/Grommet.stories.js
src/js/components/Grommet/stories/Simple.js
src/js/components/InfiniteScroll/stories/Basics.js
src/js/components/InfiniteScroll/stories/ClassChildren.js
src/js/components/InfiniteScroll/stories/Grid.js
src/js/components/InfiniteScroll/stories/InfiniteScroll.stories.js
src/js/components/InfiniteScroll/stories/Replace.js
src/js/components/InfiniteScroll/stories/Variable.js
src/js/components/InfiniteScroll/stories/typescript/OnMore.tsx
src/js/components/SkipLinks/stories/Simple.js
src/js/components/SkipLinks/stories/SkipLinks.stories.js
src/js/components/SkipLinks/stories/Themed.js
src/js/contexts/AnnounceContext/announce-context.stories.js
src/js/contexts/ResponsiveContext/stories/CustomBreakpoints.js
src/js/contexts/ResponsiveContext/stories/ResponsiveContext.stories.js
src/js/contexts/ResponsiveContext/stories/ResponsiveGrid.js
src/js/contexts/ThemeContext/stories/ExternalComponent.js
src/js/contexts/ThemeContext/stories/ThemeContext.stories.js
src/js/contexts/ThemeContext/stories/ThemeContextExtend.js

Organized storybook stories for Collapsible, Grommet, InfiniteScroll, SkipLinks, AnnounceContext, ResponsiveContext, and ThemeContext
Storybook
Storybook
#4651 
No
No

Storybook restructuring for Utilities

---

src/js/components/CheckBox/stories/Basics.js
src/js/components/CheckBox/stories/CheckBox.stories.js
src/js/components/CheckBox/stories/Custom.js
src/js/components/CheckBox/stories/CustomToggle.js
src/js/components/CheckBox/stories/Indeterminate.js
src/js/components/CheckBox/stories/InsideButton.js
src/js/components/CheckBox/stories/InsideFormField.js
src/js/components/CheckBox/stories/WithStickyDiv.js

Organized storybook stories for CheckBox.
`components/CheckBox/stories/CheckBox.stories.js`
Storybook
Storybook using PR's branch.
#4651
No.

CheckBox stories changed to new structure

---

src/js/components/Carousel/stories/Carousel.stories.js
src/js/components/Carousel/stories/Custom.js
src/js/components/Carousel/stories/Multiple.js
src/js/components/Carousel/stories/Simple.js
src/js/components/Image/stories/Fallback.js
src/js/components/Image/stories/Fill.js
src/js/components/Image/stories/Fit.js
src/js/components/Image/stories/Image.stories.js
src/js/components/Image/stories/Opacity.js
src/js/components/Image/stories/Simple.js
src/js/components/Video/stories/Video.stories.js
src/js/components/Video/stories/typescript/Simple.tsx

Organized storybook stories for Carousel, Image, and Video to be under 'Media' section
Storybook
Storybook
#4651 
No
No

Storybook organized Media stories

---

src/js/components/TextInput/stories/Icon.js
src/js/components/TextInput/stories/InsideFormField.js
src/js/components/TextInput/stories/OnSelect.js
src/js/components/TextInput/stories/Password.js
src/js/components/TextInput/stories/Simple.js
src/js/components/TextInput/stories/StyledPlaceholder.js
src/js/components/TextInput/stories/Suggestions.js
src/js/components/TextInput/stories/TextInput.stories.js
src/js/components/TextInput/stories/Themed.js
src/js/components/TextInput/stories/Uncontrolled.js
src/js/components/TextInput/stories/WithTags.js
src/js/components/TextInput/stories/typescript/CustomSuggestions.tsx

Organized storybook stories for TextInput.
`components/TextInput/stories/TextInput.stories.js`
Storybook
Storybook using PR's branch.
#4651
No.

TextInput stories changed to new structure

---

src/js/components/List/stories/Action.js
src/js/components/List/stories/Basic.js
src/js/components/List/stories/Children.js
src/js/components/List/stories/List.stories.js
src/js/components/List/stories/RenderedList.js
src/js/components/List/stories/Selection.js
src/js/components/List/stories/onClickItem.js
src/js/components/List/stories/secondaryKey.js
src/js/components/List/stories/typescript/Theme.tsx

Organize the List component storybook stories in Visualizations type
`src/js/components/List/stories/List.stories.js`
`yarn test` and `yarn storybook`
#4651 
No
No

Refactor List stories to new format

---

src/js/components/FormField/stories/FormField.stories.js
src/js/components/FormField/stories/Simple.js
src/js/components/FormField/stories/typescript/Custom.tsx

Organized storybook stories for FormField.
`components/FormField/stories/FormField.stories.js`
Storybook
Storybook using PR's branch.
#4651
No.

FormField stories changed to new structure

---

src/js/components/Form/stories/AggregateValidation.js
src/js/components/Form/stories/Controlled.js
src/js/components/Form/stories/ControlledInput.js
src/js/components/Form/stories/ControlledInputLazy.js
src/js/components/Form/stories/ControlledLazy.js
src/js/components/Form/stories/Custom.js
src/js/components/Form/stories/DynamicFields.js
src/js/components/Form/stories/FieldBorderPosition.js
src/js/components/Form/stories/FieldCustomStates.js
src/js/components/Form/stories/FieldSpacingOptions.js
src/js/components/Form/stories/FieldStates.js
src/js/components/Form/stories/FieldWithChildren.js
src/js/components/Form/stories/FieldWithComponentProp.js
src/js/components/Form/stories/Form.stories.js
src/js/components/Form/stories/HelpAndError.js
src/js/components/Form/stories/RequiredLabel.js
src/js/components/Form/stories/Themed.js
src/js/components/Form/stories/Uncontrolled.js
src/js/components/Form/stories/ValidateOnBlur.js
src/js/components/Form/stories/typescript/UncontrolledTyped.tsx

Organized storybook stories for Form.
`components/Form/stories/Form.stories.js`
Storybook
Storybook using PR's branch.
#4651
No.

Form stories changed to new structure

---

src/js/components/Tip/README.md
src/js/components/Tip/doc.js
src/js/components/Tip/stories/SidebarTip.js
src/js/components/Tip/stories/Tip.stories.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Resulted from working on https://github.com/grommet/grommet-site/pull/186

Changed Tip docs

---

src/js/components/Select/stories/Clear.js
src/js/components/Select/stories/Select.stories.js

Changed Select Clear story to use latest Storybook structure
Storybook
Storybook
no
no

Changed Select Clear story to use latest Storybook structure

---

src/js/components/Button/index.d.ts
src/js/components/Button/stories/TipOnButton.js
src/js/components/DataTable/stories/data.js
src/js/components/Tip/stories/InfoTip.js
src/js/components/Tip/stories/ResponsiveTip.js
src/js/components/Tip/stories/SidebarTip.js
src/js/components/Tip/stories/typescript/Children.tsx

Refined tsx and stories of Tip

Fixed tsx and stories of Tip

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/Detail.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Guide.js

Changed DataChart to fix an issue with detail alignment
Detail.js
Enhanced story and used it at various resolutions.
Check updated DataChart -> Guide story at various resolutions and interact to see the detail drop.
This came up when a Green Lake designer was building out some dashboard concepts using grommet-designer.
Here's a screenshot showing the alignment offset problem that is being fixed:
Here's a screenshot showing it aligned:
no
yes

Changed DataChart to fix an issue with detail alignment

---

src/js/components/Tip/stories/typescript/Animated.tsx
src/js/components/Tip/stories/typescript/Children.tsx
src/js/components/Tip/stories/typescript/Simple.tsx

Follow up on https://github.com/grommet/grommet/pull/4785
@apawson :)

Updated tsx imports for Tip stories

---

src/js/components/List/List.js
src/js/components/List/__tests__/List-test.js
src/js/components/List/__tests__/__snapshots__/List-test.js.snap
src/js/components/List/stories/Children.js

Changed List to consider false border prop
List.js
Added test and storybook example was adjusted
Storybook-> List-> Children
The issue surfaced while working on nested Tree
None
No, already documented
Yes

Changed List to consider false border prop

---

src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Changed Select to fix an issue with selecting options after searching.
search storybook
search storybook
#4829 
no
yes!

Changed Select to fix an issue with selecting options after searching.

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/StyledCalendar.js
src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap

Changed Calendar to fix an issue with disable kind buttons and with bounds without timezones
Calendar.js
whitebox Storybook with and without hpe theme
manually
https://github.com/grommet/hpe-design-system/issues/1328
no
yes

Changed Calendar to fix an issue with disable kind buttons and with bounds without timezones

---

src/js/components/Select/index.d.ts

Added clear to SelectProps interface

---

src/js/components/TextInput/index.d.ts

Added onSuggestionSelect to typedef

---

src/js/components/TextInput/TextInput.js
src/js/components/TextInput/stories/Suggestions.js

Changed TextInput to fix an issue with selecting a suggestion
no
no

Changed TextInput to fix an issue with selecting a suggestion

---

src/js/components/WorldMap/README.md
src/js/components/WorldMap/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Updated world map docs to include a more detailed description of the location.

Updated world map docs

---

src/js/components/TextInput/TextInput.js
src/js/components/TextInput/stories/Suggestions.js

Changed TextInput to improve suggestion behavior
grommet-site TextInput with suggestions
no
no

Changed TextInput to improve suggestion behavior

---

src/js/components/TextInput/TextInput.js

Changed TextInput to reflect suggestion that matches when typing
Default Suggestion story
Default Suggestion story
no
no

Changed TextInput to reflect suggestion that matches when typing

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Simple.js

Changed DataChart to fix an issue with empty series object.
One more for building DataCharts in designer.grommet.io
Enhanced unit test
whitebox test with grommet-designer
no
no

Changed DataChart to fix an issue with empty series object

---

src/js/components/Select/SelectContainer.js
src/js/components/Select/__tests__/Select-test.js
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap

Fixes https://github.com/grommet/grommet/issues/4965

Fixes issue #4965. Keypress broken in Select when labelKey specified

---

src/js/components/TableCell/README.md
src/js/components/TableCell/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Signed-off-by: gurkiran_singh <gurkiransinghk@gmail.com>
Added the align prop in the documentation of the TableCell.
#4783

ADDED - docs for the table cell align prop is added

---

src/js/components/Form/Form.js
src/js/components/Form/__tests__/Form-test-controlled.js
src/js/components/Form/__tests__/Form-test-uncontrolled.js
src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
src/js/components/Form/stories/DynamicFields.js

Changed Form to fix an issue with blur validation and dynamic fields.
The essence of the change is to remove any validation messages that don't have a corresponding validation function anymore. So, when a field that had a validation error is removed, it's validation function is removed and the next time we validate, we will remove any prior validation messages from it.
Form.js
Added two units tests.
Also changed the Form -> Dynamic Fields story to validate on blur.
Form -> Dynamic Fields story
#4743
no
yes

Changed Form to fix an issue with blur validation and dynamic fields.

---

src/js/components/Spinner/stories/typescript/Themed.tsx
src/js/components/Spinner/stories/typescript/ThemedIcon.tsx

Moves TS stories of Spinner to Visualizations

Updated Visualizations stories for Spinner

---

src/js/components/Box/README.md
src/js/components/Box/__tests__/Box-test.js
src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
src/js/components/Box/doc.js
src/js/components/Box/index.d.ts
src/js/components/Box/stories/OnClick.js
src/js/components/Button/README.md
src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap
src/js/utils/background.js
src/js/utils/prop-types.js

Changed Box hoverIndicator to accept elevation.
OnClick.js to see it in use
Updated onClick story.
Added hoverIndicator unit test.
OnClick story
We've gotten requests for this off and on over the years and figured adding it would reduce any barriers to entry to grommet for folks wanting it.
should be automatic
yes

Changed Box hoverIndicator to accept elevation

---

src/js/components/Distribution/Distribution.js
src/js/components/Distribution/__tests__/Distribution-test.js

If value in values for Distribution ins't defined and there is more than 1 item in values the app will crash.
This PR changes the behavior so that Distribution won't cause the app to crash when value isn't defined.
More discussion here: https://grommet.slack.com/archives/C09QQEG69/p1614624627045600
Distribution.js
tested with this storybook test:
```javascript
import { Grommet, Box, Distribution, Text } from 'grommet';
export const TEST = () => (
<Grommet theme={grommet} full>
<Distribution
basis="xxlarge"
values={[
{ title: 'Titulek', content: 'Obsah prvního článku', color: 'light-2' },
{ title: 'Titulek', content: 'Obsah druhého článku', color: 'graph-0' },
{ title: 'Titulek', content: 'Obsah třetího článku', color: …
```

Prevent app from crashing when Distribution value in values is not defined

---

src/js/components/Diagram/index.d.ts
src/js/components/Distribution/index.d.ts
src/js/components/DropButton/index.d.ts
src/js/components/FileInput/index.d.ts

This PR helps the transition and fixing the Input Props of components as discussed and suggested in #4998 
Changed Files
Manual tests importing the new types
Create a file importing the new extended versions of type
You can find everything in #4998
#4998 
No
Not sure.

[TS] Fix Diagram, Distribution, DropButon, FileInput type interfaces

---

src/js/components/Tip/__tests__/Tip-test.js
src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap
src/js/components/Tip/stories/Test-theme.js

Added tests for themed Tip to assure backward compatibility of #5047 
I'm planning on removing the storybook example after I assure the b/c.
tests
This PR is adding only tests
#4950 
No
No
NO

Added tests for themed Tip

---

src/js/components/Avatar/README.md
src/js/components/Avatar/__tests__/Avatar-test.js
src/js/components/Avatar/__tests__/__snapshots__/Avatar-test.js.snap
src/js/components/Avatar/doc.js
src/js/components/Avatar/stories/Sizes.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/themes/base.js

Extended Avatar sizes.
The size of the avatar is also affecting the size of the text, so that had been resolved as well.
Added jest and storybook snapshots.
storybook+snapshots+manual review
#4538 
Fixes #5064 
Done
Yes

Extended Avatar sizes

---

src/js/components/Spinner/README.md
src/js/components/Spinner/doc.js
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Updated Spinner message docs
doc.js
Implementing Spinner on the DS drove this clarification about the `message` prop
Done.
No
b/c

Updated Spinner message docs

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
src/js/components/List/List.js
src/js/components/List/__tests__/List-test.js
src/js/components/List/__tests__/__snapshots__/List-test.js.snap
src/js/utils/pagination.js

This PR updates the pagination utility function to review an empty array `[]` when the data passed in is an array but there are no current items. It also updates the function to `useMemo` instead of `useCallback` to avoid an infinite loop that could occur in the `useEffect` `useState` combination.
This fixes an issue with DataTable using `paginate` + `onClickRow` because DataTable relies on data being defaulted to `[]` however usePagination was returning back `undefined` even when the data passed in was an empty array. This ensures that usePagination returns a value that is the same type as the data it received.
src/js/utils/pagination.js
Tested in storybook by adjusting Paginated DataTable with:
```
<DataTable
columns={[
{
property: "a",
header: "a"
},
{
property: "b",
header: "b"
}
]} …
```

Pagination utility to return empty array of current items if data is passed in as array

---

src/js/components/Carousel/stories/Multiple.js

changes the image in carousel story
/Carousel/stories/Multiple.js
https://developer.hpe.com/img/hpe-dev-grommet-gremlin-rockin-static.svg is not longer available
no
no

change image in story

---

src/js/components/CheckBox/CheckBox.js
src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap

Changed React events to apply on Checkbox container level
Checkbox.js
snapshots
snapshots
Previously, the React events on checkbox weren't applied as they were not placed on the container level.
Premilinary work to #5149 
no
yes
backward compatible as this functionality never worked in the past.

Changed React events to apply on Checkbox container level

---

src/js/components/RadioButtonGroup/RadioButtonGroup.js
src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap

Changed RadioButtonGroup to add defaultValue.
Aligns with TextInput, TextArea, Select, DateInput, etc.
RadioButtonGroup.js
Added a unit test
manually
no
yes

Changed RadioButtonGroup to add defaultValue

---

src/js/components/Pagination/stories/Grid.js

Signed-off-by: Bojan Durdevic <bojan88@gmail.com>
The code is missing for Pagination -> Grid example. This PR is fixing the issue.
I couldn't fine any issues opened for this.
Before:
---
After:
No
No

Fix for missing code in Grid Pagination storybook

---

src/js/components/Meter/Circle.js
src/js/components/Meter/Meter.js
src/js/components/Meter/README.md
src/js/components/Meter/__tests__/Meter-test.js
src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
src/js/components/Meter/doc.js
src/js/components/Meter/index.d.ts
src/js/components/Meter/stories/Pie.js
src/js/components/Meter/stories/typescript/MultipleValues.tsx
src/js/components/__tests__/__snapshots__/README-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Meter to add type='pie'
doc.js
Added Pie story and unit tests.
Pie story
maybe
yes

Changed Meter to add type='pie'

---

src/js/components/Grid/StyledGrid.js
src/js/components/Grid/__tests__/Grid-test.js
src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap

Fixed an issue with Grid columns when building minmax.
This change makes the code more defensive and allows the designer to build up to the property value step by step.
StyledGrid.js
no
no
backwards compatible, old way would crash

Fixed an issue with Grid columns when building minmax

---

src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap

DateInput tests are currently setup so that the snapshots need to be updated every month. This updates the snapshots for the month of June
#5208 
No
No

Update DateInput snapshots for June

---

src/js/components/DateInput/DateInput.js
src/js/components/DateInput/__tests__/DateInput-test.js
src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
src/js/components/DateInput/stories/FormatInline.js
src/js/components/DateInput/stories/RangeFormat.js
src/js/components/DateInput/utils.js

Changed DateInput to fix an issue with setting the value
See new unit tests to get an idea of what the changes are related to.
Then utils.js to see how the utility functions are tightened up.
Added unit tests
Manual interaction with DateInput Range format story
DateInput Range format story
#5261 
no
yes

Changed DateInput to fix an issue with setting the value

---

src/js/components/DataTable/stories/Served.js

Changed DataTable to fix Served story
Closes #5364 
no
no

Changed DataTable to fix Served story

---

src/js/__tests__/default-props-test.js
src/js/components/Box/StyledBox.js
src/js/components/Box/__tests__/Box-test.js
src/js/components/Button/__tests__/Button-test.js
src/js/components/Calendar/Calendar.js
src/js/components/Carousel/Carousel.js
src/js/components/DataChart/DataChart.js
src/js/components/DataChart/Detail.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataTable/Body.js
src/js/components/DataTable/DataTable.js
src/js/components/DataTable/Footer.js
src/js/components/DataTable/GroupedBody.js
src/js/components/DataTable/Header.js
src/js/components/DataTable/buildState.js
src/js/components/DataTable/stories/Controlled.js
src/js/components/DataTable/stories/InfiniteScrollDataTable.js
src/js/components/DataTable/stories/MultiplePin.js
src/js/components/DataTable/stories/Served.js
src/js/components/DataTable/stories/Show.js
src/js/components/DataTable/stories/Sort.js
src/js/components/DataTable/stories/data.js
src/js/components/DataTable/stories/rowDetails.js

Incrementally applying [new Prettier defaults](https://prettier.io/docs/en/options.html#arrow-function-parentheses). Applying in batches for easier review.
Prioritizes components impacted in https://github.com/grommet/grommet/pull/5319 in order to unblock. 
Manual review of syntax changes, plus commit test suite.
Manual review of syntax changes
https://prettier.io/docs/en/options.html#arrow-function-parentheses
no
no

apply new prettier defaults

---

src/js/components/Menu/Menu.js
src/js/components/Menu/__tests__/Menu-test.js
src/js/components/Paragraph/doc.js
src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
src/js/components/RangeSelector/RangeSelector.js
src/js/components/RangeSelector/__tests__/RangeSelector-test.js
src/js/components/Select/Select.js
src/js/components/SkipLinks/SkipLinks.js
src/js/components/Table/stories/data.js
src/js/components/Tabs/Tabs.js
src/js/components/Text/__tests__/Text-test.js
src/js/components/Text/doc.js
src/js/components/TextArea/__tests__/TextArea-test.js
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.js
src/js/components/Video/Video.js
src/js/contexts/MessageContext/MessageContext.js
src/js/contexts/ResponsiveContext/__tests__/ResponsiveContext-test.js
src/js/themes/__tests__/theme-test.js
src/js/utils/animation.js
src/js/utils/styles.js

Batch # 3
Incrementally applying [new Prettier defaults](https://prettier.io/docs/en/options.html#arrow-function-parentheses). Applying in batches for easier review.
Prioritizes components impacted in https://github.com/grommet/grommet/pull/5319 in order to unblock. 
Manual review of syntax changes, plus commit test suite.
Manual review of syntax changes
https://prettier.io/docs/en/options.html#arrow-function-parentheses
no
no

Applying Prettier default formatting - Batch 3

---

src/js/components/CheckBoxGroup/CheckBoxGroup.js
src/js/components/Collapsible/Collapsible.js
src/js/components/DataTable/StyledDataTable.js
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/doc.js
src/js/components/DataTable/stories/typescript/OnSelect.tsx
src/js/components/DataTable/stories/typescript/Paginated.tsx
src/js/components/DateInput/doc.js
src/js/components/DateInput/stories/Format.js
src/js/components/DateInput/stories/FormatInline.js
src/js/components/Drop/DropContainer.js
src/js/components/Drop/StyledDrop.js
src/js/components/Drop/__tests__/Drop-test.js
src/js/components/Drop/doc.js
src/js/components/FileInput/stories/Custom.js
src/js/components/Form/stories/Uncontrolled.js
src/js/components/Form/stories/ValidateOnChange.js
src/js/components/Form/stories/ValidateOnMount.js
src/js/components/Form/stories/typescript/TypedForm.tsx
src/js/components/Grommet/StyledGrommet.js
src/js/components/Layer/LayerContainer.js
src/js/components/Layer/StyledLayer.js
src/js/components/Layer/doc.js
src/js/components/List/List.js
src/js/components/List/__tests__/List-test.js
src/js/components/List/doc.js

Batch # 5
Incrementally applying [new Prettier defaults](https://prettier.io/docs/en/options.html#arrow-function-parentheses). Applying in batches for easier review.
Applying remaining Prettier syntax fixes to unblock PRs which are held up from review.
Manual review of syntax changes, plus commit test suite.
Manual review of syntax changes
https://prettier.io/docs/en/options.html#arrow-function-parentheses
no
no

Applying new Prettier defaults to files - batch #5

---

package.json
yarn.lock

Updated grommet-theme-hpe to v2.2.0
Tested locally in All Components storybook.
Related to https://github.com/grommet/grommet-theme-hpe/issues/201
No.
No.

Updated grommet-theme-hpe v2.2.0

---

src/js/components/Meter/index.d.ts

Improve the types of Meter component
None
No
I really believe this is an extremally minor change
Not a breaking change, fully backwards compatible

fix(meter): add semicircle type to index.d.ts

---

src/js/components/Box/stories/Border.js
src/js/components/List/stories/RenderedList.js

This PR adds unique keys to the stories to get rid  of warnings in the console.
border.js
RenderedList.js
storybook see if warning is gone
storybook
none
want this in for release 
no
no

Added unique keys to present warning free Storybook stories

---

src/js/components/TextInput/TextInput.js

Fixes a scenario when TextInput uses a custom JSX placeholder and is uncontrolled. Regression from https://github.com/grommet/grommet/pull/5571
Fixes this [story](https://storybook.grommet.io/?path=/story/input-textinput-styled-placeholder--styled-placeholder) where entering a value does not clear the custom placeholder.
TextInput.js
Storybook
Storybook /story/input-textinput-styled-placeholder--styled-placeholder
OR this story tests both uncontrolled and controlled
```
import { Box, Button, Form, Grommet, TextInput, Text } from 'grommet';
export const StyledPlaceholder = () => {
const [value, setValue] = React.useState('');
const handleClick = () => {
setValue(100.5);
};
return (
<Grommet full theme={grommet}>
<Box> …
```

Fix uncontrolled TextInput custom placeholder

---

src/js/components/Button/index.d.ts

Fixes typescript definition for Button
button ts file
manual
make sure you dont get typescript compilation issues anymore
no
yes
backwards

fix: typescript definitions for button

---

src/js/components/Chart/stories/Animate.js
src/js/components/Chart/stories/Dash.js
src/js/components/Chart/stories/Gradient.js
src/js/components/Chart/stories/Labelled.js
src/js/components/Chart/stories/Layout.js
src/js/components/Chart/stories/Pattern.js
src/js/components/Chart/stories/Point.js
src/js/components/Chart/stories/Range.js
src/js/components/Chart/stories/Rich.js
src/js/components/Chart/stories/Round.js
src/js/components/Chart/stories/Scan.js
src/js/components/Chart/stories/Types.js
src/js/components/Chart/stories/ValueStyle.js
src/js/components/Chart/stories/Window.js
src/js/components/Chart/stories/Zoom.js

Enhance Chart Stories to use Storybook Theming Functionality
`src/js/components/Chart/stories`
#5735 
No
No
Yes

Enhance Chart Stories to use Storybook Theming Functionality

---

src/js/components/DataChart/stories/Axis.js
src/js/components/DataChart/stories/Detail.js
src/js/components/DataChart/stories/Everything.js
src/js/components/DataChart/stories/FourDimension.js
src/js/components/DataChart/stories/Guide.js
src/js/components/DataChart/stories/GuideDefault.js
src/js/components/DataChart/stories/Legend.js
src/js/components/DataChart/stories/MultipleTypes.js
src/js/components/DataChart/stories/Pattern.js
src/js/components/DataChart/stories/Prediction.js
src/js/components/DataChart/stories/Simple.js
src/js/components/DataChart/stories/StackedBars.js
src/js/components/DataChart/stories/typescript/Size.tsx

Enhance DataChart Stories to use Storybook Theming Functionality
`src/js/components/DataChart/stories`
#5735 
No
No
Yes

Enhance DataChart Stories to use Storybook Theming Functionality

---

src/js/components/Meter/stories/Bar.js
src/js/components/Meter/stories/Circle.js
src/js/components/Meter/stories/Labelled.js
src/js/components/Meter/stories/Pie.js
src/js/components/Meter/stories/SemiCircle.js
src/js/components/Meter/stories/VerticalBar.js
src/js/components/Meter/stories/VerticalBarMultiple.js
src/js/components/Meter/stories/typescript/MultipleValues.tsx

Enhance Meter Stories to use Storybook Theming Functionality
`src/js/components/Meter/stories`
#5735 
No
No
Yes

Enhance Meter Stories to use Storybook Theming Functionality

---

src/js/components/Header/stories/Responsive.js
src/js/components/Header/stories/typescript/Ref.tsx
src/js/components/Header/stories/typescript/Simple.tsx

Following #5735 , enhances support to storybook theming for `Header` component.
`src/js/components/Header/stories`
#5735 
No.
No.

Enhance storybook theming for Header

---

src/js/all/stories/CustomThemed/DefaultTheme.js
src/js/all/stories/CustomThemed/ExtendTheme.tsx
src/js/components/Accordion/stories/CustomThemed/Custom.js
src/js/components/Button/stories/CustomThemed/Plain.js
src/js/components/Card/stories/CustomThemed/RichFooter.js
src/js/components/DataChart/stories/Guide.js
src/js/components/DataTable/stories/CustomThemed/Custom.js
src/js/components/List/stories/Show.js
src/js/components/Pagination/stories/CustomThemed/Custom.tsx
src/js/components/RadioButtonGroup/stories/CustomThemed/CustomTheme.js
src/js/components/Spinner/stories/ChildrenSpinner.js
src/js/components/Table/stories/Custom.js
src/js/components/Table/stories/CustomThemed/Custom.js
storybook/preview.js

In October we hit our limit of Chromatic Snapshots. Now that it is a new month we have Chromatic snapshots again, but due to changes that occurred updating storybook stories to enable theming, some of the snapshots have changed and we need a baseline to set the snapshots to.
This PR only includes minor formatting changes on a file so that we have a 'clean' PR to review and set snapshot baselines on.
Chromatic snapshots
Review Chromatic snapshots
No
No

Chromatic Snapshots Baseline 

---

src/js/components/Tag/StyledTag.js
src/js/components/Tag/Tag.js
src/js/components/Tag/__tests__/Tag-test.tsx
src/js/components/Tag/index.d.ts
src/js/components/Tag/propTypes.js
src/js/components/Tag/stories/OnClick.js
src/js/components/Tag/stories/OnRemove.js
src/js/components/Tag/stories/Simple.js

Updates format for Tag files using Prettier
No
No

Prettier changes for Tag component

---

src/js/components/Calendar/index.d.ts

Related Issue https://github.com/grommet/grommet/issues/5833

CalendarProps interface is missing 'messages'

---

src/js/components/FileInput/stories/CustomThemed/Custom.js

Improve FileInput Custom story layout.
Custom story
Storybook with long file name
Storybook with long file names
#5867 
no
no

Improve FileInput Custom story layout

---

src/js/components/Form/Form.js

This PR is just pre-work for #5834. It pulls out the re-naming pieces of #5834 so it can be easier to see the logic changes for the Form 'onMount' improvements.
Form.js
Storybook and jest tests
Storybook Form examples
No test changes.
No
No

Separate function/variable refactor a names from the Form validate on mount changes

---

src/js/components/Tip/stories/Caret.js
src/js/components/Tip/stories/CustomThemed/ResponsiveTip.js
src/js/components/Tip/stories/CustomThemed/SidebarTip.js
src/js/components/Tip/stories/CustomThemed/Themed.tsx
src/js/components/Tip/stories/HeaderActions.js
src/js/components/Tip/stories/InfoTip.js
src/js/components/Tip/stories/typescript/Animated.tsx
src/js/components/Tip/stories/typescript/Children.tsx
src/js/components/Tip/stories/typescript/Simple.tsx
src/js/themes/base.d.ts

Working on https://github.com/grommet/grommet/issues/5735, theming support in stories for Tip component.
`src/js/components/Tip/stories`
`yarn test`
#5735
**No**

enhance Tip stories to use theming

---

package.json
src/js/components/DataChart/DataChart.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/StackedAreas.js

Changed DataChart to fix an issue with passing Chart props per property when using areas
DataChart.js
enhanced unit test and Stacked Areas story
Stacked Areas story
no updates to test approach
no
yes

Changed DataChart to fix an issue with passing Chart props per property when using areas

---

src/js/components/Notification/Notification.js

Changed Notification to include event in onClose.
Needed for grommet-designer
none
no
yes

Changed Notification to include event in onClose

---

src/js/components/Chart/utils.js
src/js/components/DataChart/DataChart.js
src/js/components/DataChart/XAxis.js
src/js/components/DataChart/YAxis.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/index.d.ts
src/js/components/DataChart/propTypes.js
src/js/components/DataChart/stories/Placeholder.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed DataChart to add `placeholder`
new story
Added a new story and unit tests
new story
new test aligns with existing tests
yes
yes

Changed DataChart to add placeholder

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Placeholder.js

Align DataChart placeholder styling with DataTable.
DataChart.js
storybook Placeholder story
storybook Placeholder story
no
yes

Changed DataChart to align placeholder with DataTable

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/XAxis.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/index.d.ts
src/js/components/DataChart/propTypes.js
src/js/components/DataChart/stories/Offset.js

Changed DataChart to add offset gap
Offset.js story
Enhanced the Offset story.
Offset story
followed existing test patterns
#6029 
yes
yes

Changed DataChart to add offset gap

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Simple.js

Fixed an issue with DataChart when there is only one datum
DataChart.js
You need `data` to contain a single object and you need `series` and/or `axis` to attempt a "coarse" x axis.
followed existing tests for DataChart
#5974 
no
yes

Fixed an issue with DataChart when there is only one datum

---

src/js/themes/base.d.ts

update digital clock type to avoid type conflict when bumping grommet 2.17.15 => 2.25

---

src/js/components/DataChart/DataChart.js

Changed DataChart to remove some ie11 specific code
DataChart.js
A few stories + unit tests
no change to tests
no
no

Changed DataChart to remove some ie11 specific code

---

src/js/components/Chart/calcs.js
src/js/components/Chart/stories/Scan.js
src/js/components/Chart/stories/data.js
src/js/components/DataChart/__tests__/DataChart-test.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap

Changed DataChart to fix an issue with negative values.
calcs.js
stories
storiers
#6231 
no
yes

Changed DataChart to fix an issue with negative values

---

src/js/themes/base.d.ts

It fixes the theme type of button.
base.d.ts
local environment, tests 
review the code
N/A
N/A
Follow up to a PR #5651 (I think) 
Nope, it's all bugs.
Yes, as a TS fix

[TS] fix: theme types of Button

---

src/js/components/DataTable/DataTable.js
src/js/components/DataTable/__tests__/DataTable-test.js
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap

Adds a useEffect to ensure if the `sort` prop on DataTable changes that a re-render occurs to make sure the sort icon is updated.
src/js/components/DataTable/DataTable.js
Added jest test. Replaced "Simple" DataTable story with:
```
import { Button, DataTable } from 'grommet';
export const Simple = () => {
const [sort, setSort] = useState({
property: 'a',
direction: 'desc',
});
const handleSort = (property, direction) => {
setSort({ property, direction });
};
return (
<>
<Button
label="Update sort"
primary
onClick={() =>
setSort({
property: 'a',
direction: sort.direction === 'desc' ? 'asc' : 'desc',
})
}
/>
<DataTable
columns={[
{ property: 'a', header: 'A' },
{ property: 'b', header: 'B' },
]}
onSort={({ property, direction }) => { …
```

Add useEffect to track change of sortProp

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/XAxis.js
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
src/js/components/DataChart/stories/Simple.js
src/js/utils/mixins.js

Makes DataChart's XAxis more robust to align labels better. See the comments.
XAxis.js
Used the props from the issue sandbox to verify.
Also reviewed all stories.
Stories
no unit test changes
#6184 
no
yes

Changed DataChart to fix an issue with x-axis label alignment

---

src/js/themes/base.d.ts

make new theme `pad` not required for TS
base.d.ts
locally
no
no

fix ts to not be required

---

src/js/components/SelectMultiple/SelectMultiple.js
src/js/components/SelectMultiple/SelectMultipleContainer.js
src/js/components/SelectMultiple/SelectionSummary.js
src/js/components/SelectMultiple/__tests__/SelectMultiple-test.tsx
src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap

Prevent application crash when `value={null}` in SelectMultiple
Added jest test and changed existing stories to have `value={null}`
No
No, component hasn't been released yet

Harden SelectMultiple against null value

---

src/js/all/stories/AllComponents.js
src/js/themes/hacktoberfest2022.js

Remove theme and spacing controls from All Components story
AllComponents
check the story
check the story
no tests
no
no

Simplified All Components story

---

src/js/components/Avatar/Avatar.js
src/js/components/Avatar/__tests__/__snapshots__/Avatar-test.tsx.snap
src/js/components/Sidebar/__tests__/__snapshots__/Sidebar-test.tsx.snap

adds the `role` to Avatar 
Avatar.js
fixes the violations for accessibility 
no
no

add role to avatar to fix violation

---

src/js/components/DateInput/DateInput.js
src/js/components/DateInput/__tests__/DateInput-test.tsx
src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap

Changed DateInput to fix an issue with range format and no value.
DateInput-test change, to see the problem
One character change to production code, but also a new unit test
followed pattern of existing tests
uncovered while using DateInput with grommet-designer
no
yes

Changed DateInput to fix an issue with range format and no value

---

src/js/components/Carousel/stories/Multiple.js

Hello there,
This should fix up the accessibility violations being reported for the "Multi" story of the `Carousel` component.
Did my best with the captioning, but happy to change if necessary.
---
Resolves accessibility violations for `Carousel` component in Storybook.
All changes are within "Multi" story.
Manually confirmed that Storybook no longer reports the accessibility violations.
As above.
N/A.
None.
Refer to #6124.
N/A.
Don't think so.
Up to maintainers to decide.
Should have no impact on consumers of the library.

Fix Storybook accessibility violations for the carousel (#6124)

---

src/js/components/Header/stories/Responsive.js
src/js/components/Header/stories/typescript/Simple.tsx

Fixes  Storybook accessibility issues in the Header Component 
Header Component, Simple and Responsive stories
Tested manually in Storybook and the accessibility issues disappeared
fixes part of #6124 
No
Yes

Fixed Storybook  accessibility in Header component

---

src/js/components/InfiniteScroll/stories/Grid.js
src/js/components/InfiniteScroll/stories/GridWithShow.js

Fixes Storybook Accessibility issues in Infinitescroll component
Infinitescroll/stories
Manual testing to see that the accessibility issues are gone
Check the accessibility tab in Infinitescroll/grid and infinitescroll/grid with show item 77, in storybook.
#6124

Fixed Storybook Accessibility for Infinitescroll component

---

src/js/contexts/AnnounceContext/stories/Polite.js

Fix accessibility violation for AnnouncedContext Polite Story
storybook
yarn test + storybook
#6124

Fix accessibility violation for AnnouncedContext Polite Story

---

src/js/components/SkipLinks/stories/Simple.js

Fixes Storybook Accessibility issues in `SkipLinks` component
SkipLinks/stories
- manual testing
- none of the existing tests broke
Check the accessibility tab in `SkipLinks/stories/Simple.js` with show item 77, in storybook.
changes don't affect tests
#6124 
There's no need

Fix color accessibility problem in SkipLinks

---

src/js/components/MaskedInput/stories/DateTimeDrop.js

Fixes Storybook Accessibility issues in `MaskedInput/DateTimeDrop` component
MaskedInput/stories/DateTimeDrop.js
- manual testing
- none of the existing tests broke
Check the accessibility tab in `MaskedInput/DateTimeDrop.js` in storybook.
changes don't affect tests
#6124 
There's no need

Fix accessibility problem in MaskedInput

---

src/js/components/Box/stories/MinMax.js

This PR is related to issue #6124
It fixes storybook accessibility violation 
/components/Box/MinMax.js
`yarn test`
#6124

fix: box/minmax storybook accessibility violation

---

src/js/components/DateInput/stories/Form.js
src/js/components/DateInput/stories/Range.js
src/js/components/DateInput/stories/RangeFormat.js

fix `invalidDate` in DateInput stories  
DateInput/stories

fix invalid date in stories

---

storybook/main.js

Runs storybook in strict mode
no
no

Change storybook to run in react's strict mode

---

src/js/components/List/List.js

This PR updates a list condition to avoid looking for object key on undefined variable.
This local setup which simulates a file browser where the list items change depending on what folder is selected.
```import React, { useEffect, useState } from 'react';
import sortBy from 'lodash/sortBy';
import { Box, List, Layer, Button, Text } from 'grommet';
import { Folder, Document } from 'grommet-icons';
const root = [
{
isFolder: false,
name: '1_SW_DVD5_Win_Svr_Std_and_DataCtr_2012_64Bit_English_Core_MLF_X18-27588.iso',
parent: '',
path: '/1_SW_DVD5_Win_Svr_Std_and_DataCtr_2012_64Bit_English_Core_MLF_X18-27588.iso',
lastModified: 1601896220,
size: 3694114816,
},
{
isFolder: false,
name: 'HDD_image2.img',
parent: '',
path: '/HDD_image2.img',
lastModified: 1539836831,
size: 536870912,
},
{ …
```

Update List condition to check for item before indexing primary key

---

src/js/components/DataFilter/DataFilter.js
src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap

Changed DataFilter to use RangeSelector label.
Removes the embedded functionality in DataFilter.
DataFilter.js
stories
stories
no
no

Changed DataFilter to use RangeSelector label

---

src/js/components/Drop/DropContainer.js

Fixes an issue where Drop's scroll position gets reset after a style change occurs in the drop.
The solution separates existing code from one useEffect into two useEffects
Tested with the following story:
``` javascript
import { Close } from 'grommet-icons';
import { Box, Button, DropButton, Heading } from 'grommet';
const align = { top: 'bottom' };
const SimpleDropButton = () => {
const [open, setOpen] = React.useState();
const [hover, setHover] = useState(false);
const onOpen = () => {
setOpen(true);
};
const onClose = () => {
setOpen(false);
};
return (
<Box align="center" pad="large">
<DropButton
label="Open"
open={open}
onOpen={onOpen}
onClose={onClose}
dropContent={
<Box pad="small">
<Box
onMouseOver={() => setHover(true)}
onMouseLeave={() => …
```

Fix drop scroll position getting reset

---

src/js/components/Data/__tests__/Data-test.tsx
src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
src/js/components/DataFilter/DataFilter.js
src/js/components/DataFilters/DataFilters.js
src/js/components/DataSort/DataSort.js
src/js/components/DataTable/Cell.js

Be more resilient to no unfilteredData.
Be better at not trying to render an object as a DataTable cell.
DataFilter.js
play with stories
no change to existing test patterns
#6580 
no
yes

Be more resilient to no unfilteredData. Be better at not trying to render an object as a DataTable cell.

---

.circleci/config.yml
package.json

Related to https://github.com/grommet/hpe-design-system/issues/3099

Updated chromatic command

---

src/js/components/Data/stories/StarWars.js

Simplified Data StarWars story use of Pagination.
Rather than track and drive Pagination properties in the story, let Data do it.
StarWars.js
interact with the story
interact with the story
no
no

Simplified Data StarWars story use of Pagination

---

src/js/components/Form/stories/Controlled.js
src/js/components/Form/stories/ControlledInput.js
src/js/components/Form/stories/ControlledInputLazy.js
src/js/components/Form/stories/ControlledLazy.js
src/js/components/Form/stories/FieldWithChildren.js
src/js/components/Form/stories/FieldWithComponentProp.js
src/js/components/Form/stories/Uncontrolled.js
src/js/components/Form/stories/typescript/TypedForm.tsx

Large forms are not fully visible in stories 
Check Form stories 
#6615 
no

Remove fill prop from Form stories to fix layout issues

---

src/js/components/Data/DataForm.js
src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
src/js/components/DataSummary/__tests__/__snapshots__/DataSummary-test.tsx.snap
src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
src/js/components/DataView/__tests__/__snapshots__/DataView-test.tsx.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
src/js/components/TextInput/StyledTextInput.js
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.tsx
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
src/js/components/TextInput/index.d.ts
src/js/components/TextInput/propTypes.js
src/js/components/Toolbar/__tests__/__snapshots__/Toolbar-test.js.snap
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed TextInput to add `width`.
Basically just adding `width` from Box to TextInput.
TextInput/index.d.ts
manual white box story
manually
no change to existing unit test patterns
needed for DataSearch in Toolbar
yes
yes

Changed TextInput to add `width`

---

src/js/components/Data/stories/Cards.js
src/js/components/Data/stories/Controlled.js
src/js/components/Data/stories/DataTable.js
src/js/components/Data/stories/Infinite.js
src/js/components/Data/stories/Inline.js
src/js/components/Data/stories/List.js
src/js/components/Data/stories/Simple.js
src/js/components/Data/stories/SpaceX.js
src/js/components/Data/stories/StarWars.js
src/js/components/Data/stories/Views.js
src/js/components/DataFilter/stories/Simple.js
src/js/components/DataFilters/stories/Drop.js
src/js/components/DataFilters/stories/Inline.js
src/js/components/DataFilters/stories/Layer.js
src/js/components/DataFilters/stories/Simple.js
src/js/components/DataSearch/stories/Simple.js
src/js/components/DataSort/DataSort.js
src/js/components/DataSort/__tests__/DataSort-test.tsx
src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
src/js/components/DataSort/index.d.ts
src/js/components/DataSort/propTypes.js
src/js/components/DataSort/stories/Drop.js
src/js/components/DataSort/stories/Simple.js
src/js/components/DataSummary/stories/Simple.js
src/js/components/DataTableColumns/stories/Simple.js
src/js/components/DataView/stories/Simple.js
src/js/languages/default.json

Changed DataSort to add drop. This makes it more consistent with DataFilters and DataTableColumns.
Reorganized Data stories to create a new 'Data' top level section and put all `<Data />` related components inside it.
anywhere
Added a story and a unit test.
Storybook
no change to test patterns
yes
yes

Changed DataSort to add drop. Reorganized Data stories.

---

src/js/components/DataFilter/DataFilter.js
src/js/components/DataFilter/__tests__/DataFilter-test.tsx
src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap

Changed DataFilter to fix an issue with the range property.
It was already correctly converting the range from Data which starts as an object: `{ min: 1, max: 100 }` and is converted to an array `[1, 100]`.
But, it wasn't converting the `range` property value similarly, until now. :) 
the very beginning, it's a good place to start
manually
followed existing test patterns
no
yes

Changed DataFilter to fix an issue with the range property.

---

package.json
src/js/components/DataSearch/DataSearch.js
src/js/components/DataSearch/__tests__/DataSearch-test.tsx
src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
src/js/components/DataSearch/index.d.ts
src/js/components/DataSearch/propTypes.js
src/js/components/DataSearch/stories/Drop.js
src/js/components/DataSearch/stories/Responsive.js
src/js/languages/default.json

Changed DataSearch to add `drop` and `responsive` properties.
index.d.ts
Added stories and a unit test.
storybook
tests follow existing patterns
yes
yes

Changed DataSearch to add drop and responsive

---

.circleci/config.yml
e2e/tests/heading-test.js
package.json
yarn.lock

add testcafe to circleCI 
closes https://github.com/grommet/hpe-design-system/issues/2826
no
maybe

add library for test-cafe circle-ci

---

src/js/components/Distribution/Distribution.js

Changed Distribution to handle undefined values better.
Found an issue using grommet-designer when the first value is undefined and there are subsequent values.
in the code
customized a story by hand to verify
???
Cannot seem to use jest as the scenario fails type checking.
no
yes

Changed Distribution to handle undefined values better

---

src/js/components/Anchor/Anchor.js
src/js/components/Anchor/__tests__/Anchor-test.tsx
src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.tsx.snap
src/js/components/Button/Button.js
src/js/components/Button/__tests__/Button-kind-test.js
src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
src/js/components/Button/stories/CustomThemed/Active.js
src/js/components/DateInput/DateInput.js
src/js/components/DateInput/__tests__/DateInput-test.tsx
src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
src/js/components/MaskedInput/MaskedInput.js
src/js/components/MaskedInput/StyledMaskedInput.js
src/js/components/MaskedInput/__tests__/MaskedInput-test.js
src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
src/js/components/TextInput/StyledTextInput.js
src/js/components/TextInput/TextInput.js
src/js/components/TextInput/__tests__/TextInput-test.tsx
src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
src/js/themes/base.d.ts
src/js/themes/base.js
src/js/utils/icon.js
src/js/utils/index.js
src/js/utils/styles.js

Adds `theme.icon.matchSize` as a boolean in the theme. When this is true, components with `icon` and `size` will pass the `size` onto the `icon`.
This still allows for any custom overrides via `size` prop on icon to come through.
For TextInput and MaskedInput, I had to adjust how the padding was calculating to account for the variable icon size. I ensured that there was a 12px gap between icon and placeholder text/value across all sizes.
Any component.
Tested in storybook (see screenshot) and added jest tests.
```
import {
Anchor,
Grommet,
Button,
Box,
Menu,
Pagination,
Select,
SelectMultiple,
MaskedInput,
TextInput,
DateInput,
Text,
} from 'grommet';
import { LinkNext, Down, Search } from 'grommet-icons';
export const Active = () => (
<Grommet
theme={{
global: …
```

Add theme.icon.matchSize

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/stories/Dual.js

Changed Calendar to honor reference when set
Calendar.js
Tried assorted stories.
Try various Calendar and DateInput stories. I'm sure I haven't covered everything from a testing perspective.
#6609 
no
yes

Changed Calendar to honor reference when set

---

src/js/components/Calendar/Calendar.js
src/js/components/Calendar/stories/Dual.js

Revert "Changed Calendar to honor reference when set"

---

src/js/components/DataTable/GroupedBody.js
src/js/components/DataTable/__tests__/DataTable-test.tsx
src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
src/js/components/DataTable/buildState.js

Fixed an issue with DataTable groupBy when value is 0
buildState.js
Also temporarily changed the GroupBy story in DataTable to verify.
groupBy a property that has 0 value data in several objects.
followed existing unit test patterns
#6744 
no
yes

Fixed an issue with DataTable groupBy when value is 0

---

src/js/utils/index.d.ts

Fixes https://github.com/grommet/grommet/issues/6791
https://github.com/grommet/grommet/issues/6791
-
-
-
-
-
-
No
No

Fix normalizeColor parameter name in types

---

src/js/components/Chart/Chart.js
src/js/components/Chart/__tests__/Chart-test.tsx
src/js/components/Chart/__tests__/__snapshots__/Chart-test.tsx.snap
src/js/components/Chart/index.d.ts
src/js/components/Chart/propTypes.js
src/js/components/Chart/stories/Layout.js
src/js/components/Chart/stories/Pattern.js
src/js/components/Chart/stories/Vertical.js
src/js/components/Chart/utils.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

Changed Chart to add `direction`.
This is pre-work for changing DataChart to support vertical direction.
Chart.js
Added a story and a unit test.
Probably manually.
Following existing test patterns.
Part of #6790 
yes
yes

Changed Chart to add direction

---

src/js/components/Footer/stories/DoubleFooter.js
src/js/components/Footer/stories/Sitemap.js
src/js/components/Footer/stories/Social.js

Updates the Site, Social and Double Footers to fix the Violations
Some minor contrast and role violations were found in the Footer (Site, Social, Double) that are now fixed.
No!!

Fixed Footer violations

---

src/js/components/DataChart/DataChart.js
src/js/components/DataChart/Detail.js
src/js/components/DataChart/propTypes.js

Add support for detail with direction horizontal
https://github.com/grommet/grommet/assets/12522275/9e1d3546-ba5a-4f05-969b-66e38bc05be0

Add support for detail with direction horizontal

---

src/js/components/DataSort/DataSort.js
src/js/components/DataSort/__tests__/DataSort-test.tsx
src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap

Fixes an issue where when the Data array is empty DataSort will throw an error.
Added a jest test and tested in storybook
This issue can be seen in the Data/DataTable story by searching with a string that doesn't match anything then trying to open the filters.
no
yes

Fix issue in DataSort when data is empty

---

package.json
src/js/components/Text/StyledText.js
src/js/components/Text/Text.js
src/js/components/Text/__tests__/__snapshots__/Text-test.tsx.snap
src/js/utils/styles.js

Updates Text to use transient props

Updates Text to use transient props

---

src/js/components/Drop/DropContainer.js
src/js/components/Drop/StyledDrop.js
src/js/components/Drop/__tests__/__snapshots__/Drop-test.tsx.snap

Convert Drop to use transient props.

Change Drop to use transient props

---

src/js/components/Layer/LayerContainer.js
src/js/components/Layer/StyledLayer.js
src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
src/js/utils/styles.js

Convert Layer to use transient props

Convert Layer to use transient props

---

CODE_OF_CONDUCT.md

Remove Eric from the code of conduct enforcement section 
no
no

Edit code of conduct enforcement section

---

.circleci/config.yml
src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.tsx.snap

Snapshot fix and small config change. Hoping we can merge this to trigger the stable release for the beta branch.

Update snapshot after merging master, remove chromatic check on merged PRs

---

.circleci/config.yml
src/js/utils/styles.js

Trivial change to test CircleCI.

Add comment 2

---

src/js/components/Box/index.d.ts

Update List existing typing's for `onClick` event handlers
`src/js/components/Box/index.d.ts`
Testing the `Box` Multiple values story in the storybook
Part #3165 
NO
NO
NO

Improve event handler typings for Box

---

src/js/components/Chart/index.d.ts

Update List existing typing's for `onClick`, `onHover` event handlers
`src/js/components/Chart/index.d.ts`
Testing the `Chart` Multiple values story in the storybook
Part #3165 
NO
NO
NO

Improve event handler typings for Chart

---

.circleci/config.yml
src/js/components/CheckBox/StyledCheckBox.js

Styled components beta minor change to trigger circleci

---

package.json

Updates package.json to use new chromatic token
no
no

Update chromatic token

---

.circleci/config.yml

Update npm token name

---

src/js/components/SelectMultiple/__tests__/SelectMultiple-test.tsx

Adds a test to SelectMultiple to cover the behavior added in this PR: https://github.com/grommet/grommet/pull/7079
no
no

Add test for adding additional options to SelectMultiple within onSearch

---

src/js/components/Tag/index.d.ts
src/js/components/Tag/propTypes.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

fix missing props and typings for tag component

---

package.json

enhancement : preventDefault added to OnDown and OnUp calls
List Component
1. Manually clicking the start icon to ensure the expected behaviour and set default value.
2. Local Jest tests.
1. Run storybook and open List Component section
2. Select Order section Test with Up and Down keys
commets : https://github.com/grommet/grommet/pull/7140#discussion_r1492901449
No

enhancement : preventDefault added to OnDown and OnUp calls

---

.circleci/config.yml

Testing new CircleCI workflow.

Add test CircleCI workflow

---

.circleci/config.yml
package.json

Remove chromatic token from package.json and reference environment variable instead.
Also, remove test worfklow.

Remove chromatic token from package.json

---

.circleci/config.yml

Add CircleCI context for release and publish jobs

Add CircleCI context for release and publish jobs

---

.circleci/config.yml

test npm token

---

CONTRIBUTING.md

Adds dco info to the contributing guide
no
no

Add DCO info to contributing guide

---

src/js/components/SelectMultiple/__tests__/SelectMultiple-test.tsx
src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap

Improve run time of SelectMultiple tests to avoid timeout issues
no
no

Change SelectMultiple tests to improve run time

---

package.json
yarn.lock

upgrade chromatic

---

package.json
yarn.lock

revert chromatic to previous release

---

src/js/themes/base.d.ts

add missing types for `pinned`
base.d.ts
locally
no

Add missing types for List pinned theme

---

.github/ISSUE_TEMPLATE.md

Changes our issue template to include a question about submitting a PR
no
no

Change issue template to include PR question

---

src/js/components/List/List.js
src/js/components/List/__tests__/List-test.tsx
src/js/components/List/__tests__/__snapshots__/List-test.tsx.snap
src/js/components/List/index.d.ts
src/js/components/List/propTypes.js
src/js/components/__tests__/__snapshots__/components-test.js.snap

enhancement: List onOrder - Hide index of items
List Grommet Component
manual testing and jest
Go to List component onOrder function new props added 
fixes: #7266

enhancement: List onOrder - Hide index of items

---

src/js/all/stories/Colors.js
src/js/components/Accordion/stories/CustomThemed/Rich.tsx
src/js/components/Box/stories/Background.js
src/js/components/Card/stories/Simple.js
src/js/components/Data/stories/Cards.js
src/js/components/Data/stories/Properties.js
src/js/components/Grommet/stories/Theme.js
src/js/components/Grommet/stories/Vars.js
src/js/components/List/stories/RenderedList.js
src/js/components/Pagination/stories/Simple.js

Fixed some stories that had accessibility violations flagged in the storybook accessibility tab. Mostly just fixed color contrast issues.
Storybook + accessibility tab
https://github.com/grommet/grommet/issues/6124
no
no

Fixed some storybook accessibility violations

---

src/js/components/Button/stories/Kind.js
src/js/components/Form/stories/CustomThemed/FieldSpacingOptions.js
src/js/components/Form/stories/CustomThemed/Themed.js
src/js/components/FormField/__tests__/__snapshots__/FormField-test.tsx.snap
src/js/components/Grid/stories/AreasPropAlternative.js
src/js/themes/base.js

Fixes storybook accessibility violations flagged by automated testing
https://github.com/grommet/grommet/issues/6124
no
yes, change to base theme
there is a change to the base theme but I would consider it to still be backwards compatible because what was there was not meeting accessibility requirements

Fix additional accessibility issues in storybook part 3

---

src/js/components/Notification/stories/CustomThemed/ThemedNotification.tsx
src/js/components/Skeleton/stories/Individual.js

update stories so the colors visually look acceptable 
stories
locally
locally
This color change affected some storybook stories. We will want to go back and clean up the Skeleton/Individual story and the Notification/Themed Notification story.
no
no

update stories for colors

---

src/js/components/Select/SelectContainer.js

Has fix for the Hover styling on Select component.
components/select/select-container.js
Tested with all the theme levels with storybook
Reset the onMouse movement
#7464 
NA
NA
NA

Fix Select - active, hover, styling issues on mouseOut

---

src/js/components/Pagination/PaginationStep.js
src/js/components/Pagination/__tests__/Pagination-test.tsx
src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap

fix  #7579 Pagination aria label

---

src/js/components/Avatar/__tests__/Avatar-test.tsx
src/js/components/Avatar/__tests__/__snapshots__/Avatar-test.tsx.snap
src/js/components/Tip/__tests__/Tip-test.tsx
src/js/components/Tip/__tests__/__snapshots__/Tip-test.tsx.snap

add tests for the following PRs
https://github.com/grommet/grommet/pull/7596
https://github.com/grommet/grommet/pull/7570
test files
locally 
test files
PRs did not have tests when merged so need to add for release
none
no
no

add tests for tip and avatar PRs

---

src/js/components/DataTable/__tests__/DataTable-test.tsx
src/js/components/Notification/__tests__/Notification-test.tsx

adds tests for the following PRs
https://github.com/grommet/grommet/pull/7694
https://github.com/grommet/grommet/pull/7683 
test files
ran tests
run the tests
yes
These PRs needed tests
for release prep
no
no

add tests for release

---

src/js/components/Cards/Cards.js
src/js/themes/base.d.ts
src/js/themes/base.js

Adds theme objects for the Cards component.
cards.js
yes
yes

add cards theme object

---

src/js/components/SelectMultiple/SelectMultipleContainer.js
src/js/components/SelectMultiple/SelectMultipleValue.js
src/js/components/SelectMultiple/SelectionSummary.js
src/js/themes/base.d.ts
src/js/themes/base.js

Adds theme objects for the SelectMultiple component. Based on changes in https://github.com/grommet/grommet/pull/7591

Add SelectMultiple theme objects

---

src/js/components/Table/StyledTable.js
src/js/themes/base.d.ts
src/js/themes/base.js

Adds theme objects for the table component.
table.js
yes
yes

add theme value table

---

src/js/components/DataChart/__tests__/DataChart-test.tsx
src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.tsx.snap
src/js/themes/base.d.ts

Adds a test for the following PRs
https://github.com/grommet/grommet/pull/7779
https://github.com/grommet/grommet/pull/7778

Add test for DataChart theme obj
