- examples/server/package.json
- examples/server/server.js
It seems the website is using the server in `examples/server`. This pull request adds compression to the server to enable compression on the website. This is tied to #32.
[Compression](https://github.com/expressjs/compression) is MIT licensed. "I think" compression is the solution for Express 4.x. There are different things for different versions of express. For example, [here's an article covering some of them](http://inspiredjw.com/do-not-forget-to-use-gzip-for-express/).
> Adding compression to the example server.

- package.json
When using `npm` commands I get the message:
```sh
$ npm install
npm WARN package.json grommet@0.2.2 license should be a valid SPDX license expression
```
This is because the license isn't keyed right. There's a [list on the SPDX site](https://spdx.org/licenses/) and this request corrects the key.
> Fixing license in package.json

- docs/src/scss/_objects.home.scss
The jumping caused by different padding size on hover state.
> Fixed jumping buttons on home page.

- package.json
- src/utils/gulp/gulp-tasks-test.js
This changes **gulp test** to use istanbul instead of blanket. the [gulp-blanket-mocha](https://www.npmjs.com/package/gulp-blanket-mocha) module seems to be inactive, while [gulp-jsx-coverage](https://www.npmjs.com/package/gulp-jsx-coverage) being maintained.
This change also fixes the problem of generating the test coverage on windows #55.
> Added new gulp task using gulp-jsx-coverage.

- package.json
- templates/cto-app-tuner/package.json
- templates/medium-app/package.json
- templates/todo-app-modular/package.json
Just downgraded jsdom from 4.4.0 to 3.1.2 and now grommet can be built with node 0.10. Also removed jsdom from the templates dependencies.
> Downgraded jsdom from 4.4.0 to 3.1.2 for compatibility with node 0.10

- package.json
- src/utils/test/mocked-dom.js
With this change we can build grommet on windows without depending on python.
> Switched jsdom to jsdom-no-contextify to avoid python dependency.

- docs/gulpfile.js
- docs/hpe/gulpfile.js
- docs/hpinc/gulpfile.js
- gulpfile-grommet-dist.js
- package.json
- src/utils/gulp/gulp-tasks.js
- templates/cto-app-tuner/package.json
- templates/init/package.json
- templates/medium-app/package.json
- templates/todo-app-modular/package.json
This PR aims to move from jsx loader to babel, which is now the recommended way to transpile future JS code.
> Switch from jsx loader to babel

- src/scss/grommet-core/_base.font.scss
- src/scss/grommet-core/_settings.font.scss
- src/scss/grommet-core/index.scss
- src/scss/hpe/_hpe.defaults.scss
- src/scss/hpinc/_hpinc.defaults.scss
Without this, apps created with the `grommet init` command will not change to the correct font when changing themes.
> Added defaults for font family and updated themes to specify default font

- src/js/components/App.js
- src/js/utils/Locale.js
- templates/init/src/index.html
This PR adds the lang attribute to the App grommet component and to the html tag as suggested but the [WCAG 2.0 guidelines](http://www.w3.org/TR/WCAG20-TECHS/H57.html). 
If no lang attribute is passed to the App component, it gets the default locale from the browser. Also, the App component sets the lang attribute to the html tag if it is not set.
> Added lang attr to html tag and grommet App.

- src/utils/gulp/gulp-tasks-test.js
With this change *selenium-standalone* will be required only when running the tests.
> Enclosed selenium-standalone dependency for test environment.

- src/scss/hpe/_hpe.defaults.scss
- src/scss/hpinc/_hpinc.defaults.scss
Since applications will be running behind https a useful default
is to set the CDN to use https. This will help to have all assets
served that way. It will also help with https everywhere which is
useful.
> Updating the font CDN to use https.

- src/js/components/Article.js
- src/js/components/Section.js
- src/js/components/SkipLinkAnchor.js
- src/js/components/SkipLinks.js
- src/scss/grommet-core/_tools.flexible.scss
- Using <a> instead of <div> on SkipLinksAnchor (@ericsoderberghp suggestion)
- SkipLinkAnchor moved from Box to Article/Section (@ericsoderberghp suggestion)
- Added tabIndex -1 to SkipLinksAnchors as suggested in [A Skip Link Primer](http://viget.com/inspire/skip-link-primer)
- Using .focus() when moving to the anchor as suggested in [A Skip Link Primer](http://viget.com/inspire/skip-link-primer)
- Removed trailing white space from scss file.
> Refactoring addressing the comments from @ericsoderberghp

- src/js/components/SkipLinks.js
This PR fix #113. The reason this is happening is that the `componentDidMount` method is not called when a react-router dynamic segments are used. React-router suggest implementing also `componentWillReceiveProps` (See [React Router Guide](https://github.com/rackt/react-router/blob/0.13.x/docs/guides/overview.md)).
> Updating SkipLinks when changing route.

- docs/src/DocsHeader.js
This minor change improves screen reader access to the Grommet Docs.  Both the logo and the Grommet text in the heading were link same location and would cause screen readers to read "Grommet twice".  It is now fixed.
> Removed redundant links in the Grommet docs header.

- src/js/components/Calendar.js
The bug is caused by the method toISOString, which returns a string representation of a date having the timezone zero UTC offset, as denoted by the suffix "Z".
On the other hand, the calendar is populated with dates having the timezone of the user's machine.
That's why Tue Jul 07 2015 00:00:00 GMT+0300 becomes 2015-07-06T21:00:00.000Z.
I replaced date.toISOString().slice(0, 10) with moment(date).format('YYYY-MM-DD') and it works ok right now.
> fix #75 Datepicker - selected date differs one day from shown date

- src/js/components/List.js
- test/components/ListItem-test.js
This PR enables non-selectable lists. Currently, all ListItems have the class `list-item--selectable` whether or not the property `onSelected` of the List component is set. Due to assigning `this._onClickItem.bind(this, item)` to all ListItems (see [code](https://github.com/HewlettPackard/grommet/blob/master/src/js/components/List.js#L128)), the onClick property of each ListItem is always truthy and thus the class `list-item--selectable` is assigned (see [code](https://github.com/HewlettPackard/grommet/blob/master/src/js/components/ListItem.js#L19-L21)).
This PR assigns `this._onClickItem.bind(this, item)` only if the onSelected property of the list is set.
Signed-off-by: Tobias Kahse <tobias.kahse@hp.com>
> Non-selectable Lists

- src/scss/grommet-core/_settings.font.scss
If the server is running over https, the fonts are not loaded as the client fails with, error 'Mixed Content'.  Loading the fonts over https all the time should solve this conflict.
> Changed http to https in font-urls

- docs/src/develop/components/ButtonDoc.js
- src/js/components/Button.js
Tested by changing order of buttons on Todo-app-modular; before this change pressing enter on the form would cancel instead of submit.  After this change, regardless of button order, pressing enter on form will submit form.
Signed-off-by: Bryan Jacquot <jacquot@hp.com>
> Addressing issue #53 allowing type of button to be set.

- src/utils/gulp/gulp-tasks-dev.js
This should make dev easier for vagrant and other vm users, without removing the override ability. Also makes it significantly easier to test out on mobile and other devices/browsers on different machines.
Also make gulp open localhost in the browser instead of 0.0.0.0 if the host is 0.0.0.0.
> Open all host ports by default for `gulp dev`

- src/utils/gulp/gulp-tasks-dev.js
If people are running npm in a vm, but editing on the host webpack does not see the changes via inotify.
This change allows folks to poll if they want by simply putting
watchOptions: {
poll: true
}
into their gulpfile.
My tests showed it was rather inefficient and consumed a fair bit of CPU cycles.
Once
https://github.com/webpack/watchpack/issues/2
is fixed we should be good, although I still probably wouldn't enable it by default.
> Gulp poll for vm hosted grommet projects

- bin/grommet.js
- docs/src/develop/GetStarted.htm
Grommet documentation said "make sure you set the NODE_PATH to point the node global modules install directory". This can be problematic, as explained in [this nvm issue](https://github.com/creationix/nvm/issues/586).
Using a relative path to the current module is safer and simpler.
> Removed dependency on NODE_PATH for grommet path resolving.

- src/utils/gulp/gulp-tasks.js
First, I wanted to support reac-hot-loader. Then, I stumbled upon an error when babel processed some libraries (eg. socket-io). I want to exclude those, or just include specific directories.
I tried to use option `webpack.module.loaders`, but these are always added after default loaders (ie. `devWebpackConfig.module.loaders.push(loader);` at gulp-task-dev.js)
Using this patch, I can add the following option to gulpfile.js:
```
jsLoader: {
test: /\.js$/,
loader: 'react-hot!babel',
include: [
path.resolve(__dirname, "src/js"),
path.resolve(__dirname, "node_modules/grommet/src/js")
]
},
```
> Added jsLoader option.

- docs/src/scss/_objects.home.scss
- src/scss/grommet-core/_objects.box.scss
https://trello.com/c/gytuTCGa/261-fix-layout-of-grommet-home-page-to-not-show-horizontal-scroll-bar-especially-when-resizing-see-screen-shot
The issue was caused my multiple modules having a `width` or `max-width` of `100vw`, which all non-gecko browsers incorrectly interpret to include the scrollbar. More here:
http://caniuse.com/#feat=viewport-units (known issue 7)
http://codepen.io/anon/pen/ZGYNWZ
The solution is to add (or replace with) `max-width: 100%` in most cases. I suggest we update this issue across all affected Grommet SCSS files.
> Fix layout of grommet home page to not show horizontal scroll bar, especially when resizing. See screen shot.

- docs/src/Home.js
- src/js/components/Menu.js
- src/scss/grommet-core/_objects.menu.scss
https://trello.com/c/aljMXJA2/259-fix-button-size-to-be-full-width-on-mobile-phone-screens
Added a `full` attribute on the Menu object, allowing menu and content to be full width.
Also, removed right margin on links inside responsive box for handheld size:
```
@media screen and (max-width: 44.9375em) {
.menu--inline.menu.box--direction-row.box--responsive > * {
margin-right: 0;
}
}
```
Not sure this is the ideal/final solution, but we wanted to avoid adding `className` directly to all links.
> Fix button size to be full width on mobile phone screens.

- docs/src/Home.js
- src/js/components/Menu.js
- src/scss/grommet-core/_objects.menu.scss
https://trello.com/c/aljMXJA2/259-fix-button-size-to-be-full-width-on-mobile-phone-screens
Reopening pull request https://github.com/HewlettPackard/grommet/pull/188, as something didn't get merged the first time. Also, removed `full` property and SCSS that I had previously added, as it already exists for Menu as an extension of Box.
> Fix button size to be full width on mobile phone screens. (reopened)

- src/scss/grommet-core/_objects.form.scss
- src/scss/grommet-core/_objects.index.scss
- src/scss/grommet-core/_objects.layer.scss
- src/scss/grommet-core/_objects.menu.scss
- src/scss/grommet-core/_objects.search.scss
- src/scss/grommet-core/_objects.sidebar.scss
- src/scss/grommet-core/_objects.tile.scss
https://trello.com/c/7vPbBNCk/269-verify-any-element-that-has-max-width-of-100vw
After completing https://github.com/HewlettPackard/grommet/pull/187, we discovered there were other modules also affected by the issue of using `width:100vw` without `max-width:100%`. This fix updates all SCSS files in Grommet `src` to resolve the issue. `max-width:100vw` was also updated to `max-width:100%`.
> Verify any element that has max-width of 100vw

- src/utils/gulp/gulp-tasks-test.js
This section passes jslint on some installs, but not others. 
eslint under 1.5.0 lets it through, 1.5.0 and later fails on indentation.
The change still works on under 1.5.0 eslint.
> Jslint fix

- src/scss/grommet-core/_base.text.scss
- src/scss/grommet-core/_objects.header.scss
As per my conversation with @ericsoderberghp, the h1-h5 styles don't really belong in the `objects.header` file. I've moved them to `base.text`. This PR directly affects https://github.com/HewlettPackard/grommet-hpe/pull/8 and this should be merged first.
> Moved h1-h5 from objects.header to base.text.scss

- src/scss/grommet-core/_tools.page.scss
I attempted to use this mixin and got an error because `$center-content-width` was undefined. Based on the purpose of this mixin, I believe the variable was supposed to be `$center-column-width`, which works as expected.
> fix variable name from "center-content-width" to "center-column-width"

- docs/src/DocsSplit.js
- docs/src/Home.js
- docs/src/develop/HelloWorld.htm
- docs/src/develop/Tutorial.htm
Fixed some `alt` tags on images and added title element on logo for Grommet documentation development and design pages.
> Added alt tags to images and fixed Grommet logo in docs

- src/img/icons/drive-cage.svg
- src/img/icons/workshop.svg
I noticed these typos in my webfont output.  Figured I'd just submit them back corrected since I corrected them on my end as well.
> Fixing typos in icon svg filenames

- src/img/icons/cursor.svg
Found another typo while working on the font icons.  Just submitting it back for correctness.  Will have a more meaningful contribution soon!
> Typo in svg name

- src/img/icons/document-pdf.svg
- src/img/icons/document-rtf.svg
- src/img/icons/document-txt.svg
There is a weird phantom path that shows up in a few of the svgs that causes issues when trying to render as a font.  Because it causes an issue with unioning the paths, the font generates with inversions of the paths.
> Fixing extraneous path nodes in document svgs

- src/scss/grommet-core/_objects.article.scss
Fixing https://github.com/grommet/grommet/issues/263 - `width: 100vw` incorrectly adds a horizontal scrollbar if a vertical scrollbar is present. Adding `max-width: 100%` fixes the issue.
> Issue 263: fix horizontal scrollbar on homepage

- src/js/components/Menu.js
Fixes #284. Also removes `a11yTitle` already defined in `Box` `propTypes`.
> Do not translate label to get menu title

- src/utils/gulp/gulp-tasks-dev.js
This will allow url changes in the app to reflect in the browsers url bar.
Hot Module Replacement will work without having to navigate to `http://<host>:<port>/webpack-dev-server/`. :smiley: 
[webpack-dev-server inline mode](https://webpack.github.io/docs/webpack-dev-server.html#inline-mode)
> Fix HMR inline mode

- src/scss/grommet-core/_objects.tag.scss
Please see this comment: https://github.com/grommet/grommet-docs/pull/13#issuecomment-174632811 for reference.
Here's what the Tag component looks like with the new styles:
__Note__: "First" tag shows the hover state
> Updated Tag component to use Secondary button styles.

- src/js/components/Layer.js
- src/js/components/Menu.js
Hello,
It seams that react router is now passing PropTypes.object trough context.
```
"grommet": "0.5.3",
"react-router": "2.0.0-rc5"
```
```
Error:
Warning: Failed Context Types: Invalid context `router` 
of type `object` supplied to `Layer`, expected `function`.
...
```
This is the problem for all grommet components that are defining proptypes router: PropTypes.func,
Opinion?
Cheers
> react-router context proptypes is changed from function to object

- src/js/components/Brick.js
- Adds optional onClick prop to Brick component so users have the option to either pass in href or onClick.  This allows the user to route to another screen in a single-page app if they're using something such as React Router, or route the user to another page the traditional way if that's what they prefer.
> Adds onClick prop to Brick component

- src/scss/grommet-core/_objects.layer.scss
- src/scss/grommet-core/_objects.tabs.scss
- src/scss/hpe/_hpe.defaults.scss
- fixing bug with extra spacing in box for flush Layers
- centering responsive (column) tabs within their LI containers
- removing underline from HPE brand link defaults
> layer flush, responsive tabs, hpe link text-decoration defaults

- src/js/components/Table.js
- src/scss/grommet-core/_objects.table.scss
I'm proposing this PR to add responsive behavior for tables. This is what I've done:
* Table is always responsive in mobile size.
* Table is also responsive depending on how many columns has to be rendered in a given container.
- To achieve that, I've set a `MIN_CELL_WIDTH` to 96 and I calculate if there is enough space for the amount of columns to be rendered in a given container. If the space is too short, the table is displayed in a responsive manner.
* Hiding header text for scrollable tables as the text is already available in the mirror.
This is a regular Table (ferret example):
This is the same table in responsive mode when the size of the window is still desktop, but there is not enough space for it to render the columns.
> Refactored table to be responsive

- src/js/components/Layer.js
- Fixes tabbing in Layer overlay content for when onClose prop is undefined
- Do not render Close (x) icon button when onClose is undefined since the button would be disabled anyway
> Fixes tabbing in Layer overlay content for when onClose prop is undefined

- src/js/components/Box.js
- src/scss/grommet-core/_objects.box.scss
Adding the following options:
**align:** baseline
**alignContent:** start, center, end, between, around, and stretch (default)
Issue: https://github.com/grommet/grommet/issues/306
> Enhancing Box with more flexbox properties

- src/js/components/Meter.js
- src/scss/grommet-core/_objects.legend.scss
- src/scss/grommet-core/_objects.meter.scss
Fixes the following issues:
* https://github.com/grommet/grommet/issues/400: font label contrast issue with background color (when legend is inline)
* https://github.com/grommet/grommet/issues/399: remove active value (displaying total) when total is false, and legend is inline
* fixing legend label/value hover colors so they don't disappear on dark-background-context colors
> Meter fixes: remove total from inline legend (total: false), dark-background-context text colors

- src/scss/grommet-core/_objects.menu.scss
updating Menu component's drop styles so active anchors have hover background color + text color (so active menu anchor is visible in apps where hover text colors are close to active text colors).
> menu component drop styles

- src/js/components/Tiles.js
- src/js/components/Video.js
- src/scss/grommet-core/_objects.tile.scss
- src/scss/grommet-core/_objects.video.scss
Video component:
* so video summary background is full width/height and centered
* allow onClick prop, so clicking on control can do something else (e.g. open a layer with the video) instead of playing the video
* videoHeader prop (for instances where we want to use the video and header component together).
* highlighting current chapter on timeline in brand-accent-3 (if available, if not use brand-color).
* hiding video title when video is playing (on hover), and on small screens
Tile component:
* allow tiles to accept pad props (but still default to small pad)
> Video Component

- src/js/components/Sidebar.js
- src/scss/grommet-core/_objects.sidebar.scss
Adds `full` option, for the `false` case in which someone may not want a full-height sidebar (such as a sidebar for a section in an article-type layout).
> "full" option for sidebar

- src/scss/grommet-core/_objects.box.scss
- src/scss/grommet-core/_tools.pad.scss
* adding back code to halve padding called by pad() mixin (used by box, form, and tile components).
* also making sure to switch between padding direction on responsive (and keep it halved).
> halve padding on responsive + between padding responsive fix

- src/js/components/Layer.js
Implements `{node}` option for `closer` prop, to be consistent with specification in Grommet Docs.
> Customizable "closer" for Layer component

- src/js/components/Video.js
Fix for grommet-estories #100
Pull request removes padding which was forcing play button down. Tested in all major browsers to ensure that the rendered components looks the same and are similar to the mock ups in all of the different media query sizes.
signed-off-by: Kent Salcedo <kentsalcedo@webmocha.com>
> Removes paddings which forces play button down

- src/scss/grommet-core/_objects.menu.scss
Fix for issue #502. Vertically aligns icons in dropdown menu and removes extra left padding (or right padding if reversed)
> add anchor icon styles for small drop menu

- src/scss/grommet-core/_objects.color-index.scss
I decided to go with appending the `-tint-1` for the colorIndex names so that in the future, we can add more tinted versions.
Let me know if I'm heading in the right direction with this, I can go ahead and add the tinted versions to the rest of the colors (accent, light, etc.).
> Adds tinted versions of the "colorIndex" neutral colors.

- src/js/components/Layer.js
- src/js/components/Video.js
addresses issues:
* layer closing when clicking on drop options: https://github.com/grommet/grommet/issues/515
* layer closing when clicking on drop options (grommet-estories): https://github.com/grommet/grommet-estories/issues/145
* fixing video progress bar bug (endless, rapidly progressing progress bar, when clicking on chapter marker): https://github.com/grommet/grommet-estories/issues/153
* taking care of video edge cases: (1) progress bar sometimes is at 101% width, so setting cap to 100%, and (2) ensuring that very last chapter marker can be "active"/highlighted
> layer + video bug fixes

- src/scss/grommet-core/_objects.tag.scss
Fix for https://github.com/grommet/grommet-estories/issues/121
> Tags take full width of container in responsive mode.

- src/scss/grommet-core/_objects.value.scss
When Value has prop `align="center"`, this makes sure the number portion of Value is also centered.
> Centers number portion of Value component when appropriate

- src/js/components/Video.js
For PR: https://github.com/grommet/grommet-estories/pull/176
using forceUpdate() when Video component receives new props so that passing in a new video source will re-render the video (instead of just updating the source).
> allow Video component to display newly received video sources

- src/scss/grommet-core/_objects.box.scss
For sized Boxes, paragraphs should be able to fill the Box.
> Update paragraph sizing for sized Boxes

- src/js/components/Video.js
- src/scss/grommet-core/_base.text.scss
* Shrink Video Icons for Mobile: https://github.com/grommet/grommet-estories/issues/157
> On mobile sizes (regardless of video size option), make sure video control icons shrink.

- src/scss/grommet-core/_objects.video.scss
Fix for Issue #154 - collapses video timeline chapter bar when in mobile view signed-off-by: Kent Salcedo kentsalcedo@webmocha.com
Replaces closed PR https://github.com/grommet/grommet-estories/pull/192
> Collapse timeline and only show progress bar in mobile view

- src/img/icons/overlay.svg
- src/scss/grommet-core/_objects.anchor.scss
- src/scss/grommet-core/_tools.icon.scss
updating viewBox of Overlay icon so that hover will have even lineweights
https://github.com/grommet/grommet-estories/issues/128
(Screenshot shows left: before and right: after.)
> changing anchor icon hover to scale instead of increase stroke width

- src/js/utils/Selection.js
The function matches and matchesElement is not supported in IE 11, so, use msMatchesSelector instead
Issue details: #246
> Fix Issue: Table selection in IE 11 is wrong

- src/js/utils/Selection.js
This matchFunction need the dom element, 
so bind the function to the dom to avoid Illegal invocation
> Bind the function to the dom to avoid Illegal invocation

- src/js/components/Video.js
- src/scss/grommet-core/_objects.video.scss
Adds styling enhancements to progress bar. On mobile view, collapses the timeline and only shows progress bar. If there is a timeline, the progress bar will be above the timeline. If the user hovers and interacts with the video, the timeline will expand and the progress bar will move to the top signed-off-by: Kent Salcedo <kentsalcedo@webmocha.com>
https://github.com/grommet/grommet-estories/issues/219
> Playhead and progress bar styling enhancement

- src/js/components/Menu.js
This fixes #540. Size means something different for menus, so don't pass the prop on to `Box`.
Fixed the same way it was fixed for a similar issue in `Header` and `Footer`, https://github.com/grommet/grommet/commit/249d383446c55d26e0947f1d4672452d39cf2396
> Don't transfer Menu size= to Box

- src/js/components/Video.js
- src/scss/grommet-core/_objects.video.scss
- Changes progress bar color to lighter shade of brand-grey-color
- Vertical align label and time
- Makes labels less bold
Signed-off-by: Kent Salcedo <kentsalcedo@webmocha.com>
> Refactors and styles timeline chapters to match mockup

- src/js/components/Tile.js
- src/scss/grommet-core/_objects.color-index.scss
- src/scss/grommet-core/_objects.tile.scss
For Issue: https://github.com/grommet/grommet-estories/issues/264
* setting padding around Tile for border-medium tiles to 6px, so hover borders overlap each other (basically halving hover border thickness for padding around Tile).
* adding hoverBorderSize option (small, medium, or large), and setting the default to large to preserve original behavior.
> Tile hoverBorderSize option (small, medium, large) + padding between Tiles

- .eslintrc
updating eslintrc to include parserOptions to fix the following errors (object rest spread, jsx, and source type module) for ESLint v2.0.0:
* `Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`
* `Parsing error: Unexpected token <`
* `Parsing error: Unexpected token ..`
> Fixing ESLint errors for gulp dist

- src/js/utils/DOM.js
fixing DOM util function so IE11 doesn't get error (stops rest of grommet app from loading in IE):
Unable to get property 'innerHTML' of undefined or null reference DOM.js (91,3)
> fixing DOM util function for IE11 error: Unable to get property 'innerHTML' of undefined or null reference DOM.js (91,3)

- templates/init/grommet-toolbox.config.js
Fixes warning during "gulp dist":
`customEslintPath has been deprecated. You should use eslintOverride instead`
When building an app that has been initialized using:
`grommet init <appname>`
Signed-off-by: Steve Mays <steve@accuzonix.com>
> Replace deprecated "customEslintPath" with "eslintOverride".

- src/js/components/Chart.js
Fixes bug if bar chart has legend inline, the top value would be partially cutoff by the bounds of the chart signed-off-by: Kent Salcedo <kentsalcedo@webmocha.com>
See screenshots below, top screenshot is current bar chart with inline legend (notice the label of the first bar has been cutoff), second screenshot is fixed chart
> Bar Chart Bug Fix - Cutoff Legend Label

- src/js/components/Article.js
Adds bug fix so that in mobile view, the arrows always render at the bottom of the page while previously they only rendered on a scroll event or on the bounce signed-off-by: Kent Salcedo <kentsalcedo@webmocha.com>
> Resolves bug for arrow not being rendered on bottom of mobile after navigating or if not scrollbar present

- src/js/components/Article.js
- src/scss/grommet-core/_objects.article.scss
* Article.js: allow updates to selected props to trigger new chapter select
* using margin instead of padding for article control to prevent arrow from overlapping scrollbar and hindering scrollbar usage
> Article.js: allow updates to selected props to trigger new chapter select + Article Control/Scrollbar Overlap Fix

- src/js/components/Article.js
Alleviates the flashing of the first slide in the `<Article />` component for the Edge browser. 
Signed-off-by: DerekAhn <git.derek@gmail.com>
> Also adding the same tabbing fix for Edge

- src/scss/grommet-core/_objects.box.scss
Signed-off-by: Michael Gilley <michaelgilley@gmail.com>
Fixes an issue with flex-shrink in IE11:
> Make sure that IE11 doesn't squash paragraphs inside Box

- src/scss/grommet-core/_objects.article.scss
- src/scss/grommet-core/_objects.box.scss
* moving box vertical centering styles into ie11-specific media-query so that they do not break other box in browsers
* removing unwanted scrollbars around article controls for mobile (in place of PR: https://github.com/grommet/grommet/pull/562)
> Bug Fixes: ie11 box vertical centering + article control arrows (mobile scrollbars)

- src/scss/grommet-core/_objects.title.scss
In response to issue #613 [Title in IE11 cuts off long text without Ellipsis](https://github.com/grommet/grommet/issues/613). It appeared to be a cross browser issue as well.
Signed-off-by: DerekAhn <git.derek@gmail.com>
> Override Box's display flex to show ellipsis

- src/js/components/NumberInput.js
We need to coerce `NaN` from bad input to `parseInt` to 0 so we don't break the maths.
Signed-off-by: Michael Gilley <michaelgilley@gmail.com>
> Ensure that bad input is parsed correctly

- src/scss/grommet-core/_objects.header.scss
Adds missing style property for `header--large` from https://github.com/grommet/grommet/pull/617
This is affecting `header--large` Header in Safari both on desktop and iOS.
https://github.com/grommet/hpe-digitaltoolkit/issues/86
> Adds missing style property for header--large Header from PR #617

- bin/grommet.js
This change improves the way the grommet command line tool handles the
options from the command line (optstrings) by parsing the initial values
using a single library, yargs.
Also, this change adds an extra validation to the task name given by the
user before trying to executing it.
Other minor changes:
* Remove print of NPM version every time the grommet tool is executed
* Remove multiple access to grommet package.json file
* Add clear error message if task is not supported.
> Improve optstrings handling on grommet tool

- src/js/components/Tile.js
- src/js/utils/CSSClassnames.js
adding NAMESPACE property to CSSClassnames (used by Tile.js to prefix hover color index with grommetux-, since it currently results in undefined).
Previously was adding the CSS class: `undefinedborder-medium-hover-color-index-unknown` instead of `grommetux-border-medium-hover-color-index-unknown`, so hover border wasn't showing up. Prefixes css class so hover border will show, as in screenshot.
> Fixing selectable tile hover color index

- src/js/components/Notification.js
Related to #652.
Currently not wrapping: 
Fixed screenshot:
> Fix IE11 Notification component not wrapping

- src/js/components/Article.js
_onScroll in Article.js causes multiple rerenderings and flashing of arrows/section content in Firefox palm/mobile screen sizes.
* in Firefox, grandchildren will oscillate between different article chapters, and not necessarily be the selectedIndex/selected chapter, which causes flashing/rerendering of arrows when height of [grandchild](https://github.com/grommet/grommet/blob/master/src/js/components/Article.js#L249) is less than or equal to `window.innerHeight + 24`. Using a check for Firefox/IE, to make sure we measure the currently selected chapter element's dimensions in Firefox.
* using grandchildren dimensions to render arrows is needed for Safari, to prevent horizontal wiggling when scrolling vertically on trackpad.
> Fix for article flashing arrows/rerendering in Firefox palm media query.

- src/js/components/Tile.js
https://github.com/grommet/grommet/issues/679
* stops passing unknown props from Tile to Box component, which was causing console warnings in grommet-core and other grommet projects.
> resolving unknown props React warning

- src/js/utils/InfiniteScroll.js
Resolves #620.
Depending on screen size, if user is zoomed in, & amount of Tiles, the `scrollState.onEnd()` function may not get called.
**Problem:** `scrollState.onEnd()` not getting called
**Fixed:**
> Fix InfiniteScroll onEnd() not being called

- src/scss/grommet-core/_objects.form-field.scss
Fixes issue #698.
Put a `NumberInput` inside a `FormField` that has a narrow width (< 300 px). Scrollbar should not be present.
> update flex value to avoid horizontal scrollbar at narrow widths

- src/js/components/Carousel.js
- src/scss/grommet-core/_objects.carousel.scss
adds SVG filter fallback for drop-shadow -webkit-filter, and applies it to carousel controls (with drop shadows) within a Safari-only selector.
Check default appearance of carousel controls in Chrome, and compare it to appearance in Safari.
tested Carousel Docs page in webkit browser (Chrome and Safari) to make sure Safari-only selector didn't affect Chrome.
1) With grommet PR branch checked out, run grommet-docs with `useAlias` flag.
2) Open Carousel Docs page in Safari, and check for visible controls (dots) and arrows.
http://localhost:8002/docs/develop/carousel
3) Open Carousel Docs page in Chrome to make sure controls are still visible/unaffected by svg fallback.
Safari has an issue rendering drop-shadow filters on SVGs, and two potential workarounds are (1) creating and applying an …
> fixing missing carousel controls for Safari

- src/js/components/Notification.js
* Addresses issue when embedding Notification in Layer
* Still defaults to 'horizontal' for IE fix (#675)
Check out http://codepen.io/michaelgilley/pen/YWZVwP. The Layer component should **not** expand the full width of the viewport.
In browser, css testing.
Use codepen above.
#675 introduced a regression on Layer implementation
#675 #652 
Perhaps?
Probably not.
Should work as before. 🎸
> Removes hardcoded full prop in Notification

- src/scss/grommet-core/_objects.form-field.scss
Keep browser input consistent, disable IE’s clear field `X` button.
Resolves #715.
Tested on IE11. 
#715
> Disable IE’s clear field `X` button

- src/js/components/AccordionPanel.js
- src/js/components/Collapsible.js
- src/scss/grommet-core/_objects.accordion-panel.scss
- src/scss/grommet-core/_objects.collapsible.scss
- Allow accordion panel content to take full width.
- Fix icons being rotated in accordion panel when active, only rotate control icon in header. 
- Fix accordion content flashing in Safari. 
Chrome, FireFox, Safari, & IE11.
> Allow accordion content to take full width & fix icons being rotated

- src/img/icons/pause.svg
- src/img/icons/play.svg
Replaces Play and Pause icons with filled versions instead of the current outlined versions. This is for the new design for the Video Component which goes into the Toolkit Video Marquee (https://github.com/grommet/hpe-digitaltoolkit/issues/103#issuecomment-233465877).
CC: @L0ZZI @kyle-locke @prewalia
> Filled versions of the Play and Pause icons.

- src/js/components/Calendar.js
Pass Calendar props to children. 
Allows user to pass onBlur, onFocus, etc. to Calendar component. 
Related to #450.
Pass onBlur and or onFocus to Calendar component. 
```javascript
<Calendar value={...} onChange={...} onBlur={...} onFocus={...} />
```
#450
> Pass Calendar props to children

- src/js/components/Chart.js
- src/js/components/Legend.js
- Updating Chart.js and Legend.js to allow units options to be an object with "prefix" and "suffix" properties (strings) instead of just a string which gets appended to end of chart value.
- Shows units on inline legends.
- Check ChartsDoc in grommet-docs, and see if configuring `units` option as object (e.g. `{prefix: '$', suffix: 'MN'}` or `{prefix: '$'})` displays correctly on charts with inline legends.
Tested changing all the ChartsDoc examples with units to use:
- `{prefix: '$', suffix: 'MN'}`
- `{prefix: '$'}`
- `{suffix: 'MN'}`
- `"MN"` (previous units type, string-only)
Chart units are prefixed/suffixed appropriately, and show up in Chrome, Firefox, and Safari.
For a grommet-based project, needed a (bar) Chart with inline legend to show units on values (see screenshots), and …
> Update Chart units options to allow suffix and prefix properties + show units on inline legends

- src/js/components/Menu.js
change PropTypes.oneOf('expand'); to PropTypes.oneOf(['expand']) 
in latest React passing string to oneOf throw an error
> oneOf expected instance of array

- src/scss/grommet-core/_objects.form-field.scss
Updates CSS to override `padding-right` on `SearchInput` component when it is a child of `FormField`
Manual UI Review
Fork the codepen below and test with this PR change applied.
N/A
http://codepen.io/nickjvm/pen/yJxYWE?editors=0110
> override padding-right on SearchInputs nested inside FormField

- src/js/components/Tiles.js
- src/scss/grommet-core/_objects.tile.scss
- adds masonry and numColumns options to Tiles (fills masonry-style layout with cards/Tiles of varying height in order from left-to-right)
- pull down related grommet-docs PR (https://github.com/grommet/grommet-docs/pull/65) and check against grommet PR branch using `gulp dev --useAlias`
- tested against toolkit contentcard modules/Tile component in Chrome, Safari, and Firefox on desktop and mobile screen widths.
- test applying masonry and numColumns options to Tiles component (use Tile with varying-height content):
```
<Tiles size="large" masonry={true} numColumns={7}>
...
</Tiles>
```
- masonry-style news feed was desired in another project, and some investigation was done to implement a css-only option, but using `column-count` and `column-gap` options lays out Tiles from …
> Tiles masonry and numColumns options

- src/scss/grommet-core/_objects.form-field.scss
- moves IE11 form-field height styles into IE-specific media query to fix overflow scrollbars
- checked to make sure overflow scrollbars disappeared for form fields in Chrome, Safari, and Firefox.
Form Fields before (overflow scrollbars from fix for IE) in Safari:
Form Fields after (IE fix only targets IE) in Safari:
Form Fields before, in Firefox:
Form Fields after, in Firefox:
No.
Might break styles if they depended on form field heights being set to 24px for non-IE browsers.
https://github.com/grommet/grommet/blame/1243fc76d5e8ad8671dbe50bc0828c0754dc7470/src/scss/grommet-core/_objects.form-field.scss#L122
> Form Field Overflow Scrollbars Fix (Safari, Firefox)

- src/scss/grommet-core/_objects.layer.scss
Fix Layer overlay in Safari when zooming out.
When you zoom out in safari, `left: -100vw` doesn’t take the whole viewport width so the Layer overlay becomes visible.
Set `left` to use a percentage unit rather than `vw`.
Resolves #692. 
Tested in Chrome, Firefox, & Safari. 
Open the grommet docs page in Safari & zoom out (`cmd` + `-`).
#692.
> Fix Layer overlay in safari when zooming out

- src/js/utils/Drop.js
Currently when you click on the Menu on mobile view, the window will scroll to the top (see gif below).
This PR should fix that by positioning the content first, then prepending `drop.container`.
Fixes #690.
Tested on mobile view.
Go to the Menu component docs page, resize the browser to mobile view & open a menu example.
#690.
This is the current issue, drop down gets rendered at the top of the page, causing the page to scroll to the top.
> Fix Menu onClick scrolls to top on mobile

- src/js/components/Menu.js
Add `componentWillReceiveProps` lifecycle hook to update Menu component `inline` state when `this.props.inline` changes.
Resolves #645.
> Allow Menu inline state to be changed via props

- src/scss/grommet-core/_objects.form-field.scss
removing horizontal padding from range input in default and focus states so that slider does not shrink (and maintains correct width) on focus.
Tested by clicking/dragging range input slider in Chrome, Firefox, Safari, and IE11. Also tested by using keyboard to increase/decrease range value when form field in focus.
https://github.com/grommet/grommet/issues/241 (fixing style in addition to non-updating range input in IE11)
Chrome, before fix:
Chrome, after fix:
No.
No.
Backwards compatible (unless project depended on input range having `$form-horizontal-padding`.
> Fix range input getting squished on focus

- src/js/components/Search.js
Transfer additional props to input element.
Search.js component.
Transfer onKeyDown property.
```<Search onKeyDown={this.onKeyDown}/>```
Enable possibility to handle enter, up, down key events
No
No
Compatible
> Search transfer props to input #734

- src/img/icons/watch.svg
Adds Watch (video play) icon for grommet based project, and ContentCard component.
Used for anchor icon and thumbnail image overlay:
https://github.com/grommet/hpe-digitaltoolkit/pull/112
https://github.com/grommet/hpe-digitaltoolkit/issues/31
No.
> Add Watch (video play) icon

- src/js/components/Article.js
I noticed a bug in the Article's onProgress functionality which would throw an error after changing routes.
This fixes a bug which did not remove the scroll listener when the Article component unmounts.
Create a basic React Router app which features an Article component with and without progress update. When the user switches routes using React Router's Link from an Article with progress monitoring to one without an error will be logged. This error is now fixed.
> Remove Article's window scroll listener on componentWillUnmount.

- src/scss/grommet-core/_objects.form-field.scss
- left-aligns calendar, searchinput, and datetime inputs across browsers
- left-aligns select inputs for Firefox and IE11
Tested calendar and drop-down (select) inputs on grommet-docs in Chrome, Safari, Firefox, IE, and Android.
https://github.com/grommet/grommet/issues/142
_**IE11 drop-down before (not left-aligned):**_
_**IE11 drop-down after:**_
_**Firefox drop-down before:**_
_**Firefox drop-down after:**_
_**Calendar input before (Chrome):**_
_**Calendar input after (Chrome):**_
No.
No.
Non-breaking change (unless other projects have included css style tweaks to form fields previously).
> left-aligning calendar + drop-down inputs across browsers

- src/js/components/Card.js
- src/js/utils/CSSClassnames.js
- src/scss/grommet-core/_objects.card.scss
- src/scss/grommet-core/_objects.scss
Applies Card styles to Card components. Previously CSSClassnames, _objects.scss wasn't updated to include new Card component. Also prefixing styles with grommet namespace.
Yes. PR Pending: https://github.com/grommet/grommet-docs/pull/86
> Card Style Fixes

- src/js/components/Tabs.js
- test/components/Tabs-test.js
allows passing of `activeIndex === 0` to `Tabs` component.
Updated unit tests to test `componentWillRecieveProps` with truthy and falsey values passed to activeIndex
1. Mount Tabs component with multiple tabs
1. Programatically change `activeIndex` to 1.
1. Programatically change `activeindex` back to 0.
1. Tabs component should re-render with first tab being active
`activeIndex` prop is not currently documented.
> Allow 0 to be passed as activeIndex prop in Tabs component

- src/js/components/chart/Range.js
This PR addresses an issue with the `_onMouseUp` method in the range component.
The range component returns extraneous values if the user drags the mouse outside of its boundaries. The PR checks for this and sets the `mouseUpIndex` to either `0` or `count` depending on which side of the component the mouse exits. 
`./components/chart/Range.js` `_onMouseUp` method
Drag one end of the slider past the range component's boundary and witness the `active` prop's values. With this fix in place, active start/end values should not exceed the count or drop below zero. 
Dragging the range slider off of the chart returns a non-existent value outside of the range of the xAxis. 
No.
> Check that mouseUpIndex is within range boundaries

- src/js/components/SocialShare.js
allows colorIndex to be set for SocialShare icons
grommet-docs: tested setting colorIndex attribute on SocialShare component
https://github.com/grommet/grommet/issues/817
Before (colorIndex option not available for SocialShare):
After:
No.
No.
Backwards-compatible.
> allowing colorIndex to be set for SocialShare icons

- __tests__/components/Calendar-test.js
- __tests__/components/__snapshots__/Calendar-test.js.snap
Fixes a failing test case in the Calendar component.  If no value is specified, the Calendar uses the current date.  When comparing this date to the corresponding field in the snapshot, the unit test fails.  This PR sets the value for both the Calendar component and the Calendar snapshot.
Review both of the modified files.  Confirm the dates match.
After running gulp dist, all the unit tests pass.  The following message is displayed: `133 tests passed (133 total in 64 test suites, 138 snapshots, run time 42.875s)`
Clone Grommet, run npm install, run gulp dist.  Notice that all test cases pass.
See discussion is Slack.  Search for "Calendar test fails".
Failing unit tests.
No
Yes
Unsure
> Fixed a failing unit test in Calendar component

- src/js/components/Card.js
- src/scss/grommet-core/_objects.card.scss
Updates to Card component.
Remove summary prop.
Rename `details` -> `text` prop.
Allow `description` to be backwards compatible. 
Yes. grommet/grommet-docs#102
> Card updates - remove summary, rename details to text, backwards compatible

- src/js/components/AccordionPanel.js
- src/js/components/Collapsible.js
Remove default padding on Accordion panel headings. 
This will allow callers to pass `pad` prop to AccordionPanel.
Resolves grommet/hpe-digitaltoolkit#118.
Yes. grommet/grommet-docs#101
> Accordion padding

- src/js/components/Meter.js
Hi Grommet Team,
Javascript use IEEE754 to calculate float and int number. Sometimes it’s hard to use binary to express a float number very exactly. 
For example, input below expression in browser console:
0.1+(0.2+0.3);  // 0.6
(0.1+0.2)+0.3;  // 0.6000000000000001
4.54+5.03;  // 9.57
4.47 + 5.09;  // 9.559999999999999
Current Meter only support integer, I enhance it to support float number.
Change grommet/src/js/components/Meter.js
From:
value: function _seriesTotal(series) {
var total = 0;
series.some(function (item) {
total += item.value;
});
return total;
}
To:
value: function _seriesTotal(series) {
let values = [];
series.forEach(function(item) {
let decimalDigits;
try{
decimalDigits = item.value.toString().split(".")[1].length;
} catch(e) {
decimalDigits=0;
} …
> Enhance Meter to support float number

- src/js/components/Carousel.js
Fixed issue where Carousel component does not get rendered properly when it's being rendered on the server side first.
Server side Carousel component rendering.
No
No
> Fixed issue where Carousel component does not get rendered properly when it's being rendered on the server side first.

- src/js/components/SkipLinks.js
Allowing skip links to wrap (otherwise, in mobile, skip links will be visible under the content div).
Made sure skip links were not visible behind app content in smaller screen widths. Checked in Chrome, Firefox, Safari.
https://github.com/grommet/hpe-digitaltoolkit/issues/124
**Chrome (before):**
**Firefox/Safari (before):**
**Chrome (after):**
**Firefox/Safari (after):**
No.
No.
> Fix Skip Links Showing Behind Content (Mobile)

- package.json
**This PR should not be merged until the https://github.com/grommet/grommet-toolbox/pull/34 is merged and updated in Grommet.  The grommet-toolbox PR contains the gulp tasks which are executed during pre-commit.**
Adds pre-commit hook
Tested by manually updating grommet-toolbox and invoking `gulp pre-commit` hook
1. npm install
2. `gulp pre-commit`
#816 
Yes, the [CONTRIBUTING](https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md) guide should be updated to mention pre-commit hooks.
Yes
Signed-off-by: Bryan Jacquot <jacquot@hpe.com>
> Added guppy pre-comit hook

- src/scss/grommet-core/_objects.box.scss
- src/scss/grommet-core/_objects.card.scss
* ie11 overflow fixes for Card.
* fixing missing flex-basis: auto for IE11 (1/3 basis Box option)
Tested in IE11.
* https://github.com/grommet/hpe-digitaltoolkit/issues/122
* https://github.com/grommet/hpe-digitaltoolkit/issues/123
**Card content not wrapping in IE11:**
**Multiple Cards in Tiles not wrapping in IE11:**
**Card IE11 fix:**
**Cards in Tiles IE11 fix:**
No.
> IE11 fixes for Card + Box

- src/js/components/Animate.js
Fix Animate component children appearing immediately when added too quickly. 
If delay is undefined, default to 50ms. 
Tested in grommet-docs page on Chrome, Firefox, & Safari
grommet/hpe-digitaltoolkit#119
> Fix Animate component children appearing immediately

- src/js/components/Table.js
Fixes Table cell headers (data-th attribute) in older Firefox versions.
Manual testing in Firefox & Chrome.
Firefox added support for non-standard [innerText property](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText) only recently (v 45, March 2016). So, if relying on innerText only, cell header text ends up to be "undefined". (I happened to have a bit outdated Firefox install.)
Using textContent by default might [improve performance](http://perfectionkills.com/the-poor-misunderstood-innerText/#note-on-perf) significantly but it's not 100 % equivalent of innerText.
No.
Compatible.
> Fix Table cell headers in FF<45

- src/scss/grommet-core/_objects.columns.scss
Adds specific styling for medium version of Columns to fix potential responsive issue
No
No
> Add specific styling for medium version of Columns

- __tests__/components/Chart-test.js
- __tests__/components/__snapshots__/Chart-test.js.snap
- src/js/components/chart/Axis.js
- src/scss/grommet-core/_objects.chart.scss
This PR updates the Chart Axis component's styling.
The reviewer can clone the latest changes and review in the grommet-docs application.
The Axis has been tested with the chart examples as well as various combinations during development.
grommet-docs would be a great starting point. To control the tick alignment I've added the property `tickAlign` to the Axis component. This prop can be either `start` or `end`, this adjusts the tick mark alignment so the tick marks can remain flush to the chart regardless of their orientation to the chart. An axis which should sit horizontally on a chart would look like the following `<Axis vertical={true} ticks={true} tickAlign="end" count={5} />`
This is the approved styling which was decided upon during various Grommet based infographic projects. …
> Updated Chart Axis styling.

- src/js/components/Video.js
- src/js/components/video/Controls.js
- src/js/components/video/ProgressBar.js
- src/js/components/video/Time.js
- src/js/utils/FormatTime.js
- src/scss/grommet-core/_objects.button.scss
- src/scss/grommet-core/_objects.video.scss
Adds video timeline based on designs:
* https://hp.invisionapp.com/d/main#/projects/8585265
* https://hp.invisionapp.com/share/PR8KJIGA8
**_Video Component Updates_**:
* when timeline ticks are clicked, set video to selected time
* when timeline ticks are hovered, set labels to active color, and highlight progress bar track until tick mark
* transition between primary controls (bottom bar) and timeline labels when progress bar hovered
* adding separate styles (extra left padding for labels, positioning for ticks) for chapter times set at 0:00.
* changing colors from accent to inverse (white) for progress bar ticks in grommet theme (but keeping accent colors for hpe theme).
* fixing video icon colors:
* using opacity to set colors for play/pause/refresh icons in Video component (otherwise …
> Video Timeline + Icons

- __tests__/components/Form-test.js
- __tests__/components/Notification-test.js
- __tests__/components/__snapshots__/Form-test.js.snap
- __tests__/components/__snapshots__/Notification-test.js.snap
It adds a test for the Form and Notification components (More coming!).
__tests__/components/Form-test.js
__tests__/components/Notification-test.js
Ran gulp test before and after snapshot generation
gulp test, also the coveralls should increase
N/A
N/A
N/A
N/A
N/A
N/A
> Feat: add form test and snapshots

- __tests__/components/__snapshots__/Accordion-test.js.snap
- __tests__/components/__snapshots__/Anchor-test.js.snap
- __tests__/components/__snapshots__/Calendar-test.js.snap
- __tests__/components/__snapshots__/Carousel-test.js.snap
- __tests__/components/__snapshots__/DateTime-test.js.snap
- __tests__/components/__snapshots__/NumberInput-test.js.snap
- __tests__/components/__snapshots__/Search-test.js.snap
- __tests__/components/__snapshots__/SearchInput-test.js.snap
- __tests__/components/__snapshots__/SocialShare-test.js.snap
- __tests__/components/__snapshots__/Video-test.js.snap
- __tests__/components/icons/__snapshots__/Pulse-test.js.snap
- src/scss/grommet-core/_objects.form-field.scss
Fixing IE11 dark-background-context issue with select drop down items (text is white on white bg).
Also updating tests.
Tested in IE11.
Open grommet-docs in IE11, and check "All field types" Form docs page.
http://localhost:8002/docs/form/examples#2
Toggle dark background, and trigger select drop-down options. Options should be black (default) text on white bg.
https://github.com/grommet/grommet/issues/442
Before PR: 
After PR:
No.
Non-breaking change.
> IE11 select options: dark background context fix

- src/js/components/Accordion.js
Fix Accordion active state.
In `componentWillRecieveProps` we should be checking `props` rather than `state`, then we update `state` with the `newProps`.
Also clone `this.state.active` since `.splice` & `.push` mutates the original array.
CodePen with **issue**: http://codepen.io/mcwagner10/pen/gwLGXj
CodePen with **fix**: http://codepen.io/epilande/pen/zKNZxV
> Fix Accordion active state

- src/js/components/Search.js
This PR fixes a bug mentioned in issue #623. The intended functionality is that the value of the search input is highlighted when the input receives focus, this functionality was not working properly in Safari. Safari was preventing the highlight capability by listening to the mouse up events. This PR removes the mouse up events from the Search input.
> Fixes Search input select bug in Safari.

- src/scss/hpe/_objects.anchor-hpe.scss
- src/scss/hpe/index.scss
This PR references issue [#77](https://github.com/grommet/grommet-docs/issues/77) on grommet-docs. 
This PR brings the HPE themed Anchor inline with other Grommet themes. It specifically target primary Anchors along with Anchors with icons and styles them with the brand color. 
This has been tested within the docs.
This PR should be tested in the grommet-docs Anchor examples.
This PR references issue [#77](https://github.com/grommet/grommet-docs/issues/77) on grommet-docs. The HPE theme's primary Anchors along with Anchors with icons text color did not match the icon color.
The Menu component will still target the primary Anchors/Anchors with icons and add a different color on hover. To fix this we could craft a PR specifically targeting the Menu component. I felt these fixes should be …
> Updated HPE theme's Anchor styling.

- __tests__/components/__snapshots__/Card-test.js.snap
- src/js/components/Box.js
- src/js/components/Card.js
- src/scss/grommet-core/_objects.box.scss
- src/scss/grommet-core/_objects.card.scss
- src/scss/grommet-core/_objects.paragraph.scss
* Only apply paragraph large-width (720px) for desktop sizes so that width doesn't remain large/overflow in mobile.
* Allow Card content in Tiles to expand full height of row.
* Allow Box with max-width size option to shrink in width instead of being stuck at max-width size.
* Also allow horizontal separators in responsive row Boxes to switch to vertical separators when switching to column direction
* Removing default white bg in Card component so that Cards are transparent instead of white when no colorIndex is passed.
Tested in Chrome, Firefox, and Safari in grommet-docs and hpe-digitaltoolkit.
**separator="right" option in desktop:**
**separator="right" option in mobile (before PR):**
**separator="right" option in mobile (after PR):**
Breaks Card bg default (changes default white bg to …
> Style Tweaks: Paragraph Width, Card (in Tiles & Default BG Color, Box (Max-Width & Separators)

- __tests__/components/__snapshots__/Anchor-test.js.snap
- src/js/components/Anchor.js
Fixes `undefined-icon` on Anchor component & set title to be more meaningful.
With a screen reader focus on the arrow icon.
grommet/hpe-digitaltoolkit#127
Current issue:
> Fix Anchor icon accessibility

- src/js/components/NumberInput.js
Fix NumberInput component to handle floats in IE.
Tested in IE11.
Set `step={0.1}` to `NumberInput` component.
https://github.com/grommet/grommet/issues/868
**Current issue on IE11:**
**With fix on IE11:**
> Fix NumberInput component to handle floats in IE

- src/js/components/Card.js
- src/scss/grommet-core/_objects.accordion-panel.scss
- src/scss/grommet-core/_objects.card.scss
* makes copy truncation for Card optional (`truncateCopy` option, defaults to `false`).
* allow Accordion Panel to expand full container width (currently `.grommet li` max-width gets applied).
Tested against hpe-digitaltoolkit repo in Chrome, Firefox, and Safari.
Copy truncation was previously desired for Card, but after Stack (which was used by Marquee/Section (toolkit components) was merged with Card, the copy truncation behavior was still applied.
https://github.com/grommet/hpe-digitaltoolkit/issues/137
Yes, update Card examples with truncateCopy option.
Breaking change for previously truncated `<p>` copy in Cards.
> Card: make copy truncation optional

- __tests__/components/Button-test.js
- __tests__/components/__snapshots__/Button-test.js.snap
- __tests__/components/__snapshots__/Carousel-test.js.snap
- __tests__/components/__snapshots__/DateTime-test.js.snap
- __tests__/components/__snapshots__/NumberInput-test.js.snap
- __tests__/components/__snapshots__/Search-test.js.snap
- __tests__/components/__snapshots__/SearchInput-test.js.snap
- __tests__/components/__snapshots__/Select-test.js.snap
- __tests__/components/__snapshots__/Tabs-test.js.snap
- __tests__/components/__snapshots__/Video-test.js.snap
- src/js/components/Button.js
- src/js/components/LoginForm.js
This PR references issue #85 regarding transferring microdata properties to components. 
Destructures `this.props` on the button component to allow for additional properties to be rendered. Additionally, I've removed the `strong` property on the login form button as this is not a valid Prop type. 
I've written additional tests to support this functionality and tested within grommet-docs.
Updating other components snapshots was necessary to pass tests - specifically aria properties. 
This is backward compatible.
> Transfer Button component props.

- __tests__/components/App-test.js
- __tests__/components/__snapshots__/App-test.js.snap
- src/js/components/App.js
This PR references issue #85 regarding microdata properties. 
This PR adds microdata functionality to the App component. Additionally, I've adjusted the CSS class order to remain consistent with other components.
I've added a test specifically for microdata properties. 
Issue #85.
This change is backward compatible.
> Transfer App component props

- src/js/components/Notification.js
cleaning warnings from the Notification component.
In grommet 0.6.12; warning messages for meter was added in case of using deprecated meter props.
Grommet is internally using meter within the Notification banner, so it threw warnings. In this PR the warning were fixed
Removing deprecated props from the Notification meter in order to remove the warning from console log 
Integrating with our Hellfire application and making sure the warnings are gone.
run the notification component to see the progress bar running, and make sure the console logs doesn't show warnings.
In grommet 0.6.12; warning messages for meter was added, in case of using deprecated props.
Grommet is internally using meter within the Notification banner
The Notification component throws warnings
No
No 
Yes
> fix/cleaning warnings from Notification component

- src/js/components/Section.js
Transfer Section component props to underlying DOM element.
Tested on grommet docs page.
#85 
> Transfer Section component props

- __tests__/components/__snapshots__/Markdown-test.js.snap
- __tests__/components/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButton.js
Transfer RadioButton component props to underlying DOM element.
Tested on grommet docs page.
#85
> Transfer RadioButton component props

- src/js/components/Tabs.js
Enables an onActive property to be set for Tabs.  This allows developers to catch Tab change events, which is essential for maintaining the activeIndex variable.  Currently, Tabs always reset to the starting activeIndex when setState is called (0 if not specified).
Provides ability to detect Tab changes.
Review Tabs.js file.
Tested the callback on a project using multiple tabs.  Was able to maintain the the activeIndex variable (Tabs no longer unexpectedly resets when a render occurs).
Make a page that uses Tabs and Tab components.  Make a variable for activeIndex and pass it to Tabs.  Make a callback that updates activeIndex to the appropriate value.  Finally, call setState somewhere unrelated to Tabs.  Notice the Tabs component no longer unexpectedly changes tabs.
Currently, there's no …
> Added a way to detect tab changes

- __tests__/components/Columns-test.js
- __tests__/components/__snapshots__/Columns-test.js.snap
- src/js/components/Columns.js
This PR references issue #85 regarding microdata properties. Columns should now properly pass properties to the rendered DOM element. This PR also adds tests for microdata properties and custom class names.
> Transfer Columns component props.

- __tests__/components/Footer-test.js
- __tests__/components/__snapshots__/Footer-test.js.snap
- src/js/components/Footer.js
This PR references issue #85 regarding microdata properties and brings the Footer component in line with Grommet's consistent component structure. This PR also adds tests for microdata properties and custom class names.
> Updated Footer to transfer component props.

- src/js/components/chart/Graph.js
Resolves issue where graph components break if the array passed to the `values` prop contains values that are all the same. This is due to the scale calculation returning `Infinity`.
To see what this fixes, make a `<Bar />` graph and pass it an array with multiple values that are all the same. Example: `[0, 0, 0, 0]` or  `[5, 5, 5, 5]`. Be sure that the max and min props are set as well. 
When the chart receives `values={[0, 0, 0, 0]}` 
No.
> NaN Chart Issue

- __tests__/components/SocialShare-test.js
- __tests__/components/__snapshots__/SocialShare-test.js.snap
- src/js/components/SocialShare.js
Transfer **`SocialShare`** component props to underlying DOM element & add test.
Tested on grommet docs page.
#85 
> Transfer SocialShare component props

- __tests__/components/icons/Spinning-test.js
- __tests__/components/icons/__snapshots__/Spinning-test.js.snap
- src/js/components/icons/Spinning.js
Transfer **`Spinning`** component props to underlying DOM element, use classnames, add test, & propType validation.
Tested on grommet docs page.
#85 
> Transfer Spinning component props

- src/js/components/Toast.js
Enable removing of a toast from outside to display a different toast without waiting 9 seconds
Manual
Neither can the timeouts for display and animation be controlled nor is there any queue-mechanism if there are 2 toasts to be shown within 10 seconds (display + animation)
setState is called on an unmounted element if the toast was unmounted from outside
No
No
> Clear timeout if Toast was umounted from outside

- __tests__/components/FormField-test.js
- __tests__/components/__snapshots__/FormField-test.js.snap
- src/js/components/FormField.js
This PR references issue #85 regarding microdata properties and brings the FormField component in line with Grommet's consistent component structure. This PR also adds tests for microdata properties and custom class names.
> Updated FormField to transfer component props.

- __tests__/components/Form-test.js
- __tests__/components/__snapshots__/Form-test.js.snap
- __tests__/components/__snapshots__/LoginForm-test.js.snap
- src/js/components/Form.js
This PR references issue #85 regarding microdata properties and brings the Form component in line with Grommet's consistent component structure. This PR also adds tests for microdata properties and custom class names.
> Updated Form to transfer component props.

- src/js/components/Markdown.js
The argument syntax changed a bit in 4.x. GFM is always enabled, so no need to pass that explicitly.
> Fix arguments being passed to markdown-to-jsx

- src/js/components/Image.js
- src/scss/grommet-core/_objects.image.scss
Allows user to specify `object-fit` CSS property on Image components.
Landscape images are constrained to a 48x48px container when `size="thumb"`. This allows to set both `size="thumb"` and `fit="contain" so that the entire image is scaled to fit within the 48x48px container, instead of the left and right of the image being cut off.
Thumbnail default:
Thumbnail with `fit="contain"`
The new prop should be added to documentation.
> add 'fit' propType to Image component

- .eslintrc
updates .eslintrc to use `react/jsx-wrap-multilines` instead of `react/wrap-multilines` which was depricated in `eslint-plugin-react` v6.0.0. Currently there's a console warning when running `gulp jslint`.
https://github.com/yannickcr/eslint-plugin-react/releases/tag/v6.0.0
> rule wrap-multilines renamed to jsx-wrap-multilines in v6.0.0

- src/scss/grommet-core/_objects.select.scss
Resolves #903. Remove tiny scrollbar within Select component in IE. 
Tested on Chrome, Firefox, Safari, & IE. 
#903 
> Fix Select scrollbar in Edge & IE

- __tests__/components/Legend-test.js
- __tests__/components/__snapshots__/Markdown-test.js.snap
- src/js/components/Legend.js
Fixes the total on legends, which is currently always equal to 0.
Read src/js/components/Legend.js
Manually tested on my own project and added unit testing.
Make a Legend component with total turned on.
Up to you I guess.
> Fix broken total in Legend component.

- src/js/utils/DOM.js
`match` can be null, causing an error “Cannot read property 'slice' of null”
> DOM: Check if `match` exists before slicing

- __tests__/components/__snapshots__/Chart-test.js.snap
- src/js/components/chart/Axis.js
- src/scss/grommet-core/_objects.chart.scss
This PR fixes a bug in the chart Axis component which prevented it from hiding the tick marks in a horizontal layout. The issue can be viewed in this [codepen](http://codepen.io/karatechops/pen/vXEPRA?editors=0010).
> Fixed horizontal Axis tick display.

- src/js/components/Menu.js
Remove `dropColorIndex` from spread props in Menu component.
> Menu: Remove `dropColorIndex` from spread props

- src/js/components/Search.js
`_onMouseUp` is accessing `this.props` without binding in the constructor, causing `this.props` to be null.
> Search: Fix onMouseUp `props` undefined

- src/js/utils/Selection.js
Allow user to deselect selected Tile, Table, List items. 
Shift-click on a selected item, will deselect the item.
https://github.com/grommet/grommet-docs/issues/134
https://github.com/grommet/grommet-docs/issues/150
https://github.com/grommet/grommet-docs/issues/156
> Selection: Multi-select shift click to deselect

- src/js/messages/en-US.js
Fixes react-intl warning for missing "List" message in Grommet 1.0.0.
> add List default message to en-US

- src/scss/grommet-core/_objects.pulse.scss
Resolves https://github.com/grommet/grommet-docs/issues/145. 
Smooth out scale animation on hover.
We're using `rotate` to trick the browser into rendering the image better.
https://github.com/grommet/grommet-docs/issues/145
> Pulse: smooth out scale animation

- __tests__/components/icons/Pulse-test.js
- __tests__/components/icons/__snapshots__/Pulse-test.js.snap
- src/js/components/icons/Pulse.js
Pulse component will now transfer properties to the DOM. This PR brings the Pulse component in line with Grommet's consistent component structure #801 .
> Updated Pulse component to transfer props.

- src/scss/hpinc/_hpinc.defaults.scss
This PR removes the HPI theme stroke width styling to allow Grommet icons to display properly.
> Updated HPI theme's icon stroke width.

- src/js/components/Menu.js
Fix menu inline state in componentWillReceiveProps.
`nextProps.inline` can be falsey, making the `||` operator go to the next expression.
Also fix labelled menu.
Tested on Header & Menu docs page.
https://grommet.github.io/docs/header/examples#3 https://grommet.github.io/docs/menu/examples/#4
Fixes https://github.com/grommet/grommet-docs/issues/130
Should be collapsed as `Label`.
Should have default icon (`...`)
> Menu: Fix menu inline state in componentWillReceiveProps

- src/scss/grommet-core/_objects.menu.scss
Removes height of anchor icons within drop menu, thus resolving a display issue with vertical alignment (see screenshot / codepen below)
Here's a codpen to demonstrate the issue: http://codepen.io/nickjvm/pen/gwzjYz?editors=0110
> remove height of anchor icons within drop menu

- src/scss/grommet-core/_objects.layer.scss
- src/scss/grommet-core/_objects.tile.scss
Remove scroll from `Tiles`. Fixes https://github.com/grommet/grommet-docs/issues/124
`overflow: auto` was added to `.grommetux-tiles` to fix infinite scroll in `Layer` component.
https://github.com/grommet/grommet/pull/866#pullrequestreview-861943
https://github.com/grommet/grommet-docs/issues/124
> Tile: Remove scroll from Tiles

- __tests__/components/LoginForm-test.js
- src/js/components/LoginForm.js
Adds an optional create account button to the LoginForm. Also adds a small convenience property to LoginForm for onFieldChange events.
Smallish change, so I would just review the code and make sure existing login pages don't break.
Tested manually using our own login page with and without create account buttons and with and without the field change function.
Check that login pages still work as expected and then add an empty create account function and see that it still works.
We are currently running in production with a modified LoginForm component manually checked into our repo. We would love for this to get in because we need the ability to have our users create an account.
Yes.
Probably?
Fully backwards compatible.
… LoginForm.
> Adds onChange prop to the LoginForm

- src/scss/grommet-core/_objects.menu.scss
Fixes #975 - Caret positioning in menu.
Don’t wrap caret icon in Menu component.
Tested on CodePen below & grommet docs.
http://codepen.io/mcwagner10/pen/vXmAEE?editors=1010
https://github.com/grommet/grommet/issues/975
Issue:
Fixed:
Nope.
> Menu: Fix caret icon wrapping

- src/js/messages/icons/en-US.js
Adding missing reference to troubleshoot icon
Adding troubleshoot string to icons en-US file to eliminate warning on console:
the committed file
Using the troubleshoot icon and seeing the warning isn't there
use the icon and see the warning disappear
We don't want console warning :)
No
No
Yes (backwards compatible)
> Cleaning intl warning

- src/scss/grommet-core/_objects.box.scss
Fixes an animation issue when `Box` (or related components such as `Card`) appears within an `Accordion`.  If the `Card` contains a video, the video placeholder image only animates in Chrome (see gifs below).
Issue was seen on Firefox and Edge.
Tested on the following:
* Firefox 49 on OSX
* Edge on Windows 10
* Chrome 54 on OSX
Codepen: http://codepen.io/franksvalli/pen/kkqkOm?editors=0010
You can manually add `max-height: 100%` to `.grommetux-box--size` to test it out.
grommet/hpe-digitaltoolkit#158
Also related to grommet/hpe-digitaltoolkit#161
Before:
After:
No
> Box: fix animation when within Accordion

- src/js/components/TextInput.js
Changes `suggestions` prop validation on `TextInput` component to accept array of objects (`value` and `label` are required) as well as array of strings. This mirrors deprecated `SearchInput` props.
> add shape as possible proptype for TextInput suggestion array

- src/js/components/Tip.js
Removes `this._drop.remove()` call outside of the check for `target` element. This way, even if the target doesn't exist, the tip can still be removed.
Manual UI testing
Test against a component similar to https://codepen.io/nickjvm/pen/KgYXkb?&editors=0010
Issue #1012
> move _drop.remove() outside of target check

- __tests__/components/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput.js
Fixes the `placeHolder` prop functionality on the `<TextInput>` component.
Tested in Chrome OSX only (since this isn't a browser bug).
Can be tested by opening `TextInputDoc.js` in `grommet-docs` and adding this to the `TextInput` in the `Examples` section:
```html
<TextInput
...
placeHolder="Some placeholder text!"
...
/>
```
http://codepen.io/franksvalli/pen/bwOzqJ?editors=0010
#987 
Before:
After:
No
> Fix TextInput placeHolder (fixes #987)

- src/js/components/Notification.js
Deletes `size` prop before passing props to Box child of Notification.
src/components/Notification.js
Manual UI testing
```
<Notification size="small" message="a notification" status="ok" />
```
And see that the width of the notification is not effected, but the size of the text and icon are still influenced by the `size` prop.
Discussed with @alansouzati that this prop shouldn't be passed to `Box` since `size` means something different to Box. 
N/A
Codepen of issue: http://codepen.io/nickjvm/pen/zKyGrP
No
> prevent sending size to Notification's Box

- src/js/components/Tiles.js
While working on a site which uses Grommet I noticed when changing routes Tiles.js would throw an error `Uncaught TypeError: Cannot read property 'scrollWidth' of null`. I also noticed quite slow performance on a site using 2 carousels, I believe this to be due to an endless loop which `Tiles.js` was stuck in. 
This PR introduces a shallow compare in Tiles' `_layout` method which judges whether to set state. The shallow compare will only happen on Tiles set to `direction=row`.
Tested in grommet-docs.
Test in grommet-docs - specifically in [Tiles example #4](https://grommet.github.io/docs/tiles/examples#4), navigate to either another route via an anchor or navigate to the next example via the arrow button. Errors will be thrown in the console. The bug is also visible in the Carousel …
> Fixed Tiles row endless loop.

- src/scss/grommet-core/_base.input.scss
Prevents `select` input from resizing on focus do to inherited `input` padding styles.
Manual UI review
Create a `select` and see that the width remains the same when the element is focused
Grommet-index `Sort` component uses a  `select` input, which is how this issue was discovered. This issue is not present when the `select` is wrapped in a `FormField` container.
codepen of the issue: https://codepen.io/nickjvm/pen/JbYMwj?&editors=0010
> override inherited styles on select:focus padding-right

- src/js/utils/Drop.js
In IE11: If there's a Select component that's towards the middle or bottom of the page, then if the user clicks the dropdown, the Drop is not aligned with the Select.
Example, open this in **IE11 or Firefox**: http://codepen.io/mcwagner10/pen/EgdaNg?editors=1010
Resolving this issue: https://github.com/grommet/grommet/issues/1043
See Drop.js.
Tested on:
Win10: IE11, Edge, Firefox, Chrome
Mac: Safari
Latest iOS
Galaxy S7
Open Firefox or IE, make a dropdown that's lower down on the page.  Open the dropdown, scroll up and down, then notice the dropdown stays in the correct spot.
Issue was discovered when a Select component is further down on the page.  Bug is only a problem in IE11 and Firefox because both those browsers use document.documentElement.scrollTop and not document.body.scrollTop …
> fixing dropdown component's position in IE11 and Firefox.

- src/js/components/Tip.js
Occasionally, when the "remove" method is called on Tip's drop, there's an error if the drop is null.  The current implementation of Tip uses a 1ms timeout (Tip.js line 50) to set up the drop.  This causes a race condition because it's conceivable that `componentWillUnmount` gets called **before** the timeout fires.  If this permutation of events happens, then the drop never gets initialized and the "remove" method will be called on null thus causing the error.  The possibility of this happening increases because Javascript setTimeout isn't a real-time system i.e. the timeout may not occur precisely after 1ms.
(see discussion about setTimeout's bad accuracy:
http://stackoverflow.com/questions/21097421/what-is-the-reason-javascript-settimeout-is-so-inaccurate)
A suggested fix in Grommet's …
> Tip's drop isn't removed properly (race condition)

- src/scss/vanilla/_vanilla.defaults.scss
This PR adds an additional color to Grommet's neutral color set. This additional color supports the latest designs for the upcoming docs templates.
> Add neutral color to Vanilla theme.

- src/js/components/Anchor.js
- src/js/components/Button.js
Currently, `Anchor` and `Button` components that use both `path` and `onClick` are provided no arguments to the `onClick` handler. This affects some use cases, such as calling `stopPropagation()` on the click event to stop it bubbling to parent elements.
I looked for an existing test for the `path` attribute functionality of `Anchor` to copy or modify, but I couldn't find one.
I have tried this patch in a real use-case where this is happening, and it works for me.
Create a Grommet project with `react-router`, and try something like this:
```js
export default function ExampleAnchorBox () {
function clickBox () {
console.log('Box clicked.')
}
function stopPropagation (event) {
event.stopPropagation()
}
return <Box onClick={clickBox}>
<Anchor path='/path/to/somewhere' …
```
> Anchor and Button components should pass arguments to onClick when using path.

- src/scss/grommet-core/_objects.layer.scss
Fixes an issue where a `<Box>` that has `full` set to `true` or `horizontal` will overflow a `<Layer align="center">`. [Example CodePen](http://codepen.io/jonathonwalz/pen/BporVd), should have a padded red box on both sides, not just the left.
Manually tested on the project where the issue was noticed. Tested with various different browser widths from 320px to 2048px.
No
Maybe? Not sure what the conventions are
Yes, just a minor css change
> Fix full horizontal boxes overflowing centered layers

- src/js/components/TextInput.js
fix 'focus jump between components when switch between multiple textinput component, and focus outside of browser and then back focus on textinput' issue
Previous version works incorrectly in below code:
`class TestComponent extends Component {
constructor(props) {
super(props);
this.state = {
ldap_root_group_filter: '',
ldap_group_base_filter: '',
ldap_default_group: '',
}
}
handleRootGroupFilterChange = (event) => {
this.setState({
ldap_root_group_filter: event.target.value
})
}
handleGroupBaseFilterChange = (event) => {
this.setState({
ldap_group_base_filter: event.target.value
})
}
handleDefaultGroupChange = (event) => {
this.setState({
ldap_default_group: event.target.value
})
}
render() {
return (
<div>
<TextInput key={1} id="ldap_root_group_filter" name="ldap_root_group_filter" …
> fix 'focus jump between components when switch between multiple textinput

- src/js/components/Article.js
Remove an `if` statement that is always true.
Search for `ignoreScroll` in the whole file.
None.
Scroll on a mobile device.
Nope. I just was trying to track the root a real issue.
#1147 
None.
No.
No.
Yes, no.
> Remove dead conditional branch

- __tests__/components/icons/Spinning-test.js
- __tests__/components/icons/__snapshots__/Spinning-test.js.snap
- src/js/components/icons/Spinning.js
- src/scss/grommet-core/_objects.icon.scss
Signed-off-by: Cullan Springstead <cullan.springstead@gmail.com>
It adds a size property to Spinning that works the same as the other icons.
Classes for the sizes were added to_objects.icon.scss. They were copied from the control-icon classes. The classes are added to the component in Spinning.js.
I compared the behavior to the base icons and examined the test snapshots.
Add Spinning icons with various sizes to a page.
Yes. The size property information from Icon needs to be copied to the Spinner page.
Yes.
It is backwards compatible because it keeps the old small property by setting the size to small when small={true}.
> add a size property to Spinning

- src/js/components/Legend.js
Signed-off-by: Mike Turley <mturley@hpe.com>
It adds a `responsive` property to the Legend component, which is passed down to its ListItem children.  This allows an instance of Legend to be created with responsive={false}, in which the values will remain to the right of the series names rather than wrapping to the next line on mobile views.  This is useful if a Legend is placed somewhere where it will always have plenty of horizontal space, such as full-width below some visualization.
Look at changes to the Legend component, they are fairly straightforward.  The `delete props.responsive` in the render method is to prevent the property from being placed on the List itself, which makes React complain about an unknown property.
Pre-commit tests were run, and I verified that leaving the …
> Add a responsive property to Legend, passed down to its ListItems

- src/js/components/TextInput.js
Fixes a bug when `autoFocus` is set on `TextInput`.  In that case, the onFocus event hander immediatly, before the componentRef is set, causing a failure when `_onFocus` calls `this.componentRef.select();`
Eh, pretty simple - look at the diff I guess.
I've tested it on my application and confirmed it works.  I attempted to write a spec, but `react-test-renderer` doesn't seem to actually focus elements, probably because it's not using a real DOM.
FYI this was the spec:
```javascript
it('can be rendered with autoFocus=true', () => {
const onFocusSpy = jest.fn();
const component = renderer.create(
<TextInput id="item1" name="item-1" autoFocus value="one" onFocus={onFocusSpy} />
);
expect(onFocusSpy).toHaveBeenCalled();
});
```
Set `autoFocus` on a `TextInput` and render it
Here's a stack …
> Fix JS exception with TextInput that has `autoFocus` property set

- __tests__/components/Legend-test.js
- __tests__/components/__snapshots__/Legend-test.js.snap
- src/js/components/Legend.js
Fix occasional floating point errors in Legend component.
Look in Legend.js
Manual testing and an unit test included.
They can use this codepen as an example of what was broken before: http://codepen.io/coltonw/pen/PWaENd
Fixes have been attempted on this problem in the past by using arithmetic to work around floating point errors, but it turns out this is extremely hard to actually do.  The "real" solution would probably be to use a real decimal library such as [this one](https://github.com/MikeMcl/bignumber.js/) but doing toFixed (which is what this change uses) will definitely work and requires no extra dependencies.
#1174 
Nope.
Up to you!
> Fix occasional floating point errors in Legend component.

- src/js/components/DateTimeDrop.js
Always show 6 weeks of days in the calendar dropdown to keep date change controls from jumping around (Issue #786).
DateTimeDrop.js
Created a test page in my sample app and wired in the DateTime component to verify that it is working correctly.
- Browse to a test page with the DateTime component wired into it. 
- Click on the icon to cause the calendar dropdown to  be displayed. 
- Use the change controls at the top of the page to change the months. Notice that there are always 6 weeks shown, and these controls no longer jump around.
- Use the odometer controls at the bottom of the calendar to change months and years. They no longer jump around either.
None
1. It's hard to tell the difference between days in the selected month and those that aren't in the month. The styling for the …
> Fix DateTime component usability issue (#786)

- src/js/components/Anchor.js
This PR fixes an Anchor bug. In our app we have a few Anchors which have dynamic paths, these Anchors render and then pass in a path after the async request has been completed. The initial render of the Anchor component is the only spot which checks for a `path` being passed in via props. I've extended the Anchor component to support checking for a `path` in `componentWillReceiveProps`.
Cloning branch and testing in docs.
Docs and our upcoming app.
> Fix Anchor unmount listen bug.

- src/scss/grommet-core/_objects.check-box.scss
- src/scss/grommet-core/_objects.radio-button.scss
Labels with long names/ email address/ layout which has checkbox/ radio buttons get cut off on smaller screen.  
For issue : https://github.com/grommet/grommet/issues/1205
This would create a word wrap of long labels/ email addresses so that the text does not get out of the screen.
2 simple changes on the scss file. 
A manual testing on long text without spaces and layout (a checkbox and a small icon next to it) which was getting cut before change, now wraps and shows correctly.
Having  a long text or layout which is "responsive: false" lay side by side for all checkboxes and radio buttons
Code pen url : http://codepen.io/kanhajeevan/pen/vgwzzz
Do the grommet …
> Word-wrapping long names/email-address without space for checkbox and radio buttons #1205

- src/scss/grommet-core/_settings.color.scss
Applies the !default flag to core colors missing said flag so that they can be overridden.
In /src/scss/grommet-core/_settings.color.scss
I've made the changes on my application and the colors I define now override the defaults.
Override some of the defined colors, as described here - [overriding style](https://github.com/grommet/grommet/issues/704#issuecomment-233392152)
Issue #704 
No
Possibly, if only to notify users that all colors in grommet-core _settings.color.scss can be overridden.
> Update all core colors to have the !default flag (issue #704).

- src/js/components/Carousel.js
This fixes https://github.com/grommet/grommet/issues/1187 
Using same names than in [Tabs](https://grommet.github.io/docs/tabs)
Adds **activeIndex** so the dev can set by code which will be the active child in the Carousel.
Adds **onActive** so the user can be notified when user swaps or chooses another child in Carousel or when this event is fired automatically by Carousel using *autoplay={true}*. 
State has been modified on constructor to get the value from props if there is one:
`activeIndex: props.activeIndex || 0,`
Just manual test with both Carousel and Tabs.
`<Carousel autoplay={true} persistentNav={false} activeIndex={this.state.activeIndex}  onActive={index => {console.log(index); this.setState({activeIndex:index})}} >`
`<Tabs activeIndex={this.state.activeIndex} …
> Added activeIndex prop and onActive event to Carousel

- src/js/components/TextInput.js
[Note: the other approach would be to alter the function _typeof to handle nulls]
null type is object, so need to check for it
handles possibility of null property for value or suggestion
at reviewer's discretion
repro steps in case #1262 and codepen
repro steps in case #1262 and codepen
a dynamic prop can sometimes have an unexpected value such as null
the unexpected unmount caused by this error can cause other issues. See commentary in https://github.com/grommet/grommet/pull/1230
no
as you wish
> merge of #1262 TextInput null handling

- src/js/components/Search.js
Signed-off-by: Raphael Gruber <raphi011@gmail.com>
Search's onSelect callback gets called when dropdown is not active and enter is pressed.
Search Component `_onInputKeyDown` method.
Tried it out in a test project.
Create a Search component and press enter when dropdown is not active
I need this feature :)
#1259 
No
Yes
Well it's in the docs but is hasn't worked until now so it MAY be a breaking change for some people who implemented this outside of grommet.
> adds Search onSelect callback when dropdown is not active

- src/js/components/Search.js
Signed-off-by: Raphael Gruber <raphi011@gmail.com>
Fixes bug #1272 
Search components onEnter method
Test project
Using this gist https://gist.github.com/raphi011/31444b68cd7224f63e18306c9d69c11f
Is an annoying bug in my project. Not entirely sure why this was a problem, my guess is that setState() is called twice in onEnter, but somehow it works if you call onRemoveDrop at the end of the method.
#1272
no
If you want
> fixes Search dropdown not closing after react-router push

- src/js/components/Button.js
Signed-off-by: Raphael Gruber <raphi011@gmail.com>
enable button if type = 'submit ' or 'reset'
Button Component
Own test project
Button with test='submit' or 'reset', checked if its enabled
#1266
yes
Probably
Breaking change
> enables reset/submit button

- src/js/components/Button.js
Signed-off-by: Zack Sinclair <zacksinclair@gmail.com>
Makes Button compatible with React Router 4 w/ the same implementation as Anchor. 
All tests pass. Locally tested that this works for both RR3 and RR4.
Use Button with a path defined. Test that react router 3 / 4 both transition to the path
@alansouzati made this nice and easy via his Anchor RR4 commit:
https://github.com/grommet/grommet/commit/74ee5fe625e7777d30d6c49098b72863a4dfd1a6
You'll notice this was mostly a cut and paste job.
#1274 
No
Yes, in combination with 74ee5fe625e7777d30d6c49098b72863a4dfd1a6, release notes should state that grommet now supports react router 4 in both Anchor and Button components.
Yes backwards compatible
> Makes Button compatible with react router 4; closes #1274

- src/js/components/Button.js
- src/scss/grommet-core/_objects.button.scss
Sometimes we need some hover capabilities when using plain Buttons
Adds hover support to `plain` Button
Button.js
Manual testing
Reading the changed files
Yes
Yes
Backwars compatible
> Added hover support for button

- __tests__/components/TextInput-test.js
- __tests__/components/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput.js
Moves the `autoComplete` property on `input` to before passed in props are set.
This way parent components can set `autoComplete="on"` and override the default of `off`.  
Sometimes when users are setting an address or other personal information it's a good idea to allow the browser auto-complete to function.
I wouldn't think so
Is backwards compatible
> Allow overriding TextInput's autoComplete property

- src/js/components/Menu.js
Use the provided icon even when a label is provided for the `<Menu />` component. This is useful for very specific menues, e.g. a "Settings" menu with a settings cog instead of a dropdown caret.
- Changes the way a label in combination with an icon behaves in the `<Menu />` component
- The effects are easily verified in the `<Menu />` examples of grommet-docs. Look there and compare to master and you will see that you're now able to have a custom icon for your labeled `<Menu />`
- I wanted to create some unit tests for `_renderButtonProps` but didn't fully understand how the test framework worked so only light manual testing has been done. LGTM :slightly_smiling_face: 
- That we weren't able to have a custom icon when we used it in combination with a label.
- No there was nothing in the …
> feat: allow custom icon with label in <Menu /> component

- src/scss/grommet-core/_objects.form-field.scss
This way they'll have the same height as other form elements.  
I'm hoping this is a simple change, but there may be more involved than I'm aware of.   Git blame says the `double` was introduced by commit https://github.com/grommet/grommet/commit/c1b7afd01e5405496c86a4da41102f9e4ecf510c to fix https://github.com/grommet/grommet/issues/143 
I'm working to fix a layout bug where a form looked like so:
After setting the margin top/bottom to 6px instead of 12, the elements have the same height:
> Remove doubled margin on top/bottom of checkbox/radio inside of form-field

- src/js/components/Select.js
Currently, a &lt;Select&gt; used as a form input will submit the label of the selected option, instead of its value. This fix will make it submit the value, following HTML semantics.
Fixes an issue with &lt;Select&gt; components, when used as a form input. Currently, the form will have the value of the select option's label. Instead it should use the selected option's `value`.
http://codepen.io/aandr/pen/jmOGYy
Tested locally.
Check out branch, try CodePen example: http://codepen.io/aandr/pen/jmOGYy 
https://github.com/grommet/grommet/issues/1305
No.
No.
Yes. If somebody relied on a <Select> to submit it's option label instead of option value, this will now change.
> Fix <Select> form input value

- src/js/components/Anchor.js
Fixes passing of wrong history object to Anchor
Uses version agnostic passing of react-router history object to Anchors attachUnlisten method
Anchor Component
Test project
Change an Anchors path
-
no
> fixes Anchors attachUnlisten react-router-v4 bug

- src/js/components/DateTimeDrop.js
Signed-off-by: Suhair Zain <suhairzain11@gmail.com>
Fixes #1285 which displays the meridian as only am / pm instead of the expected AM / PM, according to the linked moment.js docs
Check line 33 and 34 in DateTimeDrop.js
Manual testing as well as run the automated tests using `npm run test`.
Render a DateTime component with format `'M/D/YYYY h:mm A'`
#1285 
No
No
> Fix for #1285 DateTimeDrop format issue

- src/js/components/Anchor.js
Fixes the "Warning: [react-router] `isActive(pathname, query, indexOnly) is deprecated; use `isActive(location, indexOnly)` with a location descriptor instead. http://tiny.cc/router-isActivedeprecated"
src/js/components/Anchor.js
Ran automated tests on commit
Render an Anchor element and check the console for any warnings
Then use the browser's inspector to check if the rendered <a/> tag has the grommetux-anchor--active class set to it if it's the active path.
https://github.com/ReactTraining/react-router/blob/v2.8.1/upgrade-guides/v2.0.0.md/
No
No
> Fix for React Router isActive deprecated warning

- src/js/components/Split.js
Signed-off-by: Zack Sinclair <zacksinclair@gmail.com>
When on the exact small breakpoint (719px width for me), split prioritizes incorrectly because it compares smallSize with < instead of <=
< -> <=
Locally confirmed
Before:  have a split component that toggles priority between left and right based on smallSize. Go to 719px width, see that it is prioritized incorrectly
After: 719px correctly prioritizes
No
No
> Fix Split's priority when precisely on breakpoint

- src/js/components/Button.js
- src/scss/grommet-core/_objects.button.scss
The idea of this PR is to add `box` prop to Button.
Button component
Manual
Add box prop to Button and validate if the children is a flexbox element
Previously the children of a Button was not a flexbox element. So if you want more complex alignment you would need to put a box as the first children of the Button. This PR aims to avoid that wrapper.
Yes
Totally
> Added button box prop

- __tests__/components/Table-test.js
- __tests__/components/__snapshots__/Table-test.js.snap
- src/js/components/Table.js
Adds a little more error reporting for data mismatching between table header cells and row cells. See linked issue for more information.
Pretty small change in the PR.
Light manual testing, in use with another application.
Chrome developer breakpoints, using notes in reproduction steps.
none
https://github.com/grommet/grommet/issues/1334
none
No.
Probably not.
Backward compatible.
> FIX_TABLE_HEADER_ROWS

- src/js/messages/icons/en-US.js
When using the FormEdit icon, the console fills up with the following message:
[React Intl] Missing message: "form-edit" for locale: "en-US", using default message as fallback.
That shouldn't happen.
Create a page that has that icon.  See if you get the same message in your browser.
none
Create a page that has that icon.  See if you get the same message in your browser.
> The FormEdit icon needs to be localized

- src/js/components/Timestamp.js
Fix issue #1224 Timestamp not working in IE/Edge and #1157 24hour time.
In grommet-docs, chose 'minutes' or 'seconds' in Timestamp examples. 
IE/MAC, Chrome/Edge/IE/Firefox
In grommet-docs, chose 'minutes' or 'seconds' in Timestamp examples. 
imports moment.js
may want to add http://momentjs.com/timezone/ to fix #835 Add display timezone
No
No
non-breaking.
> Fix timestamp ie moment

- src/js/components/Anchor.js
Prevent JS to interfere with shortcuts to open a link in a new tab.
this [diff](https://github.com/grommet/grommet/pull/1370/commits/cb51da2770ba84a81bc0157249068fa9b38f4346) on `src/js/components/Anchor.js`. 
`pre-commit` hooks + local testing
Linking the project and cmd+clicking some links
I think it's frustrating for SPA's to break this native behavior.
No, it's just a fix.
> Allow routed Anchor links to open in new tab via CMD + Click

- src/js/components/LoginForm.js
This PR removes the trimming of the whitespace around the password field on the login form page.
When a password that either starts or ends in spaces is submitted in the login form, previously the surrounding whitespace would be removed and the user's password would be submitted as something that they didn't intend to submit.
Submitting a password with whitespace around it no longer results in the whitespace being trimmed when the field is submitted.
When a password with whitespace surrounding it is submitted, the provided value should be observed to be unmodified after this PR, whereas before it would  modify the password that the user inputted.
We have a bug against users who have passwords that start or end in spaces that are unable to login using the LoginForm. [There doesn't seem to …
> Remove whitespace trimming of password in LoginForm

- src/js/components/Button.js
Prevent JS to interfere with shortcuts to open a link in a new tab.
this [diff](https://github.com/grommet/grommet/pull/1373/commits/4d051e3462e0d7d2b396d14f2741b764079ca30c#diff-0839403ed3b1e347ea49e70ab82abca5) on `src/js/components/Button.js`. 
`pre-commit` hooks + local testing
Linking the project and cmd+clicking some buttons
PR made to match Anchor behavior implemented in related PR
No, it's just a fix.
> Allow routed Button links to open in new tab via CMD + Click

- src/js/components/Carousel.js
Fix #1327 and #1220 carousel infinite=false behavior so that it doesn't wrap
https://grommet.github.io/docs/carousel/examples
mac/pc edge/chrome
https://grommet.github.io/docs/carousel/examples
No
No
Non-breaking
> Fix infinite eq false behavior

- src/js/components/SVGIcon.js
Adds the 'xsmall' proptype to SVGIcon to fix issue #1324 
Manual - checking to see if it stops throwing a validation error when SVGIcon is used with size xsmall
Instantiate an SVGIcon with size xsmall and check the browser console for PropType errors - there shouldn't be any. [This codepen](https://codepen.io/marcelofs/pen/oWYexo?editors=0010) is a good start.
The css classes are already generated, only the prop validation was missing
No - the documentation for [Icon](https://grommet.github.io/docs/icon) already mentions the use of 'xsmall'. There doesn't seem to be documentation specific to SVGIcon.
Probably not, its just a simple fix.
> Add xsmall propType to SVGIcon #1324

- src/js/components/Image.js
According to the docs, this is what the component should do:
- https://grommet.github.io/docs/image
Sets `full` type to `true` if `fit` prop is defined.
It's a one-line change, so this will be obvious. 
0 testing. 
Set the prop `fit` and not the prop `full` on an Image component. Then, with `react-dev-tools`, check the props of the `Image` component and see if it has the prop `full` set to `true`.
[Docs][1] says this is how this is supposed to work.
[1]: https://grommet.github.io/docs/image
> Set `full` to `true` if `fit` is defined.

- __tests__/components/LoginForm-test.js
- __tests__/components/__snapshots__/LoginForm-test.js.snap
- src/js/components/LoginForm.js
Signed-off-by: Mike Turley <mturley@hpe.com>
This PR adds the ability for the errors prop of LoginForm to contain arbitrary JSX elements, so a custom error can be rendered (e.g. one which contains a link to an external resource about the error).  Today that errors prop must be an array of strings, each of which is used as the id and defaultMessage of a FormattedMessage.  With this change, if any of the elements in that array is a JSX node (checked with `React.isValidElement()`) it is used as-is instead of being used in a FormattedMessage.
LoginForm component
Testing in my own project, and also added a new snapshot test.
Try rendering a LoginForm with errors that contain both strings and JSX elements, and observe that both types of errors render properly with no console warnings.
In our …
> LoginForm: Add support for errors to be arbitrary JSX elements

- src/js/components/Accordion.js
Uses typeof instead of Number.isInteger to determine if the active property is just a number that needs to be put into an array.
Line 20 in Accordion.js
Verified that the Accordion displays without error in IE11 and Chrome.
See above.
N/A
N/A
N/A
No
Not sure.
> Fixed issue #1399 - Number.isInteger is not supported in IE11. 

- src/js/components/DateTime.js
It fixes icon in DateTimeComponent when format is set to "H" (24 hour)
DateTime.js
manualy
set datetime format="H" and check if the icon is valid(timeIcon)
nope
It is probably the smallest PR ever but it was needed in my purpose
> fix dateTime Icon when format set to 24 H

- src/js/components/Anchor.js
Explain that `path` supersedes the `href` prop if both are present.
N/A
Manual testing to ensure accuracy of new docs.
Add both `href` and `path` props, with different values, to an `Anchor` component and notice that `href` prop is ignored.
N/A
N/A
N/A
Done in this PR.
No.
N/A
> Clarify Anchor.js docs.

- src/js/components/Menu.js
Fixing issue #1419 with Menu holding focus on keyboard events after opening Layer on top
src/js/components/Menu.js:336
I have tested with our production application:
1. Expand/Collapse Menu, then press `space` - Menu opens (though there is issue that first time space pressed it opens and immediately closes, second time it opens fine, but this issue is present in 1.5.1 as well and it is not this ticket)
2. Expand Menu, click item opening layer, press space - Menu does not open
3. Expand Menu, click item opening layer with TextInput, press space within TextInput - Menu does not open
4. Close Layer, press space - Menu opens again
As above
There is codepen in the original issue
https://github.com/grommet/grommet/issues/1419
No
Backcompatible
> bug fix #1419: incorrect focus on Menu when Layer opened from Menu

- __tests__/components/__snapshots__/Select-test.js.snap
- src/js/components/Select.js
- Add React component support to Select's `render()`
- Stop `itemClick` event propagation which throws a React exception upon `Drop` dismiss.
- Fix tests to include `type="text"`
---
> Grommet `Select` now supports render of valid React component JSX on `option.label` and `option.value` when rendering non-inline.
`Select.js`
> The build passes all built-in tests within `__tests__`. I have updated the snapshot for two that initially did not pass. <br><br>I've `npm link`'ed it as a dependency in one of our internal systems at work. No functionality regressions that I can spot through basic hand-testing.
> When providing options to `Select`, set `option.label` to a React component.
> Nope.
> Sure, up to y'all.
> I do not believe this is a breaking change, as it will render the original …
> Add React component support to Select's render()

- __tests__/components/__snapshots__/RadioButton-test.js.snap
- __tests__/components/__snapshots__/Select-test.js.snap
- src/js/components/RadioButton.js
Changing the wrapper label of the Radiobutton component for a span tag to meet the WCAG requirement.
Updated the snapshots of the radiobutton.
Signed-off-by: jlevesque <jlevesque2109@gmail.com>
It removes the label tag wrapping the radiobutton component. Now the wcag requirements are met by having one label per form input.
The test coverage have been run.
By using tools like react-axe, the exception is no longer thrown since the component has one label with a for attribut.
Compatible
> Removed the label wrapping the radiobutton component (Issue #1436)

- src/js/index-commonjs.js
- src/js/index.js
Export the recently added PasswordInput component (4d4ebd2fa5e71aac4d31f4bc9479048c567927a9) in src/js/index.js and src/js/index-commonjs.js files so the component is possible to import in external projects.
Run tests, repeat 'manually tested'-step locally. Any other steps when exporting new components?
Tests ran, built project with gulp in accordance to [instructions](https://github.com/grommet/grommet/wiki/Building-Grommet) and tested that PasswordInput is available as an exported component.
I built the project using `gulp dist` before making the changes, and verified that importing the PasswordInput module was not possible, then repeated the process post-change and saw the component listed as a module. (See screenshot.)
This is my first PR and I have very limited insight in the …
> Export passwordinput component

- src/js/messages/ru-RU.js
- src/js/messages/ru.js
Adds Russian translations for messages.  
The PR is submitted as a WIP, with comments that needs to be addressed throughout the file.  
None other than running test script.  
Address comments, let me know what I could do further.  
This translation is done to the best of my ability. Russian is my mother tongue, but I haven't had a chance to practice it very often the last few years. I used the `en-US.js` translations as a base. Verified results with Google Translate and used contextual understanding to the best of my abilities. Results should be 90-95% reliable with possibility of minor mistakes. There's also a possibility that some conjugations are required if certain words are used in a context that is different from what I've managed to infer.
If this is received as something of …
> Russian translations for messages

- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/components/heading/Heading.js
- src/js/components/heading/StyledHeading.js
- src/js/components/heading/__tests__/Heading-test.js
- src/js/components/heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/heading/doc.js
- src/js/components/heading/index.js
- src/js/components/index.js
- src/js/themes/vanilla.js
The Heading differs from 1.0 in:
The `tag` property has been superseded by the `level` property.
There is a new `size` property to enable stylistic adjustment.
`margin` now supports an object allowing just top or bottom margin.
`strong` has been removed. Callers should use `<strong>`.
`uppercase` has been removed. Callers should use toUpperCase() when populating.
> Added Heading.

- src/js/components/Box.js
- src/scss/grommet-core/_objects.box.scss
I noticed Box doesn't have a way to set `justify-content: space-around;`
This adds it.
I'm using it locally
Yes, I've made https://github.com/grommet/grommet-docs/pull/264 for that.
No, i wouldn't say so.
is backwards compatible.
> Add justify=around prop to Box

- __tests__/components/TableHeader-test.js
- __tests__/components/__snapshots__/TableHeader-test.js.snap
- src/js/components/TableHeader.js
This closes #1176.
Column labels should allow for an optional tuple to define a column header. The first item in the tuple is the column label. The second item is an options object which can contain a `sortable` boolean property which will disable sorting for the column it is defined for. If no options are passed the default is still to rely on the `onSort` value to enable the sorting UI.
I am currently using my fork in a project and can verify that his behavior is as described. There is also a new snapshot test to cover this.
```jsx
<TabelHeader onSort={() => {}} labels={['first', ['second', { sortable: false }]]} />
```
Not all table columns can be sorted so there should be a backward compatible way to disable the sort icons and buttons for these.
#1176 
Yes, but the change is backward …
> Allow columns to be individually sortable.

- src/js/components/Button.js
- src/scss/grommet-core/_objects.select.scss
Fix issue #1557 
Remove undefined variable. Code checked if variable was false. Because it was undefined, it always returned false and printed an error.
None
1. Apply fix
2. Ctrl + Click a routed button
3. No error should be printed
No
> Button ctrl click fix

- src/js/components/Anchor.js
Escape the single quotes in the `Anchor` schema docs.
View the current [anchor docs](https://grommet.github.io/docs/anchor) and notice the incorrect doc string for the `path` prop:
> ...when clicked.**NaN** active only...
Built `grommet-docs` locally with modified `grommet` wc.
n/a
n/a
n/a
Yes
No.
> Fix 'NaN' in Anchor docs schema

- src/scss/grommet-core/_objects.select.scss
Fix an issue where if the text inside a Select field was too long, it overlapped the select__control arrow
None. I actually have no idea if there would be any way to test this.
1. Create a Select field with a value longer than the width of the field.
2. See if the text overlaps the arrow.
Here is a codepen illustrating the changes: https://codepen.io/Thuranel/pen/zdZeEq
No
Should not break anything :)
> Hide text behind select__control

- __tests__/components/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput.js
Sets `type='text'` in TextInput.
TextInput.js
Manual via grommet-docs and unit tests.
same
no
https://github.com/grommet/grommet/issues/1531
no
no
> Set type='text' in TextInput

- src/js/components/box/StyledBox.js
- src/js/components/box/__tests__/Box-test.js
- src/js/components/box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/box/doc.js
- src/js/components/meter/Bar.js
- src/js/components/meter/Circle.js
- src/js/components/meter/__tests__/__snapshots__/Meter-test.js.snap
- src/js/components/meter/doc.js
- src/js/components/stack/Stack.js
- src/js/components/stack/__tests__/__snapshots__/Stack-test.js.snap
Adds `highlight` and `onHover` to Meter values.
Adds `round` to Box.
Changes Stack to center stacked children.
Meter.js
next-sample
next-sample
no
none
yes
yes
> Added interactivity to Meter

- src/scss/grommet-core/_base.input.scss
- src/scss/grommet-core/_objects.form-field.scss
The problem was that the most generic css is not applied and had more priority.
This avoids this kind of cascading problem.
In Grommet 2.0 this type of issue will never happen 😄
> Fixed input border

- src/scss/grommet-core/_objects.icon.scss
This PR adds support for IE11 to the Spinning component. 
Viewing the branch in windows / IE11.
Windows 7 virtual machine.
IE11 does not support animating stroke-dashoffset, from what I can tell the only way to animate stroke-dashoffset in IE11 is through Javascript manually adjusting the style value which doesn't seem like an elegant solution to me.
#1556. 
Nope.
Sure.
Yep!
> Add IE11 Spinning support. Closes #1556.

- src/js/components/TextInput.js
This PR fixes a bug which would cause the suggestions not to show up if the initial suggestions array is empty. This issue is a bit confusing as we're checking the suggestions length before getting the new suggestions array from props. To avoid breaking any of the componentDidUpdate code I've added a looser check to the `_onInputChange` method.
I've tested this in the Grommet docs passing a variety of combinations of empty arrays at different stages of the filter process. I've also tested with screen reader and it appears to work well.
Test this branch in the grommet docs. To view the edge case pass an empty suggestions array to the TextInput on initial render, upon change add elements to this array. 
In `TextInputDoc.js`
```
const VALUES = [];
...
_onDOMChange (event) {
const suggestions …
```
> Fix text input suggestions when array is empty. Closes #1549.

- src/scss/grommet-core/_objects.icon.scss
This PR fixes a bug which was causing SVG icon strokes and fills not to adjust on dark background in IE Edge.
`/docs/anchor/examples?icon=true&label=true&animateIcon=true&href=true&c-background=dark` in Edge. 
#1568 
**Edge in current build**
**Edge after fix**
Nope
Nope
Yep
> Fix IE Edge icon stroke and fill on dark backgrounds. Closes #1568.

- src/js/components/Anchor.js
Fixes #1585 
Docs
Docs
#1585
Currently when only an href is passed to an Anchor with no onClick handler we receive an error.
```
Uncaught TypeError: Cannot read property 'apply' of undefined
```
Yes, the AnchorDocs need the onClick handler updated. I will send a PR for that shortly.
Nope.
Compatible
> Fix Anchor adjustedOnClick bug. Closes #1585 Closes #1552.

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
Changes the `onDOMChange` property to be `onInput`
TextInput.js
next-sample
next-sample
no
none
yes
yes
> Changed TextInput onDOMChange to onInput to align more with HTML spec

- src/js/components/Card.js
This PR adds a console warning when rendering a Card's description as a string.
`Grommet Deprecation Notice: Card description's Markdown support will be removed in Grommet's next major release.`
Markdown adds 55k to our app bundles. As Card accepts an element a user can explicitly use a Markdown component when created a Card's description.
#1550 
Grommet-docs PR [#290](https://github.com/grommet/grommet-docs/pull/290)
Yes.
> Deprecate Card description markdown support.

- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
Adds `size` and `plain` to TextInput.
TextInput/doc.js
next-sample and grommet-people-finder
next-sample
This allows larger Search text input elements for search-centric UIs.
none
yes
yes
compatible
> Added size and plain to TextInput

- src/js/components/Search.js
This PR reverts a piece of commit fc03118970d4fc949609c85b832144abff0b1232 which was causing inline searches with no suggestions to throw an error when the enter key is pressed.
I've tested in the docs with a variation of Search components but I'm still not totally clear what the author had in mind for this code. It seems impossible to return a suggestion if the drop is not active.
Docs on this branch.
#1544
Nope.
Potentially due to the nature of not fully understanding the original implementation's intent.
I would assume so but as I've noted here, I don't quite understand what the author was trying to accomplish by returning a suggestion that wasn't there.
> Fix Search onSelect when drop is not active.

- src/js/components/Menu.js
This PR fixes a bug in Menu which was causing React to throw an error. 
```
Uncaught Error: React DOM tree root should always have a node reference.
```
Stack trace:
invariant | @ | invariant.js?4599:44
-- | -- | --
getNodeFromInstance | @ | ReactDOMComponentTree.js?8ff5:172
didPutListener | @ | SimpleEventPlugin.js?6c81:209
putListener | @ | EventPluginHub.js?0f32:140
putListener | @ | ReactDOMComponent.js?ab8a:177
notifyAll | @ | CallbackQueue.js?f006:76
close | @ | ReactReconcileTransaction.js?ba2e:80
closeAll | @ | Transaction.js?f15f:209
perform | @ | Transaction.js?f15f:156
perform | @ | Transaction.js?f15f:143
perform | @ | ReactUpdates.js?8e6b:89
flushBatchedUpdates | @ | ReactUpdates.js?8e6b:172
closeAll | @ | Transaction.js?f15f:209
perform | @ | Transaction.js?f15f:156 …
> Fix Menu Anchor path bug. Closes #1611.

- __tests__/components/Tiles-test.js
- __tests__/components/__snapshots__/Tiles-test.js.snap
- src/js/components/Tile.js
- src/js/components/Tiles.js
This PR fixes two issues. First, when a Tile is set to `selected={true}` [it would not render selected](https://codepen.io/karatechops/pen/jGErod?editors=0010). Secondly, when a colorIndex is defined on a tile and the tile is part of the `selected` array passed to Tiles [it does not render as selected](https://codepen.io/ezzatron/pen/gmvKBE).
Tested in the docs.
This branch in the docs with the following snippet
```
<Tiles fill selectable flush={false} colorIndex='light-2' selected={[ 0, 2 ]}>
<Tile colorIndex='light-1'>0</Tile>
<Tile colorIndex='light-1'>1</Tile>
<Tile>2</Tile>
</Tiles>
```
or
```
<Tiles fill selectable flush={false} colorIndex='light-2'>
<Tile colorIndex='light-1'>0</Tile>
<Tile colorIndex='light-1'>1</Tile>
<Tile selected>2</Tile>
</Tiles>
```
Tiles is currently …
> Fix Tile select bug. Closes #1250.

- src/js/components/Stack/Stack.js
- src/js/components/Stack/styleMap.js
Refactor's the NEXT stack component so that the style object is externalized into a Map.  This should make it easier to maintain and make the Stack component cleaner.
It might be a good idea to do this within the styled-component, but I will leave that for another PR.
See the Diff
Tested with next-sample
Use the stack component and verify that the functionality is the same.
N/A
N/A
N/A
No
No
Yes, backwards compatible
> NEXT Stack refactor

- src/js/components/Menu.js
Signed-off-by: Sarah Allen <sarah@zooniverse.org>
This adds the classname prop to the `MenuDrop` and its child `Box` component. 
Just a simple two line change in Menu.js
I didn't write any tests but didn't as it would seem more like testing React than the Grommet library, in my opinion. If the grommet team feels different, I am happy to write a simple unit test for this.
Create a `Menu` component with a `className` prop and check in the DOM using dev tools and React Dev Tools to see that the classname is applied to the div component that is inserted in the DOM body.
I have a grommet `Menu` component that I'd like to slightly modify the styles for a specific use case. I can add a className to the parent `Menu` component as expected, but that class is not applied to the `MenuDrop` and its …
> Pass the classname prop to the MenuDrop and child Box component

- src/js/components/Chart/Chart.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
- src/js/components/Chart/doc.js
Allows Chart values to take a triple or tuple. When a triple, [x, y1, y2], the bar or area is drawn between y1 and y2 at x.
Chart/doc.js
next-sample
yes
yes
compatible
> Enhanced Chart to allow range for bar and area types.

- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
Adds support for 'none' as a value for top or bottom margin on Heading.
Heading/doc.js
next-sample
next-sample
no
no
compatible
> Enhance Heading to allow 'none' for top or bottom margin

- .eslintrc
- package.json
- src/js/components/Drop/DropContainer.js
- src/js/components/Grommet/Grommet.js
- src/js/components/Layer/Layer.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/Markdown/Markdown.js
- src/js/components/hocs.js
- src/js/themes/hpe.js
- src/js/themes/vanilla.js
- src/js/utils/__tests__/__snapshots__/object-test.js.snap
- src/js/utils/__tests__/object-test.js
- src/js/utils/index.js
- src/js/utils/object.js
This makes sure all theme objects will not be changed. Also removed deep clone and deep merge modules. `deep-merge` is deprecated so I decided to create a function that does the same job.
> Aded object freeze to theme objects.

- src/js/components/Toast.js
Adds a new property duration for Toast.
`src/js/components/Toast.js`
None relevant.
Add a Toast with a different duration.
Example:
`<Toast duration="5000" ... />An example message</Toast>`
Toast should use a variable duration.
See #1671 
None relevant.
Yes.
Yes.
It is backwards compatible.
> New property duration for Toast

- src/js/components/Card.js
This PR removes Card's Markdown component dependency. This reduces the Card component's size significantly. 
Cloning this branch and using the docs in alias mode.
Cross browser testing, this does not introduce anything new to the dom as the Markdown component would eventually render a grommet Paragraph.
Test docs' Card example page.
#1550
Yes, a PR for docs will follow removing the markdown deprecation notice.
Potentially as it could be considered a breaking change if an app is using Markdown in a Card.
This is somewhat a breaking change. However, apps using Card's markdown support will simply render a markdown string and not throw errors. We've had a deprecation notice for a release cycle so users should be aware of the change at this point.
> Remove Card's Markdown dependency. Closes #1550.

- src/scss/grommet-core/_objects.icon.scss
> Fix status icons css in dark context

- src/js/components/Layer.js
Prevent Layer.js eating tab characters if hidden
issue reported on Slack by aaronvasquez
> Prevent processing of tab characters if layer is hidden

- src/scss/grommet-core/_objects.form-field.scss
> Fix Select height error in forms - 1719

- src/js/components/Toast.js
- src/scss/grommet-core/_objects.icon.scss
- src/scss/grommet-core/_settings.font.scss
> Fix core font for grommet-theme Toast

- src/js/components/Meter/Bar.js
Meter outer element was setting the border-radius based on the size. It should be set based on thickness.
Meter.js
grommet-site white-box
grommet-site white-box
> Fixed an issue with Meter rounding

- src/js/components/DateTimeDrop.js
It provides locale weekdays names to DateTimeComponent
Change locale ad see  if names changed
before:
after:
> Localize DateTimeDrop Component

- src/js/components/DropButton/DropButton.js
If you have a dynamic control or children, and you use the dropbutton without explicit `open` prop, the dropbutton will be closed because and the internal state gets overriden. 
With this PR the internal state will be used, unless open was provided.
> Prevent dropbutton to close on props update without open prop

- src/scss/grommet-core/_objects.toast.scss
Fixes GitHub issue #1733.
Uses margin instead of padding for the status icon inside Toast. The use of padding, coupled with `box-sizing: border` was causing the icon to be resized to account for the padding.
One line change.
White box testing via grommet-docs.
Same as above.
See earlier comments.
#1733 
No
No
> Fixed an issue with Toast status sizing.

- __tests__/components/Markdown-test.js
- package.json
- yarn.lock
The new version of this library handles various types of input
more intelligently and is now only ~5kB gzipped.
It upgrades the version of `markdown-to-jsx`.
It's a small diff, so not much to look at. The only material change I made is the test was slightly wrong and would have led to an unexpected result. Markdown content expected to be evaluated as a block needs to suffixed by a padding newline.
Existing tests.
Open up the dev site and use the Markdown component I suppose.
I'm the developer of `markdown-to-jsx`.
Probably not.
Probably yes.
Backward compatible.
> Upgrade markdown-to-jsx

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Adds `href` support for Menu items.
Menu.js
Enhanced Menu tests to cover this. Manually tested via grommet-site.
grommet-site
No.
https://github.com/grommet/grommet/issues/1761
yes
no
backwards compatible with 2.0.
> Allow href to be used in Menu items. Fixes GitHub issue #1761.

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Stack/README.md
- src/js/components/Stack/Stack.js
- src/js/components/Stack/__tests__/Stack-test.js
- src/js/components/Stack/__tests__/__snapshots__/Stack-test.js.snap
- src/js/components/Stack/doc.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/vanilla.js
Adds `guidingChild` to Stack to allow controlling which child drives the layout.
Adjusted default theme Box border thicknesses.
Stack/doc.js
new grommet-site
grommet-site
Automatic.
Sure.
Essentially compatible.
> Added guidingChild to Stack. Adjusted Box border widths in vanilla theme.

- __tests__/components/__snapshots__/WorldMap-test.js.snap
- src/js/components/WorldMap.js
- src/scss/grommet-core/_objects.world-map.scss
IE11 world map fixes:
- Fix height in IE11.
- Fix zoom in IE11.
- Fix mouse over in IE11.
✅ Chrome
✅ Firefox
✅ Safari
✅ Browser stack: IE11
Test this PR in the world map docs page: http://grommet.io/docs/world-map/
&nbsp;  |  **Before:**  |  **After:**
:-------------:|:------------:|:-------------------------:
**Height**  |  ![image](https://user-images.githubusercontent.com/3210082/34515121-851afa2a-f025-11e7-84c8-f75a990d822d.png)  |  ![image](https://user-images.githubusercontent.com/3210082/34515130-8cc414e6-f025-11e7-963b-3c169593ffb2.png)
**Zoom**  |  ![image](https://user-images.githubusercontent.com/3210082/34515390-bd165824-f026-11e7-974a-80ee51a587ac.png)  |  ![image](https://user-images.githubusercontent.com/3210082/34515352-9835f82a-f026-11e7-94cf-16a981644031.png)
**Mouse …
> Fix world map in IE11

- src/js/utils/styles.js
When using `<Box background={{ dark: false }} />`, the color style wasn't being set correctly. If the `background` had a `color` or `image`, it was working fine.
utils/styles.js
grommet-weather app
grommet-site?
no
no
> Fixed an issue with dark background Box

- src/js/components/Video/Video.js
video events parameters are propagated to event handlers.
.... onLoadedMetadata = ({target}) => { console.log(target.duration) } #### Any background context you want to provide? issue reported on slack channel by edward10 #### Is this change backwards compatible or is it a breaking change? compatible
> Video events propagation

- src/js/components/Chart/Chart.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
When Chart had `full` width and/or height, set the sizing to match the containing element's resolution.
Chart.js
grommet-weather
grommet-site
no
no
> Fixed Chart to work better at full width or height

- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/README.md
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds an optional click handler to the Layer overlay.
Layer/doc.js
grommet-weather
grommet-site
automatically
sure
> Added onClickOverlay to Layer

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
Adds a11yTitle properties to Calendar buttons using localized date strings.
Calendar.js
grommet-site
grommet-site
no
no
> Added a11y titles to Calendar buttons

- src/js/components/Button/README.md
- src/js/components/Button/StyledButton.js
- src/js/components/Button/doc.js
- src/js/components/Drop/README.md
- src/js/components/Drop/doc.js
- src/js/components/DropButton/README.md
- src/js/components/DropButton/doc.js
- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Fixed an issue with Select not closing the Drop when the use selects an item.
Also fixed an issue with how the form drop down icon was being rendered in Select.
Also added a `focusIndicator` to both Select and Button to allow using them in more diverse form field contexts. This is similar to how TextInput and TextArea have `focusIndicator`.
doc.js files
grommet-site
grommet-site
automatic
no
> Fixed an issue with Select not closing the Drop

- src/js/components/Select.js
- src/scss/grommet-core/_objects.form-field.scss
- src/scss/grommet-core/_objects.select.scss
Fixes a couple of issues with Select when the value property is a custom element.
One issue was how the Drop was being placed incorrectly.
The other issue was how the border was being rendered.
Select.js
adding to grommet-docs example
When setting the contained `input` element to `type='hidden'`, it doesn't get placed by the browser, and so the drop has no reference location to place itself by.
https://github.com/grommet/grommet/issues/1784
no
sure
> Fixed an issue with Select not placing the drop correctly when using a custom value element

- src/scss/grommet-core/_objects.animate.scss
I'm getting "Base-level rules cannot contain the parent-selector-referencing character '&'." compiling grommet with the sass gem, I think this might be a typo.
Fixes a typo.
> Fixed base level self-referencing error

- __tests__/components/Toast-test.js
- src/js/components/Toast.js
Removed prop duration to avoid invalid html attributes on prop transfer.
`src/js/components/Toast.js`
None relevant.
1. Show a Toast.
2. See browser console.
3. Review that there is no any error messages related with **duration** prop.
Browser console not showing any error message.
See #1811.
No.
No.
It is backwards compatible.
> Removed prop duration to avoid invalid html attributes for Toast

- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Clock/StyledClock.js
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
- src/js/components/Drop/StyledDrop.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Otherwise they're global and can interfere with one another.
I discovered this when the `Drop` component failed to display after a `Layer` was rendered.  I tracked it down to them both sharing the `grow-box` keyframe, but `Layer`'s version didn't set the opacity to 1.
Replaces all `@keyframes` with the `keyframe` function from `styled-components`
Minimal, but I've verified that Drop works after rendering a Layer, which it didn't before.
verify that Drop, Layer, and Clock still work
no
no
> Use styled-components to generate keyframes

- src/js/components/__tests__/README-test.js
serializes README file reading in the README test to avoid parallelization issues causing indeterminate snapshots.
README-test.js
`npm run test`, waiting for Travis results.
`npm run test`
no
no
> Attempt to fix README test issues with Travis

- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextArea/StyledTextArea.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
See title
StyledTextInput.js
grommet-site
grommet-ferret (with grommet-v1)
grommet-site
no
maybe
not behaviorally
> Set width of Select, TextInput, and TextArea to always be 100%, filling their container

- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/RadioButton/StyledRadioButton.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
Re-orders the DOM element stacking such that the native input elements for CheckBox and RadioButton are on top. This improves accessibility.
StyledCheckBox.js
grommet-site
grommet-site
no
no
> Move native CheckBox and RadioButton inputs on top of styled ones.

- src/js/components/Markdown/Markdown.js
- src/js/components/Markdown/README.md
- src/js/components/Markdown/__tests__/Markdown-test.js
- src/js/components/Markdown/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changes Markdown to take text as a child instead of a property.
Markdown.js
unit testing
grommet-site
grommet-site
yes
YES
BREAKING CHANGE for v2
> Changed Markdown to take text as a child instead of a property

- src/js/components/Heading/Heading.js
- src/js/components/Heading/README.md
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Change Heading to allow `level` to be passed as a string.
Heading/doc.js
unit tests
unit tests
automatic
no
> Change Heading to allow string level

- src/js/components/Heading/README.md
- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds `color` property to Heading.
Heading/doc.js
grommet-site
grommet-site
https://github.com/grommet/grommet/issues/1893
yes
yes
> Changed Heading to add color.

- src/js/components/Chart/Chart.js
- src/js/components/Chart/README.md
- src/js/components/Chart/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds `onClick` and `onHover` to Chart and each Chart `values` object.
Chart/doc.js
grommet-site
grommet-site
https://github.com/grommet/grommet/issues/1857
yes
yes
backwards compatible with v2.
> Changed Chart to add onClick and onHover

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/README.md
- src/js/components/Drop/__tests__/Drop-test.js
- src/js/components/Drop/doc.js
- src/js/components/DropButton/DropButton.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/README.md
- src/js/components/Layer/doc.js
- src/js/components/TextInput/TextInput.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Layer renamed onClickOverlay to onClickOutside.
Changed Drop renamed onClose to onClickOutside and added onEsc.
Drop/doc.js
Layer/doc.js
unit tests
grommet-site
unit tests
grommet-site
no
yes
> Changed Layer onClickOverlay to onClickOutside. Changed Drop onClose to onClickOutside and added onEsc.

- src/js/components/Grommet/README.md
- src/js/components/Grommet/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Grommet to remove dir property
Grommet/doc.js
unit tests
unit tests
yes
yes
backwards compatible, the old code never honored the property
> Changed Grommet to remove dir property

- src/js/components/Button/Button.js
- src/js/components/Button/README.md
- src/js/components/Button/__tests__/Button-test.js
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Button to remove `plain`.
Button/doc.js
grommet-site
grommet-site
yes, automatic
no
essentially backwards compatible with v2
> Changed Button to remove plain property

- src/js/components/Button/Button.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
Changed Button, CheckBox, and RadioButton to not set tabindex.
The one area where this is needed is when they are embedded in an SVG, which is pretty rare. It will be the caller's responsibility to add it in that case.
Button.js
unit testing
unit testing
no
no
essentially backwards compatible, unless they are being used inside an SVG.
> Remove unnecessary tabindexes

- src/js/components/Grommet/Grommet.js
Changed Grommet to remove unnecessary defaultProps.
Grommet.js
unit testing
unit testing
https://github.com/grommet/grommet/issues/1903
no
no
> Changed Grommet to remove defaultProps. Fixes GitHub issue #1903.

- src/js/components/DropButton/DropButton.js
- src/js/components/DropButton/README.md
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/DropButton/doc.js
- src/js/components/Menu/Menu.js
- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed DropButton to add `onOpen` and use that in Select and Menu.
DropButton/doc.js
unit tests
https://github.com/grommet/grommet/issues/1922
yes, automatic
no
> Fixed an issue with DropButton, GitHib issue #1922

- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Select to remove `open`.
Select/doc.js
unit test
unit test
Remove until a definitive need for it arises.
yes, automatic
yes
> Changed Select to remove `open`

- src/js/components/Diagram/Diagram.js
- src/js/components/Diagram/README.md
- src/js/components/Diagram/doc.js
- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/README.md
- src/js/components/Drop/__tests__/Drop-test.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Drop/doc.js
- src/js/components/DropButton/DropButton.js
- src/js/components/DropButton/README.md
- src/js/components/DropButton/doc.js
- src/js/components/Menu/Menu.js
- src/js/components/Menu/README.md
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Menu/doc.js
- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Drop to rename `control` to `target`.
Changed DropButton to add `dropTarget`.
Changed Menu to add `dropTarget`.
Changed Select to add `dropTarget`.
Changed TextInput to add `dropAlign` and `dropTarget`.
Changed Diagram `connections` to have object propeties `fromTarget` and `toTarget` instead of `fromId` and `toId`.
changed doc.js files
unit tests
grommet-site
Aligning on the term 'target' when referring to a related DOM element.
yes
yes
BREAKING CHANGE in preparation for v2 beta.
> dropTarget changes

- src/js/components/Anchor/Anchor.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/Carousel.js
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/Select.js
- src/js/components/Video/Video.js
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/themes/vanilla.js
Transfer all icons to the theme instead of embedding them inside the component
I believe it is a good idea to test the following components:
anchor, calendar, carousel, menu, select, video
Yes
Yes
This is a breaking change since Menu does not have the `icon` prop anymore.
> BREAKING CHANGE: Icons in the theme as opposed as embbeded in the code.

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Button/StyledButton.js
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/themes/vanilla.js
Changed Button to set disabled opacity from theme.
vanilla.js
https://github.com/grommet/grommet/issues/1913
no
yes
> Changed Button to set disabled opacity from theme

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/FormField/FormField.js
- src/js/components/FormField/README.md
- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/FormField/doc.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Text/README.md
- src/js/components/Text/StyledText.js
- src/js/components/Text/__tests__/Text-test.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/vanilla.js
- yarn.lock
Changed FormField to be more customizable via the theme. Removed the `border` property and use it from the theme. Added `htmlFor` property.
Changed Text to add `weight`.
FormField/doc.js
vanilla.js
unit test
It's most likely that callers will want to use the same FormField design throughout their app. It makes more sense to have that come through the theme.
https://github.com/grommet/grommet/issues/1958
https://github.com/grommet/grommet/issues/1957
automatic
yes
BREAKING CHANGE since `border` was removed from FormField.
>  Changed FormField to make more themable

- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Menu/Menu.js
- src/js/components/Menu/README.md
- src/js/components/Menu/doc.js
- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Select to add the `size` property.
Select/doc.js
This allows TextInput, Menu, and Select to all be kept at a consistent size in forms.
https://github.com/grommet/grommet/issues/1954
automatic
yes
> Changed Select to add size

- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
Changed Box to set flex basis to auto when `flex` is set and isn't true and when `basis` is not specified. This ensures that the default for the basis is what is intended most of the time. The caller can always set it explicitly otherwise.
StyledBox.js
no
yes
This should be compatible with almost all uses of Box+flex. However, there might be some cases that notice a difference.
> Changed Box to set flex basis to auto sometimes

- src/js/components/Select/README.md
- src/js/components/Select/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Improved the documentation for the Select `value` property to indicate that an element can be passed.
doc.js
grommet-site
grommet-site
https://github.com/grommet/grommet/issues/1932
automatic
no
> Improved documentation for Select

- src/js/components/hocs.js
- src/js/utils/object.js
Avoids `deepMerge` on every render via `withTheme`.
Instead, `withTheme` only merges themes in the constructor or when props change.
Also reduced extra object creation and function calls in `deepMerge`.
hocs.js
grommet-sandbox InfiniteScroll with theme per item.
same as above
https://github.com/grommet/grommet/issues/1985
no
no
> Improved performance of deepMerge and withTheme

- src/js/components/Grommet/Grommet.js
Changed Grommet to set the initial dark context from the global background.
Grommet.js
This change adds background context. :)
https://github.com/grommet/grommet/issues/1987
no
yes
> Changed Grommet to set dark context from global background

- src/js/components/Grid/Grid.js
- src/js/components/Grid/StyledGrid.js
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/components/Grid/doc.js
Changed Grid to enhance `rows` and `columns` and added `fill`.
Grid/doc.js
grommet-site
These changes take advantage of the `repeat()` and `minmax()` parts of the CSS grid spec to allow callers to use grids with variable numbers of rows or columns. Typically, this is better approach than `<Box wrap={true} />`.
automatic
yes
BUT, callers should check the updated Grid `gap` property to use `row` and `column` instead of `horizontal` and `vertical`. The old behavior will be preserved for a short while to allow upgrading.
> Changed Grid to enhance rows and columns and added fill

- src/js/components/Button/StyledButton.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/RoutedButton-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
Fixed an issue with Button styling when primary + icon.
Now, when using `<Button primary icon={...} />`, the button background and rounding is styled. Before, this was treated the same as if there were only children and no label or icon.
grommet-site
no
yes
> Fixed an issue with Button styling when primary + icon

- .eslintrc
- src/js/components/Select/SelectContainer.js
- src/js/components/TextInput/TextInput.js
- src/js/components/Video/Video.js
Changed Select, TextInput, and Video to remove unused state variables
anywhere
https://github.com/grommet/grommet/issues/2029
https://github.com/grommet/grommet/issues/2030
https://github.com/grommet/grommet/issues/2031
no
no
> Changed Select, TextInput, and Video to remove unused state variables

- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Related to #2014. I see @alansouzati added a similar Safari fix [here](https://github.com/grommet/grommet/blame/NEXT/src/js/components/TextInput/StyledTextInput.js#L19).
> Fix Safari TextInput. Closes #2014

- gulpfile-grommet-dist.js
There are minified CSS theme file for all the other themes (aruba, hpe...), but not for dxc theme. This PR adds a minified dxc CSS file.
Only one file has been changed.
I tested it by importing in my personal project, the CSS works well.
See above.
Closes #2062.
There should be a dxc them minified css file.
No.
No.
> Add minified dxc CSS file

- src/js/components/WorldMap/StyledWorldMap.js
- src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.js.snap
Signed-off-by: Sean Kim <nogever@gmail.com>
This PR fixes the WorldMap not shown in IE11. Please see https://github.com/grommet/grommet/issues/2052
> Remove old IE11 style fix

- src/js/components/Drop/DropContainer.js
- src/js/components/TextInput/TextInput.js
Shows text input suggestions when focusing on input.
TextInput
TextInput stories.  The suggestions will show when focusing on the text field and will not hide when clicking on the input.  Selecting a suggestion should still hide the suggestions drop.
This needs to be tested in other scenarios.  I could use some help linking grommet to the OneSphere app so that we can test it more thoroughly.
See issue below
https://github.com/grommet/grommet/issues/2091
N/A
No
No
> Show suggestions on focus in text input

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/select.stories.js
Changed SelectContainer to not use fill={true} for contained Buttons. Fixes GitHub issue #2095.
storybook on Firefox, Opera, Edge.
storybook
https://github.com/grommet/grommet/issues/2095
no
yes
> Changed SelectContainer to not use fill={true} for contained Buttons. Fixes GitHub issue #2095.

- src/js/components/Box/README.md
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Box/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Removed justifySelf from Box documentation. It isn't implemented and not enough browsers support it.
Box/doc.js
storybook
storybook
https://github.com/grommet/grommet/issues/2045
automatic
no
> Removed justifySelf from Box documentation. It isn't implemented and not enough browsers support it.

- .babelrc
- .eslintrc
- package.json
- yarn.lock
Changes babel config to add support for class properties
.babelrc
manual
run `gulp test` and `gulp jslint`
In v2 we use class properties and in https://github.com/grommet/grommet/pull/2111 @RobertGary1 wants to add the event listeners to the class level. it would be nice to follow the same pattern as in v2.
no
no
> Added support for class properties in v1.

- src/js/components/Drop/StyledDrop.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/layer.stories.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Changed Layer and Drop to not control overflow in containers.
StyledDrop.js
StyledLayer.js
storybook
storybook Opera, Firefox, Edge, IE11
https://github.com/grommet/grommet/issues/2103
https://github.com/grommet/grommet/issues/2107
no
yes
Usage of Layer or Drop expecting the container to control overflow should be updated to control the overflow in a containing Box.
> Changed Layer and Drop to not control overflow in containers.

- src/js/components/Select/SelectContainer.js
Bugfixes #2007. The selection of multiple options was not correctly stored in selected prop. So if multiple is set to true and we have an array of options and values, selected prop need to be reevaluated based on chosen values.
SelectContainer.js - see commit, only 4 lines changed
None
Select multiple properties with current branch of NEXT and this PR.
It's my first PR on this project.
#2007 
No
Probably, as bugfix
Only a bugfix for NEXT branch
> Fix selected prop for multiple select

- src/js/components/Box/Box.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/layer.stories.js
- src/js/themes/vanilla.js
- src/js/utils/colors.js
Changed Layer to handle dark backgrounds better. Fixes GitHub issue #2044.
LayerContainer.js
storybook
storybook
https://github.com/grommet/grommet/issues/2044
no
yes
BREAKING CHANGE: Caller's who have customized the layer background via `theme.layer.backgroundColor` should change references to `theme.layer.background`. This is so the Layer background can be configured consistently with how Box background works.
> Changed Layer to handle dark backgrounds better. Fixes GitHub issue #2044.

- src/js/components/Drop/DropContainer.js
Changed Drop to fix an ie11 issue. Fixes GitHub issue #2149
storybook on Opera and ie11
storybook
https://github.com/grommet/grommet/issues/2149
no
no
> Changed Drop to fix an ie11 issue. Fixes GitHub issue #2149

- src/js/components/Meter/StyledMeter.js
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
Changed Meter to fix an overflow issue on IE11. Fixes GitHub issue #2147
StyledMeter.js
storybook on Opera and IE11
storybook
https://github.com/grommet/grommet/issues/2147
no
no
> Changed Meter to fix an overflow issue on IE11. Fixes GitHub issue #2147

- src/js/utils/Intl.js
Helps give developers freedom to show defaultMessage without maintaining a seperate translation file for default locale language. They can just pass defaultMessage value as an argument to the getMessage function and there is no need to keep the key argument value same as the defaultMessage value
default message function
Testing has been done checking backward compatibility. Also tested on google chrome and mozilla firefox.
Suppose i want to show a error on home screen - "Error retreiving data from api". So, I pass the value of key argument as unique - "HOME_API_ERROR" in the getMessage function of grommet util for internationalization  and do not keep this key in any of the translation file in the project. The default message in this case will be shown on the user interface as same as the …
> Added defaultMessage as an argument in getMessage function to avoid maintaining a separate translation file for default locale language

- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/Header.js
- src/js/components/DataTable/README.md
- src/js/components/DataTable/buildState.js
- src/js/components/DataTable/datatable.stories.js
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed DataTable to have onSearch be a top property, not per column
doc.js
storybook
storybook
no
no
well, strictly this is breaking compared to the prior version, which only existed for about 15 minutes.
So, effectively this is backwards compatible.
> Changed DataTable to have onSearch be a top property, not per column

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/README.md
- src/js/components/Drop/__tests__/Drop-test.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Drop/doc.js
- src/js/components/Drop/drop.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Drop to add center alignment and `stretch` property.
Address GitHub issue #2025.
doc.js
storybook
storybook
Changed Drop to add center alignment. Address GitHub issue #2025.
automatic
yes
> Changed Drop to add center alignment. Address GitHub issue #2025.

- src/js/components/Button/StyledButton.js
- src/js/themes/base.js
Changed Button to fix an issue with primary styling.
storybook
storybook
no
yes
backwards compatible as designed. Custom themes might have relied on the older behavior and should verify. The `dark` theme now works correctly.
> Changed Button to fix an issue with primary styling.

- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/select.stories.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/themes/base.js
- src/js/utils/styles.js
Changes Select theme to allow for `extend` and custom border dimensions.
Also moves `input.border` to `control.border`
Select.js
storybook
select.stories.js (Custom rounded example)
no
yes
breaking change since we moved `input.border` to `control.border`
> Select: add more theme flexibility.

- src/js/components/Box/Box.js
- src/js/components/Drop/DropContainer.js
Changed Drop to fix an issue with background styling.
Arguably, the similar code in Box and DropContainer should be refactored to avoid duplication. This at least fixes the issue for now.
storybook
storybook
no
yes
> Changed Drop to fix an issue with background styling

- .babelrc
- package.json
Transform icon imports from:
```
import {
Actions,
ClosedCaption,
Expand,
FormDown,
FormNext,
FormPrevious,
FormUp,
Next,
Pause,
Play,
Previous,
Subtract,
Volume,
VolumeLow,
} from 'grommet-icons';
```
to:
```
import Actions from 'grommet-icons/es6/components/icons/Actions';
import ClosedCaption from 'grommet-icons/es6/components/icons/ClosedCaption';
import Expand from 'grommet-icons/es6/components/icons/Expand';
import FormDown from 'grommet-icons/es6/components/icons/FormDown';
import FormNext from 'grommet-icons/es6/components/icons/FormNext';
import FormPrevious from 'grommet-icons/es6/components/icons/FormPrevious';
import FormUp from 'grommet-icons/es6/components/icons/FormUp';
import Next from 'grommet-icons/es6/components/icons/Next';
import Pause from …
```
> Added babel transform plugin to convert icon imports

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/select.stories.js
Changed Select to fix an issue with duplicate DOM ids and names
Select.js
storybook, unit tests
storybook
https://github.com/grommet/grommet/issues/2214
https://github.com/grommet/grommet/issues/2204
no
yes
backwards compatible for usage
However, the way `id` and `name` properties are passed to the underlying elements within `Select` has changed. For instance, if you have automated tests that were relying on the `name` being associated with the `<button>` element, that will not match anymore. Similarly, if you were relying on `id` being associated with the `<input>` element, that will not match anymore. Instead, `<id>__input` will be the id of the input element now.
> Changed Select to fix an issue with duplicate DOM ids and names

- src/js/components/Grommet/Grommet.js
- src/js/contexts/ResponsiveContext/doc.js
- src/js/contexts/ResponsiveContext/responsive-context.stories.js
- src/js/utils/index.js
- src/js/utils/responsive.js
- storybook/config.js
Changes our theme to allow any breakpoint value to be passed in addition to `narrow`.
responsive-context.stories.js
manual
open and test resizing the window for responsive-context.stories.js
https://github.com/grommet/grommet/issues/2251
no
yes
> Added dynamic responsive breakpoints.

- src/js/components/DropButton/DropButton.js
- src/js/components/Layer/layer.stories.js
Prevents layer from closing when pressing Escape key if drop is open
layer stories, form example
manual
open layer stories form example
Fixes https://github.com/grommet/grommet/issues/2290
no
yes
> Fixed Layer not closing when pressing esc on open select

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/textinput.stories.js
TextInput suggestions were not being rendered if the suggestions were fetched from a server asynchronously in some cases, such as when the user pastes the text into the input field.
Suggestions will properly show up when the state changes asynchronously.
TextInput.
Npm run test and stories.
Look at the CustomSuggestionsTextInput story inside of TextInput stories.
NO
YES
> TextInput: fixed opening suggestions after an async response

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Diagram/__tests__/__snapshots__/Diagram-test.js.snap
- src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
- src/js/components/RoutedAnchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
- src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/themes/base.js
Changes none to `0px` instead of `0` to avoid problems with calculations in the css, for example: `calc(100% - 0 - 0)` should be `calc(100% - 0px - 0px)`
StyledLayer.js
storybook
run storybook examples
no
no
> Changed margin none to 0px to avoid invalid css problems

- src/js/components/Box/Box.js
- src/js/components/Box/StyledBox.js
- src/js/components/Box/box.stories.js
Changes Box to avoid width and height props to be in the DOM
Box.js and StyledBox.js
manual
Open Fixed Sizes storybook example inside Box stories
Fixes https://github.com/grommet/grommet/issues/2312
no
no
> Box: fix to avoid width and height bleeding to the DOM

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Button/Button.js
- src/js/components/Button/StyledButton.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Button/button.stories.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/themes/grommet.js
1) Updated Button to use `as` from styled-components v4
2) Removes `strong` to be used inside Button and add it to the `grommet` theme
3) Fixes padding logic for icon and label instance
4) Improved logic to change icon color based on the background 
5) Removed Text component usage to avoid issues with customizations
Button and StyledButton
manual
Open storybook examples for buttons
Fixes https://github.com/grommet/grommet/issues/2215 and https://github.com/grommet/grommet/issues/2313
no
yes
This is a backwards compatible change. Although, previously you had to specify `span` to customize the text color of the button. Now the span is not there anymore, since we removed Text. So now to customize the text inside the button, you should not pass `span` anymore.
> Button: fixed padding and height when icon is present

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Collapsible/Collapsible.js
Fixes IE11 bug that would prevent collpasible to work when resetting styles
Collapsible.js
manual
open Collpasible and Accordion storybook examples
Fixes https://github.com/grommet/grommet/issues/2309
no
yes 
> Collapsible: fixed bug in ie11 when resetting styles.

- src/js/components/Tab/Tab.js
- src/js/components/Tabs/Tabs.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Tabs/tabs.stories.js
Changes Tabs to wrap too many tabs when there is no more space for it
Tabs.js
manual
open Responsive tabs example in storybook
Fixes https://github.com/grommet/grommet/issues/2305
no
yes
backwards
> Tabs: added wrap logic to handle a lot of tabs better

- src/js/components/Tab/README.md
- src/js/components/Tab/doc.js
- src/js/components/Tab/index.d.ts
- src/js/components/Tabs/Tabs.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Tabs/tabs.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Changed proptypes to allow more than just string.
Fixed aria label to now show `[object object]` as a string value
Tab.js and Tabs.js
manual
open Rich Tab example in storybook
Fixes https://github.com/grommet/grommet/issues/2303 and https://github.com/grommet/grommet/issues/2304
no
yes
backwards
> Tab: fixed title prop types and aria title too

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/__tests__/Drop-test.js
- src/js/components/Drop/drop.stories.js
- src/js/components/DropButton/__tests__/DropButton-test.js
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Layer/LayerContainer.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/TextInput/__tests__/TextInput-test.js
Changes click outside event listener in layer and drop to use `mousedown` instead of `click`. this avoids the drop closing for progressive drops.
DropContainer and LayerContainer
manual
open progressive drop example in storybook
no
yes
backwards
> Drop, Layer: changed onclick to mousedown to handle click outside.

- src/js/components/Drop/DropContainer.js
Allows Drop components to be close with the ESC key even if the Drop element has no focus. This is useful in cases such as when you have a text input and a drop with suggestions but the focus is on the text input. 
DropContainer
npm run test
By opening a Drop component with a correct onEsc handler, removing the focus from it and pressing esc.
No
No
> Fix to close a drop element without having the focus on the drop

- src/js/components/Box/StyledBox.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/CheckBox/checkbox.stories.js
- src/js/themes/base.js
- src/js/themes/grommet.js
- yarn.lock
Refactor Checkbox to be more aligned with styled components and existing components.
Also, exposed all inner components in the theme with the `extend` capabilities
StyledCheckBox.js and CheckBox.js
manual
open storybook examples for CheckBox, especially the Themed one.
Fixes https://github.com/grommet/grommet/issues/2140
no
yes
breaking change.
Inside the `checkBox` theme entry we have changed a few things:
* Moved `radius` from border to `check`
* Renamed `check.width` to `check.thickness`
* Moved `color` from `check` to the root entry since it affects both toggle and checkbox
We have also changed some of the inner component structure that might affect theming from external apps.
> Checkbox: changed structure to allow theming inner components.

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/StyledDrop.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Changed Drop to fix a browser warning
storybook
storybook
Noticed a browser console message while triaging an issue with Select. We were transferring the Drop `align` property to the contained Box. Box's `align` has a different signature and meaning.
no
no
> Changed Drop to fix a browser warning

- src/js/themes/grommet.js
Changes Grommet theme to properly definitely all system fonts across different devices
base.js
manual
open storybook
no
no
backwards
> Added the right system-ui font config for grommet theme.

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/AccordionPanel/README.md
- src/js/components/AccordionPanel/doc.js
- src/js/components/Anchor/README.md
- src/js/components/Anchor/doc.js
- src/js/components/Box/README.md
- src/js/components/Box/StyledBox.js
- src/js/components/Box/box.stories.js
- src/js/components/Box/doc.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
- src/js/components/Meter/utils.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
- tools/generate-readme-ts.js
* Added documentation for Accordion and Box
* Changed documentation output in markdown to account for complex default values
* Fixed box stories with gradient background
* Fix documentation for Anchor theme to use markdown syntax
* Removed unnecessary focus style in Box since focus is driven from Buttons
* Replaced opacity values in base theme to be numbers instead of strings
> Added theme documentation for Accordion and Box.

- src/js/components/RangeSelector/RangeSelector.js
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
- src/js/components/RangeSelector/rangeselector.stories.js
Changed RangeSelect to fix issues with step and vertical.
Simplified how the sub-Boxes flex values are calculated, less math.
RangeSelector.js
storybook
storybook
https://github.com/grommet/grommet/issues/2419
no
yes
> Changed RangeSelect to fix issues with step and vertical

- src/js/components/Image/README.md
- src/js/components/Image/doc.js
- src/js/components/WorldMap/README.md
- src/js/components/WorldMap/WorldMap.js
- src/js/components/WorldMap/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
Adds theme documentation for WorldMap and Image components
Moves hardcoded colors from the WorldMap component to theme
src/js/components/WorldMap/doc.js
src/js/components/Image/doc.js
jest / storybook
storybook / changing the theme to apply colors to WorldMap
No
No
> Adds theme documentation for WorldMap and Image components

- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/doc.js
- src/js/components/Select/index.d.ts
- src/js/components/Select/stories/select.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Changed Select to allow disabling individual options
Select/doc.js
storybook Select Seasons
storybook Select Seasons
https://github.com/grommet/grommet/issues/2429
no
yes
> Changed Select to allow disabling individual options

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Drop/drop.stories.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/select.stories.js
Changed Drop to fix an issue with resizing it.
This brings back calling DropContainer.place() on every update. But, we now do bottom alignment to the bottom of the window, this allows us to set maxHeight relative to the windowHeight rather than from the top to the anchor point. So, when the DropContainer is above the target, it will correctly grow upwards, just like when below the target it can grow downwards. Duh.
DropContainer.place()
storybook DropContainer, Select, and Menu
storybook DropContainer, Select, and Menu
should have one, but don't
no
yes
> Changed Drop to fix an issue with resizing it

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/theme.js
- src/js/themes/base.js
Changes SelectContainer to accept an extend on the ContainerBox
SelectContainer
manual
open custom search Select example in storybook
no issue :(
yes (when we add the Select theme documentation)
yes
backwards
> Added extend capabilities to select container

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/utils/styles.js
Changes `focusStyle` to fix an issue where firefox adds an unexpected outline around the text.
focusStyle
manual
storybook
no issue created
no
yes
backwards
> Removed Firefox outline from focused elements.

- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
adding extend theme docs to Text
doc.js
storybook
storybook
> extend Text theme docs

- package.json
- src/js/components/Button/README.md
- src/js/components/Button/__tests__/Button-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Button/button.stories.js
- src/js/components/Button/doc.js
- src/js/components/Button/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Fixes the warning for hoverIndicator warning.
hoverIndicator should accept input type of a string, to apply colors (e.g. "dark-5", "light-1"...)
src/js/components/Button/doc.js
storybook, see the hoverIndicator example added to Button plain. 
try to add hoverIndicator="dark-5" to any button on Button storybook and see the warning.
use the PR branch and see that the problem doesn't reproduce anymore.
Issue was raised as a result of  the Sidebar template example https://codesandbox.io/s/lp3y7rj1k9
Not filed yet
VM48 iframe.bundle.js:42559 Warning: Failed prop type: Invalid prop `hoverIndicator` supplied to `Button`.
in Button (created by Button)
in ThemedComponent (created by Context.Consumer)
in FocusableComponent (created by Button)
in RoutedButton (created by RoutedButton)
in …
> Button - fix for hoverIndicator warning 

- src/js/components/Button/Button.js
- src/js/components/Button/README.md
- src/js/components/Button/__tests__/Button-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Button/button.stories.js
- src/js/components/Button/doc.js
- src/js/components/Button/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2463
Let user pick a tag for the Anchor component
I added a unit test changing the tag to `span`
#2463 
I update the readme and doc file.
I kept current compatibility with Anchor when use does not supply a tag
> Add tag property into Button to let user pick a DOM tag

- src/js/components/Anchor/README.md
- src/js/components/Anchor/__tests__/Anchor-test.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Anchor/doc.js
- src/js/components/Anchor/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Documents the `as` property for the Anchor component.
My editor fixed up some trailing spaces issues on the files i opened. If you feel this is not needed i can modify.
Added a unit-test for verifying the `as` property works as intended
#2463 
The PR does that
> Document as property for Anchor component

- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
adding missing line-height property to docs
doc.js
verifying behavior in code
verify in StyledText.js
https://github.com/grommet/grommet/pull/2474
none
none
no
no
> Text - doc fix to include line-height impact

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/Heading/Heading.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
- src/js/components/Text/README.md
- src/js/components/Text/Text.js
- src/js/components/Text/__tests__/Text-test.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/Text/doc.js
- src/js/components/Text/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Contributes to: #2487 
There are a lot of css class changes going around probably due to the change of usage of styled components. Box is a bit trickier to do since it is used in other components https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox/CheckBox.js#L116-L117 so i ll do in another PR
Should i test that tag is correctly proxied?
probably
compatible
> Deprecate tag property for Text and Heading component

- src/js/components/Select/README.md
- src/js/components/Select/doc.js
- src/js/components/Select/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Adds documentation for Select onOpen callback
Select doc
manual
well if you really want to test this you can run select storybook examples
closes #2447 
yes
no
backwards
> Select: Adds documentation for onOpen

- src/js/components/Drop/Drop.js
- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/README.md
- src/js/components/Drop/StyledDrop.js
- src/js/components/Drop/__tests__/Drop-test.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Drop/doc.js
- src/js/components/Drop/drop.stories.js
- src/js/components/Drop/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2410
Adds a plain property for drop that removes background and shadow from target
i am not sure the case for this, imho it seems to render weird. i am wondering if there should be at least a border or something.
added a unit test that verifies that there is no background and shadow none
covered
compatible
> Add plain property for Drop component

- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
Closes: #2456
It all started from trying to fix the issue and then lead to a small refactoring
Unit tests are passing, the one modifying was a part of the fix to the bug. I think i improved the `MARGINS` sugar. i am open to suggestions to further improve. It still seems to me a bit code-repeating but i prefer incremental improvements here.
Added a test for the custom margin
i was playing around in the storybook for this. Maybe this could help
```
const CustomLayer = () => (
<Box background="dark-3">
<Heading>body</Heading>
<Layer background="dark-1" margin={{ top: '50px' }}>
<Box pad="xlarge">text</Box>
<Box pad="xlarge">text</Box>
<Box pad="xlarge">text</Box>
</Layer>
</Box>
</Grommet>
);
```
nope
compatible
> Fix custom margin on Layer component and refactor margin calculation

- src/js/components/Accordion/README.md
- src/js/components/Accordion/doc.js
- src/js/components/Accordion/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
removing children requirement from the Accordion component, and hence eliminating repeated warnings.
doc.js
`yarn test-update` to make sure no tests are failing, and the Accordion's related warning was removed 
run Accordion test or general `yarn test`
I'm trying to gradually clean up warnings from our tests run. each case by its own, after discussion with Eric on this scenario we came to understanding there should not be a requirement for children in the Accordion component. This fix will remove the warning from Accordion tests that don't have accordion's children.
Warnings. too many of them.
yes. done.
no
> Accordion - removing children requirement

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/Grid/README.md
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/Tabs/README.md
- src/js/components/Tabs/doc.js
- src/js/components/Tabs/index.d.ts
- src/js/components/TextArea/README.md
- src/js/components/TextArea/doc.js
- src/js/components/TextArea/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Contributes: #2464
Some of the components were misusing, i think, the react-desc and instead of using oneOfType(bool, string) they were inserting true or false values directly in the props hence provoking issues in the typescript index.d.ts file as the values where then considered as strings
I hope i didn't modify something else acctidentaly
last comment there #2464 
> Improve typescript support for some Components having true or false values in props

- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/CheckBox/checkbox.stories.js
Allows checkbox check entry to inspect toggle and disabled. This would allow different styling between checkbox and toggle
styledcheckbox
manual
open themetoggle example in storybook
no so far
no
yes
backwards
> Improved checkbox theme extend 

- src/js/components/Box/Box.js
- src/js/components/hocs.js
**Phase 1: Re-organize how HOCs are applied to Box**
Currently the documentation wrapper is treated distinctly different from
an HOC, but it is an HOC so it belongs in the hocs file. Since the
documentation path is relative to the component, we pass that value in
first to let the require dynamically pick it up.
> WIP Box Improvements

- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
Changed Select to add target when selecting an option.
Select.js
storybook
storybook
https://github.com/grommet/grommet/issues/2536
no
yes
> Changed Select to add target when selecting an option.

- src/js/components/Select/README.md
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/Select/index.d.ts
- src/js/components/Select/stories/select.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2427
Adds an empty option message when there are no options (i.e after empty search)
select-container that has the logic
added a unit-test to verify we can change message
in the storybook
#2427
did it
compatible
> Add empty option to select

- src/js/components/Layer/layer.stories.js
- src/js/utils/DOM.js
Changed Select to fix an issue with scrolling and keyboard navigation.
The issue was the isNodeAfterScroll() wasn't taking into account the top of the target element.
DOM.js
storybook
storybook
https://github.com/grommet/grommet/issues/2449
no
yes
> Changed Select to fix an issue with scrolling and keyboard navigation

- .babelrc
- README.md
- package.json
- src/js/themes/base.js
- yarn.lock
changes package.json to move grommet styles and grommet icons to peer dependency.
package.json
manual
run yarn install and npm run build and make sure everything passes.
also take a look on storybook and tests
no issues
no
yes
backwards
> grommet-styles and grommet-icons removed as peerDependency

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/SelectOption.js
- src/js/components/Select/stories/select.stories.js
Changed Select to fix an issue with rendering option state.
Previously, SelectOption wasn't looking for changes in selected state when deciding whether to update. This caused the internal child of SelectOption to not re-render.
SelectOption.js
storybook
storybook
no
yes
> Changed Select to fix an issue with rendering option state

- src/js/components/hocs.js
Adds `withTheme` proxy to styled-components so that libraries using `import { withTheme } from 'grommet/components/hocs';` don't break.
hocs.
manual
storybook
github.com/atanasster/grommet-controls/issues/3
no
yes
backwards
> Added temporary withTheme proxy.

- src/js/components/Layer/README.md
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/doc.js
- src/js/components/Layer/index.d.ts
- src/js/components/Layer/layer.stories.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Allows the user to consume a corner Layer
doc.js
storybook + added story
storybook and play with the `position` and `full` values.
#2545 
Done
Yes
> Layer - to allow corner options

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Changed Select to fix an issue with scrolling while keyboard navigating.
Note, many of the changes involve improving the names of some of the variables to be more consistent. The key change is to switch to use `scrollTo()` instead of `scrollBy()`.
storybook
storybook
https://github.com/grommet/grommet/issues/2572
no
yes
> Changed Select to fix an issue with scrolling while keyboard navigating.

- src/js/components/Grommet/Grommet.js
Changed Grommet to clear body margin when full
Grommet.js
storybook, grommet-site
storybook
This avoid a typical issue that people new to grommet face. Browsers default to putting a margin on the body element which needs to be cleared to avoid extraneous scrollbars.
no
yes
> Changed Grommet to clear body margin when full

- src/js/components/Box/StyledBox.js
- src/js/components/Box/box.stories.js
This PR allows Box to accept a px value for size in the round prop.
StyledBox
Manual
Open Box > "Round" story in Storybook
Closes #2602 
No
Yes
> Enables px value for size in Box's round prop

- src/js/components/Meter/Bar.js
- src/js/components/Meter/Circle.js
- src/js/components/Meter/__tests__/Meter-test.js
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
Closes: #2585
Fixes a bug when setting thickness value
Any of Bar or Circle. fix is identical
added unit-test. i also tested manually on storybook but didnt add a story (should I?) 
#2585
nope
maybe
compatible
> [Meter] fix bug not allowing to set custom thickness size

- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/themes/base.js
Adds a font-weight per heading functionnality in the theme
add a unit test
#2606
#2606
well the font-family is not documented so not sure where to document this either :/
compatible
> Add ability to configure font-weight by heading level in the theme

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/InfiniteScroll/InfiniteScroll.js
- src/js/components/InfiniteScroll/infinitescroll.stories.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
Brings back findDOMNode for InifiniteScroll to avoid a regression issue.
inifinitescroll.js
manual
run `Class Children` example in storybook
Closes #2600 
no
yes
backwards
> Added findDOMNode back for infinite scroll.

- src/js/components/Layer/README.md
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/doc.js
- src/js/components/Layer/index.d.ts
- src/js/components/Layer/layer.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Allowing animation to be customized on Layer
`true`- allows animation
`false` - disables
`string` - customized animation
doc.js and StyledLayer.js
storybook (use cornerLayer)
storybook (you can use the existing prop on use cornerLayer)
nop
#2578 
n/a
done
Yes
> allowing Layer a custom  animation

- src/js/components/Calendar/README.md
- src/js/components/Calendar/StyledCalendar.js
- src/js/components/Calendar/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Add `calendar.day.extend` into theme
Can style the day button on calendar component
> Can style the day button on Calendar component

- src/js/components/Grid/README.md
- src/js/components/Grid/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
adds doc to theme grid
doc.js
verify content
go over styledGrid and compare with docs
poor docs
done
no
> Grid - add theme doc

- src/js/components/Box/README.md
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2565
Add grow and shrink factor to flex property of Box component
I have one question though. i added shape to proptypes taking grow and shrink as optional parameters. Is there a way to force user to add at least one of the two? both being required seems not good to me but couldn't come up (fast) with an idea to force at least one of those.
styled box
unit test
#2565
did it.
maybe
compatible.
> [Box] add grow and shrink factor to flex property

- src/js/contexts/ResponsiveContext/index.d.ts
Fixing ResponsiveValue typing
It is that simple that does not need any explanation.
It may be something old from v1 or something, but at this moment it makes impossible to use ResponsiveContext without `@ts-ignore` so I fixed it.
When creating that I thought the breakpoints are defined in the library, but I found it is not the case.
We would need to decide whether we want to make it open or specify an array of allowable breakpoints which then can be typed and provide intellisense when creating themes
> Fix responsive context typings

- src/js/components/TextArea/README.md
- src/js/components/TextArea/StyledTextArea.js
- src/js/components/TextArea/__tests__/TextArea-test.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextArea/doc.js
- src/js/components/TextArea/index.d.ts
- src/js/components/TextArea/textarea.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2445
Add resize prop to textarea to disable resize or enable only vertically|horizontally
storybook and unittest
#2445
done
Yes
compatible
> Add resize prop to textarea

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/README.md
- src/js/components/DataTable/datatable.stories.js
- src/js/components/DataTable/doc.js
- src/js/components/DataTable/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/typescript-test.js.snap
Closes: #2634
* Enable user to turn off sortable property on selective columns
storybook.
#2634
done
yes
compatible
> [Datatable] Add sortable property on columns

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Fix: #2645
af68774c12 Introduced a regression when refactoring some code of the selectfield
Fixes the regression
At the commit introducing the regression probably. important files are the Select.js and the corresponding snapshot.
manually tested in storybook.
#2645
nope
yes
yes
> Fix regression with plain select fields

- src/js/components/DataTable/Footer.js
- src/js/components/DataTable/Header.js
- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/datatable.stories.js
* First step into some refactoring for DataTable. Not it only uses Table* components (with some extra styling). This should enable later to add functionnalities in the Table components that will be inherited in DataTable (such as onRowClick). ref #2640 
* Fixed storybook DataTable with some issues introduced by #2639 and shallow copies of the columns.
StyledDataTable.js
Updated the unit-tests and compared local storybook with existing one
#2640 
#2527 
nope
compatible
> Only Use Table* components on DataTable

- src/js/components/DropButton/index.d.ts
This PR fixes the `DropButtonProps` interface, adding the missing `ButtonProps`, wich are passed to `Button />` by the `<DropButton />`'s render method.
> Fix DropButtonProps with missing ButtonProps

- src/js/components/TextInput/README.md
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Add `extend` to the suggestions and placeholder components inside TextInput so they can be styled
Only small changes to files inside `src/js/components/TextInput/`
Tested locally with storybook
Add custom css styling to placeholder and suggestions in the TextInput component and verify manually.
Should be pretty straightforward
None
No, I've updated the docs.
No
Yes it's backwards compatible
> expose extend to additional components inside TextInput

- src/js/components/TextInput/index.d.ts
This PR fixes the `onSelect` signature of `TextInput` component and omit the one from the `JSX.IntrinsicElements['input']` type (wich creates a unusable product type).
Also, removes the `onChange` signature in order to get it from `JSX.IntrinsicElements['input']`.
TypeScript users are not able to use this component correctly.
> Fix TextInput typings.

- src/js/components/TextInput/README.md
- src/js/components/TextInput/doc.js
- src/js/components/TextInput/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Fix: #2658
Since textInput can have a type that can be a number i added that prop type into the value prop. There are other types in the input reference but i think they are all covered by string and number
played with storybook to make sure i didn't break something
#2658
did it
yes
compatible.
> Add number as possible prop type value in TextInput

- components/Grid/index.d.ts
The `Grid` component has its `fill` prop typed incorrectly. It has `true` and `false` in quotes, which prevents passing boolean values.
Very simple fix.
> Fix Broken types that prevent using fill={true}.

- src/js/components/Menu/Menu.js
- src/js/components/Menu/README.md
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Menu/doc.js
- src/js/components/Menu/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Fix: #2670
Enable user to customize label and icon justify prop
Menu
added unit-tests
didn't add a storybook i think the diff is quite minimal
#2670
did
yes
compatible
> Add justifyContent prop to Menu to customize menu label

- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
Changed CheckBox to revert part of z-index change
The first fix for the referenced issue caused another issue because the internal <input> was positioned absolute but we removed the position relative from the parent, so the input element would fill the first positioned ancestor, which might be the whole screen, making it so you couldn't interact with anything on the page.
storybook
storybook
https://github.com/grommet/grommet/issues/2653
no
yes
it brings back one issue but fixes another
> Changed CheckBox to revert part of z-index change

- src/js/components/Grid/StyledGrid.js
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
Changed Grid to handle min/max size in columns object
StyledGrid.js
unit, grommet-site
unit
this is needed to improve the responsive behavior of grommet-site
no
yes
> Changed Grid to handle min/max size in columns object

- src/js/components/Form/__tests__/Form-test.js
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/FormField/FormField.js
Fix: #2719
Fixes a small issue for form field validation
storybook and modified unit-test
storybook
#2719
no
yes
compatible
> Fix FormField validation to receive both value and all values

- src/js/components/Select/index.d.ts
This PR adds the missing `id` type to `<Select />`'s props.
> Add missing id type to <Select />'s props

- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
Enables the box gap prop to support just a css value as well
Box component
None
Adding in gap with a pixel / css value
Fixing a discrepancy with the docs
Nope.
Backwards compatible :)
> Enable Box component gap prop to use css values

- src/js/components/DataTable/Searcher.js
- src/js/themes/base.js
Changed how grommet-icons are imported to improve non-tree-shaking situations.
src/js/themes/base.js
Built a nextjs project with next-bundle-analyzer to verify that all grommet-icons weren't included.
Verified Accordion and Video in storybook to make sure icons were working.
storybook should be enough
https://github.com/grommet/grommet-icons/issues/83
no
yes
> Changed how grommet-icons are imported to improve non-tree-shaking situations.

- src/js/components/MaskedInput/index.d.ts
This PR adds the missing placeholder type to <MaskedInput />'s props.
> Add missing placeholder type to <MaskedInput />'s props

- package.json
- src/js/default-props.js
- src/js/themes/base.js
- src/js/themes/dark.js
- src/js/themes/grommet.js
Changed how themes are imported to improve non-tree-shaking situations.
any file that was changed
storybook for the components that were affected
storybook
grommet/grommet-icons#83
no
yes
> Change imports of themes to support non-tree-shaking situations

- package.json
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
Closes #2669 and https://github.com/grommet/grommet/issues/2710
changes grommet to tell webpack to not remove ThemeContext module when bundling things
package.json
* yarn build-storybook
* make sure your production version of storybook can load Rich Accordion example
#2669 
https://github.com/grommet/grommet/issues/2710
nope
yes
backwards
> Added ThemeContext to webpack side effects config.

- src/js/components/Chart/Chart.js
- src/js/components/Chart/chart.stories.js
adds custom CSS support for sizing of Chart
Chart.js
storybook
storybook - see the added example on `Line` `size="290px"`
#2750 
no
yes
> Chart - add custom css support for size

- src/js/components/Accordion/Accordion.js
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
This fixes the issue brought up in #2757 by removing the overflow prop from the Box container in the Accordion.
Just check out the code - its a small change.
None - should be as simple as removing the overflow and letting the user set it through ...rest if desired.
Make sure the accordion no longer has unwanted y-overflow scrolling.
N/A
#2757 
N/A
No
No
Backwards compatible and non-breaking
> Remove overflow prop from accordion

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed Box to update missing documentation, issues: #2761 
Box/doc.js
none
#2761
Screenshots (if appropriate)
automatic
no
Is this change backwards compatible or is it a breaking change?
> Box - Added xxsmall to the gap doc

- src/js/components/RangeInput/StyledRangeInput.js
- src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
Changed RangeInput to support theme extend for thumb and track
StyledRangeInput.js
grommet-theme-nineties
no
yes
> Changed RangeInput to support theme extend for thumb and track

- src/js/components/Grid/index.d.ts
Allow specifying inner array value for Grid columns & rows  (other than auto) as per docs: https://v2.grommet.io/grid#columns
- typed as `string[]` because repeating whole list does not provide any additional "typing benefit" and the line width would probably hit 1000 chars
- removed one duplicate `flex` declarations
https://github.com/grommet/grommet/issues/2659
> fix/typescript: allow specifying inner array value for row/column in grid component

- src/js/components/Chart/README.md
- src/js/components/Chart/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
documenting the accurate default value of Chart fill color instead of listing all colors options.
doc.js
Storybook Chart Bar
Storybook Chart Bar
Chart.js
#2775
done
no
> fix docs for Chart fill area color

- src/js/components/FormField/FormField.js
- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/FormField/formfield.stories.js
- src/js/themes/base.js
- yarn.lock
Changes FormField to allow custom theme.
FormField.js
added test for extend and add storybook story
open formfield stories and make sure it looks the same as https://storybook.grommet.io.
plus look at the new custom theme story to validate the new entries are supported.
Closes #2765 
yes, we need theme documentation for formfield!!
yes
backwards
> Better theme support for FormField.

- src/js/components/Select/README.md
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/Select/stories/theme.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
changes Select theme object to allow for additional theme entries to customize the box and text inside the container.
storybook
storybook
open Custom Search select story. type a random text. notice that "No matches found" font size is not small.
Closes #2795 
yes
yes
backwards
> Select: Allow box and text customization inside SelectContainer.

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
- src/js/components/Table/StyledTable.js
- src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
Changed StyledTable to fix issue #2631 
StyeldTable.js
storybook
storybook on FireFox, MS-Edge, Safari & Chrome
#2631 
no
yes
> Bug fix for issue 2631: Updated StyledTable to inherit width from parent

- src/js/components/InfiniteScroll/infinitescroll.stories.js
- src/js/utils/DOM.js
Changed DOM findScrollParents to use document if only parent is body.
Without this change, InfiniteScroll wouldn't work if the scrollable ancestor is a body element whose height is driven by the content. Since `<Grommet>` doesn't control the `<body>` size, the expectation is that  the document height should be used as the visible window.
DOM.js
storybook InfiniteScroll, Select, and TextInput
storybook InfiniteScroll, Select, and TextInput
https://github.com/grommet/grommet/issues/2805
no
yes
> Changed DOM findScrollParents to use document if only parent is body

- src/js/components/FormField/FormField.js
Fixes bug when used regexp validation in FormField component
1. Add FormField component inside Form component, along with Submit button
2. Add validate property with regex object (f.e. { regexp: /^[a-z]/i })
3. Press submit button and observe error message
4. Type any text into input field.
5. Press submit button again
Expected result:
Error message disappeared, form submitted
Actual result:
Error message is displayed, form didn't submit
> FormField regexp validation issue

- .circleci/config.yml
Starts migrating CI to circleci
* circleci didn't follow the project yet so it didn't run this PR yet.
* I propose that we let both circleci and travis run for now to be able to compare
* when preparing next release we discontinue travis and unfollow project
* add the release stage in circleci and release with circle ci.
Added an additional "test". when running yarn install i added `--frozen-lockfile` which will throw an error if the yarn.lock could be updated. That should help keep a synced lockfile.
> Start migrating to circleci

- src/js/components/RangeInput/StyledRangeInput.js
- src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
- src/js/components/RangeInput/rangeinput.stories.js
Changed RangeInput to fix theme track height issue.
Calculate the thumb margin based on the track and thumb height.
StyledRangeInput.js
storybook
storybook
#2830 
no
yes
> Changed RangeInput to fix theme track height issue #2830

- .circleci/config.yml
Based on the guidance here:
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
Adding tags filters for all jobs needed for publish.
> Added tag filters for CircleCI config

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
Removes obselete theme values 
theme
none
try to find any area these values where used
#2828
> Remove unused theme prop maxWidth and minWidth from button

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Accordion/accordion.stories.js
- src/js/components/Collapsible/Collapsible.js
Setting Collapsible children not to take any space when closed, (even when using the pad prop)
Collapsible.js
adjusting the Accordion stories to include a collapsible with scroll scenario.
Accordion story 
#2539
no
yes
> Collapsible - overflow fix, fixes #2539

- src/js/components/Anchor/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/RangeSelector/index.d.ts
- src/js/components/TextInput/index.d.ts
- src/js/utils/index.d.ts
`HTMLAttributes` interface has `color?: string` which collides with grommet 
`color?: string | {dark?: string,light?: string};`
hence doesn't allow setting of `{dark: string,light: string}` to `color` prop.
src/js/utils/index.d.ts
Using this block of code in the v2-launch-slides TS repo
```    <Heading color={{ dark: "white", light: "black" }}>Title</Heading>
<Paragraph color={{ dark: "white", light: "black" }}>Title</Paragraph>
<RangeSelector values={[]} color={{ dark: "white", light: "black" }}>
Title
</RangeSelector>
<Anchor color={{ dark: "white", light: "black" }} />
<Button color={{ dark: "white", light: "black" }}>Shimi</Button>
<TextInput> Shimi</TextInput>
```
use the block of code above in any Grommet+TS repo, and see all the errors before testing it with this branch. the errors …
> typescript - cross color support

- src/js/components/Layer/README.md
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Specify in the `Layer` doc that `onClickOutside={() => {}}` only applies if the layer is modal
At the single line that was changed :slightly_smiling_face: 
Discussed on Slack: https://grommet.slack.com/archives/C04LMHN59/p1551532992080800
> Specify modal-only application of onClickOutside

- src/js/components/AccordionPanel/README.md
- src/js/components/AccordionPanel/doc.js
- src/js/components/Anchor/README.md
- src/js/components/Anchor/doc.js
- src/js/components/Anchor/index.d.ts
- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/Button/index.d.ts
- src/js/components/Grid/README.md
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Menu/README.md
- src/js/components/Menu/doc.js
- src/js/components/Select/README.md
- src/js/components/Select/doc.js
- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/Text/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/index.d.ts
See #2869 
Using function components for the tag instead.
Now, because custom components are passed in as tag, `grommet` might be adding extra styling props to those children. This leads to prop warnings as in #2870 
No, already generating the new types.
Yes.
it is backwards compatible.
> Fix Tag/as ProTypes

- src/js/utils/index.d.ts
Tiny fixup for typescript utils PR I've made some time ago: https://github.com/grommet/grommet/pull/2655
Added missing type for `color` arg in `normalizeColor` to allow passing `{light: ..., dark: ...}`, not just theme key.
`Questions.map(question => question.answer("Nope"))`
Yes
> fix(typescript): allow object colorSpec argument for normalizeColor

- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/doc.js
- src/js/components/Select/index.d.ts
- src/js/components/Select/stories/select.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Fix: #2884
Allows user to set open state of select from props
unit-test and tested on storybook
#2884
done
yes
compat
> Allow user to set select open from the props

- src/js/components/Accordion/accordion.stories.js
- src/js/components/Collapsible/collapsible.stories.js
Quick PR. I received some feedback today on not being able to customize `Accordion`, so I added a few examples to demonstrate the customization better. 
No need to mention in the release notes.
backward compatible.
> incorporating feedback on Accordion stories

- src/js/components/Form/Form.js
- src/js/components/Form/README.md
- src/js/components/Form/__tests__/Form-test.js
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/Form/doc.js
- src/js/components/Form/form.stories.js
- src/js/components/Form/index.d.ts
- src/js/components/FormField/README.md
- src/js/components/FormField/doc.js
- src/js/components/FormField/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Closes: #2876
- Handles reset form with button type reset
- Adds component in the documentation
unit-tests and storybook
storybook
#2876
done
yes
compat
> Handle onReset event in Form

- package.json
Fix: #2669
So i got digging and reading documentation and talking with people :D and it seems that sideEffects should point to the file user is going to import.
I only tested this in the example provided in the issue above. i went into `node_modules/grommet/` and modified my self.
what got me into this fix was that i could import ThemeContext from the direct path
`import {ThemeContext} from "grommet/contexts"`
> Fix sideEffect path to point where user is going to import file

- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Image/Image.js
- src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
Based on feedback on already merged PR i improve the fallback image so that user can also define their own onError handler
storybook
no
no
compat
> Improve fallback image

- src/js/components/DropButton/index.d.ts
- src/js/components/RoutedAnchor/index.d.ts
- src/js/components/RoutedButton/index.d.ts
Routed* components can take props, that are not in `JSX.IntrinsicElements[...]`, but in appropriate underlaying components. E.g. Routed* components can take `margin` prop, but TS shows an error because of it. This PR fix it.
Fix TS definitions of RoutedAnchor and RoutedButton, also remove redundant properties from DropButton.
Anywhere :)
I didn't test it, but it would be great, if you can tell me how test the types.
By using this components.
No
It would be great :) 
Backward compatible and not change breaking.
> Fix some typescript definitions

- src/js/components/Button/README.md
- src/js/components/Button/StyledButton.js
- src/js/components/Button/doc.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextArea/README.md
- src/js/components/TextArea/StyledTextArea.js
- src/js/components/TextArea/__tests__/TextArea-test.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextArea/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
- src/js/utils/styles.js
- src/js/utils/themeDocUtils.js
Styles disabled TextInput TextArea. as a side-effect Select is also styled when disabled
I wonder whether we should have opacity style as a helper function and whether opacity style should first live in global section of theme. Like all the disabled things should be styled with the same way and then if user decides to override then ok.
it should remove some code-duplication from this PR. Didn't do this right now since currently we don't handle things in this way
Jest and manual on storybook
storybook
#2825 
done
yes
compatible
> Style disabled textinput and textarea

- src/js/allcomponents.stories.js
- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/RadioButton/StyledRadioButton.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- yarn.lock
Simplified CheckBox check styling. This is a minor change. The bulk of the work remains in the themes fix how they are working.
StyledCheckBox.js
storybook
#2910 
no
yes
This is backwards compatible. But, the earlier PR broke theme customization of CheckBox checkmarks.
> Simplified CheckBox check styling.

- package.json
- src/js/components/Grommet/Grommet.js
- yarn.lock
Removes mobile detect in favor of a less efficient method but smaller as well.
#2917 
no
Maybe mention that we no use the library and hence the accuracy might not be 100%
compat
> Decrease bundle size by using regex for mobile detect

- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
The PR adds the themes to the documentation for maskedInput
MaskedInput/doc.js
#2690
Screenshots (if appropriate)
auto
No
Is this change backwards compatible or is it a breaking change?
> Added to maskedInput docs to contribute to issue #2690

- src/js/components/TextArea/README.md
- src/js/components/TextArea/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds to textArea and textInput docs.
textArea/docs.js and textInput/docs.js
None
#2821
auto
no
Is this change backwards compatible or is it a breaking change?
> closes #2821 Text area and Text input docs

- src/js/components/Calendar/stories/DaylightSavings.js
- src/js/components/Calendar/stories/Simple.js
- src/js/components/Calendar/utils.js
polish the date calculation during the daylight saving periods
src/js/components/Calendar/utils.js
src/js/components/Calendar/stories/DaylightSavings.js
src/js/components/Calendar/stories/DaylightSavings.js
and storybook Calendar
I added stories for both PST and MST so it will be easy for either of us to reproduce the issues and notice if a regression occur.
#2931 
no
yes
> Calendar - fix March daylight saving

- src/js/components/Box/Box.js
- src/js/components/Grommet/Grommet.js
- src/js/components/hocs.js
Basically reverts changes to the way we are building docs in the rest of grommet for consistency and to fix parcel builds
just a yarn build. i just reverted manually the following commit https://github.com/grommet/grommet/pull/2528
#2618 
no
yes
compatible
> Revert Box architecture refactoring to fix Parcel build

- src/js/components/Accordion/__tests__/Accordion-test.js
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Accordion/stories/Custom.js
- src/js/components/Accordion/stories/CustomHeader.js
- src/js/components/Accordion/stories/Rich.js
- src/js/components/Accordion/stories/Simple.js
- src/js/components/AccordionPanel/AccordionPanel.js
- src/js/components/AccordionPanel/README.md
- src/js/components/AccordionPanel/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
allows the user to customize the heading level in Accordion.
doc.js
storybook, specifically the Custom story in Accordion
storybook, specifically the Custom story in Accordion
no ability to customize Accordions cross-app
#2894 
done
yes
> add heading customization in accordion theme

- src/js/components/RangeInput/rangeinput.stories.js
adding an explicit width to Box
the story 
browserstack Edge browser for Custom RangeInput storybook
using Edge browser for Custom RangeInput storybook
https://github.com/grommet/grommet/issues/2955
no
no
> Fix custom rangeInput on Edge

- src/js/components/DropButton/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/TextInput/index.d.ts
we probably we want to release a hot fix for this ASAP
by mistake our definitions shipped with dropProps being listed as required.
index.d.ts for dropProps
manual
no
yes
backwards
> Fixed optional drop props being treated as required.

- src/js/components/RangeSelector/README.md
- src/js/components/RangeSelector/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/grommet.js
* fixes button.extend on grommet theme
* showing the type options of the ThemeProps in RangeSelector
themes/grommet.js
with grommet-site
done
no
> fixes button extend

- .circleci/config.yml
So i got curious by the CircleCI logs and looked that in dist we have tests even if we have the ignore option. Due to https://github.com/babel/babel/issues/6226
Stats:
\ | With npmignore | without npmignore
----------- | ------------ | -------------
packed | 940kb | 3mb
unpacked| 4.5mb | 10mb
Not sure if this is the correct path forward though since the latest build on github has the tests. 
A way to fix both would be to make a script to remove tests.. maybe rimraf can delete based on pattern.
Left the --ignore in package.json so that babel doesn't process these files. should be a bit faster.
> Don't publish tests on npm

- .circleci/config.yml
- templates/grommet-v2-template/.gitignore
- templates/grommet-v2-template/README.md
- templates/grommet-v2-template/package.json
- templates/grommet-v2-template/public/index.html
- templates/grommet-v2-template/src/index.js
adds a new run command that validates a newly published release 
.circleci/config.yml
running the new template that is used for the validation
publishing
#2978 
not really, I've updated relevant README files.
no
> CircleCI validation of release using templates

- src/js/components/FormField/README.md
- src/js/components/FormField/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Mentions in documentation that formfield forwards additional properties to the component
doc.js
none
no
#2937 
done
no
yes
> Document formfield prop forwarding

- src/js/components/RoutedAnchor/RoutedAnchor.js
- src/js/components/RoutedButton/RoutedButton.js
Warns user in console when using soon to be deprecated component
#2855 
no
no
yes
> Warn on the usage of Routed components

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
- src/js/components/Table/StyledTable.js
- src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
- src/js/components/Table/stories/MeterInTable.js
Fixed the issue with table data overflow on FF browser. `width: inherit` was not respected by FF browser and data overflow issues were seen as mentioned in #2656. 
For FF, `table-layout` is set as `fixed` on StyledTable to avoid overflow issues when parent div width is smaller than table data width. 
StyledTable.js
storybook
storybook
#2656 
no
yes
> Fixed the issue with table data overflow on FF browser

- src/js/components/Distribution/index.d.ts
Update distribution typings to match examples.
Distribution/index.d.ts
Manual testing with type check
Creating a typescript Distribution component with value key/value of `color: "brand"`
No
Update Typings?
No breaking change.
> fix(typings): distribution typings missing color

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Text/StyledText.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
Currently, any styled text that has a margin applied to it will get a `margin: X` rule as well as a rule for top, right, bottom, and left which causes each text node to have 5 lines of CSS for margin, 4 of which are not needed. After looking into the styling, there's already a generic style for margin being applied via `${genericStyles}` which makes the function in `StyledText.js` not necessary, so I've removed it and updated all the text snapshots. 
`StyledText.js`
All snapshots have been updated and all tests run successfully via the test command. 
Apply a margin of `small` to a `<Text>` element and see that there is only 1 margin rule applied, not 5. 
See issue #2794 for context on why this was done. 
#2794 
No
If desired
> fix issue #2794 - optimize margin rules on styledText by removing marginStyle function

- src/js/components/Form/form.stories.js
- src/js/components/FormField/FormField.js
Fixes the FormField renderChild logic so that the `onChange` handler that updates the FormContext is not overridden when a user would like to also utilize onChange.
A reviewer could start by comparing the functionality of an `onChange` handler in the Form storybook. After this fix, it now no longer overrides the context update.
The Form storybook has been modified to test the change.
This can be manually tested via the storybook or a codesandbox with a Form and FormField.
Having Form state contained within the FormContext is excellent, but without the ability to track some of the state via onChange handlers, adjusting fields on the fly is impossible. For example, I had a form where the selection of one field determined the max value of a field after it, without being about to track the …
> Fix FormField so custom onChange does not prevent FormContext update

- CONTRIBUTING.md
- README.md
This PR makes a number of changes, most of them quite simple in nature, to the two Markdown documentation files (README & CONTRIBUTING) found in the base of the repo:
- Fix typos & awkward phrasing
- Be consistent with line-width & spacing
- Be consistent with capitalization of proper nouns (like Slack, GitHub, and Grommet) and section titles
- Give fenced-in code blocks a language
- Use reference style links for easier-to-read Markdown source
- Use a generic number (i.e. `1. `) for all ordered list items
- Use curvy/angled apostrophes & quotes (e.g. it’s “these”, it's not "these")
- Add a few more handy links
A couple things that make the changes seem more expansive than they really are:
- I tried to create consistency with line length – sometimes things were forcibly wrapping, other …
> Update Markdown files (README & CONTRIBUTING)

- src/js/contexts/ResponsiveContext/responsive-context.stories.js
This adds an example to the Storybook "ResponsiveContext > Resposive Grid" that demonstrates using the ResponsiveContext.Consumer object to create a grid with different-sized grid areas based on the available breakpoint(s).
Increases the available examples in Grommet's storybook based on a conversation in the Grommet Slack.
* Stories -> Responsive Context -> Responsive Grid
* `src/js/contexts/ResponsiveContext/responsive-context.stories.js`
Ran the pre-commit hooks and also tested in Storybook. There are some unrelated pre-commit tests failing around snapshots, but I didn't think it was wise to change those as part of this commit.
* Check results via storybook
From Slack:
> In case anyone is struggling to make `Grid` responsive, here's a super-simple component. It overloads `areas` to use …
> Creates an example using ResponsiveContext for a dynamic Grid

- src/js/components/Box/README.md
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Add support for all flex-wrap properties
unit-tests
#2754 
done
yes
backwards
> Add wrap-reverse flex support

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/Menu/README.md
- src/js/components/Menu/doc.js
- src/js/components/Menu/index.d.ts
- src/js/components/Menu/menu.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
adding the type of number to opacity prop in menu 
doc.js
storybook 
storybook  Menu
#3022
done
no
> Menu - adding type of number to opacity

- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/doc.js
- src/js/components/Select/index.d.ts
- src/js/components/Select/stories/select.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
changes select icon to allow for a custom icon component.
Fixes #3017 
yes
yes
backwards
> Allow Select custom icon to receive a node.

- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
DataTable height set to auto to fix overflow when DataTable wrapped in two levels of div. 
FIxes Datatable overflow issue #3059 . 
StyledDataTable.js
Storybook
Storybook
#3059 
No.
Yes
Yes
> DataTable height set to auto

- src/js/components/InfiniteScroll/InfiniteScroll.js
Infinite scroll fixed for IE,Edge browsers and also tested for electron. 
Page height calculation fixed when InfiniteScroll is triggered on IE and Edge browsers.
Storybook on IE11, MS Edge, Chrome, Safari, Chrome and Electron. 
Storybook
#2901 
No
Yes
Yes
> Infinite scroll fixed for IE,Edge browsers and also tested for electron

- src/js/components/Box/Box.js
fixing the index key used to be more explicit
Box.js
```
<Box align="center" pad="large">
<RadioButtonGroup
name="radio"
options={[{ label: '1', value: '1' }, { label: '2', value: '2' }]}
value={value}
onChange={this.onChange}
{...this.props}
/>
</Box>
</Grommet>
```
run the markup code above on storybook 
RadioButtonGroup is using the key index as well as the StyledBoxGap, hence it causes a key duplication.
this is the error:
```
react-dom.development.js:506 Warning: Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
in div (created by …
```
> RadioButtonGroup key warning

- src/js/components/Diagram/Diagram.js
Fixes IE and Edge compatibility issue for diagram component by replacing rect co-ordinates suitable for IE & Edge browsers.
Fix IE and Edge compatibility issue for diagram component 
Diagram.js
Storybook
Storybook
#2952 
No
Yes
> Fix IE and Edge compatibility issue for diagram component 

- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
update the docs with the default value of size Text 
according to https://github.com/grommet/grommet/blob/f944d4a6ad7e3d9c84ffe2f135d461ffecdd331f/src/js/components/Text/StyledText.js#L7
doc.js
verifying with StyledText
done
no
backwards
> Text - add default size value

- src/js/components/DataTable/Body.js
- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/DataTable/index.d.ts
- src/js/components/DataTable/stories/InfiniteScrollDataTable.js
- src/js/components/DataTable/stories/datatable.stories.js
- src/js/components/Table/stories/InfiniteScrollInTable.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
DataTable - add step prop for onMore loading
doc.js
added a storybook example 
checkout the new story
a second approach to https://github.com/grommet/grommet/pull/3074
#3063
done
yep
> DataTable - add step prop for onMore loading

- src/js/components/Drop/index.d.ts
Drop `target` should not be a required prop. When using `Menu`, passing `dropProps` fail typescript validation when you don't provide `target`, as opposed to the documentation.
N/A
Yes.
Use Menu with a typescript setup, and don't provide `target` for `dropProps`.
No.
N/A
No.
I don't think so.
Yes.
> Make target optional for Drop typescript type

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
Changed Heading to fix an issue with arbitrary size
StyledHeading.js
storybook
storybook
#3091 
no
yes
`max-width: ${levelStyle.medium.maxWidth}`
If a custom theme has been defined and that theme doesn't have a `levelStyle` for `medium`, this will result in an error. Alternatives: Note set any `maxWidth` or define a standard `maxWidth` to be used when `medium` is not available
I tried to stick to https://github.com/grommet/grommet/issues/2435 / https://github.com/grommet/grommet/pull/2436
> Changed Heading to fix an issue with arbitrary size

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/Controlled.js
Fixes the controlled open state of the Select.
There were two solutions to the problem.
1. Use componentDidUpdate
```
componentDidUpdate(prevProps) {
const { open: nextOpen } = this.props;
if (prevProps.open !== nextOpen) {
this.setState({ open: nextOpen });
}
}
```
Eslint doesn't like setting the state in this lifecycle method though and while i didn't look for why i am assuming it has its reasons
2. Turn the component into a function with hooks and useEffect to update the state based on the prop change. 
I opted for solution 2. Most of the code is intact. important parts are happening at the top of the changes were the useEffect and useState calls are. 
There is some noise in snapshots the styling got re-ordered but the styles are normally without a change.
storybook
Added a storybook …
> Fix controlled opened state in Select

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test.js
`Form#update` uses object syntax for `setState`. And initialization of `Form` has multiple `FormField`s with value makes subsequent `setState` calls. Thus I replaced object syntax with callback(updater) syntax.
ref: https://reactjs.org/docs/react-component.html#setstate
Form.js
unit test
no
no
> fix: avoid Form state's race condition

- src/js/components/DropButton/DropButton.js
Changed DropButton to allow caller to pass onClick
DropButton.js
storybook
grommet-design
storybook
grommet-design attaches a click handler to all components it renders to allow the user to select that component. Menu wasn't working because DropButton didn't honor the click handler passed.
no
yes
> Changed DropButton to allow caller to pass onClick

- src/js/components/Video/index.d.ts
removes the default types of HTML video controls, so grommet's custom types will be accepted.
index.d.ts
#3129 
no
no
> Video - removing html prop types from controls

- src/js/components/MaskedInput/StyledMaskedInput.js
Fixes https://github.com/grommet/grommet/issues/3134
https://github.com/grommet/grommet/blob/master/src/js/themes/base.js#L613 happens to be the base theme that needs to be merged with a custom theme.
I used a custom theme at `<MaskedInput />`story of email. When applied the change, custom theme applies fine for extend property.
In `src/js/components/MaskedInput/stories/Email.js`, add:
```
// add
import { deepMerge } from "grommet/utils";
const customTheme = deepMerge(grommet, {
maskedInput: {
extend: () => `
color: red,
`
},
});
// replace
<Grommet full theme={customTheme}>
```
No
Probably IDE autocomplete got in the way and filled up component name MaskedInput while typing.
No
No, there is a no example of themed MaskedInput, if that is useful I can add one in coming week.
Please use …
> modify theme property name to extend MaskedInput component

- src/js/themes/index.d.ts
Include types used in [StyledCheckBox](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox/StyledCheckBox.js)
Signed-off-by: Dimitrios Lytras <dnlytras@gmail.com>
Fixes: https://github.com/grommet/grommet/issues/3126
> types: Add missing CheckBox types

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/Collapsible/README.md
- src/js/components/Collapsible/doc.js
- src/js/components/RoutedAnchor/README.md
- src/js/components/RoutedAnchor/doc.js
- src/js/components/RoutedButton/README.md
- src/js/components/RoutedButton/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Modified usage of props with true value as in priciple,
passing true value in props is not required & it is
enough to pass the prop with no defined value.
It modifies incorrect usage of `{true}`values in props.
`src/js/components/Button/doc.js`: 21 where the first usage is corrected.
I ensured all tests continue to pass and a small change in snapshot has been updated.
After using `<Button primary label='Label' />` button should continue to be a primary button.
None
The only benefit is improved code quality by simpler props representation in code.
Non functional change.
A small change as a part of this PR is in documentation as well to show usage of `primary` prop in `<Button />` component.
No
Yes, it is backwards compatible.
> fix: modify usage of props with true value

- src/js/components/Layer/Layer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
Implements [recommended solution](https://github.com/grommet/grommet/issues/2906#issuecomment-472643372), ensuring that window.document is available before rendering the Layer container. This makes sure the Layer component will succeed in build processes for server side rendering contexts.
Waits for component mount, then accesses dependent document elements, then re-renders Layer component with document elements.
src/js/components/Layer/Layer.js
- Added state for availability of `layerComponent`.
- Moved `originalFocusedElement` and `layerContainer` into `componentDidMount()`
1. Replicated [original issue](https://github.com/grommet/grommet/issues/2906) occurring during Gatsby build
2. Manual testing in Storybook
3. Passes unit tests
4. Performed successful `gatsby build`
[original …
> Fix #2906 - Lazy load Layer container for successful use in SSR contexts

- .eslintrc
- src/js/utils/__tests__/mixins-test.js
- src/js/utils/mixins.js
The previous implementation of `parseMetricToNum` was it modifies "12px 20px" to 1220.
For "12px 20px", `fontAsString.replace(/[^0-9/.]/g, ''` removes all strings leaving "1220" and works what it was specified for.
The problem occurs when this function is used in `StyledTextInput` at [code that decides left padding](https://github.com/crashuniverse/grommet/blob/master/src/js/components/TextInput/StyledTextInput.js#L65). The user, while overriding theme variables for padding tries "12px 20px" imagining that css shorthand syntax is supported, [while documentation suggests only 1 value is supported](https://v2.grommet.io/textinput#global.input.padding). The side-effect is left padding becomes 1220px.
Fixes #3124
It modifies how `parseMetricToNum` works. The new regex `/\d+(\.\d+)?/` to …
> fix: modify implementation of parseMetricToNum mixin

- src/js/components/Menu/Menu.js
Changed Menu to pass more items properties through to Button.
The documentation states that all properties of each object in `items` will be used to construct a Button for that item. Unfortunately, only a few hard coded properties were being passed. This change passes all properties of the items through to the Buttons.
Menu.js
unit
unit
The impetus for this was to support a Download menu item where the Button needed a `download` property passed through.
no
yes
> Changed Menu to pass more items properties through to Button

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/Button/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
We could alternatively turn this into a union type and make the `target` valid only when `href` is provided. Unfortunately this would require us to change the `export interface` to `export type`, which would be a breaking change for whoever currently inherits the ButtonProps interface.
Resolves: #3158
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
Extends the typings of the Button component to support the `target` html property, so that it can be used when the `href` property is provided and an `<a>` in rendered.
I linked that to my project with TS v3.5.1 and I was able to use the `target` property as expected.
Yes, but I think that I did my part
Probably not.
It's backwards compatible.
> Button: Extend typings to include the `target` property

- src/js/components/DataTable/Searcher.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/buildState.js
`DataTable` provides user input with `RegExp` constructor directly.  But we should escape user input.
`DataTable`'s bug fix 
`buildState.js`
snapshot
storybook
> fix(DataTable): make search field accept regexp special charactors

- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
Makes all MaskedInput component props available in event.target addressing [issue #3137](https://github.com/grommet/grommet/issues/3137).
MaskedInput.js
- Local project utilizing modified MaskedInput component
- Unit tests written in MaskedInput-tests.js
- NOTE: Original tests were checking for the event argument passed to a mock onChange function with Jest's `.toHaveBeenCalledWith()`. After changing the implementation, the `.toHaveBeenCalledWith()` failed because now passing a SyntheticEvent instead of the React value setter. I think we want to be spying on whether the new `setValue` method is being called, or more specifically the `dispatchEvent()`, but was unable to get this functional in the test implementation. The current tests …
> Fix for Issue 3137 - Making all event.target props available

- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
Fixes #3112
Signed-off-by: Priya Ranjan Singh <mail@priyaranjan.net>
This PR introduces conditions to check for already focused elements in contents of Layer and avoids stealing focus if there is any. In absence of any focused elements in contents of Layer, it continues to assign focus to the hidden anchor element.
`src/js/components/Layer/LayerContainer.js` has changes in `componentDidMount` lifecycle.
In the `Form` story that renders `<FormLayer />`, placing an `autoFocus` to `<TextInput />` component. The component finally looks to be `<TextInput autoFocus />`. When layer container is visible, `TextInput` has focus. In absence of `autoFocus` prop, the hidden anchor continues to have the focus.
On this branch, if we add `autoFocus` prop in story …
> fix: fix focus behavior of Layer in presence of focusable contents

- src/js/components/Select/README.md
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/doc.js
- src/js/components/Select/stories/Basics.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
Addresses https://github.com/grommet/grommet/issues/3157 by providing the ability for a user to style the open state of the select.control by extending the `styled(DropButton)`.
Select.js
- Added `'modifies select control style on open'` test to Select-test.js
- Applied to local project, implementing Select with custom theme for select.control.open
Apply a custom theme (example below) to your Grommet Select component and add your own styling to `select.control.open`.
```
import { grommet } from "grommet/themes";
import { deepMerge } from "grommet/utils/object";
export default deepMerge(grommet, {
global: {
font: {
family: "Helvetica, sans-serif"
}
},
select: {
control: {
extend: props => `
height: 60px;
background: purple;
`,
open: {
background: "lightgrey",
},
},
container: {
extend: { …
```
> Enhance 3157 - Extend the "select.control" themability when the Select component is open

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
`<TextInput/>` uses a `<Keyboard/>` to listen for keydowns on the escape key to close the suggestions drop. When that happens, it stops the event's propagation in order to prevent other things listening for the escape key from doing their thing, like layers who might close on escape. This is good if you are using suggestions on a `<TextInput/>`, but bad if you aren't. If you want to have the escape key trigger other behaviour from a `<TextInput/>` before this change, it's not possible because the event is always stopped from propagating.
This changes `<TextInput/>` to only stop the propagation of the event when the suggestions drop is actually open, and otherwise, let the event through.
I came across this issue when trying to use `TextInput` to power a cell in an Excel style datasheet …
> Prevent TextInput from stopping all escape events from propagating

- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/doc.js
- src/js/components/MaskedInput/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed MaskedInput to improve focus management.
These changes do a better job of detecting when focus is lost. Previously, the component would think it had lost focus when in fact the focus was on the Drop container.
Also, allow mask options to be numbers.
MaskedInput.js
storybook with Safari, Firefox, and Chrome.
same
automatic
no
> Changed MaskedInput to improve focus management

- src/js/themes/base.js
There's a comment in the base theme which implies that the way to set the global font is to set a value for `theme.global.font.face`; this should actually be `theme.global.font.family`.
Tested by creating a new theme using `base` as a starting point, setting `theme.global.font.family`, and checking the result (which is [how the `grommet` theme does it](https://github.com/grommet/grommet/blob/master/src/js/themes/grommet.js#L11)).
> Fix comment in base theme

- src/js/components/Carousel/Carousel.js
- src/js/components/Carousel/README.md
- src/js/components/Carousel/__tests__/Carousel-test.js
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/Carousel/carousel.stories.js
- src/js/components/Carousel/doc.js
- src/js/components/Carousel/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Signed-off-by: Luis Deschamps Rudge <luis@luisrudge.net>
Adds `initialActiveIndex` prop to the `Carousel` component. This allows the developer to set what's the first image being shown in the Carousel.
Carousel.js
Unit test + storybook
Storybook
Super useful for scenarios that you have a lot of thumbnails and you want to open a Carousel with the active item being the item that was just clicked (today, it always starts from scratch).
#3199 
Yes (I think I already did?)
Yes
> Add initialActiveIndex to Carousel

- src/js/components/AccordionPanel/README.md
- src/js/components/AccordionPanel/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Signed-off-by: Lucian <lucian.buzzo@gmail.com>
The color of the icon used in an `AccordionPanel` can be themed, but this is undocumented, see https://github.com/grommet/grommet/blob/master/src/js/components/AccordionPanel/AccordionPanel.js#L74
This PR adds the documentation for the icon color theme prop.
This is a fairly small change, so it should be easy to review.
The docs were regenerated and manually checked.
Generate the docs and check that the output makes sense and doesn't contain any typos
N/A
Possibly https://github.com/grommet/grommet/issues/2690
This PR updates the docs already, but I imagine the site will need to be updated
No
This is a backwards compatible change
> AccordionPanel: Document icon color themeability

- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/doc.js
- src/js/components/MaskedInput/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed MaskedInput to allow number value, like TextInput
doc.js
grommet-theme-designer
automatic
yes
> Changed MaskedInput to allow number value, like TextInput

- src/js/components/MaskedInput/index.d.ts
This fixes issue #3213.
It's a one-liner so...
Let me know how you want to test this. I don't see `typescript` included as a dev dependency so I'm not sure how you are testing type definitions.
If you could reproduce the type error in #3213, then with this patch the error should be gone.
`size: string & number` leads to an empty set.
#3213.
I don't see any documentation regarding types so probably not?
Why not.
It makes `MaskedInput` from not usable with TypeScript to usable, so... "unbreaking" change?
> Fix type signature of MaskedInput

- src/js/components/MaskedInput/index.d.ts
This mainly fixes issue #3218.
Only locally with my vscode intellisense.
Previously, specifying `plain` to `MaskedInput` would throw a type error, as shown in the screenshot provided in issue #3218.
Now the type error should no longer exist.
Instead of using `'plain' | 'size'` in `Omit`, I decided to use `keyof MaskedInputProps` instead to get rid of any potential type collisions once and for all.
(Originally I thought `placeholder` was also missing its type, since I was cross-referencing the interface of TextInput, but then I realized it's used differently in `MaskedInput`. Please ignore the fact that some commits involves `placeholder`.)
#3218.
https://v2.grommet.io/maskedinput should probably mention the option `plain`.
Why not.
Should be compatible. It makes the option `plain` usable …
> Add missing prop type `plain` for MaskedInput.

- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
This PR was attempting to fix #3216, but apparently, the functionality was already there. so I just added a corresponding test to the one that exists on TextInput.
the test file.
#3216
no
no
> MaskedInput - Event propagation onEsc

- src/js/components/Layer/StyledLayer.js
Signed-off-by: Stéphane Klein <stephaneklein221@gmail.com>
It fixes ie11 compatibilty for the layer component.
Automated tests.
#3221 
No.
Not sure.
It's backwards compatible.
> Use string method supported in ie11 (closes #3221)

- src/js/components/Tab/README.md
- src/js/components/Tab/doc.js
- src/js/components/Tab/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Fixes typescript issues
/Tab/index.d.ts
I branched out grommet with these fixes and created a react app with passing in 
<Tab title={<Text>Foo</Text>}><Text>Foo</Text></Tab>
to test for the error
#3193 
done
> [TS] Tab - omit the HTML attribute title type

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
This adds to the proptypes for opacity in background
Box/doc.js
Branched out grommet with this fix and testing using 
background={{color: 'green', opacity: '0.2'}}
closes #3236 
already done
> Added String to propTypes to be accepted for opacity.

- src/js/components/Accordion/index.d.ts
- src/js/components/Anchor/index.d.ts
- src/js/components/Box/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Calendar/index.d.ts
- src/js/components/Carousel/index.d.ts
- src/js/components/Chart/index.d.ts
- src/js/components/Clock/index.d.ts
- src/js/components/DataTable/index.d.ts
- src/js/components/Distribution/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Image/index.d.ts
- src/js/components/Layer/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Meter/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Table/index.d.ts
- src/js/components/Tabs/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
- src/js/utils/index.d.ts
This PR is taking care of the overlapping of Margin
no
> Moved Margin to one file to clean up TS

- src/js/components/Box/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/utils/index.d.ts
This PR starts the clean up of the over use of type definitions with alignContent
no
> TS - Clean up align content issue3237

- src/js/components/Accordion/index.d.ts
- src/js/components/Anchor/index.d.ts
- src/js/components/Box/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Calendar/index.d.ts
- src/js/components/Carousel/index.d.ts
- src/js/components/Chart/index.d.ts
- src/js/components/Clock/index.d.ts
- src/js/components/DataTable/index.d.ts
- src/js/components/Distribution/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Image/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Meter/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Table/index.d.ts
- src/js/components/Tabs/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
- src/js/utils/index.d.ts
This PR is taking care of the overlapping of SelfAlign
no
> TS - Clean up align self issue3237

- src/js/components/Anchor/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/RangeSelector/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/utils/index.d.ts
> TS - ColorType clean up

- src/js/components/Carousel/Carousel.js
Changed Carousel to fix an issue with `fill` propagation.
If Carousel is used in a large outer container with `fill`, the children should be given a full height context, so they can align however they want to.
Carousel.js
Carousel with small images.
same
I came across this when using a Carousel with small images that I wanted to have centered.
no
yes
should be backwards compatible
> Changed Carousel to fix an issue with fill propagation

- src/js/components/Accordion/index.d.ts
- src/js/components/Anchor/index.d.ts
- src/js/components/Box/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Calendar/index.d.ts
- src/js/components/Carousel/index.d.ts
- src/js/components/Chart/index.d.ts
- src/js/components/Clock/index.d.ts
- src/js/components/DataTable/index.d.ts
- src/js/components/Distribution/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Image/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Meter/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Table/index.d.ts
- src/js/components/Tabs/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
- src/js/utils/index.d.ts
This PR cleans up the A11yTitle
no
> TS- CleanUpA11yTitle

- src/js/components/Anchor/README.md
- src/js/components/Anchor/anchor.stories.js
- src/js/components/Anchor/doc.js
- src/js/components/Anchor/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
This PR adds to the anchor docs that allows for the disabled property 
also added in the disabled property to TS file
Anchor/doc.js
closes issue #3242 
auto
no
> Added disabled prop to anchor

- src/js/components/Accordion/index.d.ts
- src/js/components/Anchor/index.d.ts
- src/js/components/Box/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Calendar/index.d.ts
- src/js/components/Carousel/index.d.ts
- src/js/components/Chart/index.d.ts
- src/js/components/Clock/index.d.ts
- src/js/components/DataTable/index.d.ts
- src/js/components/Distribution/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/Image/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Meter/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Table/index.d.ts
- src/js/components/Tabs/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
- src/js/utils/index.d.ts
This PR cleans up the GridArea
no
> TS Cleanup GridArea

- src/js/components/Grid/StyledGrid.js
Update gap property of grid to allow css sizes.
If grid-gap prop is not a known size, interpret it as css.
See https://v2.grommet.io/grid -> "any css size" for gap
Didn't open an issue, but can if needed
No, this PR adjusts the implementation to the doc
Maybe? <Shimi> Yes, it should.
I'd argue it's backwards compatible, as it fixes a bug.
> Fix grid-gap

- src/js/components/Grid/grid.stories.js
Add responsive Grid example to stories
This PR adds to stories an example of how to build two types of responsive Grids:
1. A grid with a known number of components, using areas,
2. A grid with an unknown number of components.
Both using ResponsiveContext.
`yarn test`
Check if the example got into stories and resize the screen to see if the Grids responses correctly:
1. For the first Grid with 3 elements:
a. For size small, the three elements should be one on top of the other.
b. For size medium, there should be one element on top, two elements underneath it taking 50% of the space each.
c. For size large, the three elements should be inline.
2. For the Grid with an unknown number of elements, the boxes containing animal names should resize and/or got to the next line when reducing the …
> Signed-off-by: imad <imad.messelmani@live.com>

- src/js/components/TextInput/index.d.ts
Typescript builds started failing due to a misspelled type import
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Fix type import for PlaceHolderType

- src/js/index.d.ts
This PR fixes a TS error when importing themes from grommet
js/index.d.ts
Also switch between grommet and dark theme to test both 
```
import { Grommet, grommet, dark, } from "grommet";
function App() {
return (
<Grommet full theme={dark}>
</Grommet>
```
#3251 
no
no
> Ts themefix#3251

- src/js/components/Grid/index.d.ts
- src/js/components/Heading/index.d.ts
- src/js/components/MaskedInput/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Meter/index.d.ts
- src/js/components/Paragraph/index.d.ts
- src/js/components/RoutedAnchor/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Table/index.d.ts
- src/js/components/Tabs/index.d.ts
- src/js/components/Text/index.d.ts
- src/js/components/TextArea/index.d.ts
- src/js/components/TextInput/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
- src/js/utils/index.d.ts
This PR cleans up the textAlign type definitions and puts all component ts prop types in alphabetical order.
Manually tested by branching out to a typescript project.
Issue #3237
> TS - Clean up textAlign

- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
Allows users to use up/down arrow keys to navigate within a masked input.
js/components/MaskedInput/MaskedInput.js
Testing has been done in Storybook to ensure changes function correctly.
Storybook can be used as visual reference to make sure the keyboard can be used to achieve expected interactions.
Previously, when arrow keys were used, the background color of the active option would not change, so the user would not know which element of the drop was selected.
Issue #3225
No.
Yes, it is backwards compatible.
> Allow up/down arrows to navigate within MaskedInput.

- src/js/components/FormField/index.d.ts
Fix a bug in FormField typings introduced by https://github.com/grommet/grommet/commit/396e0129ac74575d16be710092efc514d4267bb4.
Not sure why it hasn't been spotted yet.
This is a pretty trivial fix ;)
No.
Probably not.
Not a breaking change.
> [FormField] Add missing import in ts typings

- src/js/components/Layer/Layer.js
- src/js/components/Layer/README.md
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Layer to un-animate on exit.
The trick in this is that it clones the DOM element before unmounting it, reverses the animation, and starts a timer to remove the clone when the animation ends.
Layer.js
Center and Notification Layer stories on Safari, Chrome, and Firefox
more flavors and browsers
#2387 
no
yes
> Changed Layer to un-animate on exit

- src/js/components/Paragraph/Paragraph.js
- src/js/components/Paragraph/StyledParagraph.js
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
In #3222, we added the `fill` property. Styled Components passes all properties through to their DOM children. However, because `fill` isn't in react's `camelCase` format, React assumes this must be a native DOM property and throws a warning ("Received `true` for a non-boolean
attribute `fill`.)
The fix means consuming the `fill` prop on `Paragraph` and converting it to `fillProp` when calling the `StyledParagraph` object. This is similar to the fix we use for `color` / `colorProp`.
Paragraph & StyledParagraph
Relaunched Storybook, checked console, checked tests.
Storybook => Paragraph
#3222 
No
No
**DCO In Commit Log**
> fix(Paragraph): Removes console warning for passing `fill` to `p`

- src/js/components/DataTable/Cell.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/buildState.js
Changed DataTable to allow columns properties to traverse data object properties.
For example, if a datum is `{ a: { b: 'hi' } }`, then you can do: `columns={[{ property: 'a.b' }]}`.
buildState.js
Added unit test.
Used with new grommet-data in progress.
unit test
This is part of some DataTable updates coming down the pipe, trickling in in smaller bits.
yes
> Changed DataTable to allow columns properties to traverse data object properties

- src/js/components/MaskedInput/index.d.ts
Update onBlur type to be more specific to the event 
maskedInput/index.d.ts
manually 
write onBlur function in TS app 
We are using ``` JSX.IntrinsicElements['input'] ``` this includes the 
HTML input elements so we just need to add the react event handling
of focus event
#3165 
no
no
> Changed onBlur type to match with react focusevent

- src/js/utils/colors.js
This PR fixes the `opacity` param of `getRBGA` being ignored when using `0`
I discovered this issue when playing with a dynamic background opacity like below:
```jsx
const opacity = myDynamicValueBetweenZeroAndOne;
return <Box background={{ color: 'primary', opacity }} />
```
Had to change it to
```jsx
const opacity = `${myDynamicValueBetweenZeroAndOne * 100}%`;
return <Box background={{ color: 'primary', opacity  }} />
```
> fix(utils/colors): prevent opacity being ignored when equal to zero

- src/js/components/Keyboard/index.d.ts
This changes the TS definitions for all Keyboard props from ((...args): any => any) to ((event: React.KeyboardEvent<HTMLElement>) => void).
src/js/components/Keyboard/index.d.ts
Testing has been done in a local TS project. Keyboard was wrapped around content in a local TS file, and the type definitions were checked for the different keyboard interactions. First, I created a separate handler and defined the event type to match the TS definition. I expected there to be no errors, and there weren't. Then, I tried breaking it by providing the function with different types such as a string to be sure it would flag this error. It did.
In a project with TS added.
When TS definitions are "any", it defeats its purpose. In this case, the event is a KeyboardEvent and this will happen on an HTML …
> Adjust Keyboard TS Definitions

- src/js/components/WorldMap/index.d.ts
This changes the TS definition for onSelectPlace prop from ((...args): any => any) to ((place: number[]) => void).
src/js/components/WorldMap/index.d.ts
Testing has been done in a local TS project. The pattern for WorldMap from the grommet storybook was copied into the local project, and the type definitions were checked. First, I logged the value of the "place" parameter to confirm that is was, in fact, an array of numbers ([latitude, longitude]). Then, I tried breaking it by providing the function with different types such as a string to be sure it would flag this error.
In a project with TS added.
When TS definitions are "any", it defeats its purpose. In this case, the argument received is an array of numbers (latitude and longitude) for the place coordinates. Therefore, a number array …
> Adjust onSelectPlace type definition

- src/js/components/DataTable/stories/datatable.stories.js
- src/js/components/FormField/stories/TextInput.js
- src/js/components/Select/stories/ObjectMultiple.js
- src/js/components/Select/stories/Search.js
- src/js/components/Select/stories/SimpleMultiSelect.js
Escapes special characters that were printing errors to the console in stories that contain regular expressions.
Any of the story files with changes.
Special characters were entered into the text input field of each changed file to ensure no errors were printed regarding invalid regular expressions.
Open the console while engaging with any of the changes stories, and enter any special characters for regular expressions ( [ \ ^ $ . | ? * + ( ) ).
An error was appearing in the console if a user typed a character that was considered a "special character" by regular expressions.
None. This was just to test the recent release.
No.
No.
> Escape special characters for stories with regular expressions.

- src/js/components/Menu/Menu.js
This PR fixes the issue with padding when a menu component is set to plain
src/js/components/components/Menu/Menu.js
I did a quick test (Google Chrome), with plain set to true and with no plain property set. The extra padding has disappeared in the former case.
Set plain={true} for a menu component and see the decrease in the height and width of the box around the component.
I needed to have a thin header on my page, but the menu component does not allow it as it is surrounded with a Box with fixed 'small' padding.
No
Screenshots (if appropriate) …
> Removed padding with a plain menu

- src/js/components/RangeSelector/RangeSelector.js
This PR fixes the issue with dragging the range selector on Edge.
src/js/components/RangeSelector/RangeSelector.js
These changes have been tested using Browserstack on Edge. First, I recreated the issue and saw that there was difficulty when dragging the ends of the range selector. The value jumped around in a way that was not accurate to my mouse motions. Then, after making changes, I tested again and saw that the range selector was behaving as expected (would move to the correct coordinates according to my mouse motion).
Using Microsoft Edge and the Grommet storybook example of "Thin".
A similar fix was done on this issue: https://github.com/grommet/grommet/pull/3078/files
The values of x and y need to be switched to left and top, respectively.
Issue #3295 
No.
No.
Yes, backwards …
> Fix Edge RangeSelector Issue

- src/js/components/Drop/index.d.ts
- src/js/components/Keyboard/index.d.ts
- src/js/components/Layer/index.d.ts
- src/js/utils/index.d.ts
Extracts Keyboard type into singe variable. Previously, many lines were copy and pasted. This change places the definition in a single place which will makes any future adjustments for streamline.
src/js/utils/index.d.ts
Testing has been done on local TS project.
On a project with TS enabled.
Issue #3165 
No.
No.
> Extract keyboard type to single variable.

- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Fixing the error showing in the log for `DataTable` test
```
console.error node_modules/prop-types/checkPropTypes.js:20
Warning: Failed prop type: checker is not a function
in DataTable
```
src/js/components/DataTable/doc.js
Running `yarn test` before this fix will yield the above error and after the fix the error disappear
N/A
N/A
```
console.error node_modules/prop-types/checkPropTypes.js:20
Warning: Failed prop type: checker is not a function
in DataTable
```
Yes
No
> Fix error showing in log for DataTable test

- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Fixing an error that showed in the logs for `DataTable` `replace` prop
```
console.error node_modules/prop-types/checkPropTypes.js:20
Warning: Failed prop type: Invalid prop `replace` of type `boolean` supplied to `DataTable`, expected `function`.
in DataTable
```
`src/js/components/DataTable/doc.js `
Running `yarn test` before the fix and running `yarn test` after the fix
N/A
N/A
Yes
Yes
> Fix prop type for 'replace' in DataTable to be bool and not a func

- src/js/components/RadioButtonGroup/radiobuttongroup.stories.js
As requested in https://github.com/grommet/grommet/issues/3394 the story in RadioButtonGroup is converted to use the `useState` hook.
The story in RadioButtonGroup is converted to a functional component using the `useState` hook.
Check the RadioButtonGroup story
Visual testing in storybooks
Visual testing in storybooks
As requested in https://github.com/grommet/grommet/issues/3394
https://github.com/grommet/grommet/issues/3394
No
No
Yes
> Convert RadioButtonGroup story to hooks

- .circleci/config.yml
Currently, all PRs (except for my PRs) are breaking on the chroma job because the environment variables are not being fetched to the build process, for example:
Passed build: https://circleci.com/gh/grommet/grommet/6900?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Failed to build: https://circleci.com/gh/grommet/grommet/6880
The passing build (in green) is able to fetch the environment variables, hence the build passes.
The failed build doesn't.
I'm still trying to investigate what may cause this behavior, I made an attempt to update the node container #3405 , and although it works for my PR it doesn't work on others (e.g I tried it on https://github.com/grommet/grommet/pull/3404 as well, but it was still failing)
Until I'll resolve this issue and …
> CircleCi - removing dependency from environment variables

- src/js/components/CheckBox/stories/CustomToggle.js
refactor `src/js/components/CheckBox/stories/CustomToggle.js` using hooks
#3394 
no
no
> refactor custom toggle using hooks

- src/js/components/Select/stories/CustomSearch.js
It fixes a bug (#3247) in a demo story: https://storybook.grommet.io/?path=/story/select--custom-search.
When you open Select, type a search query, click outside and then open Select again, a list of options for the query is shown, although the search input is empty.
The fix is done by reseting the list of matched options when Select gets closed (and resets).
Try to reproduce the bug and then run my code, if necessary.
I'm just reseting the list of options on Select close.
Clone the forked repo, `yarn install`, `yarn storybook`, open http://localhost:9001/?path=/story/select--custom-search and compare the behavior with current one.
Nope.
#3247
None.
Nope.
Nope.
It's fully compatible, only demo code was edited.
> Fix Select with search issue (#3247)

- src/js/components/CheckBox/index.d.ts
- src/js/components/Keyboard/index.d.ts
- src/js/components/RangeInput/index.d.ts
- src/js/components/SkipLinks/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/TextArea/index.d.ts
This PR updates the type definitions for components that have been refactored to hooks for Hacktober Fest. Before the changes were made, there were some components that had been refactored to hooks but their type definitions still said `React.ComponentClass`. This changes those to say `React.FC`.
Any of the index.d.ts files listed in files changed.
These changes have been tested in a local typescript project. While the components that had mismatched type definitions were not being flagged in the editor, some where not rendering onto the screen. Once their type definitions were updated, the components all work as expected.
In a local typescript project, use any of the components whose types have been updated in the PR. There should be no flags in the editor, and the components should …
> Update type definitions for Functional Components

- src/js/components/Layer/Layer.js
Fixes #3359.  
Read the diff.
Verified that after applying this fix to my project, the issue is resolved.
Layer component regression tests.
General background:
`querySelector` operates on a DOM element, not a React element. So in some cases a race condition can occur where the DOM element no longer exists because the component is no longer mounted.
Specific example:
Build a Single Page Application in React + Grommet + React Router, like
```jsx
<Route render={({ location }) => (
<TransitionGroup>
<CSSTransition
timeout={100}
key={location.key}
exit={false}>
<Switch location={location}>
<Route exact path={'/a'}              render={(props) => <PageA {...props} />} />
<Route exact path={'/b'}              render={(props) => <PageB {...props} />} />
</Switch>
</CSSTransition> …
```
> Fixes #3359

- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
This PR creates a new test for when a user tabs through all menu items until the menu closes.
src/js/components/Menu/__tests__/Menu-test.js
Jest's debug feature was used to view the DOM structure before the menu opens, when the menu opens, and when the menu was expected to be closed again. Also, the test utilizes the `    expect(document.getElementById('test-menu__drop')).toBeNull();` to confirm that the menu has closed.
This behavior (tabbing through menu until it closes) was not reflected in any of the tests, so it needed to be added.
No.
No.
Yes, it is backwards compatible.
> Create test for when user tabs through menu until it closes

- src/js/components/Box/index.d.ts
- src/js/components/Drop/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/utils/index.d.ts
This PR extracts `elevation` and `justifyContent` into variables that can be used across various components.
src/js/utils/index.d.ts
These changes have been tested in a local TS project on the components that have these properties to ensure it only accepts the types defined in the utils/index.d.ts file.
In a local TS project, use one of the components that has these props and put a value that matches the prop type (no flag should appear and the app should render) and then provide a value that doesn't match the prop type (should cause an error).
#3237 
No.
No.
> TS Extraction: justifyContent & Elevation

- src/js/utils/colors.js
Removes a dead link from `src/js/utils/colors.js`
`src/js/utils/colors.js`
None needed
Not needed
No context, was just checking out codebase and clicked on link for some more info but it took me to a go-daddy page so guessing domain was not kept up to date.
Nope
Nope
> Removed dead link

- .circleci/config.yml
This PR is a complete solution for https://github.com/grommet/grommet/pull/3512
Since we only need to run `--auto-accept-changes` (that accepts the chromatic changes) on the master branch, I've created a new job of `chromatic-accept` that will run only on master after a PR is merged, hence will automatically accept the changes on master so the baseline will be updated.
The solution offered on #3512 will run `--auto-accept-changes` for every feature branch and make the changes hard to catch.
With this PR solution, the job of chromatic will run as usual for feature branches, but the job that will run on the master branch will be chromatic-accept that will accept changes on master and fix the changed snapshots on the baseline.
I'll be merging this PR to make sure the behavior I'm …
> Changed circleci to accommodate chromatic changes

- src/js/all/stories/typescript/AllComponents.tsx
- src/js/components/Box/index.d.ts
- src/js/components/Distribution/README.md
- src/js/components/Distribution/doc.js
- src/js/components/Distribution/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/utils/index.d.ts
While working on AllComponents.tsx, I noticed the `basis` prop is missing from the typescript interface definition as well from the docs.
According to https://github.com/grommet/grommet/blob/27e372be78c559e114ecaf541d399b336872f910/src/js/components/Distribution/Distribution.js#L44
the `basis` value is derived from props, hence needs to be documented as a prop along with its typings.
This PR is addressing both missing docs and typescripts, and the ts compilation of AllComponents.tsx is passing as expected.
> Distribution - Added docs and typescript support for basis prop

- src/js/components/Button/index.d.ts
This PR removes the type definition for Button onClick type definition and just leaves the definition from the intrinsic elements since we are not adding any new/different behavior.
src/js/components/Button/index.d.ts
This has been tested on a local TS project with the following:
```
<Button label="Click Me!" onClick={() => alert('clicked!')} />
```
With the above code in a local TS project.
We are not adding any new/different behavior to the onClick handler from what the intrinsic element already provides, so we should remove it.
#3165 
No.
No.
> Just leave onClick from Intrinsic Elements for Button

- src/js/components/Anchor/index.d.ts
This PR removes the type definition for Anchor onClick type definition and just leaves the definition from the intrinsic elements since we are not adding any new/different behavior.
src/js/components/Anchor/index.d.ts
This has been tested on a local TS project with the following:
```
<Anchor icon={<Add />} href="https://v2.grommet.io/components" target="blank" onClick={(event) => console.log(event)}/>
```
With the above code in a local TS project.
We are not adding any new/different behavior to the onClick handler from what the intrinsic element already provides, so we should remove it.
#3165 
No.
No.
> Remove onClick and leave intrinsic for Anchor

- src/js/components/Button/stories/Custom.js
- src/js/utils/background.js
Changes the text color to use normalizeColor when the theme uses a dark background. 
Currently, if you apply on the theme:
```
button: {
color: { dark: 'accent-1', light: 'dark-2' },
},
```
The dark text color wouldn't be used as expected, because the string `accent-1` isn't normalized to actual CSS color (i.e. #6FFFB0)
But if you will try to use (which has the same colors as the above)
```
button: {
color: { dark: '#6FFFB0, light: 'dark-2' },
},
```
This will work as expected, since the dark color is already provided in an acceptable CSS format.
This PR fixes the text color to work on both of the scenarios presented above.
An example of this use case is added to Button/stories/Custom.js, the Button is primary hence should use the dark text …
> Changed text color to use normalizeColor when background is dark

- src/js/components/FocusedContainer.js
Fixed FocusedContainer hook issue
storybook and unit
storybook
We were seeing lint warnings without this:
/home/circleci/grommet-ci/src/js/components/FocusedContainer.js
53:6  warning  React Hook useEffect has missing dependencies: 'hidden', 'removeTrap', and 'trapFocus'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
no
no
> Fixed FocusedContainer hook issue

- .eslintrc
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- yarn.lock
Updating dependencies resulted in linter and snapshots changes.
The linter failures were due to [react/sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md), which is regarding the orders of elements on Class components. I decided to disable this rule since we are getting away from Class components by moving to hooks, and retro fixing how the Classes were built is tedious work (I gave it a try and decided it is not worth it).
Regarding the snapshots changes, class names had been changed but I didn't notice any changes that require special attention.
Let me know if that works.
> Updated dependencies

- src/js/all/stories/Focus.js
- src/js/all/stories/typescript/Focus.tsx
Following up on some slack requests for customization of Focus color via theme.
Added showcase support with typescript.
Tested on storybook.
@ANDRESROMEROH FYI
> Added stories for focus color customization

- package.json
- src/js/components/Grommet/Grommet.js
- src/js/components/Select/StyledSelect.js
- src/js/components/TextInput/TextInput.js
- src/js/utils/styles.js
- yarn.lock
Grommet currently uses external package for some of its utility functionalities, util functions as:
* `colorIsDark(...)`
* `sizeStyle(...)`
This PR is removing the dependency of the package by:
* Relying on the already existing util function of `colorIsDark(...)` from utils package. (functions are operating/implemented in the same way)
* Added it's own `sizeStyle(...)` function to styles.js, and removing the dependency of the external util function.
> Dependency removal of 'grommet-styles'

- src/js/components/Chart/Chart.js
- src/js/components/Chart/README.md
- src/js/components/Chart/doc.js
- src/js/components/Diagram/Diagram.js
- src/js/components/Diagram/README.md
- src/js/components/Diagram/doc.js
- src/js/components/Meter/README.md
- src/js/components/Meter/doc.js
- src/js/components/Meter/utils.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Remove `theme.global.graph` and added ability to use `theme.global.colors.graph-*`.
`theme.global.graph.colors` didn't lend itself to making graph keys easy enough. So, removing this, which hasn't been part of an official grommet release yet, thankfully.
base.js
unit
theme designer
unit
no
yes
> Remove theme.global.graph and added theme.global.colors.graph-*

- webpack.config.babel.js
Make styled-components external.
grommet-designer using react, react-do, styled-components, grommet, and grommet-icons all loaded via `<script />` tags.
no
yes
> Make styled-components external.

- src/js/components/Box/Box.js
- src/js/components/Box/StyledBox.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
Changed Box to fix an issue with background color darkness.
Specifically, Box was updating the ThemeContext to contain itself, and therefore using the darkness of the Box to influence the Box's styling. This change moves the ThemeContext resetting to apply to only the children of Box. So, `theme.dark` for StyledBox refers to the context the Box is in while `theme.dark` for the children of Box reflects the background of the Box.
One note on the RadioButton snapshot changes, the snapshots now look correct, with the background of the children reflecting the checked state. I don't think we reviewed the styling details of the previous snapshots enough.
Box.js
grommet-designer with latest HPE theme and a variety of color mixes.
storybook
see above
no
yes
> Changed Box to fix an issue with background color darkness

- src/js/components/RadioButtonGroup/RadioButtonGroup.js
Changed RadioButtonGroup to set option ids based on group id.
This makes it easier for callers to not have to pass object to the `options` prop of RadioButtonGroup and just set an `id` for the group.
no
yes
> Changed RadioButtonGroup to set option ids based on group id

- src/js/components/Layer/LayerContainer.js
This fixes the issue in which a non-modal notification may appear in the corner of the app and starts stealing keystrokes from a user active in an existing window.
> Dont steal keystrokes from the user if the layer is not modal.

- src/js/components/Box/stories/Background.js
- src/js/utils/background.js
This PR fixes how low opacity backgrounds control the text color that appears on them.
src/js/utils/background.js
Stories were added to test how this would affect text on light and dark backgrounds.
Use stories Box Background.
When low opacities were used for backgrounds, the background behind them should drive if text renders as light or dark. This currently wasn't being done, so in some cases, text on dark backgrounds was being rendered dark.
N/A
No.
No.
> Fix how low opacity backgrounds affect text color

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/stories/Placeholder.js
- src/js/components/TextInput/stories/StyledPlaceholder.js
Fix a bug when a React.node is passed at placeholder props in TextInput.
Created a isInputEmpty flag in TextInput state to not render a StyledPlaceholder when a React.node is passed by props in placeholder and the input value is empty.
TextInput.js
Placeholder Story TextInput
StoryBook
no
https://github.com/grommet/grommet/issues/3657
|Before|After|
|-|-|
|<img src="https://i.imgur.com/wZ78xbZ.gif" width="300"/>|<img src="https://i.imgur.com/mCkgGel.gif" width="300"/>|
yes, a story  was added in TextInput
yes, 'cause it's a bug a fix.
no
> fix custom placeholder bug (#3657)

- src/js/components/FormField/FormField.js
This PR is coming from a slack request:
https://grommet.slack.com/archives/C04LMHN59/p1579558921032600
>srallen 3:22 PM
>I updated to styled-components v5 today and then started getting test failures with components using Grommet’s FormField . The line that throws is https://github.com/grommet/grommet/blob/362b1a3d4a8266d0cc3d9e5f9e8d21a51c8fbb39/src/js/components/FormField/FormField.js#L33
>specifically the issue is that I’m trying to test in isolation, but since the theme is not defined, a type error is thrown
If I wrap the component with Grommet with a theme prop, it fixes the type error, but it can interfere with using shallow rendering with enzyme, like trying to use enzyme’s setProps API method for instance.
It seems like there needs to be a existential check there for the theme? …
> Changed FormField theme extend reference

- src/js/components/Form/__tests__/Form-test.js
- src/js/components/Form/stories/Submit.js
- src/js/components/FormField/FormField.js
- src/js/components/FormField/README.md
- src/js/components/FormField/doc.js
- src/js/components/FormField/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed FormField.validate to accept an array.
This allows supplying separate regexps with different messages for each of them.
This is a first step towards a set of updates coming to Form/FormField.
index.d.ts
storybook, unit
manual
automatic
yes
> Changed FormField.validate to accept an array

- src/js/components/Button/StyledButton.js
- src/js/utils/colors.js
- src/js/utils/styles.js
Related to #3667, I checked the latest master against my branch with styled-components v5 and had a few more TypeErrors when running automated tests where we had a Button component styled using the styled HOC, `styled(Button)`. 
Using theme object / context API is preferable, but this particular case isn't updated to do that yet.
This PR adds safety existential checks for the theme object where I was getting additional TypeErrors. 
The changes are contained in the `StyledButton.js`, `colors.js`, and `style.js` utility functions files.
No additional tests have been added. Existing automated tests pass with the changes.
The Button stories in the storybook continue to work. Another option is trying to extend the Button styles using `styled()` yourself.
The TypeErrors were occurring after …
> Check for theme existence for styled-components v5 compatibility

- src/js/components/Diagram/index.d.ts
- src/js/components/Diagram/stories/typescript/Connections.tsx
The issue is coming from slack https://grommet.slack.com/archives/C04LMHN59/p1579887376150400
Fixing types of the connections object and adding the example shared on slack.
> [TS] Fixed typing for Diagram connections

- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- yarn.lock
Fixes bug experienced when a user provides their own `ref` to `<TextInput>` as shown below:
If the `ref` is removed, TextInput w/ suggestion functions as normal. However, when `ref` is provided, the following error is thrown: 
TextInput.js line 192
Local project. Plus additional tests written.
Create a `<TextInput>` with a `ref`
Wondering if `const inputRef = useRef();` should be updated to `const inputRef = ref || useRef()`, then all executions of `(ref || inputRef)` could be simplified to `inputRef` and make this less bug prone. Thoughts?
No
🤷‍♂ Probably not necessary
> restore focus to provided ref and tests

- src/js/components/Form/Form.js
Changed Form to re-run all failed validations on any field update.
This allows validations that depend on multiple fields to be cleared when the value changes in on of those fields.
Form.js
storybook
storybook
no
yes
> Changed Form to re-run all failed validations on any field update

- src/js/themes/base.d.ts
- src/js/themes/base.js
Added colors of `background-contrast`, `background-front`, `background-back` with dark/light modes.
The text color changes will be filed on a separate PR as we haven't got it yet.
base.js
Not being used yet.
Following the HPE theme changes, this proposal came for grommet base theme as well.
Chris sent the following:
I've updated the colors but kept the opacity similar to HPE theme.
None.
no
yes
yes
> Added background colors

- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/TextInput.js
Removes the error
```
Warning: A component is changing a controlled input of type undefined to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa).
```
when testing by giving a default value of an empty string to the components causing the error.
The issue was caused by the components starting at a value of undefined making the input uncontrolled.
> Fixes test error of uncontrolled to controlled input

- src/js/components/CheckBox/README.md
- src/js/components/CheckBox/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Noticed this in-accuracy while comparing the HPE Designer theme with base.js.
> Fixed theme docs of CheckBox toggle.size

- src/js/components/Menu/index.d.ts
- src/js/components/Menu/stories/typescript/Custom.tsx
Excluded the `icon` prop of Button, so it won't override the types of Menu icon.
Menu/index.d.ts
storybook Menu/Custom example as modified on the story file
the loader of typescript and storybook
Less than 5 seconds to verify the fix is working thanks to typescript on storybook 🎉 
Fixes #3711 
no
yep
> [TS] Fix type issue of Menu icon

- src/js/components/Select/Select.js
setValue(event.value) was causing the select test -- select an option with complex options -- to fail. an object was being passed into the values prop, causing the error.
> Fixes an error with select test

- src/js/components/RadioButtonGroup/README.md
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/doc.js
- src/js/components/RadioButtonGroup/index.d.ts
- src/js/components/RadioButtonGroup/stories/Disabled.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed RadioButtonGroup to add a disabled property.
This makes it easier to disable a simple RadioButtonGroup than having to convert an options array of strings to objects.
doc.js
storybook, added RadioButtonGroup Disabled story
storybook
automatic
yes
> Changed RadioButtonGroup to add disabled

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/Grid/README.md
- src/js/components/Grid/StyledGrid.js
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/prop-types.js
Changed Grid to add pad
This allows Grid `fill` to work. Without it, Grid has `margin` but that doesn't work with `fill`.
Grid/index.d.ts
unit
unit
automatic
yes
> Changed Grid to add pad

- src/js/components/CheckBox/stories/Indeterminate.js
This changes a story name from "Interminiate" to "Indeterminate"
src/js/components/CheckBox/stories/Indeterminate.js
I ran storybook after making this change and saw that the story name change was reflected.
This can be tested by running storybook on this branch and seeing the "Indeterminate" story under CheckBox
N/A
No
No
> docs: fix indeterminate typo in Indeterminate story

- src/js/components/Box/StyledBox.js
This PR fixes the gapStyle to include column-reverse in the way that height is calculated for the box gap
Box/StyledBox.js
Storybook testing was done I used this simple code to check
```
<Box
background="brand"
gap="medium"
direction="column-reverse"
pad="medium"
>
<Text>Copyright</Text>
<Anchor label="About" />
</Box>
</Grommet>
```
StoryBook
gapStyle function was taken into account if direction prop was column then push the height for the gap otherwise it was calculating the width which was being used for row 
I made a quick code sandBox in order to show my issue. 
https://codesandbox.io/s/elated-sea-2m3cs
no
no
> added column-reverse to also calcualte gap height

- src/js/components/Heading/stories/All.js
- src/js/components/Heading/stories/Color.js
- src/js/components/Heading/stories/CustomHeading.js
- src/js/components/Heading/stories/Extend.js
Added a storybook example using extend property for heading.
Gave each storybook example for heading an individual file.
> Heading storybook example using extend, reorganize heading storybook files

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test.js
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
Fixed validate when the error object is a react node.
Form.js
Added a section of tests for the validate props with all of its different flavors.
storybook-> Form -> All
storybook-> Form -> Validate onBlur (when wrapping the string with `<Text>`)
Read the tests.
#3762 
no
no - it's a fix for a new feature on master so never released with this bug.
> Form - Fixed validate when error is a react node

- src/js/components/FormField/FormField.js
Changed FormField to associate rest props with container when not used to automatically render input element.
FormField.js
???
Without this change, there is no way to add attributes to a FormField element. The grommet designer wants this to be able to attach an `onClick` event handler to the FormField.
no
yes
> Changed FormField to associate rest props with container when not used to automatically render input element

- src/js/components/RadioButtonGroup/README.md
- src/js/components/RadioButtonGroup/doc.js
- src/js/components/RadioButtonGroup/index.d.ts
- src/js/components/RadioButtonGroup/stories/typescript/Simple.tsx
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds object type to RadioButtonGroup `value` prop
doc.js
Added typescript story file for RadioButtonGroup
storybook
Coming from a slack conversation https://grommet.slack.com/archives/C04LMHN59/p1582222660202300
Shared on slack
https://codesandbox.io/s/strange-star-trfpe
yep, done
yep
> Update types of RadioButtonGroup value prop

- src/js/components/Select/Select.js
In 2.11.0, when using a select without passing value as a prop, selecting
a dropdown entry won't update the Select component to have that entry
selected. This sets the value using `setValue` from the `useFormContext` hook.
src/js/components/Select/Select.js
Before this change, the Select in the All storybook story would not update when a dropdown entry was clicked. Now it does.
This can be tested by creating a Select component with no value prop and no onChange prop and trying to click it.
It looks like this was intentionally removed in https://github.com/grommet/grommet/commit/caa63f3715dfd7f21a1a7f7bbce898d6fef87c92#diff-19aa4813d5217c4120837104c9b593ff, so I'm not sure if adding this back in is the desired fix, but I thought I'd give it a shot.
#3772 
It's a hotfix, so …
> fix: select dropdown entry when the input isnt controlled

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Drop/Drop.js
- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/PortalContext.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Drop/stories/Multiple.js
- src/js/components/DropButton/DropButton.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed Drop to use hooks.
Also, fixed the lingering issues from https://github.com/grommet/grommet/pull/2745.
Now, you can close a drop opened from within another drop without closing the first drop.
Storybook for Drop, DropButton, Menu, TextInput, MaskedInput, Select.
Added Drop Multiple story to show more flavors.
Storybook
See https://github.com/grommet/grommet/pull/2745
no
yes
> Changed Drop to use hooks

- src/js/components/Meter/README.md
- src/js/components/Meter/__tests__/Meter-test.js
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
- src/js/components/Meter/doc.js
- src/js/components/Meter/utils.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Allows Meter to accept a background opacity value of number (such as 0.8).
src/js/components/Meter/utils.js
A test has been added, and it was test on a local storybook.
Add `background={{color: 'red', opacity: 0.2}}` to a Meter.
Meter could accept theme opacity values such as "weak" but not just a number value.
#3759 
N/A
They've been updated in this PR.
No.
> Allow Meter to accept number value

- src/js/components/Grid/stories/Responsive.js
- src/js/components/Menu/stories/typescript/Themed.tsx
- src/js/themes/base.d.ts
- src/js/utils/index.d.ts
Added missing breakpoint types on ThemeType
base.d.ts
run build for typescript with newly added story that reproduces the issue
running ts build on the new story
The fix on Responsive.js story was something I caught along the way.
fixes #3787 
no
yes as a bug fix on TS
> [TS] Theme - Added missing breakpoint types

- src/js/components/Layer/__tests__/Layer-test.js
Adds a test that checks if layer unmounts from dom
Final test in Layer-test.js
Checked if test fails if layer is not unmounted
Can change the setShowLayer from true to false in SimpleLayer component.
None
No
No
> Test that checked if layer component unmounts from DOM

- src/js/components/Meter/__tests__/Meter-test.js
Changes Meter test to use 0.2 instead of '0.2' for opacity of background. The test should check that opacity accepts a number. This removes the console warning.
src/js/components/Meter/__tests__/Meter-test.js
Tests have been updated and no warning was printed to the console.
yarn test-update
A console warning was being printed since '0.2' (as a string) is not a valid value for opacity.
No.
No.
> Update Meter test to fix console warning

- src/js/components/MaskedInput/MaskedInput.js
This PR fixes a bug in `MaskedInput` where a user can input a value that doesn't match the mask given for the input.
For example, if a mask was given for a date (dd-mm-yyyy) https://storybook.grommet.io/?path=/story/maskedinput--date, the user could input 01-01-19999, which is one character too many for the mask to be valid.
The issue is because the event given to the onChange function is the original change event from the user typing into the input. The `event.target.value` doesn't reflect the validation and masking done by `parseValue`. `onChange` does fire an event with the updated text on the input ref, but then also calls the `onChange` prop provided with the old event which doesn't have the updated input value.
This updates `event.target.value` with the `nextValue` build by …
> fix(MaskedInput): set nextValue as event's value in onChangeInput

- src/js/components/Grid/Grid.js
- src/js/components/Grid/README.md
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed Grid to add responsive.
This aligns Grid more with Box, in terms of how margin and pad respond.
doc.js
unit test
grommet-publisher
automatic
yes
> Changed Grid to add responsive

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
Before this change, the only way `border="between"` worked was if `align="stretch"`. This change fixes the gap elements to use `align-items: self;` so the between border will be seen and allow any value of `align` on the Box to work.
manual
no
yes
> Changed Box to use align-self for gap element, so border between works

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Adds in conditions to allow onSuggestionsOpen/Close to be called when the suggestions drop opens.
src/js/components/TextInput/TextInput.js
Tests have been added to the testing suite in this PR. I reverted my changes, and the tests I wrote failed. However, with the changes added in, they pass.
In storybook, you can add this code to the TextInput Suggestions story. If you click on the text input, you'd expect a console statement to be printed but there isn't one. Similarly, if you click outside of the suggestions to close them, no statement is printed.
```
onSuggestionsOpen={() => console.log('opening suggestions')}
onSuggestionsClose={() => console.log('closing suggestions')}
```
#3829 
No.
No.
> Fix onSuggestionsOpen/Close

- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/Form/stories/ValidateOnBlur.js
- src/js/components/FormField/FormField.js
- src/js/components/FormField/README.md
- src/js/components/FormField/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed FormField to allow react nodes for help, error, and info
FormField/doc.js
Form -> Validate on Blur story
storybook
automatic
yes
> Changed FormField to allow react nodes for help, error, and info

- src/js/components/List/stories/typescript/selected.tsx
- src/js/components/Meter/stories/typescript/MultipleValues.tsx
- src/js/components/Tabs/stories/typescript/Controlled.tsx
When testing a different pull request, I encountered Storybook build failures due to TypeScript errors.
This pull request clears the errors and allows the build to finish and Storybook to be available in the browser. The errors are cleared by initializing `useState()` to something other than `undefined`.
The `useState()` initialization in each of these files:
- `src/js/components/List/stories/typescript/selected.tsx`
- `src/js/components/Meter/stories/typescript/MultipleValues.tsx`
- `src/js/components/Tabs/stories/typescript/Controlled.tsx`
Storybook builds and components function as expected in the browser.
Storybook builds and List, Meter, and Tabs function in the browser.
None.
None at the moment.
Not available.
No.
No preference.
Not applicable.
> Fix Storybook TypeScript errors

- src/js/themes/base.d.ts
Since the literal breakpoint fields are optional
(and can be undefined), the string index type has to be
optional as well.
This broke as part of https://github.com/grommet/grommet/pull/3793/files
Signed-off-by: Stevche Radevski <stevche@balena.io>
Fixes a typing error
N/A
N/A
N/A
N/A
N/A
N/A
No
Yes
Yes
> Fix type error in theme breakpoints field

- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/stories/Target.js
Changed Layer to enable target to work for non-modal layers
All of the interesting stuff is in StyledLayer.js
The key here is that we include the target bounds, which will be 0,0,0,0 for the window, when calculating the position for the Layer.
Added Layer -> Target story
add unit test
Layer -> Target story
no
yes
> Changed Layer to enable target to work for non-modal layers

- src/js/components/Box/stories/Background.js
- src/js/utils/background.js
- src/js/utils/colors.js
Changed Box to ensure background.dark forces color choice.
When a background color name is used that has both dark and light variants, passing the `dark` sub-property now controls which variant is used. `<Box background={{ color: 'background', dark: true }} />`
backgroundStyle() and normalizeColor()
Added two new examples in the Box -> Background story
Storybook Box -> Background
no
yes
> Changed Box to ensure background.dark forces color choice

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/stories/Range.js
Changed Calendar to fix an issue with selecting a date when starting from a range.
Calendar.js
Enhanced the Calendar -> Range story
storybook
#3844
no
yes
> Changed Calendar to fix an issue with selecting a date when starting from a range.

- src/js/components/Grommet/Grommet.js
Signed-off-by: Brent Burgoyne <brent47@gmail.com>
Fixes broken SSR (#3914) caused by me referencing `document` in the `Grommet` render method in a previous commit.
I have tested this with a reproduced failing nextjs build and it is working now. I started to go down the rabbit whole of adding better SSR tests, but with `styled-components` i was running in to issues with having those tests in the same test suite/babel config as everything else so I bailed. It may be worth revisiting something like that in another commit. Maybe a separate jest suite with `environment: node` that just does a sanity check `ReactDOMServer.renderToString()`.
This can be tested with a basic nextjs build rendering `<Grommet>`. For some reason I wasn't able to reproduce the issue with gatsby.
No
#3914
N/A
No
No
Yes
> Fix SSR with document referenced in Grommet render

- src/js/components/List/List.js
- src/js/components/List/stories/action.js
Fixes issue #3861 where adding the action prop to a List component would generate the react unique key error. 
I added a key of actionContainer[index] the content when action is passed in. I did not simply make it index because a key must still be provided in the action prop; shown in the list storybook example.
Both need a unique key to get rid of the warning. This issue seems to have been around since, at least 2.9.
```
action={(elem, index) => {
return (
<Menu
// this is needed as well to prevent the error
key={index}
icon={<More />}
hoverIndicator
items={[{ label: 'one' }]}
/>
);
}}
/>
```
List.js
```
if (action) {
content = [
//added key here
<Box align="start" key={`actionContainer${index}`}>
{content}
</Box>,
action(item, index),
];
```
Tested in the List storybook example …
> List with 'action' property generates a warning #3861 fix

- src/js/components/Image/Image.js
- src/js/components/Image/__tests__/Image-test.js
- src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
Account for the `a11yTitle` prop that is already documented but not being fetched to aria-label.
Added a test.
see the snapshot with the aria-label added.
Fixes #3930
no
yes
> Changed Image to take `a11yTitle`

- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adding dark/light object support to DataTable PropTypes `background` prop.
Tested on 'Styled.js' story by injecting the example provided on #3937, it works as expected without a warning.
Fixes #3937
> Changed propTypes of DataTable background

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Changed sort condition when resolving the icon on DataTable
before the fix, the sort icon on https://storybook.grommet.io/?path=/story/datatable--sort wasn't resolved properly, now it should work as expected.
Also tested the `sortable` examples on https://storybook.grommet.io/?path=/story/all--all to make sure they are not being impacted by this change, and it seems to work as expected as well.
fixes https://github.com/grommet/grommet/issues/3916
no
yea
> Changed sort condition when resolving the icon on DataTable

- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
These tests are a little abusive for Box pad/margin, but will keep us on the safe side with backward compatibility of #3939
> Added margin and pad tests

- src/js/components/Box/Box.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
Refined Box gap of value 'none' to not apply gap
fixes https://github.com/grommet/grommet/issues/3837
no
yes
> Refined Box gap of value 'none'

- src/js/components/Calendar/stories/Multiple.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/Form/Form.js
- src/js/components/Form/FormContext.js
- src/js/components/Form/__tests__/Form-test.js
Changed Form and FormContext to fix caret issues. The key problem was that the caret position would get reset to the end of the field when entering text in the middle of the field.
In general, this is a simpler approach to FormContext. Instead of trying to hold everything in the `contextValue` state, we only use that for uncontrolled situations when there is no `initialValue`. And, we pass the value to use by checking which source is correct when we pass it to the `useFormContext()` caller. This leaves the state wherever it should be controlled without introducing intermediate state.
FormContext.js
Form.js useFormContext()
Storybook Form, Select, CheckBox, TextInput, etc.
Especially entering text from various caret positions.
Storybook Form flavors, entering text from various caret …
> Changed Form and FormContext to fix caret issues

- src/js/components/Form/README.md
- src/js/components/Form/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Completes the PR https://github.com/grommet/grommet/pull/3929 by changing the docs and snapshots for Form `onChange`
doc.js
Cleaning up https://github.com/grommet/grommet/pull/3929 and #3920 
done
no
> Changed docs for Form onChange

- src/js/components/Menu/Menu.js
- src/js/components/Menu/stories/Simple.js
Changed Menu drop to propagate props
Menu.js
storybook quick example on Simple
storybook Menu->Simple
According to documentation https://v2.grommet.io/menu?#dropProps
Menu should be able to propagate dropProps, it currently only propagates the alignment.
fixes https://github.com/grommet/grommet/issues/3963
no
yes
> Changed Menu to propagate dropProps

- src/js/components/Select/README.md
- src/js/components/Select/doc.js
- src/js/components/Select/stories/typescript/CreateOption.tsx
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
Changed docs and typescript for the open select control
bade.d.ts and doc.js
added the theme prop to tsx story
tsx story
Noticed this problem when working on the Select component.
Done
yes
> [TS] - Changed docs and typescript for the open select control

- src/js/components/DropButton/DropButton.js
- src/js/components/DropButton/__tests__/DropButton-test.js
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/utils/index.js
- src/js/utils/refs.js
Changed DropButton to fix an issue with function refs.
This just fixes DropButton for now. We likely will need to switch to `useForwardedRef()` in other components as well.
utils/refs.js
Added a unit test for this, verified that it failed before changing the code.
Whitebox tested Select -> Simple story too.
should be covered by unit test
fixes #3942
no
yes
> Changed DropButton to fix an issue with function refs.

- src/js/components/hocs.js
Fixes compatibility with Preact.
In Preact, the React compatibility layer returns a function instead of an object for `forwardRef()`. In `hocs.js`, Grommet attempts to set the name property of the return value of `forwardRef()`, causing an issue as `Function.prototype.name` is read-only.
Allows compatibility with Preact.
`src/js/components/hocs.js`
Basic testing using a pre-existing application (just making sure it works at all).
Ensure it still works with React.
There's no reason why `name` should be set in the first place, as basically the entire React ecosystem has settled on using `displayName` instead. Also, [React itself only uses `displayName` and never `name`.](https://reactjs.org/docs/react-component.html#displayname)
[preactjs/preact#2484](https://github.com/preactjs/preact/issue …
> Fix Preact compatibility

- src/js/components/Tab/README.md
- src/js/components/Tab/Tab.js
- src/js/components/Tab/doc.js
- src/js/components/Tab/index.d.ts
- src/js/components/Tabs/__tests__/Tabs-test.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/Tabs/stories/Icon.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Allows user to provide an `icon` to the Tab and control its placement with `reverse`.
src/js/components/Tab/Tab.js
A new storybook has been added, and a new jest-test has been added as a baseline.
Add an icon to a `Tab` and `reverse` if you want.
To align with HPE Design system designs, teams would need to create complex `title` on a Tab to achieve an icon with the tab label -- this opens up lots of room for inconsistency. Because `Tab` is technically a Button, it felt well-suited to allow Tab to accept icon and reverse props like Button does.
Yes, they're updated here.
Yes.
> Allow Tab to accept icon and reverse

- src/js/components/Select/Select.js
Changed Select to fix an issue with propagating onClick.
Before this change, the `rest.onClick` was being passed to the underlying TextInput but then being overridden by Select's own onClick.
Select.js
manually with grommet designer
This was causing issues in the grommet designer where the Select component couldn't be selected via clicking on it.
no
sure
> Changed Select to fix an issue with propagating onClick

- src/js/components/Drop/Drop.js
Fixes issue #3755 by adding ThemeContext.Consumer to drop js
Drop.js
Tested on storybook and using the codesandbox example here.
https://codesandbox.io/s/frosty-hofstadter-rhqkd
Storybook and codesanbox is best
I'm assume this issue is occuring because of createPortal(). The drop container is created outside of root, and misses out on some props that are passed into grommet.
#3755 
No
No
> Menudrop not receiving rtl from theme

- src/js/components/Tab/README.md
- src/js/components/Tab/doc.js
- src/js/components/Tab/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds disabled to Tab docs. This functionality already works on the grommet end since Tab is built on top of Button, but it is not a prop we document for Tab.
src/js/components/Tab/doc.js
> Add disabled to Tab docs

- src/js/components/Drop/Drop.js
- src/js/components/Tab/Tab.js
This PR ensures that the focus outline around a tab does not get hidden by the hover styling of adjacent tabs. When a tab receives focus, it is given a zindex of 1 to pull it on top of surrounding tabs. onblur, the zindex returns to undefined.
src/js/components/Tab/Tab.js
Tested in storybook.
Use the Icon example on Tabs in storybook. Tab onto one of the tabs, then hover on adjacent tabs. The focus outline should remain visible on all sides.
Hover styling was covering one edge of the tab when there was no space between tabs.
No.
No.
> Toggle zindex to keep focus intact

- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
Following a conversation with @halocline, this PR is supporting #3973 and making sure we are maintaining backward compatibility with the coming changes of `disabled` FormField.
The second test has a placeholder code that should be un-commented in order to test the new functionality of #3973, it also has instructions of what to expect from the snapshots after merging it with branch halocline:formfield-disabled-styling.
> Added FormField tests for disabled state and custom theme.

- src/js/contexts/AnnounceContext/index.d.ts
Adds timeout parameter to announce context
contexts/AnnounceContext/indext.d.ts
using this code
```
import PropTypes from 'prop-types';
import { storiesOf } from '@storybook/react';
import isChromatic from 'storybook-chromatic/isChromatic';
import { Grommet,  Box, Text, AnnounceContext, Heading } from 'grommet';
const Announcer = ({ announce, message, mode, role }) => {
React.useEffect(() => {
const timeout = 3000;
announce(message, mode, timeout);
}, [announce, message, mode]);
return (
<Text  role={role} aria-live={mode}>
{message}
</Text>
);
};
Announcer.propTypes = {
announce: PropTypes.func.isRequired,
message: PropTypes.string,
mode: PropTypes.string,
role: PropTypes.string,
};
Announcer.defaultProps = {
message: …
```
> added missing parameter to announce context [TS]

- package.json
- src/js/all/stories/AllComponents.js
- yarn.lock
Adds the HPE NEXT theme to the available themes in the All Components story.
This makes it a bit easier to work on grommet changes needed for the theme.
no
no
> Added HPE NEXT theme for All Components story

- src/js/__tests__/__snapshots__/default-props-test.js.snap
- src/js/__tests__/default-props-test.js
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Avatar/__tests__/__snapshots__/Avatar-test.js.snap
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test.js.snap
- src/js/components/Grommet/__tests__/Grommet-test.js
- src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Sidebar/__tests__/__snapshots__/Sidebar-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/utils/background.js
- src/js/utils/colors.js
Refactored backgroundStyle to split out backgroundAndTextColors.
This will make it easier to share the colors between properties and styles.
The snapshot changes are primarily due to the new code only setting `background-color` instead of `background` when we are only providing a color value.
Storybook
Storybook
no
no
> Refactored backgroundStyle to split out backgroundAndTextColors

- src/js/components/Distribution/README.md
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- yarn.lock
Updating dependencies of yarn.lock requires some snapshot changes.
Closes #4030.
Should unblock #4031.
The snapshot changes are occurring on the theme-test for the hpe theme testing, we didn't change anything on the hpe theme (^1.0.0) recently, I'm wondering if the recent #4023 PR changes are somehow related to this snapshot update.
> Updated dependencies and changed snapshots

- src/js/components/Markdown/README.md
- src/js/components/Markdown/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- yarn.lock
Taken care of the missing statement of doc.js from PR https://github.com/grommet/grommet/pull/3734.
I'm not sure how the snapshots passed on that PR but they should have failed, currently, there is a mismatch of snapshots on the master branch.
> Changed docs for Markdown options

- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/StyledMaskedInput.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/MaskedInput/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds disabledStyle to MaskedInput. Currently, disabled styling is not being applied to maskedinput like it is for other inputs such as TextInput.
src/js/components/MaskedInput/StyledMaskedInput.js
disabled was applied to a storybook to ensure the opacity changed the same way that TextInput opacity does by default. A jest test was added for future.
Add `disabled` to MaskedInput -- if using `grommet theme`, or base.js, the disabledStyle should default to opacity 0.3.
When working on MaskedInput examples for the HPE Design System, I noticed that the placeholder text of the MaskedInput was not being toggled in opacity the same that TextInput was.
Yes, they're updated here.
[Shimi] Yes - Added `disabled` theme styling to MaskedInput.
This will now toggle opacity to 0.3 for disabled …
> Allow disabled styling to affect MaskedInput

- src/js/components/Drop/DropContainer.js
Changed DropContainer to use a constant default prop value.
I've found this to help reduce re-rendering in general. It isn't fixing a particular issue.
no
no
> Changed DropContainer to use a constant default prop value

- src/js/components/Button/Button.js
Changed Button to fix an issue with plain + icon.
This only occurs when a Button has `plain`, `icon`, and the theme has `button.default`.
Button.js
whitebox
no
no
> Changed Button to fix an issue with plain + icon

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Propagates the a11yTitle prop as `aria-label` prop to TextInput, hence fixes the aria-label issue for both Select and TextInput components.
TextInput.js
Added unit tests and verified snapshots are containing the `aria-label` prop.
snapshots
a request for this fix came from @MikeKingdom
https://codesandbox.io/s/restless-smoke-g3zjc?file=/src/App.js
no
yes
> Changed Select and TextInput to accept a11yTitle

- src/js/components/Header/index.d.ts
The header was set to use `BoxProps` for the type, but it should use `BoxTypes` so that it inherits the JSX `div` types.
Fixes an issue where the Header component did not extend the general `div` types
I made the type change on my machine and verified that the header props extended div props.
Use the Header component and verify it now extends `div` props.
I was trying to customize the Header and noticed it only had the Box props, without also having div props.
Probably not
Probably not necessary
> fix: header should include JSX div types

- src/js/components/DropButton/DropButton.js
Changed DropButton to fix an issue with caller controlling state.
Specifically, if the caller is explicitly setting `open`, don't set the internal `show` state to false, only to have the effect checking the `open` value to reset it immediately.
DropButton.js
you would need to create a caller controlled DropButton
no
yes
> Changed DropButton to fix an issue with caller controlling state

- src/js/components/AccordionPanel/AccordionPanel.js
- src/js/components/Menu/Menu.js
With the new button.default theme assignment, the core components that use Button are being impacted by the new styles.
This PR is assigning the `plain` prop for those Buttons in case theme.button.default is defined.
Any changed file.
jest
with the design system
#4077 
nope
no
> Changed core components that use Button to apply 'plain' for theme.button.default

- package.json
- yarn.lock
Fixes a security warning coming from the markdown-to-jsx package.
https://github.com/probablyup/markdown-to-jsx/issues/306#issuecomment-634729312
Also, updating the project dependencies.
package.json
Closes https://github.com/grommet/grommet/issues/4105
No
Yes, as a bug fix.
> Bump markdown-to-jsx from 6.9.1 to 6.11.4

- package.json
- src/js/all/stories/AllComponents.js
- yarn.lock
Removes hpe V0 and NEXT packages
package.json
jest and storybook
storybook is intact
The NEXT package is causing integrity issues of the yarn.lock.
The V0 package is outdated. 
All the failing PRs due to integrity checks.
no
not really
> Removed hpe V0 and NEXT packages

- src/js/components/Button/StyledButtonKind.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
This PR fixes a bug in Button component due to which Size and Kind (primary, secondary) won't work together. For KindButton the padding values are being read from a `theme.button.size[size].padding` path, which is not present in the theme.
src/js/components/Button/StyledButtonKind.js
create a theme with button kind (default, primary) definitions in theme
https://github.com/grommet/grommet/issues/4134
no
no
yes
> Changed Button to make Kind and size work together (#4134)

- src/js/components/Form/README.md
- src/js/components/Form/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Fix a little typo in Form doc (Their keys instead of they keys).
Fix a little typo in Form doc.
In  src/js/components/Form/doc.js
None.
Nope.
Your project is cool :)
A typo.
Yes it is.
I don't think so.
No.
> Fix little typo in Form doc

- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
- src/js/components/Chart/calcs.js
- src/js/components/Chart/index.js
- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/README.md
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataChart/doc.js
- src/js/components/DataChart/index.d.ts
- src/js/components/DataChart/stories/Axes.js
- src/js/components/DataChart/stories/Multiple.js
- src/js/components/DataChart/stories/StackedBars.js
- src/js/components/DataChart/stories/typescript/Size.tsx
- src/js/components/Grid/README.md
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed DataChart to improve axes.
- truncate y-axis values to avoid long fractions
- added prefix and suffix for axis values, to avoid the need for a custom renderer in typical situations
- y-axis with key will check for a date format and use “right” default date format for the span of dates
- align y-axis labels better with guide lines
DataChart.js
enhanced unit tests, enhanced stories
storybook
no
yes
This has a breaking change for the `yAxis.render()` signature. It is now called with `(content, data, dataIndex, axisIndex)` instead of `(dataIndex, axisIndex)`.
> Changed DataChart to improve axes

- src/js/themes/base.d.ts
`text.extend` is not defined in the `ThemeType` definition, causing TS compile to throw an error.
Adds type definition for the themes `text.extend` 
`src/js/themes/base.d.ts` -> `ThemeType`
Tested locally
Using typescript, attempt to add the following theme:
```
{
text: {
extend: (props: any) => {
const { value } = props.theme.global.breakpoints.small;
return `
@media (max-width: ${value}px) {
font-size: 16px
}
`;
},
},
};
```
they already reference this property, so no
https://v2.grommet.io/text#text.extend
> TS: Add extend type to text

- src/js/components/RadioButtonGroup/README.md
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/components/RadioButtonGroup/doc.js
- src/js/components/RadioButtonGroup/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed RadioButtonGroup to support numeric values.
This allows setting something to `5` instead of `"5"`.
doc.js
added unit test
see unit test
automatic
yes
> Changed RadioButtonGroup to support numeric values

- src/js/components/RadioButton/README.md
- src/js/components/RadioButton/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds missing documentation for `radioButton.color` in docs and base.js. `radioButton.color` is referenced in implementation here: https://github.com/grommet/grommet/blob/6219ed0086c8673692ff78ca6a31d710f550ed79/src/js/components/RadioButton/RadioButton.js#L29
base.js & RadioButton/doc.js
local env
Surfaced when implementing theming for https://github.com/hpe-design/design-system/issues/518#issuecomment-639097244
https://github.com/hpe-design/design-system/issues/518
Yes.
Not needed.
> Include RadioButton color reference in basejs and documentation
