grommet/grommet

- src/js/themes/base.d.ts
Adds missing type definition for `formField.info`
`themes/base.d.ts` -> `ThemeType`
Manually tested
Verify you can add an `info` key to a type theme object.
They already have this: https://v2.grommet.io/formfield#formField.info.color
> Add missing `formField.info` type definition

- src/js/components/Button/Button.js
- src/js/components/Select/SelectContainer.js
Changed Select to fix an issue with onSearch being called multiple times.
The management of `activeIndex` was too convoluted and too different between onSearch and no onSearch cases. Previously, if onSearch was specified, an effect would initialize activeIndex differently than if it wasn't. So, keyboard navigation was inconsistent. Now, we only set activeIndex based on any `search` text, which aligns the keyboard behavior better.
Also, uncovered that `onSearch` was being called repeatedly due to the effect with a dependency on it. So, callers that didn't use `useCallback()` would see repeated calls. Now, we only call `onSearch` directly in the onChange handler.
Also fixed a linter warning in Button.
Button.js, for a lightweight warm up ;)
whitebox by adding onSearch to Select in All …
> Changed Select to fix an issue with onSearch being called multiple times

- src/js/components/Anchor/__tests__/Anchor-test.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
Fixes warnings on `yarn test` for Anchor-test.js. This PR has no effect on the overall testing coverage. Also updated the tests to use render instead of renderer.create which is what causes the changes in the snapshots.
Look at the warnings that were previously being generated from running yarn test. Run this command again on this PR and there won't be warnings for Anchor-test.js.
Running yarn test, looking at the snapshots for 'warns about invalid icon' and 'warns about invalid label', and checking that the coverage stayed the same.
^ see above
#4177
No
No
> fixed warnings in Anchor test

- src/js/components/Accordion/__tests__/Accordion-test.js
- src/js/components/CheckBoxGroup/__tests__/CheckBoxGroup-test.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
Increases testing coverage for CheckBoxGroup:
| Type | Before | After |
| --- | --- | --- |
| Statements | 58.82% | 100% |
| Branches | 47.62% | 85.71% |
| Functions | 66.67% | 100% |
| Lines | 60.61%  | 100% |
Increases repository coverage:
| Type | Before | After |
| --- | --- | --- |
| Statements | 80.9% | 81.16% |
| Branches | 70.65% | 70.82% |
| Functions | 78.58% | 78.73% |
| Lines | 82.11%  | 82.34% |
CheckBoxGroup-test.js
I looked through the snapshots to make sure the tests were working and I looked at the coverage report to see line by line what was being covered for CheckBoxGroup.js to maximize coverage without any unnecessary tests.
Run `yarn test` and look at the coverage report and snapshots.
No
No
In line 154 I had to use `expect(warnSpy).toBeCalled();` …
> Testing for CheckBoxGroup

- src/js/components/RadioButtonGroup/README.md
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/components/RadioButtonGroup/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Resolving all non-string types of options to a string for the `label` prop.
Regarding the snapshot changes, I noticed that now all non-string label values (boolean and numbers) are now wrapped with span on the DOM which is consistent with how label strings are rendered.
doc.js
tested locally with storybook examples and made sure the jest snapshots are up to date as expected.
go over snapshots.
This issue was revealed during tests clean-ups.
https://github.com/grommet/grommet/pull/4208
#4180 
https://github.com/grommet/grommet-site/pull/174
Yes, done on https://github.com/grommet/grommet-site/pull/174
Yes
> Fixed display of non-string values on RadioButtonGroup

- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/Button-kind-test.js
- src/js/components/Button/__tests__/Button-test.js
Applies the default disabled component styling to `<StyledButtonKind />` for backwards compatibility.
Specifically, ensures a disabled Button does not receive a cursor treatment indicating the Button can be interacted with in a disabled state.
StyledButtonKind.js
Storybook - Button --> 'Custom' story
Additional Jest tests
Storybook - Button --> 'Custom' story is a good one
Original issue surfaced: https://github.com/hpe-design/design-system/issues/920
This compliments https://github.com/grommet/grommet/pull/4232
https://github.com/hpe-design/design-system/issues/920
No.
Not necessarily.
> Applies default disabled component styling to StyledButtonKind

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/Button/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
The Button propTypes currently complain about specifying
something other than _self, _blank, _parent, _top. In
html the anchor tag actually allows any string in target
to create a named tab/window. The names above that start
with _ are special names but it is perfectly fine to
create a named window.
Changes Button propTypes for the target prop to allow any string
and not just _self, _blank, _parent, _top
Manually tested with a temporary tweak in the storybook for Button.
Ran jest tests.
Just add a target="somename" to a Button with an href.
Setting target to some string like quakehelp is something we often do for help links. That way, when the user selects any links with the same target window name, the help always ends up in the same window rather than continually creating new …
> Fix Button propTypes for the target property to allow string

- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
12 tests were being skipped in MaskedInput-test.js this PR fixes it so that all the tests are being run
MaskedInput-test.js
`yarn test --verbose`
closes #4239
No
No
> Tests no longer skipped in MaskedInput

- src/js/components/TextInput/README.md
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Updates the TextInput documentation to include the a11yTitle
TextInput/doc.js
`yarn test`
#4244 
Updated
No
> Updated documenation for TextInput a11yTitle

- src/js/components/RadioButton/README.md
- src/js/components/RadioButton/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds documentation for the `control` color as part of the theme docs for RadioButton
RadioButton/doc.js
closes #4159 
Updated
No
> Documentation for RadioButton `control` color

- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/DataTable/stories/Simple.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
This PR adds to PropTypes for size of pad to also accept a string
Closes #4268 
DataTable/doc.js
storybook 
add this to the simple story to test and check console warning 
```
pad={{ vertical: '100px', horizontal: '80px' }}
```
`pad={{ vertical: '100px', horizontal: '80px' }}`
issue #4268 
issue #4268 
auto
no
> DataTable - update docs for prop type on size to accept string

- src/js/components/Tab/Tab.js
- src/js/components/Tabs/Tabs.js
- src/js/components/Tabs/TabsContext.js
- src/js/components/Tabs/__tests__/Tabs-test.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
Creates `TabsContext` which stores the `activeIndex` (needed to properly assign `activeTitle`), if tab is `active` (previously passed to Tab as a prop via clone child), `onActivate` (previously passed to individual Tab as a prop via clone child), `setActiveContent` (allows Tab to assign its children as the active content to be rendered by Tabs, and `setActiveTitle` (for screen reader accessibility).
Previously, Tabs was looking into its children to find what should be the active content displayed. If `Tab` was not the direct descendant of `Tabs`, it wouldn't render the child properly. Now, `Tab` takes more control by assigning its children to the activeContent. This hand-off is done using `TabsContext`.
Closes #4224 
src/js/components/Tabs/Tabs.js
In local storybook, I recreated the setup …
> Create TabsContext to fix Tab issue

- src/js/components/DataTable/README.md
- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
This PR adds to extend for DataTable Body 
Closes #3792 
StyledDataTable.js
Storybook
Took code from CodeSandBox and tested it in local storybook 
https://codesandbox.io/s/grommet-v2-template-55rdu?file=/index.js
use `const theme2 = {
dataTable: { body: { extend: `min-height: 800px;` } },
};
`
Use a custom theme to set height of table body 
```
const theme2 = {
dataTable: { body: { extend: `min-height: 800px;` } },
};
```
Issue #3792 
auto
no
> add extend to datatable body

- src/js/components/RadioButton/README.md
- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButton/__tests__/RadioButton-test.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
- src/js/components/RadioButton/doc.js
- src/js/components/RadioButton/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds the `a11yTitle` prop to RadioButton
RadioButton.js
`yarn test`
added an accessibility test
Closes #4287
#4284
Updated in this PR
No
Backwards comaptible
> Add a11yTitle support to RadioButton component

- src/js/components/Clock/README.md
- src/js/components/Clock/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adjusts clock docs. While looking to resolve the `onChange` docs, I noticed that this wording needed to be updated as well. Regardless of if a clock is analog or digital, if the time provided includes a date then the date gets stripped off.
src/js/components/Clock/doc.js
Updated README etc
Finding related to closing https://github.com/grommet/grommet/issues/4251
#4251 
Updated here.
No.
> Adjust wording of time docs

- src/js/components/Calendar/index.d.ts
Signed-off-by: Llorenç Muntaner <llorenc.muntaner@gmail.com>
Improve typings for Calendar component
`src/js/components/Calendar/index.d.ts
No extra tests added.
No manual testing.
When Calendar is used with single option select, the parameter passed to the handler is a string, not an array of strings.
No issue found.
Not applicable.
No.
No need.
> Fix Calendar onSelect type

- storybook/manager.js
- storybook/theme.js
Fix Storybook Theme
Start with `storybook/theme.js`
Checking that its running properly with `yarn build-storybook`
Just run `yarn build-storybook` and check that its working as it should
It was remove in a previous PR due to a small confusion caused by cache. This PR recovers it
No
No
No
> Fix storybook theme that was mistakenly deleted

- src/js/components/Tab/README.md
- src/js/components/Tab/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Adds missing documentation for the `tab.extend` component, mentioned on #4310 
`/Tab/doc.js`
Fixes #4310
> add proper documentation for tab.extend

- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/README.md
- src/js/components/CheckBox/__tests__/CheckBox-test.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/CheckBox/doc.js
- src/js/components/CheckBox/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds `a11yTitle` to CheckBox. Updates documentation to show `a11yTitle` and show that setting the `label` prop also fulfills accessibility requirements
CheckBox.js
Added a second accessability test to test accessibility for `a11yTitle` and `label`
#4244 
Done
No
> CheckBox added `a11yTitle` and updated documentation

- src/js/components/Chart/Chart.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
Proposes a new approach to chart gradients ID, as a fallback to missing `id` prop.
src/js/components/Chart/Chart.js:475
#3992
> rework chart gradient id

- .yarnclean
- package.json
- src/js/all/stories/typescript/ExtendTheme.tsx
- src/js/themes/base.d.ts
- src/js/utils/index.d.ts
- tsconfig.json
- yarn.lock
Adds TypeScript support for using styled-components interpolations as `extend` values in the `ThemeType`, fixing #3578.
src/js/themes/base.d.ts
src/js/all/stories/typescript/ExtendTheme.tsx
* Created a TypeScript story to type-check various usages of `extend` in a custom theme.
* Updated my own project using locally linked `grommet` and confirmed our custom theme now passed type-checking
* Ensure that `yarn tsc --project .` reports no type-checking errors for the ExtendTheme story.
1) I added a utility type called `PropsOf` which makes use of a TypeScript 2.8 feature called conditional types. This means that TypeScript Grommet users should be using TypeScript >= 2.8, which I think is a reasonable tradeoff. If one of the goals of Grommet's TypeScript support is to be compatible with …
> Update ExtendType to support styled-components interpolations

- src/js/components/Chart/Chart.js
- src/js/components/Chart/README.md
- src/js/components/Chart/__tests__/Chart-test.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
- src/js/components/Chart/doc.js
- src/js/components/Chart/index.d.ts
- src/js/components/Chart/stories/ValueStyle.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/index.d.ts
- src/js/utils/mixins.js
Changed Chart to add per-value color and thickness for bar and point types.
Take a look at the new story to see how they are used.
Added unit tests and a storybook story.
storybook
This was asked for by a group doing data science work as a way to represent four values in one Chart: x, y, thickness, and color.
automatic
yes
> Changed Chart to add per-value color and thickness for bar and point types

- src/js/components/Heading/Heading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Text/Text.js
- src/js/components/Text/__tests__/Text-test.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Allow `Text` and `Heading` components to accept the React `ref` prop
Look at the tests in the first commit, then look at the fix in the second commit.
Unit tests, run storybook
Not sure
I have a use case where all my components must be able to accept `ref` (specifically for use in Slate.js). Most grommet components already call `forwardRef`, but it's missing on `Text` and `Heading` (it might be missing on more, but I didn't check).
https://github.com/grommet/grommet/issues/3133
No
Not sure
> Allow Text and Heading to accept ref

- src/js/components/Card/Card.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Implements Card with forwardRef to resolve an issue on design system where ref could not be passed to Card.
src/js/components/Card/Card.js
Card implement with forwardRef locally in design system to ensure that the console error was resolved.
No.
No.
> Implement Card with forwardRef

- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
This PR adds the alignment of svgs when used within a plain button
button/styledbuttonkind.js
storybook
https://design-system.hpe.design/components/layer#notifications
Using the code 
```
<Box
align="center"
direction="row"
gap="xsmall"
justify="between"
round="medium"
elevation="medium"
pad={{ vertical: "xxsmall", horizontal: "small" }}
background="status-ok"
>
<Box align="center" direction="row" gap="small">
<StatusGood color="text-strong" />
<Text color={{ light: "text", dark: "text-strong" }}>
This is a notifcation with position="top"
</Text>
</Box>
<Button plain icon={<FormClose color="text-strong" />} />
</Box>
```
with the hpe theme 
https://github.com/hpe-design/design-system/issues/865
issue #865 in design system
no
no
> Fix vertical height for svg in plain button

- src/js/components/RadioButtonGroup/README.md
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
- src/js/components/RadioButtonGroup/doc.js
- src/js/components/RadioButtonGroup/stories/CustomTheme.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- yarn.lock
closes #4184 
Adds boxprops to RadioButtonGroup in theme
RadioButtonGroup.js
base.js
base.d.ts
RadioButtonGroup Stories - CustomTheme.js
RadioButtonGroup doc.js
Storybook, tested with and without custom theme.
Used none, xxsmall, small, medium, large, xlarge, and px values to test gap within custom theme.
Also, tested other box props, like animation, to see if they applied.
same as above
RadioButtonGroup did not have the ability to set box props within theme.
#4341 
Yes, they are in this pr
> Box props added to RadioButtonGroup theme

- src/js/components/Calendar/stories/Dual.js
- src/js/components/DateInput/stories/Range.js
- src/js/components/DateInput/stories/RangeFormat.js
Replaces new Date() found in some stories with a static date
Calendar Stories - Dual.js
DateInput Stories - Range.js, RangeFormat.js
Double checked if examples functioned the same as they did before the change
Same as above, in storybook
new Date() was causing unnecessary updates to snapshots
No
No
> Removed new Date() from stories and replaced with static date

- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/prop-types.js
Clarifies docs for Text margin by explaining that Text needs to be wrapped in a Box for margin to take effect. Uses the `genericStyles` as a base for wording, then adds clarification sentence.
src/js/components/Text/doc.js
Updated snapshots.
Reasoning can be found here: https://github.com/grommet/grommet/issues/4093#issuecomment-631759230
Closes https://github.com/grommet/grommet/issues/4093
Updated in this PR.
No.
> Add clarification to text margin docs

- src/js/components/DropButton/stories/Calendar.js
- src/js/components/DropButton/stories/Menu.js
- src/js/components/DropButton/stories/Simple.js
Removes Chromatic testing from DropButton stories because the chromatic screenshots aren't capturing anything valuable for DropButton.
Number of chromatic snapshots should be reduced by three (326 => 323).
Issue #4385 
No
No
> Removed Chromatic testing from DropButton stories

- src/js/components/DateInput/stories/Range.js
- src/js/components/DateInput/stories/Simple.js
- src/js/components/Layer/stories/Center.js
- src/js/components/Layer/stories/Corner.js
- src/js/components/Layer/stories/Form.js
- src/js/components/Layer/stories/Full.js
Removed chromatic testing from the following stories because the screenshots weren't capturing anything useful
DateInput: Range and Simple stories
Layer: Center, Corner, Form, and Full stories
Number of chromatic snapshots should be reduced by 6 (326 => 320).
Issue #4385
No
No
> Removed chromatic snapshots for stories in DateInput and Layer

- src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
Adds a test to infinite scroll that checks if the `show` item is being rendered when show > step
Currently this test is passing, but once the show prop is fixed lines 96 and 97 need to be deleted and lines 89, 98, and 99 uncommented for the test to work correctly.
#4334 #4369 
No
No
> InfiniteScroll Test `show` item should be visible

- src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
Adds testing to infinite scroll `step` prop. Tests small, medium, and large step sizes. Ensures that the number of elements being rendered is correct.
NOTE: this also tests that only unique items are being rendered, (no duplicates). On the `length when step < array` test if you uncomment `show={117}` the test will generate a warning and fail because of a bug causing there to be duplicate items when `show` is set and it is a higher value than `step`.
`yarn test` before and after uncommenting line 89
No
No
> Infinite Scroll test number of items generated

- src/js/components/Chart/stories/Scan.js
- src/js/components/Chart/stories/Zoom.js
Removed Chart -> scan and zoom stories from chromatic testing
Number of chromatic snapshots should go down by 2
#4385 
No
No
> Removed Chart (Scan and Zoom) stories from Chromatic

- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Layer/Layer.js
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/index.d.ts
- src/js/components/SkipLink/SkipLink.js
- src/js/components/SkipLinks/README.md
- src/js/components/SkipLinks/SkipLinks.js
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
- src/js/components/SkipLinks/doc.js
- src/js/components/SkipLinks/stories/Simple.js
- src/js/components/SkipLinks/stories/Themed.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- src/js/utils/DOM.js
1. Allows the SkipLinks layer to open by entering Tab on the keyboard once the page loaded.
1. Allows skipping the SkipLinks layer content and tabbing to the header.
1. Allows editing the SkipLinks message and styling the container, layer, and the text message.
1. Allows cyclic navigation of the page that includes the layer using the keyboard.
1. Enabling access to the rest of the interactive elements while the layer is shown.
1. Changing the DOM behavior to prepend the Layer to the DOM so tabIndex order will behave correctly by default.
1. Provides clear examples of how to use the component on Storybook.
1. Tested with typescript.
1. Change initial focus behavior to the first focused link instead of the container.
SkipLinks.js
Manual testing - many.
Typescript local testing - all passed. …
> Changed SkipLinks 

- src/js/components/Tabs/stories/Icon.js
Changes the template literal found in Tabs/Icons.js to a static value, and adds a comment.
Tabs - Icons.js storybook example
storybook
same as above
Some template literals are being parsed and showing up as ___CSS_0___ or __CSS_1___
It looks like its due to react-syntax-highlighter that storybook uses. It might think that this is a css value and needs to be parsed. It also, doesn't look like this issue has a very high priority on either storybook or react-syntax-highlighter. Storybook plans to fix it by migrating to a new syntax highlighter eventually.
This fix just makes it easier for people to copy and paste the example on storybook.
none on grommet
storybook - https://github.com/storybookjs/storybook/issues/10011
react syntax highllighter - …
> Storybook example Tabs - Icon.js parsing template literal

- storybook/preview.js
Removes import that causes warning on `yarn storybook`
storybook
#4385 
No
No
> Removed chromatic import that causes warning

- src/js/components/Tabs/stories/CustomTheme.js
Changes the template literal found in Tabs/Icons.js to a static value, and adds a comment.
Tabs - CustomTheme.js storybook example
storybook
same as above
Some template literals are being parsed and showing up as ___CSS_0___ or __CSS_1___
It looks like its due to react-syntax-highlighter that storybook uses. It might think that this is a css value and needs to be parsed. It also, doesn't look like this issue has a very high priority on either storybook or react-syntax-highlighter. Storybook plans to fix it by migrating to a new syntax highlighter eventually.
This fix just makes it easier for people to copy and paste the example on storybook.
none on grommet
storybook - https://github.com/storybookjs/storybook/issues/10011
react syntax highllighter - …
> Storybook example Tabs - CustomTheme.js parsing template literal

- src/js/components/Collapsible/stories/Horizontal.js
- src/js/components/Collapsible/stories/Nested.js
- src/js/components/Collapsible/stories/Simple.js
- src/js/components/Menu/stories/ControlBottom.js
- src/js/components/Menu/stories/Custom.js
- src/js/components/Menu/stories/Reverse.js
- src/js/components/Menu/stories/Simple.js
- src/js/components/Menu/stories/Themed.js
Removes all the Collapsible stories and all Menu stories (except for for Item with Icon) from chromatic testing because the chromatic snapshots aren't capturing anything valuable.
Look at the Menu and Collapsible snapshots
Number of chromatic snapshots should be reduced by 8 (318 -> 310)
#4385
No
No
> Removed Chromatic snapshots from some Menu and Collapsible stories

- src/js/components/DateInput/DateInput.js
This PR takes out a statement that only sets value if it is valid 
DateInput.js
storybook 
I wanted to be able to access the value in `onChange`
the value was only being passed if it was valid
so If the field was empty I was not able to set an error 
```
const onChange = event => {
const nextValue = event.value;
setValue(nextValue);
if (!nextValue) {
console.log('no value error message ');
} else {
console.log('value no error message');
}
};
```
above code 
I want to be able to access the event.value even if it is undefined 
design-system 
showing an example of validation 
no
no
> change value is set in dateInput

- src/js/components/InfiniteScroll/index.d.ts
- src/js/components/InfiniteScroll/stories/typescript/OnMore.tsx
This PR updates typescript types for InfiniteScroll based on work started in [this PR](https://github.com/grommet/grommet/pull/3800).
src/js/components/InfiniteScroll/index.d.ts
Implemented new TS story and tested locally with `items` of type array of object and React Element and number. such as:
```
const items = [
{ name: "John", age: 22 },
{ name: "Jenny", age: 23 },
]
```
Run in storybook and ensure no flagged type warnings.
https://github.com/grommet/grommet/issues/3165
Closes #3800 
No.
No.
> Update InfiniteScroll typescript

- src/js/all/stories/typescript/AllComponents.tsx
- src/js/components/RangeInput/index.d.ts
Relies on intrinsic `input` types, which include `onChange` as opposed to duplicating in our props. Takes over https://github.com/grommet/grommet/pull/4304 which was addressing the same thing.
src/js/components/RangeInput/index.d.ts
Tested local, no TS errors.
Open in TS grommet project and ensure no typing flags for `RangeInput` onChange.
No need to override the `onChange` since we are not modifying the default behavior.
Closes https://github.com/grommet/grommet/pull/4304
Closes https://github.com/grommet/grommet/pull/4275
No.
No.
Yes, backward compatible.
> RangeInput TS: Rely on intrinsic onChange

- src/js/components/WorldMap/index.d.ts
Fixes a Typescript error when setting `WorldMap`'s `color` property to a `{ dark: string, light: string }` object.
It looks like the intersection of `WorldMapProps` and `JSX.IntrinsicElements['svg']` results in `color` getting type `ColorType & string`. So, when you use a ColorType object, the following error occurs:
```
Type '{ dark: string; light: string; }' is not assignable to type 'string | ({ dark?: string; light?: string; } & string)'.
Type '{ dark: string; light: string; }' is not assignable to type '{ dark?: string; light?: string; } & string'.
Type '{ dark: string; light: string; }' is not assignable to type 'string'.
```
I fixed it by omitting `color` from the intersection. This way `color` stays `ColorType` only.
I'd be happy to make changes if there is another preferred way …
> [Typescript] Fix WorldMap color Type error

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Clarifies that if children are provided to button, it will be styled as a `plain` Button`.
src/js/components/Button/doc.js
Provide children to button.
Provide children to button.
https://github.com/grommet/grommet/blob/master/src/js/components/Button/Button.js#L320
https://github.com/grommet/grommet/issues/4272#issuecomment-676784288
No.
> Update button docs to clarify effects of adding children

- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
- src/js/components/Box/Box.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
Implements the solution recommended by Eric. It makes the gap element be a span rather than a div if the box is a span. Browsers produce warnings in the console if a div is a child of a span.
One example of this is the implementation of Anchor with an icon and label. This change fixes this situation.
This PR replaces #4436 and #3130 with a different implementation
Box.js
JEST, storybook
See #3046 and #3130 for background.
#3046
Done
No need.
> Changed the gap to be a span if the box is a span

- src/js/components/DataTable/buildState.js
It solves problem when use has applied aggregate function as "min" in DataTable
Issue can be duplicated by having negative value in data and apply aggregate function as min on that data, it will provide value 0 instead of negative value which is lowest
Tested with local data setup by running buildState.js file by providing sample data and columns
No
Yes
Yes backward compatible.
> Fix "min" aggregate function in DataTable

- src/js/components/Calendar/__tests__/Calendar-test.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
Fixes Jest test where date drift results in failed match snapshot. Sets a selected date on the `disabled` story so that the snapshot will be static going forward.
Calendar-test.js
Jest
Calendar "disabled" story snapshot was created in the Month of Aug 2020. Being September 1, the rendered component no longer matched the August snapshot. Plus, the snapshot was not accurately capturing the disabled state of Jan 15, 2020.
No.
No.
> modify calendar test to avoid drifting date snapshot

- src/js/components/Accordion/stories/Simple.js
- src/js/components/DataTable/stories/typescript/Clickable.tsx
- src/js/components/Drop/stories/Lazy.js
- src/js/components/Drop/stories/Multiple.js
- src/js/components/Drop/stories/Overflow.js
- src/js/components/Drop/stories/Plain.js
- src/js/components/Drop/stories/Progressive.js
- src/js/components/Drop/stories/Simple.js
- src/js/components/Drop/stories/Tooltip.js
- src/js/components/Select/stories/LazyLoading.js
- src/js/components/Select/stories/ManyOptions.js
- src/js/components/Select/stories/ObjectOptions.js
- src/js/components/Select/stories/Search.js
- src/js/components/Select/stories/Uncontrolled.js
- src/js/components/TextInput/stories/Suggestion.js
- src/js/components/TextInput/stories/Uncontrolled.js
Removed the following stories from chromatic stories as discussed with shimi because their snapshots were not showing anything valuable.
**Accordion:**
Dark no animation
Multiple
**Drop:**
Lazy,
Multiple,
Overflow,
Plain,
Progressive,
Simple,
Tooltip
**Select:**
Lazy loading options
Lots of options
Object options
Search
Uncontrolled
**TextInput:**
Suggestions
Uncontrolled
Look at the chromatic snapshots of the stories to see that the snapshot isn't capturing anything valuable.
Number of chromatic snapshots should decrease by 16
No
No
> Removed chromatic snapshots of some stories

- src/js/components/DateInput/DateInput.js
Previously props that were added to `dropProps` in DateInput were being ignored. See issue #4485 for more info
Look at this code sandbox, see that the props added to `dropProps` are being ignored
https://codesandbox.io/s/grommet-v2-template-forked-58djv?file=/index.js
Storybook
Can be tested with this storybook example:
```javascript
import React from "react";
import { storiesOf } from '@storybook/react';
import { grommet, Box, Grommet, DateInput } from "grommet";
const Example = () => {
return (
<Box align="center" pad="large" width="medium" margin={{top: '300px'}}>
<DateInput
calendarProps={{
size: "small"
}}
dropProps={{
plain: true,
align: {bottom: "top"}
}}
format="mm/dd/yyyy"
/>
</Box>
</Grommet>
);
};
storiesOf('DateInput', module).add('TEST', () => …
```
> DateInput `dropProps` fix

- src/js/components/Button/StyledButtonKind.js
This PR disables hover styles of Styled Button when it is disabled.
The only one file in the PR
Local environment using a  ` theme.button.default` 
Manually test adding a ` theme.button.default`  and add a button with kind
https://github.com/grommet/grommet-theme-hpe/pull/110
#4492 
https://github.com/grommet/grommet-theme-hpe/pull/110
No
No
No
> fix: remove hover indicator of disabled Styled Button

- src/js/components/Anchor/stories/Default.js
- src/js/components/Carousel/stories/Simple.js
- src/js/components/Form/stories/ControlledInput.js
- src/js/components/Form/stories/ControlledLazy.js
- src/js/components/List/stories/onClickItem.js
- src/js/components/MaskedInput/stories/Date.js
- src/js/components/MaskedInput/stories/Filtered.js
- src/js/components/MaskedInput/stories/IPv4Address.js
- src/js/components/MaskedInput/stories/SizeUnits.js
- src/js/components/MaskedInput/stories/URL.js
- src/js/components/Select/stories/FormSelect.js
- src/js/components/Select/stories/Multiple.js
- src/js/components/TextInput/stories/OnSelect.js
- src/js/components/TextInput/stories/Simple.js
- src/js/components/WorldMap/stories/Simple.js
Removes the following stories because snapshots weren't valuable & trying to decrease chromatic numbers
Original list:
**Accordion**
Simple - decided to keep this story because previously we removed 'Dark no animation' and 'Multiple' because they were similar to this story. This story is covered by jest testing but I think that it might be good to have a chromatic test.
**Anchor**
Default
**Carousel**
Simple
**Form**
Controlled input
Controlled lazy
**List**
onClickItem
Selection - kept selection instead of onClickItem
**MaskedInput**
Date
Filtered
IPv4 address
Size + units
URL
**Select**
Multiple
**TextInput**
onSelect and onSuggestionSearch
Simple
**WorldMap**
Simple
Number of chromatic snapshots should decrease by 14.
No
No
> Removed some stories from chromatic testing

- src/js/components/Select/index.d.ts
In Select index.d.ts options has the number array type:
`options: (string | boolean | number | JSX.Element | object)[];`
but this array type wasn't included in value.
Changed value to include number type
`value?: string | JSX.Element | number | object | (string | number | object)[];`
**NOTE**
most of the changes in this PR are due to prettier. The only real change is line 49.
Select index.d.ts
Closes #4451 
No
Maybe
> TS added number option to Select value

- .circleci/config.yml
Tests are successfully running locally, but are failing on CircelCi. The node image version in CircelCi might be the reason.
> Updated docker image of node

- src/js/components/List/List.js
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/utils/styles.js
Updates the way focus is handled within List. In order for the click event to properly propagate, we have to restore focus on the List container after the onClick of the list item has completed. However, for a brief interim (when the user has the mousedown, but has not completed the click event), the individual list item has focus in the DOM. At this stage, the focus indicator was being pulled away from the list container to wrap around an individual list item— creating a jumpy behavior of the focus indicator. Since the focus is restored to the list container as soon as the onClick finishes, we wanted to eliminate this visual jump of the focus before wrapped briefly around an individual list item.
@ericsoderberghp and I worked through a couple variations to this approach. We noted that …
> Fix onClick event for List and handle focus

- src/js/components/RadioButtonGroup/RadioButtonGroup.js
Previously theme.radioButtonGroup.container.gap would override the `gap` prop for RadioButtonGroup. Now `gap` takes precedence 
storybook
```javascript
import { storiesOf } from '@storybook/react';
import { Box, Grommet, RadioButtonGroup } from 'grommet';
radioButtonGroup: {
container: {
gap: 'xlarge',
},
},
};
const CustomRadioButtomGroup = ({ value: initialValue, ...props }) => {
const [value, setValue] = useState(initialValue);
return (
<Grommet theme={customTheme}>git 
<Box align="center" pad="large">
<RadioButtonGroup
gap='medium'
name="radio"
options={[
{ label: 'Choice 1', value: 'c1' },
{ label: 'Choice 2', value: 'c2' },
{ label: 'Choice 3', value: 'c3' },
]}
value={value}
onChange={event => …
```
> RadioButtonGroup `gap` prop overrides theme.radioButtonGroup.container.gap

- package.json
- yarn.lock
We need to update the grommet dependencies. This PR is upgrading all dependencies except the `styled-components` one due to the breaking changes on the tests, see https://github.com/styled-components/styled-components/releases/tag/v5.2.0  for more insight.
The styled-components upgrade will be isolated to a separate and more thought-through PR.
> Updated dependencies - styled-components excluded

- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/buildState.js
Closes #4484
Adds support for nested object in sort of DataTable
`src/js/components/DataTable/buildState.js `
Unit tests
Storybook
#4484
[Shimi] Yes, DataTable to support nested object on sort
It's backwards compatible
> feat(DataTable): Add support for nested object in sort

- src/js/components/Button/StyledButtonKind.js
- src/js/components/DataTable/Header.js
- src/js/components/DataTable/README.md
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- src/js/utils/styles.js
This PR extends theming capabilities of data table header cells. The contents of this cell can include a label (clickable if column is sortable, otherwise just text/custom render), a search button (not encouraged but already exists and left untouched), and a resizer. The `theme.dataTable.header` structure now supports:
```
background: undefined,
border: undefined,
font: {
weight: undefined,
size: undefined,
},
gap: 'small', // previously defined inline, but now giving users to style via theme and setting inline value as default
hover: {
background: undefined,
},
pad: undefined,
```
`background` and `border` will apply to the overall `th`, but the remaining will affect the styling of the content instead. In the case that the content is just a Text, then it will be applied to the Box …
> Update theme styling options for DataTable header

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
A quick enhancement/fix to this [recently merged PR](https://github.com/grommet/grommet/pull/4542). We want the header content to flex="grow" to fill any available space even when there is no `search` or `resizer` -- in the previous implementation the logic only applied when resizing or searching was present in the header cell. There are cases where a header cell has a sortable button (but is not searchable or resizeable) and we would still want the button to take up any available space. This just shifts where the content becomes wrapped.
src/js/components/DataTable/Header.js
Jest tests updated.
Tested on `Sort` story with and removed any `search` and `resizeable` from the DataTable
```
dataTable: {
header: {
background: 'skyblue',
border: {
color: 'green',
size: …
```
> Content should fill any available space in header cell

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
This PR updates the logic so that when a DataTable is not sortable, the column label is still able to receive layout props from the theme. Additionally, an update is made to ensure that extend will be applied on this Box correctly. Previously, `extend` was being applied properly to sortable column headers but not those that are plain text.
src/js/components/DataTable/Header.js
No.
No.
> Allow layoutProps to affect Text when DataTable not sortable

- yarn.lock
Updates yarn.lock integrity check for grommet-icons stable branch.
yarn.lock
At first I thought including the stable branch of grommet-icons was a mistake because the package.json specifies "^4.2.0", but then realized that it is being included because of grommet-theme-hpe.
No.
No.
> Updating yarn.lock with latest grommet-icons

- src/js/components/DataTable/Cell.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Fixes data + column configuration which causes app crash.
Closes https://github.com/grommet/grommet/issues/4487
Closes https://github.com/grommet/hpe-design-system/issues/1099
Review error reproduction: https://codesandbox.io/s/aggregating-on-property-of-nested-object-rs27r?file=/src/App.js
Modified unit test to reproduce the error, then placed fix.
Recreate https://codesandbox.io/s/aggregating-on-property-of-nested-object-rs27r?file=/src/App.js
https://github.com/grommet/grommet/issues/4487
https://github.com/grommet/hpe-design-system/issues/1099
No.
Sure.
> fix-4487 nested obj + aggregate with custom render

- src/js/components/Calendar/__tests__/Calendar-test.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
Adds a fixed reference date to a Calendar test to prevent the snapshot and test breaking when a new month arrives.
Jest
None.
No.
No.
> fixes wandering date in calendar test snapshot

- src/js/components/Grommet/index.d.ts
Signed-off-by: Hassan Usman <husseyexplores@gmail.com>
Fixes #4545
Added the missing `containerTarget` type in the type definitions.
https://github.com/husseyexplores/grommet/commit/6ecfc49ab378795bb8124d85a844128806771003
-
-
-
#4545 
No
No
-
> Add missing type in GrommetProps

- src/js/components/DataTable/Footer.js
- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Allows DataTable footer to be pinned on Safari by applying relative positioning to `tfoot`.
DataTable/Footer.js
DataTable/StyledDataTable.js
Storybook DataTable / "Fill and pin" on Safari (13), FF(78), Chrome/Edge (84)
Storybook DataTable / "Fill and pin" on Safari (13), FF(78), Chrome/Edge (84)
Primary implementation of pinned behavior applies to th/td in DataTable cells (largely b/c of a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=702927) which does not allow for relative positioning on thead). `td/th` in `tfoot` in Safari is not behaving in the same manner, thus the need to apply the relative positioning at the `tfoot` level.
https://github.com/grommet/hpe-design-system/issues/1133
No.
Sure.
> Fix 1128 - Allows DataTable footer to be pinned on Safari

- src/js/utils/index.d.ts
Fixes error on TS theme with formField.border.error.color
Test with a TS theme that contains
```
formField: {
border: {
color: "border",
error: { color: { dark: "white", light: "status-critical" } },
position: "inner",
side: "bottom"
},
}
```
Closes #4519 
No
No
> TS fixed BorderType for FormField

- src/js/components/RangeInput/__tests__/RangeInput-test.js
- src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
Add specs for `RangeInput` when users fire events like: `onFocus`, `onBlur` and `onChange` 
`src/js/components/RangeInput/__tests__/RangeInput-test.js`
No
See #4539 
No
> Add RangeInput specs for events

- src/js/components/List/index.d.ts
Update `List` existing typings for event handlers: `primaryKey`, `secondaryKey`
`src/js/components/List/index.d.ts`
This has been tested on a local TS project
Testing the List secondaryKey story in the storybook
#3165 
No
No
> Add primaryKey and secondaryKey event typings

- src/js/components/Meter/index.d.ts
- src/js/components/Meter/stories/typescript/MultipleValues.tsx
Update List existing typings for `onHover `and `onClick` event handlers
`src/js/components/Meter/index.d.ts`
Testing through a local TS project
Testing the `Meter` Multiple values story in the storybook
[#3165](https://github.com/grommet/grommet/issues/3165)
No
No
> Add Meter type definitions for event handlers

- src/js/components/Main/__tests__/Main-test.js
- src/js/components/Main/__tests__/__snapshots__/Main-test.js.snap
Signed-off-by: Evan Silverman <es4753@nyu.edu>
Introduce testing for Main component because there was none previously.
`/src/js/components/Main/__tests__/Main-test.js`
#4539
Before (80% coverage):
After (100% coverage):
No
> Improve Test Coverage for Main component

- src/js/components/Anchor/__tests__/Anchor-test.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.js.snap
Signed-off-by: Evan Silverman <es4753@nyu.edu>
Add testing for `size` prop, `onFocus`, and `onBlur` to raise coverage to 100%.
`/src/js/components/Anchor/__tests__/Anchor-test.js`
#4539 
Before (82.93%)
After (100%)
No
> Improve Anchor Component Test Coverage

- src/js/components/RadioButton/README.md
- src/js/components/RadioButton/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Changed RadioButton docs to include icons.circle
doc.js
snapshots created.
Came across the missing docs via exploring #4465 
Also, I've verified typing works as expected.
Relevant to #4465 
done
No
> Changed RadioButton docs to include icons.circle

- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Signed-off-by: Evan Silverman <es4753@nyu.edu>
`onPreviousMenuItem` had little coverage so I introduced tests to open the Menu with the `up` key and to navigate backwards through the Menu with `shift + tab` keys. Also added a test for bottom aligned drop.
`/src/js/components/Anchor/__tests__/Menu-test.js`
#4539
Before (80.52%)
After (97.40%)
No
> Improve Testing Coverage for Menu

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Updated Button kind `plain` deprecation docs not to be used with kind button.
doc.js
#4492 
Done.
No.
backward compatible.
> Updated Button kind plain deprecation docs

- src/js/components/Box/README.md
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds support to set width in width object prop.
`src/js/components/Box/StyledBox.js`
Unit
Storybook
#4591
> Feat(Box): support width value on width object prop

- src/js/components/Text/StyledText.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/Text/stories/All.js
Adds a `max-width: 100%;` to Text span when truncation is applied. This is to ensure that even when text is end-aligned in its surrounding Box that the text can be truncated. Currently, if a Box applies `align="end"`, the truncation will not apply and instead the text will attempt to expand out of the bounds of the Box.
src/js/components/Text/StyledText.js
Jest test and added storybook test so that it can captured by Chromatic.
```
<Box align="end" width="small" pad="small">
<Text truncate>Hi this is a very very long string</Text>
</Box>
```
Before:
After:
> Allow truncation with end aligned text to work

- src/js/components/Heading/Heading.js
- src/js/components/Heading/README.md
- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
- src/js/components/Heading/index.d.ts
- src/js/components/Heading/stories/All.js
- src/js/components/Paragraph/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Addresses #4593 :
- Add prop `fill` to Heading -> `Heading.js` and `StyledHeading.js`
- Remove `const {...} = props` from `Heading.js`. Instead, pass props as object.
- Add prop `fill` to docs: `doc.js` (prettier also removed some spacing) and type to `index.d.ts`
- Add storybook example (`All.js`) and unit test (`Heading-test.js`)
- `doc.js` reflected changes on `Heading/README.md`
- Updated snapshots changed in the process
`Heading.js` and `StyledHeading.js`
Storybook, unit test (Jest) and manual testing.
Add `fill` prop to a Heading component. It should have style `max-width: none`.
Also check reducing the screen to a width smaller than 768px. It should have the same prop.
Closes #4593 
Yep. Already done.
> Add  prop 'fill' to Heading

- src/js/components/Grid/__tests__/Grid-test.js
Fixed a bug that was introduced in #4612 
`src/js/components/Grid/__tests__/Grid-test.js`
`yarn test`
No
#4539 
No
No
> Fixed a bug where only the border test run for the Grid component

- src/js/components/DataTable/Searcher.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- Add missing `aria-label` to the search field in `DataTable`
- Update `aria-label` for the search button in `DataTable`
- Update query selector to find the search button in `DataTable` test
- `__snapshot__` automatically updated
`Searcher.js`
Storybook, jest, manual. Verified using WAVE tool (see screenshot below).
Verify that correct `aria-labels` are set.
Closes #4347
No
Meh
> Fix aria-label for DataTable searcher

- src/js/components/DataChart/stories/Simple.js
- src/js/components/DataTable/stories/ResizableColumns.js
- src/js/components/List/List.js
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/List/stories/secondaryKey.js
* Implements the already documented behavior of `theme.list.exted` and `theme.list.item.exted`.
* Cleaned up stories
Anywhere. Snapshot changes are reasonable since StyledList and StyledListItem had changed.
jest + storybook
storybook.
I got a separate story to test the list behavior on a separate PR of Tip component #4599 
No
Fixed theme `extend` for List 
> Updated list theme extend and stories

- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Closes #4366 
Maskedinput docs - mask
None, only documentation changes
https://codesandbox.io/s/grommet-buttons-forked-5i1vc?file=/index.js
When using regex to match number values with options that are strings, a user is unable to input more values when the regex matches the option. If the option values are numbers this will not happen.
#4366 
Yes
No
> added to maskedinput docs

- src/js/components/WorldMap/stories/Color.js
- src/js/components/WorldMap/stories/SelectPlace.js
Removed chromatic snapshots for WorldMap stories Color and SelectPlace because snapshots were similar to other WorldMap snapshots and we are trying to reduce the number of snapshots
storybook
number of chromatic snapshots should be reduced by 2 (303 -> 301)
No
No
> removed WorldMap stories Color and SelectPlace from chromatic

- storybook/main.js
Updated loader of storybook to include 46 missing stories: 
1. Context stories '../src/js/contexts/**/*stories.js',
2. All stories '../src/js/all/**/stories/*.(ts|tsx|js|jsx)',
3. stories with the format file of `stories.js` '../src/js/components/**/*stories.js', '../src/js/contexts/**/*stories.js',
4. Added missing typescript stories under stories/typescript/*.tsx
main.js
storybook
storybook imports all the stories mentioned above.
Related to PR #4651 
no
no
> Updated loader of storybook to include context stories and 'All' stories

- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Adds Menu tests for case where theme has `theme.button.default` defined.
src/js/components/Menu/__tests__/Menu-test.js
Added jest tests.
No.
No.
> Enhance Menu testing to test theme with button.default

- src/js/components/Image/__tests__/Image-test.js
improve coverage for Image to %100
`src/js/components/Image/__tests__/Image-test.js`
yarn test
yarn test
No
#4539
From 75%
To 100%
No
No
> improve coverage for Image

- src/js/components/Card/stories/Card.stories.js
- src/js/components/Card/stories/Clickable.js
- src/js/components/Card/stories/RichFooter.js
- src/js/components/Card/stories/Simple.js
- src/js/components/Card/stories/Stacked.js
- src/js/components/Card/stories/Themed.js
Organized the `Card/stories` by type of its component which is Layout.
`src/js/components/Card/stories/Card.stories.js`
- `yarn test`
- `yarn lint`
No
#4651 
No
No
> Organized Card stories structure

- src/js/components/Box/stories/Animation.js
- src/js/components/Box/stories/Background.js
- src/js/components/Box/stories/Border.js
- src/js/components/Box/stories/Box.stories.js
- src/js/components/Box/stories/Custom.js
- src/js/components/Box/stories/Elevation.js
- src/js/components/Box/stories/Fixed.js
- src/js/components/Box/stories/MinMax.js
- src/js/components/Box/stories/OnClick.js
- src/js/components/Box/stories/RTL.js
- src/js/components/Box/stories/Round.js
- src/js/components/Box/stories/Simple.js
Organized the `Box/stories` by type of its component which is Layout.
`src/js/components/Box/stories/Box.stories.js`
- `yarn test`
- `yarn lint`
No
#4651 
No
No
> Organized Box stories structure

- src/js/components/Grid/stories/AreasPropAlternative.js
- src/js/components/Grid/stories/Border.js
- src/js/components/Grid/stories/Grid.stories.js
- src/js/components/Grid/stories/NColumn.js
- src/js/components/Grid/stories/Percentages.js
- src/js/components/Grid/stories/Responsive.js
- src/js/components/Grid/stories/ResponsiveCards.js
- src/js/components/Grid/stories/typescript/App.tsx
Organized the `Grid/stories` by type of its component which is Layout.
`src/js/components/Grid/stories/Grid.stories.js`
- `yarn test`
- `yarn lint`
No
#4651 
No
No
> Organized Grid stories structure

- src/js/components/Tabs/stories/AlignControls.js
- src/js/components/Tabs/stories/Custom.js
- src/js/components/Tabs/stories/Icon.js
- src/js/components/Tabs/stories/Responsive.js
- src/js/components/Tabs/stories/Rich.js
- src/js/components/Tabs/stories/Scrollable.js
- src/js/components/Tabs/stories/States.js
- src/js/components/Tabs/stories/Tabs.stories.js
- src/js/components/Tabs/stories/Uncontrolled.js
- src/js/components/Tabs/stories/typescript/Controlled.tsx
Update Tabs stories to Controls/Tabs.
`components/Tabs/stories/Tabs.stories.js`
Storybook
Visit storybook using PR's branch and check Controls/Tabs.
#4651
No.
> Tabs stories changed to new structure

- src/js/components/Menu/stories/BottomControlButton.js
- src/js/components/Menu/stories/ItemWithIcon.js
- src/js/components/Menu/stories/Menu.stories.js
- src/js/components/Menu/stories/Reverse.js
- src/js/components/Menu/stories/Simple.js
- src/js/components/Menu/stories/typescript/Children.tsx
- src/js/components/Menu/stories/typescript/Themed.tsx
Update Menu stories to `Controls/Menu`.
`components/Menu/stories/Menu.stories.js`
Storybook
Visit storybook using PR's branch and check Controls/Menu.
#4651
No.
> Menu stories changed to new structure

- src/js/components/Header/stories/Header.stories.js
- src/js/components/Header/stories/Responsive.js
- src/js/components/Header/stories/typescript/Simple.tsx
Organized the `Header/stories` by type of its component which is Layout.
`src/js/components/Header/stories/Header.stories.js`
- `yarn test`
- `yarn lint`
No
#4651 
No
No
> Organized Header stories structure

- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/StyledMaskedInput.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/MaskedInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `maskedInput.container.extend` to theming to match what is already implemented in `StyledTextInput`. This allows users to extend styling on the container that wraps both the `input` and the icon (if present). The functionality already exists on TextInput but was not present on MaskedInput.
src/js/components/MaskedInput/StyledMaskedInput.js
Added jest test.
Local storybook with custom theme.
No.
> Extend MaskedInput theming

- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/TextArea/README.md
- src/js/components/TextInput/README.md
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/themes/__tests__/theme-test.js
- src/js/themes/base.d.ts
- src/js/utils/styles.js
- src/js/utils/themeDocUtils.js
Add `extend` to global.input in theme. This will allow users to add extended styling across inputs (TextInput, MaskedInput)
src/js/utils/styles.js
Added jest test.
Local storybook testing.
yes, updated here.
no.
> Add global.input.extend to theme

- src/js/components/Layer/stories/Center.js
- src/js/components/Layer/stories/Corner.js
- src/js/components/Layer/stories/Form.js
- src/js/components/Layer/stories/Full.js
- src/js/components/Layer/stories/Layer.stories.js
- src/js/components/Layer/stories/Margin.js
- src/js/components/Layer/stories/Notification.js
- src/js/components/Layer/stories/Plain.js
- src/js/components/Layer/stories/RTL.js
- src/js/components/Layer/stories/ScrollBody.js
- src/js/components/Layer/stories/Target.js
Organized the `Layer/stories` by type of its component which is Layout.
`src/js/components/Layer/stories/Layer.stories.js`
- `yarn test`
- `yarn lint`
No
#4651
No
No
> Organized Layer stories structure

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Collapsible/Collapsible.js
When the Collapsible is closed the user can still tab the focus to the elements within the Collapsible. This PR changes the way they children of the Collapsible render. The children will only render when the Collapsible is open or animating. The user will no longer be able to tab the focus to the children when the Collapsible is closed.
Related to https://github.com/grommet/grommet/pull/4501
Collapsible.js
Tested with Collapsible Nested story
With Collapsible storybook stories
Closes #4498
No
No
> Fix Collapsible tab focus

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
This PR updates the internal logic of Menu so that if a theme defines `theme.button.default`, then the Menu button will use the default button styling for its control as opposed to a `plain` button. The existing issue was that if Button has children, it acts as plain, so a Menu button was built by creating a Box (with direction row) and adding in the label/icon to appear like a Button. However, any button hover styles etc. no longer apply.
It makes more sense that the button control would not rely on children/plain (as this is a practice we want to avoid when possible) and instead relied on the `label` and `icon` props. This approach enhances the logic so that if a theme has `theme.button.default`, the menu control will inherit all the stylings of default button. This seemed like a more …
> Update Menu Button logic to account for default button

- src/js/components/Heading/stories/All.js
- src/js/components/Heading/stories/Color.js
- src/js/components/Heading/stories/CustomHeading.js
- src/js/components/Heading/stories/Extend.js
- src/js/components/Heading/stories/Heading.stories.js
- src/js/components/Markdown/markdown.stories.js
- src/js/components/Paragraph/stories/All.js
- src/js/components/Paragraph/stories/Paragraph.stories.js
- src/js/components/Paragraph/stories/Themed.js
- src/js/components/Text/stories/All.js
- src/js/components/Text/stories/Color.js
- src/js/components/Text/stories/Text.stories.js
- src/js/components/Text/stories/WordBreak.js
Changes Type components (Heading, Markdown, Paragraph, Text) stories to be organized under Type in storybook
Storybook
Storybook
#4651 
No
No
> Storybook restructure Type components

- src/js/components/Keyboard/stories/Keyboard.stories.js
- src/js/components/Keyboard/stories/OnDocument.js
Adds a demo/example of the `Keyboard` component in Storybook, under the **Utilities** section
`src/js/components/Keyboard/stories`
`npm run storybook`
No
> Add Keyboard in Storybook examples

- src/js/components/DataTable/stories/Clickable.js
- src/js/components/DataTable/stories/ColumnSize.js
- src/js/components/DataTable/stories/Controlled.js
- src/js/components/DataTable/stories/ControlledGrouped.js
- src/js/components/DataTable/stories/Custom.js
- src/js/components/DataTable/stories/DataTable.stories.js
- src/js/components/DataTable/stories/Fill.js
- src/js/components/DataTable/stories/Grouped.js
- src/js/components/DataTable/stories/InfiniteScrollDataTable.js
- src/js/components/DataTable/stories/NoPrimary.js
- src/js/components/DataTable/stories/ResizableColumns.js
- src/js/components/DataTable/stories/Select.js
- src/js/components/DataTable/stories/Served.js
- src/js/components/DataTable/stories/Simple.js
- src/js/components/DataTable/stories/Sized.js
- src/js/components/DataTable/stories/Sort.js
- src/js/components/DataTable/stories/Styled.js
- src/js/components/DataTable/stories/Tunable.js
- src/js/components/DataTable/stories/typescript/Clickable.tsx
Organize the datatable storybook stories in Visualizations type
`src/js/components/DataTable/stories/DataTable.stories.js`
Tests on Storybook Dashboard
#4651 
No
No
> Refactor datatable stories to new format

- src/js/components/Grid/index.d.ts
[This PR](https://github.com/grommet/grommet/pull/4612) added border support for Grid. This adds the `border` prop to the Grid typing.
The Grid component's typing
Just making sure it compiles
Try using the Grid component with a border in a typescript app
Nope
Relevant PR: https://github.com/grommet/grommet/pull/4612
Was already mentioned to be updated in the other relevant PR
Yes
Nope
> Add border prop to Grid typing

- src/js/components/Keyboard/stories/OnDocument.js
The OnDocument story for Keyboard creates a lint warning because of alert (line 9). This PR disables the lint warning for this story.
OnDocument.js
yarn lint
yarn lint
No
No
> Disable yarn lint warning on Keyboard story

- src/js/components/Select/stories/Controlled.js
- src/js/components/Select/stories/Custom.js
- src/js/components/Select/stories/CustomSearch.js
- src/js/components/Select/stories/Dark.js
- src/js/components/Select/stories/InsideFormField.js
- src/js/components/Select/stories/LazyLoadingOptions.js
- src/js/components/Select/stories/ManyOptions.js
- src/js/components/Select/stories/Multiple.js
- src/js/components/Select/stories/ObjectMultiple.js
- src/js/components/Select/stories/ObjectOptions.js
- src/js/components/Select/stories/Search.js
- src/js/components/Select/stories/Seasons.js
- src/js/components/Select/stories/Select.stories.js
- src/js/components/Select/stories/Simple.js
- src/js/components/Select/stories/Themed.js
- src/js/components/Select/stories/Uncontrolled.js
- src/js/components/Select/stories/Unselect.js
- src/js/components/Select/stories/typescript/CreateOption.tsx
Organized storybook stories for Select, and did some cleanups.
**Note:** It might be interesting to check which stories should have `chromatic: disable` param, as PRs such #4502 removed some of them but there were some leftovers in Select stories, such as (quotes from grommet/master):
-This one refers to Object Multiple, but ObjectMultiple chromatic disable was removed.
https://github.com/grommet/grommet/blob/c4e8a025cc1f3a868bfe7e2531e6b8236e002e52/src/js/components/Select/stories/Multiple.js#L28-L31
https://github.com/grommet/grommet/blob/c4e8a025cc1f3a868bfe7e2531e6b8236e002e52/src/js/components/Select/stories/ObjectMultiple.js#L52
-This one had this note that I don't know if should be kept.
https://github.com/grommet/grommet/blob/c4e8a025cc1f3a868bfe7e2531e6b8236e002e52/src/js/componen …
> Select stories changed to new structure

- src/js/components/Layer/LayerContainer.js
Changed LayerContainer to use trapFocus by default, so the background of the modal won't trap the focus.
LayerContainer
Storybook https://storybook.grommet.io/?path=/story/layout-layer--corner-layer
Storybook https://storybook.grommet.io/?path=/story/layout-layer--corner-layer
The root-cause was https://github.com/grommet/grommet/pull/4378
Closes #4721 
No
Yes
b/c
> Changed LayerContainer to use trapFocus

- src/js/components/Table/README.md
- src/js/components/Table/doc.js
- src/js/components/Table/stories/Custom.js
- src/js/components/Table/stories/Default.js
- src/js/components/Table/stories/InfiniteScrollInTable.js
- src/js/components/Table/stories/MeterInTable.js
- src/js/components/Table/stories/Table.stories.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Organized storybook stories for Table to be under 'Visualizations' section
Fixed the link to Table stories in the grommet documentation (related to https://github.com/grommet/grommet-site/issues/185)
Storybook
Storybook
And test link https://storybook.grommet.io/?selectedKind=${availableAt}&full=0&addons=0&stories=1&panelRight=0 with ${avaliableAt} set to one of the stories that has already been changed (format for avaliableAt is type-component) to updated structure or with Table on localhost
#4651 
No
No
> Storybook story organization for Table and routing fix

- src/js/components/Box/README.md
- src/js/components/Box/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Signed-off-by: Zack Urben <zackurben@gmail.com>
Fixes spelling issue in the Box component docs
Looking at the diff or [live docs](https://v2.grommet.io/box#gap)
None, cant figure out the proper way to build the docs site.
Build the docs site and check the spelling
I made this patch in the Web IDE - I may need to fix the sign-off statement.
N/A
N/A
Yes
No
> Fix: Spelling fix in Box docs

- src/js/components/Video/index.d.ts
Signed-off-by: Ray Knight <array.knight+github@gmail.com>
Fix the Typescript types for the Video component and its props
src/js/components/Video/index.d.ts
None
See: https://github.com/grommet/grommet/issues/4746
Only effects Typescript types
https://github.com/grommet/grommet/issues/4746
No, they're accurate
Yes? It's a minor fix but worth surfacing
Yes
> fix: Video prop and component types

- src/js/components/DateInput/index.d.ts
Signed-off-by: Arthur Sakemi <arthursakemi@gmail.com>
Fix the TS types for the onChange event in DateInput component
described on issue #4738
src/js/components/DateInput/index.d.ts
None
Only effects Typescript types 
#4738
No, the current docs are accurate
Don't think so
> Fix: TS types for the onChange event in DateInput component

- src/js/components/Text/README.md
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Clarifies that for `global.colors.text` to take effect, the theme must also define `global.colors.background`. Some approaches were considered that could try to apply the text color even if no background was defined, however this posed backwards compatibility concerns. Instead, it was decided that clarifying the docs would be sufficient. 
The thread discussion and resolution can be found here: https://github.com/grommet/grommet/issues/4606#issuecomment-729042646
src/js/components/Text/doc.js
Jest snapshots updated.
Default Text color is applied only when a theme defines theme.global.colors.background.
Closes https://github.com/grommet/grommet/issues/4606
No.
> Update Text doc to clarify global.colors.text usage

- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
DataTable's sort property allows an `external:true` flag that makes it not actually sort the table (although it still allows clicking the column headers result in onSort() getting called if defined. However, when it does call onSort() it changes the current sort options and in the process removes any `external` flag.
This change makes it retain any original external flag from the `sort` property, if present.
DataTable.js
StoryBook DataTable example plus a new Jest testcase.
Create a similar example as shown in https://codesandbox.io/s/grommet-v2-template-forked-ly6rc?fontsize=14&hidenavigation=1&theme=dark
Fixes #4703 
No
No
> Made DataTable onSort honor the origin sort external flag if present

- src/js/components/CheckBoxGroup/CheckBoxGroup.js
- src/js/components/CheckBoxGroup/README.md
- src/js/components/CheckBoxGroup/StyledCheckBoxGroup.js
- src/js/components/CheckBoxGroup/__tests__/CheckBoxGroup-test.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
- src/js/components/CheckBoxGroup/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `checkBoxGroup` to theme and supports `checkBoxGroup.container` which accepts all Box props (aligned with `radioButtonGroup.container`. This allows users to control gap, margin, etc. of checkboxgroup from theme. Previously `gap` was only available to be controlled via prop.
src/js/components/CheckBoxGroup/CheckBoxGroup.js
Added jest test and tested locally with storybook.
Create custom theme in storybook.
Users could only control the gap between checkboxes in checkboxgroup via prop. This is not ideal from applications that want to consistently apply gap across many instances (or for design system usage).
Related to https://github.com/grommet/hpe-design-system/issues/1246
In this example, a margin has been applied to the checkboxgroup itself to create the desired dimensions within a …
> Enhance CheckBoxGroup theming

- src/js/components/Layer/LayerContainer.js
Does not restrict page scroll when a layerTarget is present. A previously merged PR monitored for scroll event and that was working for the tested implementation. However, if a `Grommet` component is provided with `height="auto"` (to properly calculate the height of the entire page), suddenly the page still would not scroll. In order to overcome this, we need to adjust the `restrictScroll` prop, that is used internally for Layer in modal cases, to only be true if a Layer does not have a target.
src/js/components/Layer/LayerContainer.js
Tested locally with a long page with Layer with a target on a Box contained in the page. Grommet component of the example was given `style={{height: 'auto'}}`. 
Same as above.
Modal layer + target was restricting scroll on pages with height="auto". …
> Dont restrict scroll when layerTarget present

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to be more resilient to invalid properties when using bars.
Previously, if a `chart={[{ property }]}` didn't match any `series` data when the chart `type='bars'`, it would throw an exception. Now, it is more resilient and just doesn't show anything instead.
This change makes it possible for grommet-designer to let the user to type out the property without crashing.
DataChart.js
Added unit tests.
verified with grommet-designer
check unit tests
no
yes
> Changed DataChart to be more resilient to invalid properties when using bars

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to fix an issue with stacked bars colors.
You can see how typescript allows `property={[{ property: 'a', color: 'graph-1' }, ...]}`.
This fixes DataChart to be able to handle it.
DataChart.js
ran a custom story to validate as well
well, eventually the DataChart docs need some overhaul.
yes
> Changed DataChart to fix an issue with stacked bars colors

- src/js/components/Grid/README.md
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- Fixes Grid `columns` typing warning when using values different from common Grommet sizes.
- Remove type duplicates on Grid interface.
`src/js/components/Grid/doc.js`
Manual testing.
```js
const colors = [
'forestgreen',
'orange',
'wheat',
'sienna',
'salmon',
'lightcoral',
'olive',
'thistle',
'tan',
];
export const AppGrid = () => {
return (
<Grommet full theme={grommet}>
<Grid
fill
gap="small"
rows="min-content"
columns={{ count: 3, size: ['300px', '400px'] }}
>
{colors.map((color, i) => (
<Box key={color} background={color}>
<Text>{i % 2 === 0 ? 'foo' : 'bar'}</Text>
</Box>
))}
</Grid>
</Grommet>
);
};
```
Values such as `min-content` and `max-content` could also be used.
#4767 
Just typing. Already did.
> Fix Grid columns prop incorrect type warning

- src/js/components/Clock/README.md
- src/js/components/Clock/StyledClock.js
- src/js/components/Clock/__tests__/Clock-test.js
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
- src/js/components/Clock/doc.js
- src/js/components/Clock/stories/Digital.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
The second part of splitting PR #4656
- Fix component breaking when providing undefined or incomplete object size to digital clock. Now, if the size passed as prop doesn't exist, `medium` size will be used. Also, considering that for Digital Clock size is defined as `{ size: "VALUEpx", height: value}`, if any of these props is missing, `medium` size/height will be used instead.
- Add unit test for custom size Digital Clock.
- Add Digital Clock styling properties to docs.
- Update Digital story to showcase all sizes.
`src/js/components/Clock/StyledClock.js`
Storybook and unit testing.
```js
const override = {
clock: {
digital: {
text: {
customSize: {
size: '30px',
height: 1.234,
},
customMissingSize: {
height: 1.234,
},
customMissingHeight: {
size: '30px',
}
},
},
},
};
const theme = …
```
> Fix Digital Clock breaking with undefined/incomplete size prop

- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/stories/Search.js
https://github.com/grommet/grommet/issues/2961
Previously it was impossible to select multiple values using search. Fix this case.
The problem was that options change when they are filtered using search. So indexes of selected values are invalid. Now we always use the initial list of options, so the indexes will always be valid.
tested selecting multiple values using search and without using search
```
<Select
size="medium"
placeholder="Select"
multiple
value={value}
options={options}
closeOnChange={false}
onChange={({ value: nextValue }) => setValue(nextValue)}
onClose={() => setOptions(defaultOptions)}
onSearch={text => {
const escapedText = text.replace(/[-\\^$*+?.()|[\]{}]/g, '\\$&');
const exp = new RegExp(escapedText, 'i');
setOptions(defaultOptions.filter(o => exp.test(o)));
}}
/> …
```
> fix selectMultiple + search

- src/js/index.d.ts
Adds missing `Tip` TypeScript export
Tested/confirmed on local dev ENV.
Attempt to `import { Tip } from 'grommet';`
No
No
> chore: Updates index.d.ts with Tip export

- src/js/components/DataTable/Footer.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Changed DataTable Footer to fix an issue with showing pin background even in non-pinned situations
white-box test with Simple story
Storybook
no
yes
> Changed DataTable Footer to fix an issue with showing pin background even in non-pinned situations

- src/js/components/Select/README.md
- src/js/components/Select/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Added the following information to the Select `multiple` docs 
When multiple is true, 'value' should be an array of selected options and 'options' should be an array of possible options
Related Slack thread https://grommet.slack.com/archives/C09QQEG69/p1607119885347000?thread_ts=1607087274.344700&cid=C09QQEG69
Done
No
> Update Select `multiple` docs

- src/js/components/Layer/stories/Layer.stories.js
- src/js/components/Layer/stories/Timeout.js
New storybook example for Layer showing a Layer working with a timeout and a slide in and slide out animation. Disabled from chromatic because snapshot won't show animation or timeout behavior.
Storybook
Storybook
#4809 
No
No
> Layer Timeout Story With Animation

- src/js/components/Layer/README.md
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.js
Sets Layer z-index and Drop z-index to the same value. As Layer/Drop are appended to the DOM, the most recent one will take precedence over any other open portals. So, a Layer opened after a Drop will be on top, and vice versa.
Previously, Layer had a lower z-index than Drop which caused conflicts if a Drop was open when a Layer opened (the Drop would appear on top of the layer instead of behind).
src/js/themes/base.js
Tested scenarios with Drops inside Drops, Drops inside Layers, etc. to ensure the expected behavior remained.
Implement this as a story:
```
export const TestLayer = () => {
const [openDrop, setOpenDrop] = React.useState(true);
const [openLayer, setOpenLayer] = React.useState(false);
const [countdown, setCountdown] = React.useState(5); // seconds
const intervalId = …
```
> Adjust layer zindex to match drop

- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Heading/StyledHeading.js
- src/js/components/Paragraph/StyledParagraph.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/Text/StyledText.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
- src/js/components/TextInput/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/styles.js
Add `textAlign` property to TextInput.
Refactor the conversion of `textAlign` to CSS into utils and changed other places that use `textAlign` to use this util rather than duplicating its implementation.
One main use-case of `textAlign` in an input is in DataTables when TextInput is used for numeric data. In this case it is helpful to align the numbers like you would for static numeric cell data. See #4736 .
Note: some of the existing TextInput-related snapshots changed, likely due to how styled-components names css classes due to the 'empty' style when textAlign isn't defined, although the resulting styles are the same.
StyledTextInput.js and utils.js
Manual testing in storybook.
Added a Jest test case.
Manual testing in storybook.
#4736 
yes
Yes
> Added textAlign to TextInput

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
Resets uncontrolled input values when form has reset. Previously, if a Form reset, CheckBox/RadioButtonGroup/Select would not reset their value.
Tested with "Uncontrolled" storybook example and added jest test.
Uncontrolled Form example storybook.
Closes https://github.com/grommet/grommet/issues/4796
No.
Yes. "Uncontrolled input values properly reset when Form is reset."
> Reset inputs when form resets

- src/js/components/DataTable/index.d.ts
- src/js/components/DataTable/stories/DataTable.stories.js
- src/js/components/DataTable/stories/typescript/OnSelect.tsx
Fixes DataTable onSelect types by excluding the onSelect inferred from table
src/js/components/DataTable/index.d.ts
Storybook stories
See added storybook story or by linking the package and using DataTables onSelect -function
#4784 
No
> Fix DataTable onSelect type

- src/js/themes/base.d.ts
fix: added missing types for textInput > placeholder, placeholder, suggestions
add typescript types
typescript should still compile
no
no
no
no
> fix: added missing types for textInput

- src/js/components/Layer/README.md
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Update StyledContainer to allow custom styling through extend prop
So in your theme you can do as such:
```js
...grommet,
layer: {
container: {
extend: 'border-radius: 40px',
},
},
};
```
`src/js/components/Layer/StyledLayer.js `
`yarn test -u src/js/components/Layer`
#4805 
No
> Fix Layer container custom theming

- src/js/components/TextInput/README.md
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Follow-on to #4806 , this adds documentation for the newly added prop.
`doc.js`
I've run tests, manually inspected the auto-generated README file, and run `test-update` to update the README snapshots.
Manual inspection of the generated README is probably the best route.
See #4806 
#4781 
N/A
This does that.
Not separately from #4806 , no.
Backwards compatible (documentation only).
> Add docs for TextInput defaultSuggestion prop

- src/js/components/Chart/Chart.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
Changes Chart.js to sort a copy of the colors array rather than sorting the original and accidentally modifying it.
Chart.js
Storybook Chart examples and Jest test cases.
Look at the id and mask of the gradient in the storybook Chart gradients example.
Fixes #4858 
No
No
> Fix Chart to not modify passed in colors array property

- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
`kind` prop was leaking to the DOM. This change makes sure that it does not. In React 16, unknown attributes passed onto elements are no longer sifted out. See documentation here (https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html). Therefore, this change makes sure that no kind value is passed onto the DOM element.
src/js/components/Button/StyledButtonKind.js
Snapshot updates, only the `kind` attribute is being removed. no styling changes.
kind prop was leaking to the DOM, this removes it.
before:
after:
No.
No.
> Don't let kind attribute leak to DOM

- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
Disables animation for Layer tests that involved onClickOutside/onEsc. There have been occasional test failures, and I am wondering if the layer animation in the jest environment was causing timing issues. Disabling animation to see if that removes test failures consistently. If we see Layer test failures again in the future, then more investigation will be needed.
src/js/components/Layer/__tests__/Layer-test.js
Updated snapshots.
Occasional Layer test failures. They would pass sometimes, and fail on others. Animation was potentially causing that unreliability.
No.
No.
> Disable animation on layer tests

- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
When Layer receives full of any kind (true, vertical, horizontal, etc), the corners are touching the edge of the screen and should receive a radius of 0.
src/js/components/Layer/StyledLayer.js
Used border radius Layer story.
Necessary to apply desired behavior as demonstrated here and other designs such as global header menu layer:
No.
No.
Backwards compatible, this functionality has not yet been included in a release.
> Fix border radius when full

- src/js/components/Distribution/Distribution.js
- src/js/components/Distribution/__tests__/Distribution-test.js
- src/js/components/Distribution/__tests__/__snapshots__/Distribution-test.js.snap
Changed Distribution to fix an issue with undefined values.
If the caller passed `<Distribution values={[{ value: undefined }]} />` the browser would hang. This scenario can happen when editing a Distribution in grommet-designer.
Also changed the layout when a value is 0, to ensure it doesn't show anything.
Distribution.js
add a unit test
verified with grommet-designer
white box
no
yes
> Changed Distribution to fix an issue with undefined values

- src/js/components/Heading/README.md
- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Enhance theme to allow for `heading.color`.
src/js/components/Heading/StyledHeading.js
Tested in storybook custom heading and added a jest test
```
heading : {
color: 'text-strong',
}
```
With the above in a custom theme.
Theme now supports `theme.heading.color`
> Enhance heading theme to accept color

- src/js/components/DataTable/Body.js
Changed DataTable to use onMouseEnter for hover detection. This reduces the amount of re-rendering needed. There might be even more aggressive ways to tackle this down the road. But, this seems a good quick win.
whitebox 400 rows and onClickRow
same
#4881
no
yes
> Changed DataTable to use onMouseEnter for hover detection

- src/js/components/Form/Form.js
This PR allows click events, such as reset, to complete prior to onBlur validation. A state variable called `pendingValidation` and a useEffect hook track what input (if any) is awaiting validation from a blur event. A timeout is set to ensure that click events complete prior to running the validation. Without this, click events like reset, etc. were sometimes not being called because the click event was not being registered. See https://github.com/grommet/grommet/issues/4863 for detailed scenario.
The timeout value was tested across Chrome, Safari, and Firefox to empirically determine the minimum value.
Tested in Validate onBlur form story.
1. Type a letter into the first input
2. Click "Reset" button
Expected outcome: Form resets, no validation error is …
> Allow clicks to complete before running onBlur validation

- src/js/components/Meter/Meter.js
- src/js/components/Meter/README.md
- src/js/components/Meter/__tests__/Meter-test.js
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
- src/js/components/Meter/doc.js
- src/js/components/Meter/index.d.ts
- src/js/components/Meter/stories/Bar.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed Meter to accept a single value property and a color property.
This makes it easier to use for the 80% case where there is only one value.
index.d.ts
Revised the "Bar" storybook to use it.
Bar story
automatic
yes
> Changed Meter to accept a single value property

- src/js/components/InfiniteScroll/__tests__/InfiniteScroll-test.js
Closes https://github.com/grommet/grommet/issues/4908 by adding timers to Jest test, plus mocking `scrollIntoView` function which is called in some InfiniteScroll + show scenarios, but is not supported by JSDOM.
InfiniteScroll-test.js
Jest tests. 
Re: reliably reproducing issue - The issue was intermittent because the timer calling `scrollIntoView` could be longer than the duration of the test. Reducing the timeout duration allowed consistent reproduction, followed by use of Jest timers.
There is quite a bit of discussion on the JSDOM project about how to test components relying on the scroll APIs https://github.com/jsdom/jsdom/issues/1695#issuecomment-449931788.
https://github.com/grommet/grommet/issues/4908
No.
No.
> Fix 4908 - InfiniteScroll test timing and call to scrollIntoView

- src/js/components/Form/stories/Controlled.js
- src/js/components/Form/stories/Uncontrolled.js
- src/js/components/Layer/stories/Form.js
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/index.d.ts
- src/js/components/TextInput/stories/WithTags.js
- src/js/components/TextInput/stories/typescript/CustomSuggestions.tsx
Handling the double trigger of keypress up/down of TextInput suggestion.
The issue only reproduces on stable and not on an official release, the issue was introduced ~2 weeks ago with the new `capture` prop addition for the Keyboard component.
https://github.com/grommet/grommet/pull/4864
TextInput is currently using two instances of the Keyboard component and each one fired the onDown/onUp event, since `capture` was added, none of the events got waved, and each single keyboard arrow action was triggered twice.
Along with fixing the issue, this PR is attempting to clean-up some of the `onEnter` code duplications, and as a result of making `onEnter` as generic as possible for both keyboard instances the test file had to be changed since `onSelect` would no longer be called in case there is …
> Changed keyboard handling of TextInput suggestions

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Fixes condition that determines if styledplaceholder should show. We only want to show it if the placeholder is not a string (custom placeholder)
src/js/components/TextInput/TextInput.js
Tested in TextInput Icon story and styled placeholder. Added jest test.
In TextInput Icon story, type a value (placeholder should be removed). Then delete value, placeholder should appear.
Same in Styled Placeholder story.
In both, only one placeholder should be there.
showStyledPlaceholder was being set to true regardless of if placeholder was custom or not.
Closes https://github.com/grommet/grommet/issues/4922
No.
> Dont show styledplaceholder if placeholder is string

- src/js/components/List/README.md
- src/js/components/List/doc.js
- src/js/components/List/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Updates the prop type of `pad` in List to `padPropType`. This allows an object to be used to define pixel size `pad={{ vertical: '0' }}`
Storybook
added `pad={{ vertical: '0' }}` to List story
Storybook
Closes #4912 
Done
No
> Updated prop type for pad in List

- src/js/themes/base.d.ts
Bug Fix: updates the typings in `src/theme/base.d.ts`. The typings for the newly added text sizes `2xl, 3xl, 4xl, 5xl, 6xl` were incorrectly typed and non-optional. This updates the typings so the optional property is correctly outside of the string used for the key.
NA
NA
[4928](https://github.com/grommet/grommet/issues/4928)
No
No
Backwards
> Allow new Text sizes to be optional props

- src/js/components/Form/stories/RequiredLabel.js
- src/js/components/FormField/FormField.js
- src/js/components/FormField/README.md
- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/FormField/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Enhances the theme to allow users to enable an asterisk * to appear next to required form field labels. Alternately, they can provide a string or a custom JSX element (if they want their own symbol for example). Currently, grommet users have to create a custom label render component any time they want to have this functionality. Having a place in the theme to control this would remove the need for users to use a custom component on every instance of a required formfield.
If the user flags this theme item as "true", then grommet will automatically apply an a11yTitle of "required". This a11yTitle is necessary so that screen readers read out the symbol as "required" as opposed to "star". If a user provides a custom element, such as a custom icon, then it will render this. …
> Allow required formfield asterisk to be enabled in the theme

- package.json
- storybook/webpack.config.js
- yarn.lock
Signed-off-by: quaresma <j.quaresmasantos_98@hotmail.com>
Replace the unsupported devDependency `awesome-typescript-loader` to `ts-loader`, a TypeScript loader for webpack.
The reviewer should start running the command `yarn install` and check that warning bellow, does not appear anymore:
> awesome-typescript-loader@5.2.1" has incorrect peer dependency "typescript@^2.7 || ^3"
No test was written. Just was executed the existent tests
No test was written
This new TypeScript loader for webpack added, according to what I researched, it has greater support from the community and is commonly used in web applications that make use of TypeScript
The issue #4894
No need
I think not
I'm not sure
Waiting for your feedback.
> Replaced devDependecy awesome-typescript-loader to ts-loader

- src/js/components/CheckBoxGroup/CheckBoxGroup.js
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
Previously when the options array was updated using map or other methods that create a new array, the useMemo function wouldn't trigger. This PR removes useMemo from the options function so that when the options array is changed this function will be called.
This codesandbox shows RadioButtonGroup not updating
https://codesandbox.io/s/small-lake-uyt2p
Tested with the following storybook stories
CheckBoxGroup:
```javascript
import React, { useState } from "react";
import { Grommet, Button, CheckBoxGroup } from "grommet";
const GrommetComponent = (props) => {
const { options } = props;
const [value, setValue] = useState();
console.log(options);
return (
<CheckBoxGroup
labelKey="label"
valueKey="key"
value={value}
onChange={event => {
setValue(event.value);
console.log('Group2: ', …
```
> Fixed RadioButtonGroup and CheckBoxGroup to update with mutated array

- src/js/components/RangeSelector/RangeSelector.js
This PR made sure values of RangeSelector are updated when its bar is dragged quickly to max or min end. If the drag is too fast, values may not be updated in time. The previous method using `delta` won't apply to the correct values. 
The only file changed.
Manual testing using storybook. 
Test and compare the behavior of the Thin RangeSelector example in storybook. 
NA
#4927
NA
No.
Probably not. 
> Made sure RangeSelector values are updated when bar is dragged quickly to ends

- src/js/all/stories/AllComponents.js
- storybook/preview.js
In the new storybook format when storybook is opened, the AllComponents story is displayed. It is also listed first before every thing else. I moved the 'All' story outside of the 'Others' category so that the entire 'Others' category was not moved to the top.
storybook
No
No
> AllComponents Story Loaded First

- src/js/components/RadioButtonGroup/stories/CustomTheme.js
This PR adds an example of changing the text color for RadioButtonGroup into the already existing CustomTheme story. This is a common question people ask on Github and Slack so it will useful to have in a storybook example.
storybook
storybook
Closes #4935
No
No
> RadioButtonGroup CustomTheme story showing custom text color

- src/js/components/Tip/Tip.js
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap
Changes Tip to use `onMouseEnter` instead of `onMouseOver` to determine when the Tip should be displayed. Fixes an issue where Tip is displayed when hovering over the children of a disabled button.
Tested with the following storybook story as well as existing Tip stories.
```javascript
import { grommet, Text, Box, Button, Grommet, Tip } from 'grommet';
import { Copy } from 'grommet-icons';
export const TEST = () => (
<Box pad="small" gap="large" width="medium">
<Tip content="Tooltip should render as expected">
<Button label="Button" />
</Tip>
<Tip content="Tooltip should render as expected">
<Button label={<Text>Button with custom label</Text>} />
</Tip>
<Button
icon={<Copy />}
label="Button with Icon"
tip={{ content: 'Tooltip should …
```
> Updated Tip to use onMouseEnter instead of onMouseOver

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataChart/stories/Simple.js
Changed DataChart to be more resilient to empty properties.
This helps makes DataChart more resilient when used in designer.grommet.io.
Added unit tests.
Tested with grommet-designer locally
no
yes
backwards compatible, without these changes, the browser crashes
> Changed DataChart to be more resilient to empty properties

- src/js/components/Button/Button.js
- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/Button-kind-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
This PR ensures that StyledButtonKind uses size "medium" by default. Currently, it wasn't falling back to any size and this was causing discrepancies between buttons implemented as `<Button />` vs `<Button size="medium" />` but they should be identical.
src/js/components/Button/StyledButtonKind.js
Tested local in storybook, created custom theme with size definitions. Default (no size prop specified) and medium should be the same always.
Before (notice padding difference between default and medium):
After:
Noticed the HPE button dimensions had shifted after we removed padding values in this PR but when I looked into it further I also noticed that buttons implemented as `<Button label="Label" />` were not receiving styling for "medium" size like they should.
Noticed issue after …
> Button padding should use size "medium" by default

- src/js/components/FileInput/README.md
- src/js/components/FileInput/doc.js
- src/js/components/Pagination/README.md
- src/js/components/Pagination/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds config option to `doc.js` for Pagination and FileInput so that the urls built for Storybook on Grommet site resolve correctly.
`Pagination/doc.js`
`FileInput/doc.js`
Jest
No.
No.
> Fix docs config for storybook path

- src/js/all/stories/Colors.js
- src/js/all/stories/DefaultTheme.js
- src/js/all/stories/typescript/ExtendTheme.tsx
- src/js/all/stories/typescript/Focus.tsx
Removes Others section and moves Theme stories into Utilities
storybook
storybook
Closes #4943 
No
No
> Removed Others Section From Storybook

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/MaskedInput/doc.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/TextArea/README.md
- src/js/components/TextArea/TextArea.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextArea/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/utils/styles.js
- `focusIndicator` prop on inputs (TextInput, TextArea and MaskedInput) should only be valid if `plain` is set aswell. This PR fixes that.   
- Many snapshots were updated. Mostly due to changing `props.focus` to `&:focus { }`
`src/js/utils/styles.js`
Manual testing.
Play around with possible combinations using `plain` and `focusIndicator`.
```js
export const Simple = () => {
const [value, setValue] = React.useState('');
const onChange = event => setValue(event.target.value);
return (
<Grommet full theme={grommet}>
<Box fill align="center" justify="start" pad="large">
<TextInput
plain
focusIndicator={false}
value={value}
onChange={onChange}
/>
<TextArea
plain
focusIndicator={false}
value={value}
onChange={onChange}
/>
<MaskedInput
plain
focusIndicator={false}
value={value} …
```
> Fix focusIndicator behavior on components using inputStyle

- src/js/components/InfiniteScroll/InfiniteScroll.js
Provides a fix for #4934, allowing `onMore` to be triggered when manually resetting `DataTable` data.
Even though it's related to `DataTable`, the fix was made on `InfiniteScroll`, as it's the one handling `onMore` calls.
This issue has a use case that updates data dynamically, but when a manual reset is made, some internal states are kept. This fix verifies a condition that indicates a manual data reset (data length = 0, last page = 0, and pending length != 0). If the condition is valid, it resets pageHeights, pendingLength and renderPageBounds, which will make the DataTable behave just as how it works when it first renders.
Note that the given example starts with `currentData = [ ]`, and this should be consistently followed in order for this to work, meaning that the reset should set …
> Handle DataTable data reset with InfiniteScroll

- src/js/components/Form/Form.js
Fields with pendingValidation should be added to an array (as opposed to just a single value being accepted).
Tested in https://storybook.grommet.io/?path=/story/input-form-validate-on-blur--validate-on-blur
With above story, click into the first input and quickly hit tab twice (to blur the current input and the subsequent). The "required" validation error should appear on both.
Closes https://github.com/grommet/grommet/issues/4989
No.
Fixed an issue with Form onBlur validation timing.
> Change Form validation to create pendingValidation array

- src/js/components/Grommet/Grommet.js
- src/js/components/Menu/Menu.js
- src/js/components/Menu/README.md
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Menu/doc.js
- src/js/components/Menu/stories/Simple.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `theme.menu.drop` to theme to allow users to style their Menu drop from the theme rather than having to repeat the styling every time via props. This is beneficial for apps that always want a Menu to have drop alignment of, for example, `{ top: 'bottom', left: 'left' }`.
src/js/components/Menu/Menu.js
Tested in storybook example by creating custom theme and added jest test.
Create custom theme.
HPE Design System calls for Menu that is always aligned `{ top: 'bottom', left: 'left' }`. Instead of having teams implement on every Menu instance, it should come automatically from theme.
Related to https://github.com/grommet/hpe-design-system/issues/1416
Added `theme.menu.drop` to allow theming of Menu's drop alignment.
> Allow Menu drop to be themed, any Drop props accepted

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
Certain button theming is only available if the caller has defined `button.default` in their theme as well. This adds a note to the doc descriptions to clarify.
src/js/components/Button/doc.js
Updated here.
No.
> Update button docs to clarify what relies on button.default

- src/js/components/TableCell/index.d.ts
- src/js/components/TableRow/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the TableRow and TableCell components, forming part of issue #4998.
The only files changed are the TS declaration files for each of the components. The simplest is the TableRow component, so it's a good place to start.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing `TableRowExtendedProps` should make `tr` keys available, as well as general HTML keys like `children`.
All background context is available in this discussion/design issue: #4978
Progress tracking: #4998
Design/discussion: #4978
No
Not this PR specifically, …
> [TS] Fix TableRow and TableCell Prop Types

- src/js/components/Table/index.d.ts
- src/js/components/TableBody/index.d.ts
- src/js/components/TableFooter/index.d.ts
- src/js/components/TableHeader/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the Table, TableHeader, TableFooter and TableBody components, forming part of issue #4998.
The only files changed are the TS declaration files for each of the four components. Any of these files are good places to start
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing `TableExtendedProps` should make `table` keys available, as well as general HTML keys like `children`.
All background context is available in this discussion/design issue: #4978
Progress tracking: #4998
Design/discussion: #4978
No
Not this PR specifically, …
> [TS] Fix Table, TableHeader, TableFooter and TableBody Prop Types

- src/js/components/Sidebar/index.d.ts
- src/js/components/Stack/index.d.ts
- src/js/components/Tab/index.d.ts
- src/js/components/Tabs/index.d.ts
Add ExtendedProps declarations for Sidebar, Stack, Tab and Tabs components, forming part of issue #4998.
Reviewers can start from any of the files, there were independent changes only in TS declaration files
No additional tests were added
The import of any of the modified components in question will now have the respective _JSX.IntrinsicElements_ property 
Discussed in the #4978
Progress track: #4998
No
No
Yes
> [TS] Fix Sidebar, Stack, Tab and Tabs extended types

- src/js/components/Accordion/stories/Custom.js
Change the custom story in Accordion to use `hover.heading.color` instead of the deprecated `hover.color`. This gets rid of the console warning on this story.
Custom.js
Storybook
Storybook
No
No
> Fix warning on Accordion custom story

- src/js/components/Anchor/index.d.ts
- src/js/components/FormField/index.d.ts
- src/js/components/Image/index.d.ts
- src/js/components/TextArea/index.d.ts
This PR adds and exports ExtendedProps declarations for the Anchor, FormField, Image and TextArea components, forming part of issue #4998.
Any of the type definition files, the changes should be simple to understand, it's just a new export using the intrinsic elements properties. Component Class has also being replaced by Functional Component.
No new tests has been written, the changes passed in all the current ones and it seem to be enough.
Now the type definition must contain the intrinsic elements properties. 
These changes were discussed in the #4978 issue.
#4998 and #4978
No.
No.
> [TS] Fix Anchor, FormField, Image and TextArea extended types definition

- src/js/components/RadioButton/index.d.ts
- src/js/components/RadioButtonGroup/index.d.ts
- src/js/components/RangeInput/index.d.ts
- src/js/components/RangeSelector/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the RadioButton, RadioButtonGroup, RangeInput and RangeSelector components, forming part of issue #4998.
The only files changed are the TS declaration files for each of the four components. Any of these files are good places to start.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing `RadioButtonExtendedProps` should make `input` keys available, as well as general HTML keys like `children`. Also double check any keys included in `Omit<..., ...>` types for consistency with original intersected types.
All background context …
> [TS] Fix RadioButton, RadioButtonGroup, RangeInput and RangeSelector type interfaces

- src/js/components/Collapsible/index.d.ts
- src/js/components/List/index.d.ts
- src/js/components/Video/index.d.ts
- src/js/components/WorldMap/index.d.ts
Create and export extended type declarations with component and JSX.IntrinsicElements props for the following components:
- Collapsible
- List
- Video
- World Map
any of these declaration files:
`src/js/components/Collapsible/index.d.ts`
`src/js/components/List/index.d.ts`
`src/js/components/Video/index.d.ts`
`src/js/components/WorldMap/index.d.ts`
`yarn storybook` (typescript stories) and `yarn test`
On a local typescript project, you can import the extended types and you should be able to reference both `<component>Props` and `JSX.IntrinsicElements` keys 
Relevant to #4998 and #4978
No
> [TS] Fix Collapsible, List, Video and World Map extended type definitions

- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Enhances the way that Pagination is integrated with DataTable to allow the DataTable to overflow horizontally but leaves the Pagination controls in place. This is necessary so that the Pagination controls always remain where the user has styled them but the DataTable data can be flexible. 
This is done by creating an OverflowContainer that wraps the DataTable when the caller has used `paginate`.
One additional styling was added to take care of a case where Firefox default behavior was not filling the same as Chrome/Safari. This ensures that all browsers have the same behavior when `fill` is used.
src/js/components/DataTable/DataTable.js
Tested in storybook example:
https://user-images.githubusercontent.com/12522275/111232658-c7526d80-85a8-11eb-98bc-a71c778a134e.mov
In storybook, …
> Allow DataTable to overflow but leave pagination controls in place

- src/js/components/DataTable/README.md
- src/js/components/DataTable/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
groupBy cannot be used at the same time as select/onSelect and vice versa. Updating docs to add clarity.
> Update DataTable groupBy/select/onSelect docs

- src/js/components/Calendar/StyledCalendar.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
Currently, when given the `fill` prop, the calendar is rendered larger than the available space, causing part of it to be cut off to the right side of the screen. This is easily visible in the [CustomDay story](https://storybook.grommet.io/?path=/story/visualizations-calendar-custom-day--custom-day-calendar) of the storybook:
I set the `DayContainer` wrapper to shrink down if there is not enough space available:
None. Should be covered by chromatic.
> [Bug] right calendar border not visible 

- src/js/components/DataTable/Header.js
Signed-off-by: AkshayChoulwar <achoulwar901@gmail.com>
If the data is not present in the DataTable then header checkbox was enabled by default. In this PR we have disabled the header checkbox if the data is not present.
/src/js/components/DataTable/Header.js
Creating the data table with empty data.
Creating the data table with empty data.
https://github.com/grommet/grommet/issues/5072
NA
No need.
No need to update the docs.
Yes
Yes
> Leave header checkbox unchecked if table data is not present.

- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
Sets `focusIndicator={false}` on the TextInput that is inside of Select button. This TextInput is purely to display the value of the select and should not receive focus.
src/js/components/Select/Select.js
Tested in Select stories. Click on Select, only focus around Select component should appear.
Same as above.
https://github.com/grommet/grommet/pull/4753 set focusIndicator to `true` but for the TextInput inside of Select, we don't want that.
Closes https://github.com/grommet/hpe-design-system/issues/1453
No.
No. (this bug is only on stable, not on a release)
> Fix double focus on Select

- src/js/components/Avatar/index.d.ts
- src/js/components/Chart/index.d.ts
- src/js/components/CheckBoxGroup/index.d.ts
- src/js/components/Clock/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the Avatar, CheckBoxGroup, Chart and Clock components, forming part of issue #4998.
The only files changed are the TS declaration files for each of the four components. The `Clock` component required some discussion, so should be reviewed last.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing `AvatarExtendedProps` should make `div` keys available, as well as general HTML keys like `children`. Also double check any keys included in `Omit<..., ...>` types for consistency with original intersected types.
All background …
> [TS] Add Avatar, CheckBoxGroup, Chart and Clock extended props interfaces

- src/js/components/Chart/index.d.ts
- src/js/components/Layer/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Select/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the Layer and Menu components, forming part of issue #4998. It also changes the type of the `Chart` and `Select` components to `React.FC<component>` instead of `React.ComponentClass<component>`, for consistency with the component implementation.
The only files changed are the TS declaration files for each of the four mentioned components. All components are eaqually good places to start.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing `LayerExtendedProps` should make `div` keys available, as well as general HTML keys …
> [TS] Add Layer and Menu extended props interfaces, use React.FC for Chart and Select types

- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/FormField/FormField.js
- yarn.lock
This PR adjusts FormField setFocus to check if the FormField contains DOM focus. If true, it sets focus to true and applies focus styling. If false, it does not apply focus styling since another DOM element has focus.
This resolves a bug where the TextInput in Select + Search was displaying focus on both the FormField and the TextInput. See "Background context" below for more details.
with fix
without fix
Formfield.js
storyboook
When `select` is in `formfield` there should only be one focus
```
<FormField>
<Select
size="medium"
placeholder="Select single option"
value={value}
options={options}
onChange={({ option }) => setValue(option)}
onClose={() => setOptions(defaultOptions)}
onSearch={text => {
// The line below escapes regular expression special characters:
// [ \ ^ $ . | ? * + ( ) …
```
> Only set focus on FormField if it containsFocus in the DOM

- src/js/components/DataTable/Body.js
- src/js/components/DataTable/Cell.js
Extracted `DataTable` row to another component and wrapped with `React.memo` to improve performance. Also wrapped `Cell` to gain a bit more improvement (check JS activity in screenshots for more info).
It should be simple - we need to confirm all the props are properly extracted.
Compared with all DataTable Storybook components - everything looks the same.
Just make sure everything works as before.
https://user-images.githubusercontent.com/1783133/111567926-2b765c80-8776-11eb-9595-4a4be85f37a1.mp4
https://user-images.githubusercontent.com/1783133/111568070-72fce880-8776-11eb-995d-3b339901489c.mp4
No
Maybe as a performance improvement, or bug fix.
No breaking changes, and no API changes.
> Clickable DataTable performance improvement

- src/js/components/FileInput/FileInput.js
- src/js/components/FileInput/README.md
- src/js/components/FileInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
When caller applies pad to FileInput, the dimensions of the pad need to be taken into account in the rightOffset of the `input`. If not, the `input` will cover the RemoveButton which allows the user to delete a file they have uploaded.
Previously, the pad was not taken into account which meant that the RemoveButton would at times be inaccessible by the mouse.
Also resolved incorrect propType in docs for `renderFile`.
src/js/components/FileInput/FileInput.js
Test in Custom Story.
In CustomStory. Upload a file then click to remove.
Previously, the input would cover the remove button when pad was applied.
Updated here.
New component.
> Adjust rightOffset when caller applies pad on FileInput

- src/js/components/Layer/Layer.js
Fixes a bug where layer was no longer animating on exit after upgrading to react-dom v17. In react-dom 17 `useEffect` changed effects to run asynchronously. `useLayoutEffect` should now be used instead when you are using an effect that is mutating the DOM and will change a change in the appearance of the DOM node between the time that it is rendered and your effect mutates it. `useLayoutEffect` runs synchronously. Since the animation is effecting how the DOM node looks it should use `useLayoutEffect` instead of `useEffect`
more info here: https://kentcdodds.com/blog/useeffect-vs-uselayouteffect
and here: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues
Layer.js
Storybook
with the Layer/Notification story check to see that the layer is animating on exit instead …
> Fix Layer animation on exit

- src/js/components/List/README.md
- src/js/components/List/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Signed-off-by: Zack Urben <zackurben@gmail.com>
This PR updates the List element docs to fix the html entities conversion of `<` and `>` in the examples. Additionally removes a dangling `/>`. I followed the format used in the [DataTable Component](https://v2.grommet.io/datatable) for props with code examples, e.g. `onSelect` and `onSort`.
Check the diff or [live docs](https://v2.grommet.io/list) for the `action` and `children` props.
`yarn generate-readme` and `yarn test-update`
I am not sure how to run the doc site locally to confirm changes. I'll gladly do some further testing/verification if I can get some guidance on how to do so.
N/A
N/A
Yes
No
> Updating List docs to fix html entities conversion.

- src/js/components/Box/index.d.ts
- src/js/components/Button/index.d.ts
- src/js/components/Calendar/index.d.ts
- src/js/components/Drop/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the Box, Button, Calendar and Drop components, forming part of issue #4998
The only files changed are the TS declaration files for each of the four mentioned components. All components previously defined a `<component>Type`, which has been kept in addition to the `<component>ExtendedProps` interfaces for backwards compatibility. The reviewer should double check that the changes are backwards compatible. I am happy to discuss potential deprecation warnings etc. and log a separate issue for deprecation notices if required.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed …
> [TS] Add Box, Button, Calendar and Drop extended props interfaces

- src/js/components/MaskedInput/index.d.ts
- src/js/components/Spinner/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the Spinner and MaskedInput components, forming part of issue #4998
The only files changed are the TS declaration files for each of the two mentioned components. The spinner component is more straightforward, since it is more similar to the majority of the components changed as part of issue #4998.
The `MaskedInput` component previously defined a `MaskedInputType`, which has been kept with the addition of the `MaskedInputExtendedProps` interface for backwards compatibility. The reviewer should double check that the changes are backwards compatible.
Importing the extended prop interfaces from a separate project should allow …
> [TS] Add Spinner and MaskedInput extended props interfaces

- src/js/components/Calendar/index.d.ts
The render functions of the `Calendar` component were `any` typed. This PR replaces those typings with correct ones.
> Type render functions of calendar component

- src/js/components/DataTable/index.d.ts
- src/js/components/Grid/index.d.ts
- src/js/components/Grommet/index.d.ts
- src/js/components/InfiniteScroll/index.d.ts
This PR adds and exports `<component>ExtendedProps` declarations for the DataTable, Grid and Grommet components, forming part of issue #4998. It also changes the type of the `InfiniteScroll` component to `React.FC<InfiniteScrollProps>` instead of `React.ComponentClass<InfiniteScrollProps>`, for consistency with other components.
The only files changed are the TS declaration files for each of the three components, with the `InfiniteScroll` component having a different change. Any of those TS files are a good place to start.
Importing the extended prop interfaces from a separate project should allow `JSX.IntrinsicElements` keys to be passed through to the imported interface, e.g. importing …
> [TS] Add DataTable, Grid and Grommet extended props interfaces, use React.FC for InfiniteScroll type

- src/js/components/InfiniteScroll/InfiniteScroll.js
Introduces a patch to #5095,  introduced on PR #4936 .
This fix uses two states to help tracking changes to data length. On this approach, we avoid going back to using `items.length === 0` as a check and thus we wouldn't assume that the caller wants to reset the data to an empty array before repopulating it.
Please note that this covers a very specific use case ( #4934 ) where the reporter wanted to reset data to an empty array before setting it. The condition `lastPage === 0` will make this work only for situations where the modified length is smaller than the initial step. 
Would love to hear your thoughts on that @ShimiSun @halocline, and I'd suggest we open this matter to discussion so we can have a clear view of use cases we want to cover before any attempt of broadening the whole …
> Fix InfiniteScroll loop when Data length changes

- src/js/components/Layer/README.md
- src/js/components/Layer/StyledLayer.js
- src/js/components/Layer/__tests__/Layer-test.js
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Layer/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Checks if Layer is plain before applying elevation. Also, used styled-components `withConfig` to ensure that the elevation prop doesn't leak to the DOM.
src/js/components/Layer/StyledLayer.js
Tested with this code snippet, no elevation was applied. Updated jest test.
```
<Layer
position="bottom"
modal={false}
margin={{ vertical: 'medium', horizontal: 'small' }}
responsive={false}
plain
>
<Text> example layer </Text>
</Layer>
```
With code snippet above, make a theme that has a value for `theme.layer.container.elevation`.
Closes #5129 
Updated here to clarify that Layer `plain` will not apply elevation.
Fixed Layer elevation styling, should not apply when plain.
> Don't let Layer elevation leak to DOM, don't apply elevation when plain

- src/js/components/Button/Button.js
- src/js/components/Button/__tests__/Button-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
Previously we only used the a11yTitle prop for button aria labels. This is a little unintuitive to someone who is already familiar with a11y. Rather than deprecate the a11yTitle prop we allow for it in addition to aria-label.
At the Button component.
Added a unit test to ensure the Button has no aXe a11y violations, manually tested to see the attribute rendered.
Create a Button, passing in aria-label. Then, check to see that the rendered button does in fact contain the given `aria-label` attribute.
I created a `Button` and gave it an `aria-label`. TypeScript allowed this, which tripped me up. An alternative here is to just ensure that the [ButtonExtendedProps](https://github.com/kid-icarus/grommet/blob/cea630132b637c223dd155292afdcd5399afbdce/src/js/components/Button/index.d.ts#L45) …
> Pass aria-label prop through as button attribute.

- src/js/components/Select/index.d.ts
This PR fixes #5134 by adding typings for `ref` on the `Select` component type definitions.
src/js/components/Select/index.d.ts
* Tested the changes on a real world project using `patch-package`
No type errors should occur with the following:
```typescript
const Example = () => {
const ref = useRef<HTMLButtonElement>();
return <Select options={[]} ref={ref} />;
};
```
#5134 
N/A
No docs updates needed
It's backward compatible
> Add ref to Select props type

- src/js/components/DateInput/README.md
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/DateInput/doc.js
- src/js/components/DateInput/stories/Format.js
- src/js/components/DateInput/utils.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds the ability to specify if you want leading zeros in the displayed date for DateInput. If the format 'mm/dd/yyyy' is used, leading zeros are shown. If the format 'm/d/yyyy' is used leading zeros are not shown. Previously leading zeros were not shown by default.
Also adds the ability have the displayed year show with 2 digits or 4 digits. For 2 digit year format='mm/dd/yy' for 4 digit year format='mm/dd/yyyy'.
I also changed the DateInput/Format story to show a format without leading zeros and a two digit year. Leading zeros and 4 digit year are shown in other stories.
Tested with storybook DateInput/Format story
storybook
Closes #5036 
Yes, done
Yes
> DateInput leading zeros and 2 digit year format option

- src/js/components/Box/Box.js
Currently Box only inserts a `<ThemeContext.Provider>` around the content if it needs to supply a background and/or a value for `dark` based on the background. However if the background changes (like when a validation error causes `FormField` to set the background of it's content `Box` to red or back to no background) this addition or removal of the `ThemeContext.Provider` causes the content in the Box to get re-constructed, losing any state. This manifested in issue #5146 
Change Box to always render a `<ThemeContext.provider>` for a consistent component hierarchy. This allows the child component specified by the user for the box to maintain state and render more efficiently.
Box.js
Storybook and Jest tests
Any FormField  using the HPE theme and marked required with a TextInput child and …
> Fixed Box to always render ThemeContext.Provider

- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/README.md
- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/CheckBox-test.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/CheckBox/doc.js
- src/js/components/CheckBox/index.d.ts
- src/js/components/CheckBox/stories/InsideFormField.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Orginal work was done [here](https://github.com/grommet/grommet/pull/5019) 
This PR adds a new `fill` prop to `checkbox` 
When a user includes the `fill` prop the box containing the label and checkbox/toggle will fill the width and set `justify-content:  space-between`
styledcheckbox.js
storybook and added a test for using the fill prop
```
<FormField
label="Toggle fill"
name="toggle"
htmlFor="check-box-toggle"
{...props}
>
<Box pad={{ horizontal: 'small', vertical: 'xsmall' }}>
<CheckBox
id="check-box-toggle"
name="toggle"
label="CheckBox"
toggle
fill
reverse
/>
</Box>
</FormField>
```
feature request: see below
closes  #5001 
already done
yes
> add new fill prop to checkbox

- src/js/components/Form/__tests__/Form-test-uncontrolled.js
- src/js/components/Form/stories/ValidateOnChange.js
- src/js/components/Select/Select.js
This PR ensures that when Select value changes, a `change` event is dispatched in order for upstream elements, such as FormField/Form to register this change event and trigger any validations (when necessary).
The way Grommet Select results in only `click` or `keyDown` event type to occur when a Select option is chosen. However, FormField validation relies on a `change` event bubbling up from the contained component to run validations. This PR mirrors what is implemented in MaskedInput and was inspired by this [Stack Overflow discussion](https://stackoverflow.com/questions/23892547/what-is-the-best-way-to-trigger-onchange-event-in-react-js/46012210#46012210). If a select value is changing and it has a `name` prop, we ensure that a change event is triggered on the underlying input so it …
> Trigger `change` event when Select value changes

- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
Addresses CheckBox `fill` property behavior issues and `type` warnings while using the same prop. 
- `fill` prop behavior
CheckBox component can have the checkbox itself and a label, both wrapped on a div Container. Right now, setting the `fill` prop doesn't result in any changes, where it should expand this Container to the limits of the parent component. 
After some debugging, I ended up discovering that this happens due to fill styling not being properly applied:
https://github.com/grommet/grommet/blob/adfc3091a933958aa5762c9bd493dbe059fb4e61/src/js/components/CheckBox/StyledCheckBox.js#L46-L49
Since `fillStyle` isn't used anywhere else, we can incorporate the `justify-content` prop to it, and call this function if `fill` prop is set.
- `fill` prop type warnings
The warnings mentioned …
> Fix CheckBox fill prop behavior and type warnings

- src/js/contexts/ResponsiveContext/__tests__/ResponsiveContext-test.js
- src/js/contexts/ResponsiveContext/__tests__/__snapshots__/ResponsiveContext-test.js.snap
Adds a snapshot test for ResponsiveContext, to ensure we start "medium".
#5103
no
no
> Added snapshot test for ResponsiveContext.

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Changed Select to fix an issue with onChange + valueLabel
If the caller specifies a `valueLabel`, there is no `inputRef` so we shouldn't be triggering the native change event.
Select.js
Added a unit test for this. Verified that it fails without the changes.
Testing in grommet-designer.
add `valueLabel` and `onChange`.
no
yes
> Changed Select to fix an issue with onChange + valueLabel

- src/js/components/CheckBoxGroup/index.d.ts
Options can accept an array that contains string or CheckBoxType object. Previously, "string" was not included in this definition.
src/js/components/CheckBoxGroup/index.d.ts
1. Converted Simple CheckBoxGroup example to TSX locally, got typescript error. 
2. Adjusted type definition.
3. Error was resolved.
Create TSX version of CheckBoxGroup story.
CheckBoxGroup in TS projects was flagging use of array of strings for `options` prop even though it is an accepted type and is documented.
No.
Fixed Typescript definition for CheckBoxGroup `options`.
> Fix CheckBoxGroup options type

- src/js/components/DataTable/Footer.js
- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/buildState.js
When a DataTable has a pinned header and selectable rows, the select checkbox column header cell (and footer cell) doesn't stay pinned on scroll like the other cells.
This PR changes the select checkbox column to stay pinned like other header/footer cells in a DataTable that has the `pin` property set. The background styling of the header and footer cell for the select checkbox now also comes from the theme `pinned` header and footer styling.
DataTable/Header.js
Manual testing via storybook and Jest.
See the simple example from issue #5070 
Fixes #5070 
No
Yes
> made select column pay attention to table pin property

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Fixes bug were .charAt() was trying to be called on a JSX element when a user was typing to select a Select option.
Functionality was added to allow a user to open a Select then start typing and an option that matched the typed value would become selected. However, the comparison is handled by `.charAt()` which must be called on strings. Caller is already responsible for reducing non-string options to string values or their select may not behave fully. However, the .charAt() wasn't checking that user had properly reduced their option.
This adds a check that the option is of type string before trying to index .charAt().
src/js/components/Select/SelectContainer.js
Added a test in this PR and confirmed it fails when I comment out my change and then passes with change added.
WITHOUT CHANGE: …
> Fix Select "type to select" functionality when JSX provided

- src/js/components/DataTable/Body.js
- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Make DataTable's groupBy togglable.
`DataTable.js`
Check if the error below was not thrown when toggle `groupBy` props between `undefined` and `"a"`.
>Uncaught [TypeError: Cannot read property 'expanded' of undefined]
> Make DataTable's groupBy togglable

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Button/StyledButton.js
- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/DataChart/Detail.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap
- src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/utils/styles.js
Inspired by [this](https://nelo.is/writing/styling-better-focus-states/) I'm adding support for `:focus-visible` if available so that we only show the focus ring if you are using the keyboard
Show focus only when using keyboard
StyledButton
manual
Make sure you see the focus outline when using the keyboard and you dont see it when clicking on buttons
nope
yes
> fix: only show focus on keyboard use

- src/js/components/Pagination/Pagination.js
- src/js/components/Pagination/__tests__/Pagination-test.js
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap
Update pagination page state on page prop change. This will allow users to update the page from the parent component.
Tested manually and added 1 unit test.
Maybe editing one of the stories to verify this.
I tested pagination components in 3 other UI frameworks.
They are updating the page on prop change. Also, they are not calling `onChange` on prop change.
One of the drawbacks for this change is an excess component re-render on click. I think we can leave it as is since it's not impacting performance a lot, but saving bytes with simple logic.
I didn't find any relevant issues.
Maybe as a bug fix
> Pagination update on page prop change

- src/js/components/BoxSnowpack/BoxSnowpack.js
- src/js/components/BoxSnowpack/README.md
- src/js/components/BoxSnowpack/doc.js
- src/js/components/BoxSnowpack/index.d.ts
- src/js/components/BoxSnowpack/index.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/components/index.js
- src/js/index.d.ts
This is a test component to be used for testing a snowpack project using Grommet. It will be removed after testing and will never be officially released.
The component is exactly the same as the Box component but it doesn't have `BoxDoc = require('./doc').doc(Box);`. I think that the require statements in the component files are causing problems with snowpack. The goal of this component is to test if removing the require statement will solve the problems with using grommet and snowpack as discussed in [this issue](https://github.com/grommet/grommet/issues/4895) or if there are other problems that need to be fixed as well to get grommet working in a snowpack project.
I also included a doc.js file for this component to see how the documentation for BoxSnowpack will behave without the …
> BoxSnowpack test component -- Revert before next release

- src/js/components/CheckBoxGroup/CheckBoxGroup.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
- src/js/components/CheckBoxGroup/stories/FormControlled.js
- src/js/components/CheckBoxGroup/stories/FormUncontrolled.js
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
Currently, CheckBoxGroup and RadioButtonGroup aren't read correctly by screen readers when they are in a Form/FormField. The screen readers can't tell they are in a group or are related, especially to their FormField label.
One typical solution suggested by #4108 is to make the group be in a `<fieldset>` with a `<legend>` which would allow the screen readers to read them more appropriately.
Because `<fieldset>` and `<legend>` come with some styling intent which is awkward to make match `FormField` labels and such from the themes, it's much simpler and cleaner to use ARIA `role="group"` or `role="radiogroup"` properties. Then the developer can also easily add `aria-labelledby` to the group to connect it with it's `FormField` as appropriate. Screen readers then correctly read the label with …
> Add role to CheckBoxGroup and RadioButtonGroup

- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/SkipLinks/SkipLinks.js
- src/js/components/SkipLinks/__tests__/SkipLink-test.js
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
Uses `React.Children` to map through children which allows SkipLinks to a have a single SkipLink child. Previously, just using `children.map` with a single child threw an error. Explanation can be found in link below, but essentially when `props.children` is a single child, `.map()` can't be performed. That is why we use `React.Children.map` which supports it regardless of if there is a single or multiple children: https://stackoverflow.com/questions/29464577/why-doesnt-this-props-children-map-work
src/js/components/SkipLinks/SkipLinks.js
Tested in SkipLinks story book and created jest test.
BEFORE changes, jest test will fail:
Create SkipLinks with single SkipLink child.
Related to https://github.com/grommet/hpe-design-system/issues/1585 where we want to have a single "Main Content" …
> Allow SkipLinks to have single child

- src/js/components/DataTable/DataTable.js
Signed-off-by: Daniel Baird <daniel.baird@jcu.edu.au>
Like other Grommet components, DataTable will default to `defaultProps.theme` if there's no Theme context available. However defaultProps isn't imported. This PR adds that missing import.
Line 12 is the change; line 104 is the reference to defaultProps
I ran the standard tests, which passed (except for a date-related one because the test doesn't allow for my +10 timezone. I'll PR a fix for that later)
You could use a DataTable outside of a ThemeContext -- it will fail without this change.
I hit this bug while updating all my dependencies, when I accidentally included multiple instances of styled-components in my app. That broke ThemeContext enough that my DataTable tried to fall back to (the non-existent) defaultProps.
Nope
Not unless …
> adds import for defaultProps to DataTable

- src/js/components/RangeSelector/RangeSelector.js
- src/js/components/RangeSelector/__tests__/RangeSelector-test.js
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
Fix RangeSelector change events to able to respond to mobile touch gestures for when the user drag on of the edge points
`src/js/components/RangeSelector/RangeSelector.js`
`yarn storybook`, `yarn test` and test on a real device
`yarn storybook`, go to a range selector story and then enabling device emulation on browser
See #5076 
No
> Fix RangeSelector to respond to touch gestures

- src/js/components/Button/README.md
- src/js/components/Button/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Enhancing Button badge docs to elaborate what happens when a user provides an object of shape:
```
{
background: ,
value: ,
max: 
}
```
Updated here.
No.
> Enhance Button badge docs

- src/js/components/Box/README.md
- src/js/components/Box/StyledBox.js
- src/js/components/Box/doc.js
- src/js/components/Box/index.d.ts
- src/js/components/Grid/Grid.js
- src/js/components/Grid/README.md
- src/js/components/Grid/StyledGrid.js
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/index.d.ts
- src/js/utils/prop-types.js
- src/js/utils/styles.js
Changed Grid to add width and height, same as Box.
This makes it easier to use Grid to drive layout without having to wrap with a Box to constrain its dimensions.
anywhere
added unit tests
tested with grommet-designer locally
use it
yes, automatic
yes
> Changed Grid to add width and height

- src/js/components/Grid/README.md
- src/js/components/Grid/StyledGrid.js
- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/components/Grid/doc.js
- src/js/components/Grid/index.d.ts
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed Grid to enhance columns capabilities.
Particularly, this change allows single fractional column sizes or min/max fractional sizes. For instance, you can now do `columns={{ size: ['small', '1/3'] }}` which says the columns should at least be small but not more than 1/3 of the available space. 
It also takes care of automatically accounting for any gap. So, if you have columns="1/3" gap="medium", you will actually get three columns. Before, you would get two, since the gap space would prevent three columns from being shown.
index.d.ts
added unit tests
custom stories with a variety of columns
Ideally, try it out with a variety of `columns` values.
yes, additional custom example syntaxes should be added, once this goes in.
yes
> Changed Grid to enhance columns capabilities

- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/FormField/FormField.js
- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButton/StyledRadioButton.js
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
This PR fixes the keyboard behavior for RadioButtonGroup and ensures that the onChange event is always called when the checked radio button changes.
The keyboard event handlers were adjusted to ensure that the native `onChange` event is always called, since it is called every time a user clicks with mouse. Previously, the event was not always called with keyboard navigation.
When in a FormField, the formfield receives focus indicator and the radiobuttons receive hover treatment so it is clear which is active.
In order for the interaction to work correctly on Firefox, a tabindex is toggled between the active radiobutton vs the others to ensure that pressing tab will leave the radiobuttongroup as opposed to navigating between them.
The expected behavior is that (view WCAG demo: …
> Fix keyboard behavior of RadioButtonGroup

- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/StyledMaskedInput.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/MaskedInput/doc.js
- src/js/components/MaskedInput/index.d.ts
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/TextInput/StyledTextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed MaskedInput to add textAlign. This is the same property as with TextInput.
Also fixed TextInput to style textAlign before `extend`.
doc.js
tested with grommet-designer
automatic
yes
> Changed MaskedInput to add textAlign

- src/js/components/CheckBox/CheckBox.js
- src/js/components/CheckBox/README.md
- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
- src/js/components/CheckBox/doc.js
- src/js/components/CheckBoxGroup/CheckBoxGroup.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/FormField/FormField.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
When CheckBox or CheckBoxGroup is within a FormField, the focus styling should appear on the formfield. When rendered outside of a FormField, the focus styling should appear on the CheckBox itself. However, a keyboard user still needs to be aware that an element is active inside the FormField, especially in a CheckBoxGroup. When in a FormField, the formfield receives focus indicator and the CheckBoxes receive hover treatment so it is clear which is active.
Additionally, the theme was enhanced to support `checkBox.hover.background.color` which mirrors the behavior of `radioButton.hover.background.color`. Once merged, we will leverage this new theme object in grommet-theme-hpe as opposed to `extend` like we have to do now and will remove where we manually remove box-shadow from checkbox …
> Remove duplicate focus styling on CheckBox/CheckBoxGroup inside FormField

- src/js/components/Anchor/stories/Weight.js
- src/js/components/Form/stories/typescript/TypedForm.tsx
- src/js/components/Layer/stories/Round.js
- src/js/contexts/ThemeContext/stories/ThemeContextExtend.js
Minor fixes on some of the storybook stories.
**Anchor/weight story:**
fixed warning about weight prop to use a number
**Form/TypedForm:**
fixed story to follow new annotation style
**Layer/Round:**
fixed story to follow new annotation style
**ThemeContext/ThemeContextExtend:**
fixed story naming
No
No
> Small fixes in storybook stories

- .eslintrc
- package.json
- yarn.lock
This PR does some of the pre work for upgrading to webpack 5.
- bumps node version from 10 to 12
- removes deprecated package `@types/storybook__react`, @storybook/react provides its own type definitions so it is no longer needed
- removed deprecated package `babel-eslint` and replaces with `@babel/eslint-parser`
package.json
`yarn build`
`yarn build-storybook`
`yarn test`
Related to #5250 
No
No
> Bump node version, upgrade and remove some packages

- src/js/components/Button/StyledButton.js
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
When you have custom children in Select the hover styling is applied but the selected styling is not applied. This PR adds the selected styling to custom children when they are selected.
Tested with this storybook story
```javascript
import { Box, Grommet, Select, Text, Paragraph } from 'grommet';
export const TEST = () => {
const options = ['one', 'two'];
return (
<Grommet full theme={grommet}>
<Box gap="small" width="small">
<Select options={options} />
<Select options={options}>{(option) => <Text>{option}</Text>}</Select>
<Select options={options}>{(option) => option}</Select>
<Select options={options}>{(option) => <Paragraph>{option}</Paragraph>}</Select>
</Box>
</Grommet>
);
};
export default { …
```
> Added selected styling to custom child in Select

- src/js/components/Button/__tests__/Button-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-test.js.snap
`src/js/components/Button/__tests__/Button-test.js`
`yarn test`
No.
No.
> Refactor Button tests to use `render` @testing-library function

- src/js/components/Carousel/Carousel.js
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
This fixes the issue by explicitly hiding every other child except for
the initial child on mount (and the previously visible child for
animation purposes after the initial child has changed) so that only the
desired image will be visible on mount.
#5093 is a bug where a wrong image is shown in the carousel on mount. This PR fixes that bug.
Storyboard works and my local site which uses the carousel works.
On master, open the storyboard carousel and watch the wrong image initially be visible. Pull in this commit and then watch how the initial child doesn't change when the page loads.
#5093
#5093
no
It is a bug fix, so sure.
It is backwards compatible.
> carousel: Fix carousel showing the wrong image initially.

- src/js/components/DateInput/__tests__/DateInput-test.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
Changed DateInput tests to remove react-test-renderer. This is being done to prepare for a fix to a DateInput issue, updating the tests first.
test
unit test, review snapshots
review snapshot changes
no
no
> Changed DateInput tests to remove react-test-renderer

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/Detail.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to allow detail to work for more data points.
The old way was using the outer `pad` to drive the thickness of the detail segments. This sort of worked, as long as half the pad could be determined. But, when the thickness of the Chart elements was `hair`, the half size of that became 0, which meant there was no pad, but then no width to the Detail segments. This new approach separates the outer `pad` from the thickness of the detail segments.
Detail.js
Changed the Detail story to have 130 data points.
#5312 
no
yes
> Changed DataChart to allow detail to work for more data points.

- src/js/components/WorldMap/__tests__/WorldMap-test.js
- src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.js.snap
Update WorldMap tests to use the standard render method from [react-testing-library](https://testing-library.com/docs/react-testing-library/intro/).
`src/js/components/WorldMap/__tests__/WorldMap-test.js`
`yarn test`
No.
No.
> Refactor WorldMap tests to remove react-test-renderer

- src/js/__tests__/__snapshots__/default-props-test.js.snap
- src/js/__tests__/default-props-test.js
- src/js/components/CheckBoxGroup/__tests__/CheckBoxGroup-test.js
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.js.snap
- src/js/components/Tip/__tests__/Tip-test.js
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap
`src/js/components/Tip/__tests__/Tip-test.js`
`src/js/__tests__/default-props-test.js`
`src/js/components/CheckBoxGroup/__tests__/CheckBoxGroup-test.js`
`yarn test`
No.
No.
> Refactor Tip, extendDefaultTheme and CheckBoxGroup tests to remove react-test-renderer

- src/js/components/Carousel/__tests__/Carousel-test.js
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/DropButton/__tests__/DropButton-test.js
- src/js/components/DropButton/__tests__/__snapshots__/DropButton-test.js.snap
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
`src/js/components/Carousel/__tests__/Carousel-test.js`
`src/js/components/DropButton/__tests__/DropButton-test.js`
`src/js/components/Form/__tests__/Form-test-uncontrolled.js`
`yarn test`
No.
No.
> Refactor Carousel, DropButton and FormUncontrolled tests to remove react-test-renderer 

- src/js/components/Markdown/__tests__/Markdown-test.js
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
- src/js/components/Select/__tests__/SelectMultiple-test.js
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/contexts/ResponsiveContext/__tests__/ResponsiveContext-test.js
- src/js/contexts/ResponsiveContext/__tests__/__snapshots__/ResponsiveContext-test.js.snap
`src/js/components/Markdown/__tests__/Markdown-test.js`
`src/js/components/Select/__tests__/SelectMultiple-test.js`
`src/js/contexts/ResponsiveContext/__tests__/ResponsiveContext-test.js`
`yarn test`
No.
No.
> Refactor Markdown, SelectMultiple and ResponsiveContext tests to remove react-test-renderer

- src/js/components/Avatar/__tests__/Avatar-test.js
- src/js/components/Avatar/__tests__/__snapshots__/Avatar-test.js.snap
`src/js/components/Avatar/__tests__/Avatar-test.js`
`yarn test`
No.
No.
> Refactor Avatar tests to remove react-test-renderer

- src/js/components/Box/__tests__/Box-test.js
- src/js/components/Box/__tests__/__snapshots__/Box-test.js.snap
`src/js/components/Box/__tests__/Box-test.js`
`yarn test`
No.
No.
> Refactor Box tests to remove react-test-renderer

- src/js/components/Calendar/__tests__/Calendar-test.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
`src/js/components/Calendar/__tests__/Calendar-test.js`
`yarn test`
No.
No.
> Refactor Calendar tests to remove react-test-renderer

- src/js/components/Clock/__tests__/Clock-test.js
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.js.snap
`src/js/components/Clock/__tests__/Clock-test.js`
`yarn test`
No.
No.
> Refactor Clock tests to remove react-test-renderer

- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
`src/js/components/DataChart/__tests__/DataChart-test.js`
`yarn test`
No.
No.
> Refactor DataChart tests to remove react-test-renderer

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
Fix/Add required FormField validation when value is an empty array (`[]`).
Closes #5333
`src/js/components/Form/Form.js` and on `DateInput` storybook.
I created a test case on `src/js/components/Form/__tests__/Form-test-uncontrolled.js` to cover the bug described in #5333
Manual running: 
```bash
yarn test
```
I also simplified a validation on the same file: instead of doing `value2 === undefined || value2 === '' || value2 === false` we can simply do `!value2` that means the same thing and also validates when the value is `null`.
#5333
No.
Yes.
> Fix required FormField validation when value is an empty array

- src/js/components/Grid/__tests__/Grid-test.js
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
`src/js/components/Grid/__tests__/Grid-test.js`
`yarn test`
No.
No.
> Refactor Grid tests to remove react-test-renderer

- src/js/components/CheckBox/__tests__/CheckBox-test.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.js.snap
`src/js/components/CheckBox/__tests__/CheckBox-test.js`
`yarn test`
No.
No.
> Refactor CheckBox tests to remove react-test-renderer

- src/js/components/Chart/__tests__/Chart-test.js
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.js.snap
`src/js/components/Chart/__tests__/Chart-test.js`
`yarn test`
No.
No.
> Refactor Chart tests to remove react-test-renderer

- src/js/components/Card/__tests__/Card-test.js
- src/js/components/Card/__tests__/__snapshots__/Card-test.js.snap
`src/js/components/Card/__tests__/Card-test.js`
`yarn test`
No.
No.
> Refactor Card tests to remove react-test-renderer

- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
`src/js/components/FormField/__tests__/FormField-test.js`
`yarn test`
No.
No.
> Refactor FormField tests to remove react-test-renderer

- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
`src/js/components/Heading/__tests__/Heading-test.js`
`yarn test`
No.
No.
> Refactor Heading tests to remove react-test-renderer

- src/js/components/Image/__tests__/Image-test.js
- src/js/components/Image/__tests__/__snapshots__/Image-test.js.snap
`src/js/components/Image/__tests__/Image-test.js`
`yarn test`
No.
No.
> Refactor Image tests to remove react-test-renderer

- src/js/components/Meter/__tests__/Meter-test.js
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.js.snap
`src/js/components/Meter/__tests__/Meter-test.js`
`yarn test`
No.
No.
> Refactor Meter tests to remove react-test-renderer

- src/js/components/Paragraph/__tests__/Paragraph-test.js
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
`src/js/components/Paragraph/__tests__/Paragraph-test.js`
`yarn test`
No.
No.
> Refactor Paragraph tests to remove react-test-renderer

- src/js/components/RadioButton/__tests__/RadioButton-test.js
- src/js/components/RadioButton/__tests__/__snapshots__/RadioButton-test.js.snap
`src/js/components/RadioButton/__tests__/RadioButton-test.js`
`yarn test`
No.
No.
> Refactor RadioButton tests to remove react-test-renderer

- src/js/components/RangeInput/__tests__/RangeInput-test.js
- src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.js.snap
`src/js/components/RangeInput/__tests__/RangeInput-test.js`
`yarn test`
No.
No.
> Refactor RangeInput tests to remove react-test-renderer

- src/js/components/RangeSelector/__tests__/RangeSelector-test.js
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
`src/js/components/RangeSelector/__tests__/RangeSelector-test.js`
`yarn test`
No.
No.
> Refactor RangeSelector tests to remove react-test-renderer

- src/js/components/Heading/README.md
- src/js/components/Heading/__tests__/Heading-test.js
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.js.snap
- src/js/components/Heading/doc.js
- src/js/components/Paragraph/README.md
- src/js/components/Paragraph/__tests__/Paragraph-test.js
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
- src/js/components/Paragraph/doc.js
- src/js/components/Text/README.md
- src/js/components/Text/__tests__/Text-test.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
- src/js/components/Text/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/index.d.ts
- src/js/utils/styles.js
* Adds 'justify' to Text Align styles
* Update doc.js of tested components
Minor change at styles.js at the utils directory and TextAlignType
Tests if the Text, Heading, Paragraph components renders with the textAlign="justify" prop
Test the main components that uses the textAlign prop
'Justify' text-alignment #5368
No, the changes already includes docs update
No
> Add text align justify

- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
`src/js/components/Menu/__tests__/Menu-test.js`
`yarn test`
No.
No.
> Refactor Menu tests to remove react-test-renderer

- src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js
- src/js/components/RadioButtonGroup/__tests__/__snapshots__/RadioButtonGroup-test.js.snap
`src/js/components/RadioButtonGroup/__tests__/RadioButtonGroup-test.js`
`yarn test`
No.
No.
> Refactor RadioButtonGroup tests to remove react-test-renderer

- src/js/components/Sidebar/__tests__/Sidebar-test.js
- src/js/components/Sidebar/__tests__/__snapshots__/Sidebar-test.js.snap
`src/js/components/Sidebar/__tests__/Sidebar-test.js`
`yarn test`
No.
No.
> Refactor Sidebar tests to remove react-test-renderer

- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
`src/js/components/Select/__tests__/Select-test.js`
`yarn test`
No.
No.
> Refactor Select tests to remove react-test-renderer

- src/js/components/Spinner/__tests__/Spinner-test.js
- src/js/components/Spinner/__tests__/__snapshots__/Spinner-test.js.snap
`src/js/components/Spinner/__tests__/Spinner-test.js`
`yarn test`
No.
No.
> Refactor Spinner tests to remove react-test-renderer

- src/js/components/Stack/__tests__/Stack-test.js
- src/js/components/Stack/__tests__/__snapshots__/Stack-test.js.snap
`src/js/components/Stack/__tests__/Stack-test.js`
`yarn test`
No.
No.
> Refactor Stack tests to remove react-test-renderer

- src/js/components/Table/__tests__/Table-test.js
- src/js/components/Table/__tests__/__snapshots__/Table-test.js.snap
`src/js/components/Table/__tests__/Table-test.js`
`yarn test`
No.
No.
> Refactor Table tests to remove react-test-renderer

- src/js/components/Text/__tests__/Text-test.js
- src/js/components/Text/__tests__/__snapshots__/Text-test.js.snap
`src/js/components/Text/__tests__/Text-test.js`
`yarn test`
No.
No.
> Refactor Text tests to remove react-test-renderer

- src/js/components/TextArea/__tests__/TextArea-test.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
`src/js/components/TextArea/__tests__/TextArea-test.js`
`yarn test`
No.
No.
> Refactor TextArea tests to remove react-test-renderer

- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/themes/__tests__/theme-test.js
`src/js/themes/__tests__/theme-test.js`
`yarn test`
No.
No.
> Refactor Theme tests to remove react-test-renderer

- src/js/components/RoutedAnchor/__tests__/RoutedAnchor-test.js
- src/js/components/RoutedAnchor/__tests__/__snapshots__/RoutedAnchor-test.js.snap
`src/js/components/RoutedAnchor/__tests__/RoutedAnchor-test.js`
`yarn test`
No.
No.
> Refactor RoutedAnchor tests to remove react-test-renderer

- src/js/components/Keyboard/__tests__/Keyboard-test.js
- src/js/components/Keyboard/__tests__/__snapshots__/Keyboard-test.js.snap
- src/js/components/RoutedButton/RoutedButton.js
- src/js/components/RoutedButton/__tests__/RoutedButton-test.js
- src/js/components/RoutedButton/__tests__/__snapshots__/RoutedButton-test.js.snap
`src/js/components/Keyboard/__tests__/Keyboard-test.js`
`src/js/components/RoutedButton/RoutedButton.js`
`yarn test`
No.
No.
> Refactor Keyboard and RoutedButton tests to remove react-test-renderer

- package.json
- Upgrades `markdown-to-jsx` from 6.11.4 to 7.1.4
package.json
- Commit test suite
- Storybook markdown stories
https://github.com/grommet/grommet/issues/5373
No
No
> Upgraded markdown-to-jsx latest

- package.json
- yarn.lock
Remove `react-test-renderer` from the project since there is no component using it anymore.
Closes #5197 
`yarn test`
No.
No.
> Remove react-test-renderer

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
For uncontrolled forms, when a field is dynamically removed, the form will also remove this field's value from the stored form value. This ensures that removed fields will not be included in the form submission. This is handled by creating a boolean ref that tracks if the field has become part of the form value or not. Then, a useEffect listens for when this input has unmounted. if it has, its value is removed from the form value.
For controlled forms, it is up to the caller to clean their form value. This PR does not affect controlled forms.
Tested locally in storybook wiht Dynamic Fields Form story.
With Dynamic Fields story.
1. Fill in Name with a value
2. Check "alias?"
3. Fill in Alias with a value
4. Uncheck "alias?"
5. Hit Submit --> the console.log …
> Remove value of unmounted inputs from uncontrolled form value

- package.json
- yarn.lock
Downgrade ts-loader to v8.3 since v9 doesn't support webpack v4
package.json
storybook
storybook should have no browser warnings about typescript stories
#5421 
no
no
> Downgrade ts-loader to v8.3 since v9 doesn't support webpack v4

- src/js/components/DateInput/README.md
- src/js/components/DateInput/__tests__/DateInput-test.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/DateInput/doc.js
- src/js/components/MaskedInput/README.md
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/MaskedInput/doc.js
- src/js/components/TextArea/README.md
- src/js/components/TextArea/__tests__/TextArea-test.js
- src/js/components/TextArea/__tests__/__snapshots__/TextArea-test.js.snap
- src/js/components/TextArea/doc.js
- src/js/components/TextInput/README.md
- src/js/components/TextInput/__tests__/TextInput-test.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
- src/js/components/TextInput/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/utils/styles.js
Allow inputs to have custom inputs sizes.
```ts
<DateInput size="1rem" />
<MaskedInput size="1em" />
<TextInput size="16px" />
<TextArea size="60%" />
```
Only the changes at **styles.js**
Tests if **TextInput, TextArea, DateInput, MaskedInput** renders with the default and custom sizes values
Tests if the inputs sizes renders and changes if  
Closes #5402
No
No
> Allow custom styled input size

- src/js/components/FileInput/stories/Custom.js
- src/js/components/FileInput/stories/Simple.js
Fixes console errors that were showing up in FileInput Custom and Simple stories when a file is removed.
Related to #5028 and #5143
Storybook
Storybook, add a file and then remove it and check console
#5143
No
No
> Fix console errors in FileInput stories

- src/js/components/List/index.d.ts
Updates the List component's onOrder function prop to receive the reordered data.
At the single line change
Only manual testing. The tests for the onOnder fuctions were already created with the reordered data.
Creating the List component, at some typescript project, with the updated onOrder prop
Closes #5441
No
No
It's possible to break List components, at some typescript project, thats uses the onOrder without arguments
> fix: Update onOrder parameters' type definition

- src/js/components/Paragraph/StyledParagraph.js
- src/js/components/Paragraph/__tests__/Paragraph-test.js
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.js.snap
- src/js/components/Paragraph/stories/All.js
This PR allows for a custom string to be passed to `paragraph` size
styledparagraph.js
added a custom string to the test size
storybook
closes #5464 
no
yes
> fix paragraph so it accepts a custom string

- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButtonGroup/stories/Children.js
Signed-off-by: Sarah Allen <sarah@zooniverse.org>
This fixes #5472 by including the `RadioButton` focus state as part of the state object that gets passed to children by the `RadioButtonGroup`.
The `RadioButtonGroup` children story is now updated to demonstrate that the focus state is now available and the children can now be styled based on that state like it is for hover and checked.
Manual testing via storybook. I didn't see an existing unit test for testing hover with children, so I didn't add one for focus. Happy to do so if requested.
As noted above, the story is now updated.
As of right now, if someone uses `RadioButtonGroup` and defines custom children, then the child components can be inaccessible for keyboard users if there's no focus state styling.
#5472 
> Pass along RadioButton focus state to children.

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/README.md
- src/js/components/Calendar/doc.js
- src/js/components/__tests__/__snapshots__/README-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/contexts/MessageContext/MessageContext.js
- src/js/languages/default.json
This PR adds to the `MessageContext` in order for the `values` to be read for the announce messages
MessageContext.js
Calendar.js
I changed  `calendar` in order to add the `format` to:
```
announce(
format({
id: 'calendar.previous',
messages,
values: {
date: previousMonth.toLocaleDateString(locale, {
month: 'long',
year: 'numeric',
}),
name: 14,
},
}),
);
```
use the screen reader on calendar using the next and previous buttons
`values: (optional) currently unused but in the future
will be an object with substitution values for
positional variables in the message text.`
We needed to add values 
closes #5459 
no
sure
> add values to format messageContext

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
Removes use of role="gridcell" on blank Calendar days and role="row" from weeks that are completely blank to improve experience of screen readers.
Removing "gridcell" on blank days ensures a screen reader user doesn't need to navigate over these days.
The removal of role="row" on blank weeks is needed for screen reader to properly calculate number of rows in a table. If not, a completely blank week will still be included in the row count but not accessible by screen reader which is confusing. For example "Row 1 of 6" where only 5 rows are able to be accessed because on week is empty.
src/js/components/Calendar/Calendar.js
Tested with VoiceOver locally.
Test on showAdjacentDays story with VoiceOver and arrow keys. Should not be able to access blank days.
Closes #5436 
No.
Yes. Improved …
> Don't apply role="gridcell" to blank days or role="row" to blank week

- src/js/components/FocusedContainer.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/Layer/stories/MarginTop.js
- src/js/contexts/OptionsContext.js
- src/js/contexts/RootsContext.js
This PR adds default values for both `OptionsContext` and `RootsContext` 
RootsContext.js
OptionsContext.js
Storybook
Take out `<Grommet/>` wrapper to ensure that `Layer`  is still being rendered correctly
There was no default value there was only `undefined` being passed through.
__This default value can be helpful for testing components in isolation without wrapping them.__
The default value needs to match what is being passed to the  `useContext` for instance `OptionsContext` would expect an object so the default value needs to be an object
closes #5516 
no
no
> Fix options layer bug

- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
This PR moved a block of  code outside of backticks 
styledDataTable.js
storybook
add an option in the extend to pass theme this was not working before
https://github.com/grommet/grommet-theme-hpe/pull/202
When trying to add an option for the `background` to look for `theme.dark ?` this was not  working correctly
Need this to work to fix an issue in Hpe theme
no
no
> move theme option out of back ticks

- src/js/components/RangeSelector/RangeSelector.js
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
In jest-axe v5 the RangeSelector accessibility pass is failing because the use of any aria-* attribute on a div should be accompanied by a role attribute. This PR adds the `role="slider"` attribute and `aria-valuemin`, `aria-valuemax`, and `aria-valuenow` as advised in https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role
Upgrade to jest-axe v5
run yarn test
accessibility test for RangeSelector should pass
Closes #5500 
no
no
> Accessibility enhancements for RangeSelector

- src/js/components/Markdown/index.d.ts
Added options prop to index.d.ts in the Markdown component
Closes #5470 
no
maybe (fixed Typescript compatibility for Markdown component)
> Add options prop to Markdown index.d.ts

- package.json
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.js.snap
- src/js/components/Carousel/__tests__/__snapshots__/Carousel-test.js.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/Select/index.d.ts
- src/js/components/Select/propTypes.js
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- yarn.lock
Upgrades `grommet-icons` to `4.6.1` which includes a fix to forward refs to `<StyledIcon />`.
- `package.json`
- Commit test suite
- Manual review of snapshot changes
- Using grommet-icon v4.6.1 will close https://github.com/grommet/grommet/issues/5256.
- Snapshot changes result from SVGs using updated `<StyledIcon />` resulting in new classNames.
- Valid Select `icon` PropTypes needed to be extended to accept React elementType.
Closes https://github.com/grommet/grommet/issues/5256
No.
Yes. "Fixed bug when using a Grommet icon as a direct child of Tip."
> Upgraded grommet-icons to latest version

- package.json
- yarn.lock
Upgrades `grommet-icons` to v4.6.2 which includes fix for icon `displayName`
package.json
No.
No.
> Upgraded grommet-icons

- src/js/components/Grid/index.d.ts
- src/js/components/Grid/stories/typescript/App.tsx
Aims to resolve #5496. Introduces `Grid.available` as a part of the `GridExtendedProps` to stop TypeScript from marking it as an issue when trying to access `Grid.available` in your own code.
`Grid/index.d.ts`: to view the addition of the boolean to GridExtendedProps
`Grid/Grid.js`: to see where it is given a value
Manual testing in Grid's TypeScript story (`Grid/stories/typescript/App.tsx`) by trying to console log `Grid.available`.
1. Open Grid's TypeScript story (`Grid/stories/typescript/App.tsx`)
2. Try to log/access `Grid.available` and notice how TypeScript does not complain about the `available` property
Issue #5496 
No
No
> Available boolean: now accessible from extended props

- src/js/components/Select/index.d.ts
This PR aims to:
- Add `className` as a valid attribute to the `Select` component
- View `src/js/components/Select/index.d.ts` file to see changes that were made
- Inside `src/js/components/Select/stories/typescript/CreateOption.tsx` try to add a `className` to `<Select>` and note how TypeScript doesn't complain about the attribute
Manual testing inside code editor (VSCode)
After adding a `className` to the story mentioned above, hover over the className and see how TypeScript will not mark the attribute as an error
#5249
No
No
> Fix: Adding className to Select component

- CONTRIBUTING.md
Updates the information in the contributing guide to reflect the recent removal of react-desc and move of the docs to grommet-site.
Contributing.md
Read through information
#5540 
No
No
> Updated Contributing.md to reflect documentation contributing changes

- CONTRIBUTING.md
Removes the Developer's Certificate of Origin from the contributing guide. This wasn't something we were enforcing and it is covered by the Apache 2.0 license.
Contributing.md
Grommet is licensed under Apache 2.0
Section 5 of Apache 2.0 states:
> Submission of Contributions. Unless You explicitly state otherwise,
> any Contribution intentionally submitted for inclusion in the Work
> by You to the Licensor shall be under the terms and conditions of
> this License, without any additional terms or conditions.
> Notwithstanding the above, nothing herein shall supersede or modify
> the terms of any separate license agreement you may have executed
> with Licensor regarding such Contributions.
> This serves the same purpose as the Developer's Certificate of Origin.
More info: …
> Remove Developer's Certificate of Origin from Contributing.md

- src/js/components/Markdown/Markdown.js
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
- src/js/components/Markdown/stories/Simple.js
Currently Markdown uses `TableCell` for any `<td>` elements generated from the markdown content.
`TableCell` wraps the cell content in a `Box`. However, since `Box` is `display:flex` and `direction=column` so
causes any inline content like `<em>`, `<a>`, `<b>`, etc, to end up `display:block` rather than being inline.
This PR removes the `Box` wrapper for `<td>` cells in markdown content so that any other interesting inline
elements in the cells continue to be inline.
From what we can tell, we don't need the `Box` wrapper here.
Markdown.js
Storybook, Jest and some handcrafted examples.
Go to the Markdown Simple example in the Storybook and verify the table cells with other markup
continue to be inline as desired.
Fixes #5486 
No
Yes
Should be backwards compatible although it may be hard to …
> remove box container from Markdown table cells

- package.json
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/SelectMultiple-test.js
- yarn.lock
Upgrades jest-axe to v5.0.1
Disables 'nested-interactive' rule on Select accessibility tests per [discussion here ](https://github.com/grommet/grommet/pull/5580)
package.json
`yarn test`
Closes #5501
Closes #5502 
No
No
> Upgrade Jest-Axe

- package.json
- tsconfig.json
- tsconfig.tests.json
- yarn.lock
This is a proof-of-concept PR related to #5111 that adds **strict** TypeScript unit testing support, without forcing the rest of the `grommet` code base to use strict type checks. This means that we can gradually convert existing unit tests from `*-test.js` to `*-test.tsx` files, and fix any issues that TypeScript raises in the process. This should allow us to find and fix existing TypeScript issues quicker, as well as decrease opportunities for TS-related bugs in the future.
The most important change is in `package.json`, where I specify we want to use the new `ts-jest` dependency for all `tsx?` tests, but use existing pipelines (`babel-jest`) for all `.jsx?` tests.
Secondly, there have been some changes to the `tsconfig.json` file, to support the creation of a more strict …
> [TS] Add TypeScript unit testing support

- src/js/components/InfiniteScroll/InfiniteScroll.js
When an InfiniteScroll is passed an empty items array and it has an onMore callback, onMore was getting called continuously.
Storybook example, jest tests
Storybook InfiniteScroll examples
Fixes #5633 
No
Yes
> Fix an InfiniteScroll onMore infinite recursion

- src/js/components/Heading/stories/All.js
- src/js/components/Heading/stories/Color.js
- src/js/components/Heading/stories/CustomThemed/CustomHeading.js
- src/js/components/Heading/stories/CustomThemed/Extend.js
Following #5735 , enhances support to storybook theming for `Heading` component.
`src/js/components/Heading/stories`
#5735 
No.
No.
> Enhance storybook theming for Heading

- src/js/components/FileInput/FileInput.js
Changes the factor that determines the conversion for fileinput max size message to use 1024 as opposed to 1000.
src/js/components/FileInput/FileInput.js
Tested locally by adjusting the `maxSize` story locally and setting MAX_SIZE to just under a known file size I was going to upload. Then, I uploaded the file and saw the error message.
Same as above.
1024 is the factor for file size conversions (bytes --> KB ...etc): http://myrepono.com/faq/4
Closes #5756 
No.
Yes. Fixed FileInput `maxSize` conversion.
> Change FileInput maxSize factor to 1024

- src/js/components/Clock/stories/Analog.js
- src/js/components/Clock/stories/Countdown.js
- src/js/components/Clock/stories/CustomThemed/CustomAnalog.tsx
- src/js/components/Clock/stories/CustomThemed/Digital.js
Following #5735 , enhances support to storybook theming for `Clock` component.
`src/js/components/Clock/stories`
#5735 
No.
No.
> Enhance storybook theming for Clock

- src/js/components/Tip/Tip.js
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.js.snap
Fixes an issue where the Tip would display after getting focus back (ex. when Tip is on a Button and the Button opens a Layer the Tip would display when the Layer closes).
Now the Tip only displays after getting focus back from another element when navigating with the keyboard. This maintains accessibility while removing the behavior for mouse users.
Tested with the following story:
```javascript
import { Add } from 'grommet-icons';
import { Box, Button, Grommet, Layer, Text, Tip } from 'grommet';
export const Test = () => {
const [open, setOpen] = React.useState();
const onOpen = () => setOpen(true);
const onClose = () => setOpen(undefined);
return (
<Grommet theme={grommet} full>
<Box fill align="center" …
```
> Fix Tip behavior after getting focus back from another element

- src/js/components/NameValueList/NameValueList.js
- src/js/components/NameValueList/__tests__/__snapshots__/NameValueList-test.tsx.snap
- src/js/components/NameValuePair/__tests__/__snapshots__/NameValuePair-test.tsx.snap
Removes the browser default margin of `dl` from NameValueList ,similar to what is done in NameValuePair.
src/js/components/NameValueList/NameValueList.js
Inspected browser on NameValueList stories and confirmed there was no margin.
Same as above.
No.
No (component has not been released).
> Remove default margin of `dl` from NameValueList

- src/js/components/NameValueList/__tests__/__snapshots__/NameValueList-test.tsx.snap
- src/js/components/NameValuePair/__tests__/__snapshots__/NameValuePair-test.tsx.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Sets default `row` gap on NameValueList to small to align with designs.
src/js/themes/base.js
Storybook and snapshots.
Inspect stories.
Yes.
No. Not released yet.
> Update default gap NameValueList

- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/InfiniteScroll/InfiniteScroll.js
- src/js/components/InfiniteScroll/__tests__/__snapshots__/InfiniteScroll-test.tsx.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
InfiniteScroll calculates its lastPage index slightly wrong. This fixes that calculation.
The test snapshot changes are cases where InfiniteScroll really shouldn't have put
a marker div. Most of the cases are pagination enabled (where it doesn't need to
detect that the list is scrolled to the end). The change to the InfiniteScroll snaphot
is a case where it had a number of items that was exactly a multiple of the step
(the main bug this fixes.)
Storybook plus some special situations with DataTable onUpdate.
See #5794 
Fixes #5794 
No
Yes
This is backwards compatible
> Fix InfiniteScroll lastPage calculation

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
This fixes a condition to check if `groupBy` prop exists before trying to access `groupBy.onSelect` and restores `onSelect` functionality for DataTables that don't have `groupBy.onSelect`.
Our jest tests did not have a test for this, so I have added one. I confirmed that the test failed with the published code and is resolved with the fix in this PR.
src/js/components/DataTable/Header.js
Tested `onSelect` storybook and added jest test.
`onSelect` storybook, click the checkbox in the header to select all, all should be selected.
BEFORE:
AFTER:
no.
Yes. Fixed DataTable `onSelect` bug.
> Fix DataTable groupBy.onSelect condition

- .eslintrc
- package.json
- src/js/components/Accordion/__tests__/Accordion-test.tsx
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- yarn.lock
Updated tests for the component to follow the testing guidelines//best practices that are being added to the contributing guide. We can use the Accordion tests as a reference for people to look at.
I also added `eslint-plugin-testing-library` to catch errors related to using react testing library. For now I only enabled it for the Accordion test file.
Note: switching from `container.firstChild` to `asFragment()` is causing the majority of snapshot changes
Accordion-test.tsx
Related to grommet/hpe-design-system#1959
No
No
> Update Accordion tests to use best testing practices

- src/js/themes/base.d.ts
This PR fixes a TS error that was with `pagination` 
base.d.ts
storybook
The error was 
```
{ background: { color: string; }; color: string; }' is not assignable to type 'ButtonKindType & { [key: string]:
```
It seemed that since there was a & with the `{ [key: string]: ButtonKindType }` it was flagging that it should of been included but we do not always want this so I added an OR option
https://stackoverflow.com/questions/57145172/how-to-create-an-optional-object-key-string-in-typescript/57145386
no
no
> add or for ts in theme for pagination

- src/js/components/Avatar/stories/Basic.js
- src/js/components/Avatar/stories/CustomThemed/Stacked.tsx
- src/js/components/Avatar/stories/CustomThemed/Themed.js
- src/js/components/Avatar/stories/Round.js
- src/js/components/Avatar/stories/Sizes.js
- src/js/components/Avatar/stories/typescript/Stacked.tsx
It is a ticket related to https://github.com/grommet/grommet/issues/5735 
it enabled to switch theme in Avatar component in storybook
> enable avatar storybook theme

- src/js/components/Clock/Clock.js
- This PR aims to fix `NaN` being displayed when using Clock with the iso8601 format and not providing an hour (ex. PT30M10S)
- `Clock.js` line 16 where the hours are parsed
- Trying `time` prop with no hour and making sure it displays 00
- In any clock storybook, add a Clock component with a time given to it with no hours specified
- Resolves #5804
- No
- No
- Backwards compatible
> Fix: Clock not handling period when no hour is assigned

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/__tests__/Calendar-test.tsx
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/languages/default.json
It add aria-label in chevrons when messages is given 
Starts by Calendar
Add messages in Calendar on storybook 
`messages={{ next: 'go to {date}', previous: 'go to {date}', }}`
and run `yarn storybook`
turn on voice over and focus in chevrons to listen the message
https://github.com/grommet/grommet/issues/5844
Yes, it is
> Calendar component chevron aria label not informative enough 

- src/js/components/TextInput/TextInput.js
This PR addresses issues with the TextInput suggestion dropdown closing and suggestions not reappearing upon further user input or after regaining focus.
- Changes made in `TextInput.js`
Manual testing with a focus on TextInput suggestion behavior after losing / regaining focus through various methods
- Example given with the `TextInput/Default suggestion` story
Part 1:
- Type in sug, the dropdown is open
- Double click inside and delete
- Type again sug --> dropdown remains open after deletion and is ready to scan for new suggestions
Part 2:
- Type in sug, dropdown opens
- Click on the TextInput box --> dropdown remains open after the click and is still actively listening for suggestions
- Resolves #5426
- Resolves #5440
- Resolves #5790 
No
Can be included for TextInput fixes
Backwards …
> Fix: TextInput suggestions closing incorrectly

- src/js/components/NameValueList/NameValueList.js
- src/js/components/NameValueList/__tests__/NameValueList-test.tsx
- src/js/components/NameValueList/__tests__/__snapshots__/NameValueList-test.tsx.snap
- src/js/components/NameValueList/stories/CustomValue.js
Adds check if caller has passed an array for `valueProps` -- resolves backwards compatibility.
src/js/components/NameValueList/NameValueList.js
Added jest test, storybook.
No.
No.
Yes.
> Fix NameValueList for backwards compatibility

- src/js/components/Notification/Notification.js
- src/js/components/Notification/__tests__/Notification-test.js
- src/js/components/Notification/__tests__/__snapshots__/Notification-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- yarn.lock
This PR updates the code to match the Grommet documentation for the Notification component. The time prop is specific to the toast notification. This could change as more types of notifications are introduced. Updated in the component, `base.js` and `base.d.ts`. 
`Notification.js`
Updated tests to match best testing protocols.
View the toast notification story in Storybook
#5873 
No
No
> Fix/toast-time-prop5873: updated notifications code to make time prop specific to toast

- src/js/components/Collapsible/stories/Horizontal.js
- src/js/components/Collapsible/stories/Nested.js
- src/js/components/Collapsible/stories/Simple.js
- src/js/components/DataTable/stories/ColumnSize.js
- src/js/components/DataTable/stories/Controlled.js
- src/js/components/DataTable/stories/ControlledGrouped.js
- src/js/components/DataTable/stories/CustomThemed/Fill.js
- src/js/components/DataTable/stories/Grouped.js
- src/js/components/DataTable/stories/GroupedOnSelect.js
- src/js/components/DataTable/stories/InfiniteScrollDataTable.js
- src/js/components/DataTable/stories/MultiplePin.js
- src/js/components/DataTable/stories/NoPrimary.js
- src/js/components/DataTable/stories/OnUpdate.js
- src/js/components/DataTable/stories/Placeholder.js
- src/js/components/DataTable/stories/ResizableColumns.js
- src/js/components/DataTable/stories/Served.js
- src/js/components/DataTable/stories/Show.js
- src/js/components/DataTable/stories/Simple.js
- src/js/components/DataTable/stories/Sized.js
- src/js/components/DataTable/stories/Sort.js
- src/js/components/DataTable/stories/SpaceX.js
- src/js/components/DataTable/stories/SpaceXUngrouped.js
- src/js/components/DataTable/stories/Styled.js
- src/js/components/DataTable/stories/Tunable.js
- src/js/components/DataTable/stories/Units.js
- src/js/components/DataTable/stories/rowDetails.js
- src/js/components/DataTable/stories/typescript/Clickable.tsx
- src/js/components/DataTable/stories/typescript/OnSelect.tsx
- src/js/components/DataTable/stories/typescript/Paginated.tsx
Working on #5735, theming support for following components is added:
The theme can now be switched between the currently available themes: base, grommet, hpe.
Start in src/js/components and look at the changes made to the following folders:
Passed the existing tests ran through jest and manually verified the changes on storybook.
Run storybook and navigate to the following stories: Collapsible, DataTable. Themes can now be switched for these stories using the Theme button.
https://github.com/grommet/grommet/issues/5735
No.
No.
Is this change …
> Allow theming for Collapsible, DataTable stories - Issue 5735

- src/js/components/Calendar/Calendar.js
This PR checks for if someone is passing an empty string for value in `date` in Calendar
Calendar.js
dropdown calendar story
The `timeStamp` function was checking if a string was provided however if a user passed in an empty string then the `timeStamp` should be `undefined` 
This was blocking the release currently the simple story was showing the wrong date when clicked 
no
no
> fix when empty string in Calendar

- src/js/components/TextInput/TextInput.js
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
Adjusts "fill" on the Button within TextInput suggestions to be `fill="horizontal"` as opposed to `fill`, which was causing the suggestion to take the full height on the drop in some environments.
src/js/components/TextInput/TextInput.js
Updated snapshots and the changes are expected.
N/A did not touch tests.
The exact scenario causing this issue was on Windows Firefox where a Grommet app was inside an existing application. The team had isolated that the "height: 100%" on the suggestion "Button" in the DOM (coming from the `fill`) was causing this issue. Removing it caused no changes to the UI on any browser.
The plan would be to release this fix on stable and allow the team to test in their environment and confirm this resolves the issue.
No.
Yes. Fixed TextInput suggestions styling. …
> Fix fill on TextInput suggestions

- package.json
- storybook/main.js
Fixes deprecation warnings on storybook.
For the first warning `--static-dir CLI flag is deprecated` I removed the -s flag from the storybook commands in package.json and added `staticDirs: ['./public']` to `storybook/main.js`. (More info here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag)
For the second warning, `Default PostCSS plugins are deprecated` I added `features: { postcss: false }` to `storybook/main.js` since we are not using the postcss-loader in storybook. (More info here: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader)
Ran `yarn storybook` and `yarn build-storybook`  and checked that warnings were no longer showing up and storybook is working as expected
See above ^
Closes …
> Fix storybook deprecation warnings

- src/js/components/Button/StyledButtonKind.js
This PR fixes an issue with the alignment of icons in plain buttons.
storybook
View the Tag/onRemove story with the hpe theme
Closes #5884
Before:
After:
No
Yes
> Fix icon styling for plain buttons

- src/js/components/Calendar/utils.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/DateInput/utils.js
Resolves a bug where a date with format of `yyyy-mm-dd` or `yyyy/mm/dd` (day at end) was resulting in the date prematurely being considered "complete" and miscalculating the date.
I have also resolved bug in a calculation that converts hours to ms.
Regarding the snapshot change, I believe this is fixing an existing bug in a fairly new test/snapshot (created by https://github.com/grommet/grommet/pull/5837). The date of August 9 should not have been in the snapshot. See screenshot below of the storybook rendering:
src/js/components/DateInput/utils.js
Tested locally with the following:
```
import { Box, DateInput } from 'grommet';
export const Format = () => {
const [value, setValue] = React.useState('');
const onChange = (event) => {
const nextValue = event.value; …
```
> Resolve DateInput incomplete date bug

- src/js/components/TextInput/TextInput.js
Fixes an issue where TextInput would jump back up to the most recent hovered option when scrolling.
The fix moves the content in `onClickOutside` to a callback function. Using an arrow function was causing unnecessary re-renders which resulted in the jumping scroll behavior. `useCallback` ensures the component only re-renders when necessary.
Tested with TextInput Default suggestion and Custom suggestion stories.
Closes #4098 
No
Maybe
> Fix TextInput scroll issue

- src/js/components/RangeInput/StyledRangeInput.js
- src/js/components/RangeInput/stories/SimpleRange.js
Changed RangeInput to handle undefined value and convert simple story to allow theming.
StyledRangeInput.js
storybook, jest
storybook with hpe theme and Simple story
no
yes
> Changed RangeInput to handle undefined value and convert simple story to allow theming.

- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
Add [aria state attributes](https://www.w3.org/TR/wai-aria-1.1/#aria-setsize) to Select component to better identify active options, the position of each item, and the total amount of options available regardless of how many items are on the DOM (for instance, when using infinite scroll)
`src/js/components/Select/Select.js`
`yarn test`
`yarn storybook`, choose a select story and turn on your screen reader
Related to #5898 
No
> Fix Select's infinitescroll accessibility issues

- src/js/components/Tab/Tab.js
- src/js/components/Tabs/__tests__/Tabs-test.tsx
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.tsx.snap
Tab normally ignores an onClick property since it overrides it with it's own that updates the TabContext.
This change make Tab honor any onClick handler from the properties like it does for onMouse*.
This problem was observed in Grommet Designer where it tries to attach onClick handlers in edit mode to make it easy to select the particular component in the tree and allow easy access to the component properties. Because the onClick is ignored/overridden, when you click on a Tab in edit mode the event bubbles up to the parent `Tabs` component and selects it instead.
Tab.js
Fixes #5936 
No. The basic handlers aren't spelled out for Tab.
Yes
> Enabled onClick prop in Tab component

- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Select/Select.js
- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/languages/default.json
Improves how the screenreader reads and interacts with the Select component. 
- Options can now be selected with either 'Enter' or 'Space' (previously only 'Enter' worked)
- Options are read when navigating with up and down arrows (previously they were not read out)
- The user is notified when an option is selected and when revisiting a selected option.
- When an option is selected and the drop is closed and the select has focus the aria-label, a11yTitle, or placeholder is read along with the selected option.
Notes: 
- There is an issue in Chrome with voice over where once an option is selected, when navigating to other options the screen reader reads out the selected option. This issue is present in other Select components when using a screenreader (see …
> Improve Select screenreader and keyboard navigation experience

- src/js/components/Chart/Chart.js
- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataChart/index.d.ts
- src/js/components/DataChart/propTypes.js
- src/js/components/DataChart/stories/Offset.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed DataChart to add offset
DataChart.js
added story and unit test
new story
didn't refactor the DataChart tests yet, so continuing with existing patterns :( 
#5233 
yes
yes
> Changed DataChart to add offset

- src/js/themes/base.d.ts
According to [this line](https://github.com/grommet/grommet/blob/31456ab4f9dbcf314030dc4f1984d7a8e40cba53/src/js/components/TextInput/StyledTextInput.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L32) in the StyledTextInput definition and the [TextInput docs](https://v2.grommet.io/textinput#:~:text=textInput.disabled.opacity), the type for `theme.textInput.disabled` should include something with a property of `opacity`.
This PR updates that type in the ThemeType to align with the usage and documentation.  Since I don't know if the existing type is also acceptable, I left it in place.
N/A
N/A
Assign a theme object that uses the `theme.textInput.disabled.opacity` to a variable with the …
> types(theme): fixes disabled opacity type

- src/js/components/Markdown/Markdown.js
- src/js/components/Markdown/__tests__/Markdown-test.js
- src/js/components/Markdown/__tests__/__snapshots__/Markdown-test.js.snap
Currently any `wrapper` specified in the Markdown `options` parameter gets ignored since `Markdown` forces it to be a `Fragment`. This change will honor a `wrapper` specified in `options`, if any.
Markdown.js
A custom storybook example, plus a Jest case added
```jsx
const Wrapper = props => <Box gap="small" {...props} />;
...
<Markdown
options={{ wrapper: Wrapper }}
components={{
p: { 
component: Paragraph,
props: { margin: 'none' },
},
}}
>
{'first paragraph\n\nsecond paragraph'}
</Markdown>
```
#5832 
No
Yes
> Made Markdown wrapper overrideable

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Restores arrow key navigation to the Menu component
Tested with existing Menu stories
Closes #5935
No
Yes
> Restored arrow key functionality to Menu component

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataChart/index.d.ts
- src/js/components/DataChart/propTypes.js
- src/js/components/DataChart/stories/StackedLines.js
Changed DataChart to add lines type
StackedLines story
new unit test, added story
story
no change to DataChart test approach yet
yes
yes
> Changed DataChart to add lines type

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/DataChart-test.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to be more resilient to empty property array
DataChart.js
designer with DataChart chart type 'areas' with no properties
just following existing tests for now
uncovered in grommet designer use
no
yes
> Changed DataChart to be more resilient to empty property array

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/Detail.js
- src/js/components/DataChart/XAxis.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to fix issues with x-axis alignment.
Previously, the x-axis labels were only roughly aligned to the data/guide lines. You could see this most on bar charts with medium or fine grained x-axis labels. These changes make them align.
XAxis.js
visual verification using stories
storybook
no unit test changes
previously:
now:
no
yes
> Changed DataChart to fix issues with x-axis alignment

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/stories/Simple.js
- src/js/components/Calendar/utils.js
- src/js/components/DateInput/DateInput.js
- src/js/components/DateInput/__tests__/DateInput-test.tsx
- src/js/components/DateInput/utils.js
When DateInput value starts as undefined, the `onChange` logic should be in UTC relative to the local timezone of the user. In these instances, we don't want to perform the subsequent normalization logic. This PR introduces a state variable in dateinput that is passed ot the normalization functions. When it is true, we proceed with normalization. When it is false, we don't normalize because the date is already in UTC with respect to the timezone.
DateInput.js
Format Inline story in timezones before UTC and after (for example, pacific time and eastern european.
With FormatInline story in various timezones.
N/A did not touch tests aside from fixing a test that did not have `defaultValue` in ISO8601 format.
Closes #5920 
No.
Yes.
> Improve logic for when to normalize date in DateInput

- src/js/components/Tip/Tip.js
- src/js/components/Tip/__tests__/Tip-test.tsx
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.tsx.snap
Changed Tip to not crash when it doesn't have children.
This was uncovered when adding Tip to grommet-designer.
Tip.js
none of the below apply
no
yes
> Changed Tip to not crash when it doesn't have children

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/YGuide.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
Changed DataChart to ensure y guide encompasses thickness.
Because of how we draw the graphics in SVG, any line thickness overflows into the padding area. This change ensures that the `guide` for the Y dimension always covers the horizontal padding area.
YGuide.js
visually with storybook and inspecting unit test snapshots
Guide Default storybook
no
yes
> Changed DataChart to ensure y guide encompasses thickness

- src/js/components/Notification/__tests__/__snapshots__/Notification-test.js.snap
- src/js/components/Notification/stories/Global.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
- yarn.lock
Change Notification Global story to not customize theme
However, it looks like the `hpe` theme hasn't been published yet, so there's no background coloring.
Also, I'm wondering if the `base` theme should have some default background coloring, as that feels more consistent, like just using our `status-*` colors with some opacity.
Global.js
Global story
Global story
no
no
> Change Notification Global story to not customize theme

- CONTRIBUTING.md
Removes the reference to the design-kit in the contributing guide since we don't actively maintain the design kit. 
No
No
> Remove reference to the design-kit in the contributing guide

- src/js/components/Box/__tests__/Box-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
- src/js/components/Grid/__tests__/__snapshots__/Grid-test.js.snap
- src/js/utils/styles.js
Changed Box to fix an issue with desired height using an object.
The prior code was awkwardly using `height={{ min, ..., max: ..., width: ... }}` rather than `height={{ min, ..., max: ..., height: ... }}`. It looks like a cut/paste issue.
utils function
Also verified with grommet-designer.
Followed existing test patterns.
yes
yes
> Changed Box to fix an issue with desired height using an object

- src/js/components/Calendar/stories/Multiple.js
- src/js/components/DateInput/stories/Form.js
- src/js/components/DateInput/stories/Format.js
- src/js/components/DateInput/stories/FormatInline.js
- src/js/components/DateInput/stories/Inline.js
- src/js/components/DateInput/stories/Range.js
- src/js/components/DateInput/stories/RangeFormat.js
- src/js/components/DateInput/stories/Simple.js
- src/js/components/DateInput/stories/typescript/European.tsx
Previously the stories would only log the selected date in iso format which caused confusion in UTC+ timezones since the date logged would be one day before what was selected when displayed in iso format.
Now the stories log the iso date and the utc date to avoid confusion.
Test with storybook in a UTC+ timezone
Closes https://github.com/grommet/grommet/issues/5989
No
No
> DateInput and Calendar stories log selected date in both iso and utc format

- src/js/components/Tip/stories/typescript/Children.tsx
Remove non-interactive children of Tip from the Tip Children story
Tip Children story
Manual
Check the story
N/A
https://github.com/grommet/grommet/issues/5971
No
> Remove non-interactive children of Tip from story

- src/js/themes/base.d.ts
Adds missing type documented [here][1]. It's a trivial change so I'm leaving the sections below blank.
[1]: https://v2.grommet.io/radiobutton#radioButton.check.color
> Add missing type for radioButton.check.color theme

- src/js/components/DateInput/DateInput.js
If you open a DateInput by pressing space it will scroll down the page.
Tested with the following code:
```javascript
<Box width="medium" gap="medium">
<DateInput format="dd/mm/yyyy" value={value} onChange={onChange} />
</Box>
<Box width="medium" height="xlarge" background ="orange" />
```
I put a colored box below the DateInput so you can see the page scroll down
Closes https://github.com/grommet/grommet/issues/5978
no
no
> Prevent DateInput from scrolling down the page when opening with space

- src/js/components/Select/Select.js
- src/js/components/Select/index.d.ts
- src/js/components/Select/propTypes.js
Select's `valueLabel` prop can now accept a function. This PR also fixes the rendering of the selected option when `labelKey` is a function. Previously no value would display in the textInput area of the select if `labelKey` was a function. Now if `labelKey` is a function, the function will determine how the selected option is displayed. `valueLabel` takes precedence on displaying the selected option when both `valueLabel` and `labelKey` are defined.
Tested with the following story, uncommenting and commenting out various options
```javascript
import { Box, Select } from 'grommet';
export const Test = () => {
const options = ['one', 'two'];
const [value, setValue] = useState('');
return (
// Uncomment <Grommet> lines when using outside of storybook …
```
> Select - `valueLabel` can be a function & selected option renders when `labelKey` is a function

- src/js/components/Calendar/stories/Simple.js
Removes one of the Calendars from the Calendar/Simple story. Having two Calendars was causing confusion since they share they same date variable which means in UTC+ timezones the calendar the date was not originally selected on will show one day earlier. See full explanation on why this happens here: https://github.com/grommet/grommet/issues/6023#issuecomment-1079488663
storybook
n/a
Related to https://github.com/grommet/grommet/issues/6023
no
no
> Change Calendar/Simple story to only have 1 Calendar

- src/js/components/Drop/Drop.js
- src/js/components/Drop/__tests__/Drop-test.tsx
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.tsx.snap
- src/js/components/Drop/index.d.ts
- src/js/components/Drop/propTypes.js
- src/js/components/Drop/stories/Inline.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed Drop to add `container="inline"`. This allows the Drop to be rendered within its parent as opposed to in a React portal.
See the issue for some detail around when this might be useful.
Inline.js story
Added a new Inline story and added a jest test.
Inline story
no changes to the unit test patterns already in the file
#6032 
yes
yes
> Changed Drop to add container inline

- src/js/components/Select/Select.js
- src/js/components/Video/Video.js
- src/js/components/Video/index.d.ts
- src/js/components/Video/propTypes.js
- src/js/components/Video/stories/typescript/TheaterMode.tsx
This PR disables `play` button in the control menu when the video is already playing as well as disables the pause button in control menu when the Video is already paused
video.js
storybook 
add `prop` to Video in storybook 
```
controls={{ position: "below", items: ["pause", "play"] }}
```
User plays or pauses the video via the extended "controls" prop. They are able to pause or play with any of the two controls. For example, the video will be playing and the user can go to the extended controls and hit the play icon. This will pause the video.
#6021 
no
maybe
> add disabled to controls in which the video is already playing or paused

- src/js/components/Box/__tests__/Box-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
- src/js/components/Box/propTypes.js
Very similarly to https://github.com/grommet/grommet/pull/5823, this PR enhances Box to accept any React element for the `as` prop.
When working with legacy code or `styled-components`, I stumbled upon the need for this extension.
Before this PR, a warning like this would appear, but the code would still work like a charm.
At the tests
Extensive testing 🧐
Pass a React element such as an old school component as the `as` prop to a Box
They update automatically, right?
Yes.
This PR does not change Grommet's behavior, but simply removes a useless warning on a specific edge case.
> Make "as" prop on Box accept any React element

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/SelectMultiple-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/stories/Clear.js
It fixes the issue https://github.com/grommet/grommet/issues/6039
It can start reproducing the bug in local storybook
Created unit test
Yes, it should
**NOTE** Need to use getByPlaceholderText since I didn't find a role for dropdown button. 
https://github.com/grommet/grommet/issues/6039
No
Yes, it is
> fix: show clear button on select only when select has value

- package.json
- yarn.lock
Upgrades jest-axe to the latest version
yarn test
https://github.com/grommet/hpe-design-system/issues/2498
No
No
> Upgrade jest-axe to v6

- package.json
- src/js/components/Accordion/__tests__/Accordion-test.tsx
- src/js/components/Button/__tests__/Button-test.tsx
- src/js/components/Carousel/__tests__/Carousel-test.tsx
- src/js/components/DateInput/__tests__/DateInput-test.tsx
- src/js/components/Image/__tests__/Image-test.tsx
- src/js/components/MaskedInput/__tests__/MaskedInput-test.js
- src/js/components/Notification/__tests__/Notification-test.js
- src/js/components/RoutedAnchor/__tests__/RoutedAnchor-test.js
- src/js/components/RoutedButton/__tests__/RoutedButton-test.js
- src/js/components/Select/__tests__/SelectMultiple-test.js
- src/js/components/Tag/__tests__/Tag-test.tsx
- yarn.lock
Upgrades testing-library/user-event to the latest version
More info about the changes from v13 to v14 of user-event can be found here: https://testing-library.com/docs/user-event/intro
Notable changes are that all the user event apis return promises and [userEvent.setup()](https://testing-library.com/docs/user-event/setup) should now be used at the beginning of tests that use userEvents.
yarn test
https://github.com/grommet/hpe-design-system/issues/2498
no
no
> Upgraded testing-library/user-event

- src/js/components/NameValueList/index.d.ts
It broadens the type for NameValueList's props to include Grid's props. This makes the types match what the code actually does.
I have verified that the the fix works by editing the source in `node_modules`
See above
Here is where the rest of the props to `NameValueList` get passed to `Grid`
https://github.com/grommet/grommet/blob/d34c1e8826b7632aefa488bf5409472603875242/src/js/components/NameValueList/NameValueList.js#L62
None
Yes: https://github.com/grommet/grommet-site/pull/370
No
> Include Grid props in NameValueList props type

- package.json
Node 12's end of life is April 30th. Changed the package.json to require node v14 or higher.
No
Yes
> Drop support for Node 12

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Fixes the clear button on Select to only fill horizontally instead of both horizontally and vertically which caused an issue on Firefox:
Before (`fill={true}`)
After (`fill='horizontal'`)
No
Yes, a released version of grommet contains this bug (v2.22.0)
> Fixed clear button filling vertically on Firefox

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/TableCell/TableCell.js
Fixes an issue with DataTable where if the columns in the table are `sortable` and there are columns that have names that span multiple lines and columns names that are only on one line, the one line column header button will not fill the vertical space in the header. See screenshots below for a visual.
Notes:
1. This PR changes `height: auto` to `height: 100%` in `StyledDataTable.js`. We previously had height set to 100% but it was changed to auto in https://github.com/grommet/grommet/pull/3533 to fix an issue in FireFox where having a DataTable with the `groupBy` prop set, wrapped with `<Box fill>` resulted in this:
See [this related slack thread](https://grommet.slack.com/archives/C04LMHN59/p1573141859413900) for more info.
The change from `height: auto` to `height: 100%` was made over …
> Fixed hover indicator to fill cell on DataTable header

- package.json
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.tsx.snap
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- yarn.lock
Upgrades grommet to use the latest version of babel-plugin-styled-components
https://github.com/grommet/hpe-design-system/issues/2552
No
No
> Upgrade babel-plugin-styled-components

- src/js/components/Form/stories/HelpAndError.js
The email label in the `HelpAndError` story for `Form` is linked to the wrong input field. This should fix the warning in the storybook accessibility panel.
Check the Accessibility panel in the storybook for this story. There’s an unlabelled form input error, which should be fixed by using the correct ID in the label. 
storybook
No
No
Very small change that shouldn’t break anything.
> Fix email label in HelpAndError story

- package.json
- src/js/components/Tip/Tip.js
- src/js/components/Tip/__tests__/Tip-test.tsx
Fix Tip to respect onMouseEnter, onMouseLeave, onFocus, and onBlur functions from child
Tested with the following story
``` javascript
import { grommet, Box, Button, Grommet, Tip } from 'grommet';
export const Test = () => (
<Box align="center" justify="center" pad="large" gap="xlarge">
<Tip content="action info">
<Button
label="Edit onMouseEnter Hijacked"
onClick={() => {}}
fill
onMouseEnter={() => console.log('Mouse enter A')}
onMouseLeave={() => console.log('Mouse leave A')}
onFocus={() => console.log('Focus A')}
onBlur={() => console.log('Blur A')}
/>
</Tip>
<Button
label="Edit onMouseEnter Hijacked"
onClick={() => {}}
fill
onMouseEnter={() => console.log('Mouse enter B')}
onMouseLeave={() => console.log('Mouse leave B')}
onFocus={() => console.log('Focus …
```
> Change Tip to respect mouse and focus functions from child

- package.json
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.tsx.snap
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- yarn.lock
This PR reverts 
`"babel-plugin-styled-components": "2.0.6",`
package.json
yarn test update
n/a
n/a
With this update, there were snapshot changes that were being made 
which is affecting any new PRs that are being made. Need to look further into why upgrading this package would include snapshot changes 
none
no
no
> revert babel back

- src/js/components/Anchor/Anchor.js
- src/js/components/Anchor/__tests__/Anchor-test.tsx
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.tsx.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `theme.anchor.gap` to allow the gap to be specified by the theme. Necessary for HPE theme.
base.js
Tested in story and added jest test.
Yes.
Yes.
> Allow theme to specify Anchor gap

- package.json
- src/js/components/Drop/DropContainer.js
- src/js/components/Layer/Layer.js
- src/js/components/Layer/LayerContainer.js
Fixes an issue where when a Layer or Drop is rendered in a shadow dom any click is identified as a click outside the Layer or Drop, this causes the Layer or Drop to close whenever a click occurs. This PR also fixes an issue with Layer when animate is true it is in a shadow dom the Layer will not be removed when it is closed.
Start by looking at this codesandbox to see what the issue is https://codesandbox.io/s/wizardly-poincare-uufkpw?file=/src/index.js
Tested with the following code: (note getting storybook to play nicely with shadow dom is tricky so I ended up testing in a separate project)
CSS file: (while in a shadow dom we should not see this css applied)
```
p {
color: red;
}
```
index.js file:
``` javascript
import React, { useState } from "react";
import ReactDOM from "react-dom"; …
```
> Fix onClickOutside and animation for Layer and Drop in a shadow dom

- src/js/components/Notification/index.d.ts
- src/js/components/Notification/propTypes.js
Adds missing `propTypes` and `index.d.ts` definition for `global` prop of Notification.
src/js/components/Notification/index.d.ts
N/A
Closes #6113 
Updates handled in: https://github.com/grommet/grommet-site/pull/383
No.
> Add global to notification propTypes and index.d.ts

- src/js/components/PageHeader/__tests__/__snapshots__/PageHeader-test.tsx.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Updates default behavior of subtitle, gridAreas, and column definitions to improve the readability and responsiveness of the component.
base.js
Tested with: https://github.com/grommet/hpe-design-system/issues/2557
N/A
https://github.com/grommet/hpe-design-system/issues/2603
Yes. https://github.com/grommet/grommet-site/pull/384
No.
Backwards compatible, component hasn't been released yet.
> Update PageHeader defaults

- src/js/components/FileInput/index.d.ts
Fixes the typescript definition for onChange in FileInput
Tested with the following code in a typescript story:
```typescript
const onChange = (event, { files }) => {
console.log(files);
);
```
and
```typescript
const onChange = ({ target: { files } }) => {
console.log(files);
};
```
with `<FileInput onChange={onChange} />`
Test an `onChange` function with FileInput in a typescript file
Closes https://github.com/grommet/grommet/issues/6143
No
Maybe
> Fix onChange type for FileInput

- src/js/components/PageHeader/PageHeader.js
- src/js/components/PageHeader/__tests__/__snapshots__/PageHeader-test.tsx.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- Allows a caller to set default PageHeader pad in their theme.
- Related to: https://github.com/grommet/hpe-design-system/issues/2603
PageHeader.js + base.js
- Jest suite
- Manual storybook
- Storybook 
- Verify that a top and bottom pad is now added as default
- PageHeader custom themed --> add specify `pageHeader.pad` in custom theme --> confirm pad is rendered as expected.
N/A no adjustments or additions to Jest tests.
https://github.com/grommet/hpe-design-system/issues/2603
Yes, pad should be added to the PageHeader theme documentation.
No. Only the announcement of NEW PageHeader.
> PageHeader - Add pad to theme

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Menu/index.d.ts
- src/js/components/Menu/propTypes.js
- src/js/components/Menu/stories/Grouped.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
[Deploy Preview](https://deploy-preview-6162--sad-tereshkova-173d07.netlify.app/?path=/story/controls-menu-grouped--grouped)
This PR enhances `items` prop on Menu to allow for grouped items by passing an array of menu item arrays.
Looking for feedback on:
```
API
<Menu
items={[
[
{ label: 'View Details' },
{ label: 'Edit Permissions' },
],
[
{ label: 'Delete' },
],
]}
/>
```
**Theme**
- Adds `theme.menu.group.container` --> any Box props for an individual group
- Adds `theme.menu.group.separator` --> Color and size of separator
Related to https://github.com/grommet/hpe-design-system/issues/2621
Yes.
Yes.
> Enhance Menu to allow grouped items

- src/js/components/Button/__tests__/Button-test.tsx
- src/js/components/Button/__tests__/__snapshots__/Button-test.tsx.snap
- src/js/components/Button/propTypes.js
Allows Button `as` to accept elementType. This is important for cases when someone uses a router like react-router-dom and wants to do something like:
```
<Button
as={Link}
to="/home" (to is the prop for react-router-dom link)
label="Home"
/>
```
Yes.
> Allow Button to accept elementType for as

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/Swatch.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/DataChart/stories/Legend.js
- src/js/components/DataChart/utils.js
Changed DataChart to improve how swatches are rendered for detail and legend.
The key concept is that instead of always drawing a path and filling it, we now draw a line and style the stroke to align better with how the Chart renders.
DataChart.js
Check Detail and Legend stories.
Enhanced Legend story to include dash and round.
Verified that unit test snapshots changes are expected.
Detail and Legend stories
#6119 
no
yes
> Changed DataChart to improve how swatches are rendered for detail and legend

- src/js/components/Accordion/__tests__/Accordion-test.tsx
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- src/js/components/Accordion/stories/CustomThemed/Custom.js
- src/js/components/AccordionPanel/AccordionPanel.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `accordion.hover.background` to theme.
AccordionPanel
Adjusted Custom story and added jest test.
Closes #6176 
Yes.
Yes.
> Add accordion.hover.background to theme

- src/js/index.d.ts
Added missing page header export to index.d.ts
src/js/index.d.ts
Checked on a local typescript story
Locally on typescript story
closes #6178 
No functionality was changed
Yes, fix typescript page header export
Yes, backwards compatible
> fix page header typescript export

- src/js/components/Calendar/index.d.ts
Fixes typescript error caused but having two `HeaderProps` one in Calendar and one in Header. I renamed the Calendar one to `CalendarHeaderProps`.
See slack conversation: https://grommet.slack.com/archives/C09QQEG69/p1655286991166619
No
No
> Rename HeaderProps to CalendarHeaderProps

- src/js/components/Tabs/Tabs.js
The `isVisible` function is returning false is a tab is visible but it's focus indicator is not. If we are navigating through the tabs with the left and right arrow buttons `isVisible` returning false when a tab is visible but the focus indicator is not causes an issue where sometimes we scroll further than we want to. In the video below we are on a small screen and should only be advancing or moving back by 1 tab. Sometime we move by multiple tabs.
https://user-images.githubusercontent.com/54560994/173963077-988ccd65-a70c-4c85-8d96-6d4ba1e7355b.mp4
This pull request changes the `isVisible` function to return true if a tab is visible even if the focusIndicator is not. FocusIndicator visibility is only handled if we are navigating with the keyboard.
This can be tested with the storybook …
> Tabs - Fix isVisible to ignore if focusIndicator is visible

- src/js/components/Chart/index.d.ts
Adds the `id` prop to the typescript prop definitions.
`index.d.ts`
Closes #6149 
No
Yes
Compatible
> Added id prop to typescript prop definitions

- src/js/all/stories/AllComponents.js
- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/__tests__/__snapshots__/DataChart-test.js.snap
- src/js/components/Grid/Grid.js
- src/js/components/Grid/README.md
- src/js/components/Grid/index.d.ts
- src/js/components/Grid/stories/typescript/App.tsx
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Removes `grid.available` from Grid which affects DataTable as well
`Grid.js`
Testing through Storybook and updating tests.
Ensure Storybook examples are still working
Closes #6116 
No
Yes
Compatible
> Removed grid.available since IE is no longer supported

- package.json
- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adjusts the Menu grouped separator to have the same amount of padding/margin as the menu options.
Closes https://github.com/grommet/grommet/issues/6188
Yes
No
> Adjust menu grouped separator

- src/js/components/Paragraph/StyledParagraph.js
- src/js/components/Paragraph/__tests__/Paragraph-test.tsx
- src/js/components/Paragraph/__tests__/__snapshots__/Paragraph-test.tsx.snap
- src/js/components/Paragraph/index.d.ts
- src/js/components/Paragraph/propTypes.js
- src/js/components/Paragraph/stories/MaxLines.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Many designs have situations where they put a paragraph of text on a card or some other space-restricted area. Often that content comes from a dynamic source like external product descriptions, etc. This designs typically would like to truncate this content at a certain number of lines. Our current `<Text>` component can truncate a single line with an ellipsis, but we have no convenient solution for truncating something that is multiple lines with an ellipsis in an effecient way.
This adds a `maxLines` property to `<Paragraph>`. When the `<Paragraph>` gets constrained by a parent container or its max width restriction the content will get cleanly truncated with an ellipsis using an efficient browser css-supported mechanism much like `<Text truncate>`
Storybook Paragraph->Maxlines …
> Implement Paragraph maxLines

- src/js/components/Notification/index.d.ts
- src/js/components/Notification/propTypes.js
Adds `info` as a StatusType type definition for Notification.
src/js/components/Notification/index.d.ts
Locally on TS storybook.
https://github.com/grommet/grommet-site/pull/396
Yes.
> Typescript - include info as status type on Notification

- src/js/components/Image/Image.js
- src/js/components/Image/__tests__/Image-test.tsx
Image's onLoad prop is not provided to an Img tag
```
src/js/components/Image/Image.js
```
```sh
yarn test
```
1. You can change the Image storybook story in `src/js/components/Image/stories/Simple.js` to:
```js
export const Simple = () => (
<Image
src="//v2.grommet.io/assets/IMG_4245.jpg"
onLoad={() => console.log('onLoad')}
/>
);
```
2. Run the Storybook,
3. Go to the Image Simple story
4. Open the browser console to check if the `onLoad` message appears
#6202
No
> Fix image onLoad not being called

- src/js/components/FormField/FormField.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Prevents the debounce function from executing if the FormField is unmounted.
Tested with the following story and console log statements in the debounce function
```
import { Box, Form, FormField, TextInput, Button } from 'grommet';
export const TEMP = () => {
const [showForm, setShowForm] = useState(true);
return (
<Box fill align="center" justify="center">
<Box width="medium">
{showForm && <MyForm setShowForm={setShowForm} />}
<Button
label="Show form"
onClick={() => {
setShowForm(true);
}}
/>
</Box>
</Box>
);
};
const MyForm = ({ setShowForm }) => (
<Form
validate="change"
onChange={(val) => {
console.log(`onChange ${val}`);
setShowForm(false);
}}
>
<FormField
name="myField"
validate={(val) => {
console.log(`validate ${val}`);
}}
>
<TextInput …
```
> Cancel debounce function after FormField unmounts

- src/js/components/Tabs/Tabs.js
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.tsx.snap
Fixes and issue where the tabs header container was getting squished when Tabs is contained with a fixed height.
This issue shows up well when using the hpe theme because we have a bottom border on the tabs header container.
I solved this issue by adding `flex={false}` to the box around the tabs header content.
While working on this I noticed a separate issue where if justify is set to anything other than 'start', scrolling left through the tabs isn't working well. This can be sen in the Tabs/Responsive story by changing justify to 'center'. To resolve this I set justify to start when the tabs are overflowing.
Tested with the following code:
```
<Box pad="small" height="medium">
<Tabs alignControls="start">
<Tab title="Tab 1">
<Heading>Title</Heading>
<Paragraph>
Lorem ipsum dolor sit …
```
> Fix Tabs when container has a fixed height

- src/js/components/Menu/index.d.ts
Fixes Menu `items` typescript definition to use ButtonExtendedProps which includes intrinsic properties.
src/js/components/Menu/index.d.ts
TS example
Yes. Fixed Menu `items` typescript definition.
> Fix TS definition on Menu items

- src/js/components/DataTable/index.d.ts
This PR omits the HTML table `border` 
DataTable/index.d.ts
locally 
storybook
```
src/js/components/DataTable/index.d.ts:130:18 - error TS2320: Interface 'DataTableExtendedProps<TRowType>' cannot simultaneously extend types 'DataTableProps<TRowType>' and 'Omit<DetailedHTMLProps<TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>, "placeholder" | "onSelect">'.
Named property 'border' of types 'DataTableProps<TRowType>' and 'Omit<DetailedHTMLProps<TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>, "placeholder" | "onSelect">' are not identical.
```
since we are extending our DataTable props while vomiting some of the `html` table props there was an issue with `border` 
closes #6236 
no
sure
> omit border for table

- package.json
- tools/pack.js
- tools/release-stable.js
- yarn.lock
This PR reverts back the `del` package 
package.json
With the new release, they are moving directly to ESM and no longer supporting CommonJS support. This would mean that we need to move our CommonJS project to ESM. Which would change some of our package.json.. We cannot do this yet because some of our packages are not defined in ESM.  
closes #6258 
no
no
> revert del package

- src/js/components/Tab/Tab.js
- src/js/components/Tabs/__tests__/Tabs-test.tsx
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.tsx.snap
Changed Tab to be resilient to not be contains in Tabs.
This showed up when someone added a Tab to a Box in grommet designer, where it crashed.
Tab.js
Tab with Tabs
preserved existing test structure
no
yes
> Changed Tab to be resilient to not be contains in Tabs

- src/js/components/DataTable/DataTable.js
Uses the usePagination util so the Datatable component step can be defined with either `step` prop or inside `paginate` prop when used as an object.
`src/js/components/DataTable/DataTable.js`
`yarn test`
Use or create a datatable story in storybook using the paginate prop
https://storybook.grommet.io/?path=/story/visualizations-datatable-paginated--paginated
Issue #6221 
no
> Fix Datatable conflicting paginated step

- src/js/components/DataTable/__tests__/DataTable-test.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DataTable/buildState.js
In a Datatable, If you have a sortable column and some of the rows have a string value but some have a null, undefined or no value for that property then the table doesn't sort by that column.
This fixes Datatable sorting so that when some rows have a null or undefined value for a property it treats that value as an empty string for sorting purposes.
buildState.js
Manual testing via storybook as well as added jest test cases.
Closes #6281 
No
Yes
> Fix datatable sort when some attributes are null

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/SelectMultiple-test.js.snap
- src/js/components/Select/stories/Clear.js
- Fixes Select so that when `clear` is used, all Select options still render (original issue filed)
- Improves accessibility behavior of clear button by:
- Moving ClearButton outside of the options box (clear button is not an option)
- Improving styling of focused element to apply hover treatment (since focusIndicator={false}) so that keyboard user can track where the active element is
- Enhanced a11yTitle of Clear Button
To Do: 
User should be able to tab to the "Clear Selection" button if it is at the bottom.
In this video, I open the select with "space", use down arrow to move through the options, "enter" to select options", then "tab" to tab through the select options and get to "Clear Selection". I am using VoiceOver on Mac. …
> Fix Select to load all options even when clear={true}

- package.json
- src/js/components/Anchor/Anchor.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.tsx.snap
- src/js/components/Button/Button.js
- src/js/components/Form/Form.js
- src/js/components/Grommet/Grommet.js
- src/js/components/Grommet/index.d.ts
- src/js/components/Grommet/propTypes.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/Tabs/Tabs.js
- src/js/contexts/AnalyticsContext/AnalyticsContext.js
- src/js/contexts/AnalyticsContext/index.d.ts
- src/js/contexts/AnalyticsContext/index.js
- src/js/contexts/index.js
Implement the onAnalytics instrumentation in <Grommet>.
This is a follow on to https://github.com/grommet/hpe-design-system/issues/2714
```jsx
<Grommet onAnalytics={(evt) => { ... } } />
```
onAnalytics called with events in situations like:
- Form onSubmit and in a form
- evt contains touched, the form element, number of failed validations per field, time spent in the form.
- Form open and close. This can help detect form cancel
- Layer open and close.
- Tabs activated
- Button onClick - send button element to track actions and other usages
- URL changes (e.g. pageViews.) Use the MutationObserver trick to track url changes and send events for page views.
- const sendAnalytics = useAnalytics() API available for external use (as well as internal)
Some example data sent to `onAnalytics`: …
> Implement basic Analytics

- src/js/components/Meter/Circle.js
- src/js/components/Meter/__tests__/Meter-test.tsx
- src/js/components/Meter/__tests__/__snapshots__/Meter-test.tsx.snap
This fixes an issue where large data values for a circle style `<Meter>` cause no segments to be drawn (typically values in the 10000+ range)
Circle.js
Manual, jest and storybook
See the added jest test case for an example of the problem.
Fixes #6287 
No
Yes
Backwards compatible (fixes a regression)
> Fix circle meter angle calculation for large values

- src/js/components/Heading/Heading.js
- src/js/components/Heading/StyledHeading.js
- src/js/components/Heading/__tests__/Heading-test.tsx
- src/js/components/Heading/__tests__/__snapshots__/Heading-test.tsx.snap
- src/js/components/Heading/index.d.ts
- src/js/components/Heading/propTypes.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Closes #6276 by adding `weight` to `<Heading />`
Heading.js
Jest test suite, Storybook, plus new snapshot.
```
<Heading weight="normal">My Heading</Heading>
<Heading weight="bold">My Heading</Heading>
<Heading weight={700}>My Heading</Heading>
```
#6276
Yes.
Yes.
> Add weight prop to Heading

- src/js/components/Spinner/Spinner.js
- src/js/components/Spinner/__tests__/__snapshots__/Spinner-test.tsx.snap
Adds `min-width` css rule to Spinner to keep correct size. Usually, the issue is visible on mobile devices where content can squeeze Spinner component.
Spinner.js
Manual/snapshot
Enable Responsive Design mode in dev tools and validate Storybook
Spinner is not keeping its original size.
with `min-width`
No
No
> (Spinner) fix: keep the correct size

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/utils.js
In Select, previously if the caller provided `options` as an array of objects but did not pass a `labelKey` or `valueKey` this crashed the browser due to attempting to render a javascript object.
This change makes Select more resilient to this scenario by using `labelKey` if `valueKey` isn't provided and vice versa and using the first key otherwise.
utils.js
Manually changed the Object Options story to have neither or only one of the *key properties.
Also, added a new unit test for this scenario and validated that it failed without the change but passed with it. 
See above ^
Preserved existing Select test patterns.
This was uncovered via users of grommet-designer where they would pass the array of objects for `options` but hadn't set either of the *key properties yet. Crashing the browser …
> Changed Select to fix an issue when options are objects and no labelKey or valueKey is provided

- src/js/components/FormField/FormField.js
- src/js/components/FormField/__tests__/FormField-test.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
adds `formField.checkBox.pad` this will add `pad` to checkbox from theme.
FormField
set pad value to formField.checkBox.pad
set pad value to formField.checkBox.pad
Custom story
needed for theme
https://github.com/grommet/grommet-theme-hpe/pull/269
yes I will add a PR if this is the direction we go
sure
> add formField.checkBox.pad as an option to be handeled in formField

- src/js/components/DataTable/stories/SpaceX.js
- src/js/components/DataTable/stories/SpaceXUngrouped.js
adds a `key` to text
[DataTable/stories/SpaceXUngrouped.js](https://github.com/grommet/grommet/compare/master...britt6612:clean-console-error-storybook?expand=1#diff-bfe6bcf159bf6f25e0fc779f35ec3bf90001be6ad3cec007d72ed6d344d353df)
locally 
locally 
saw error while going through storybook for release thought it would be nice to clean up 
none
no
no
> fix console error in storybook story

- src/js/components/Anchor/Anchor.js
- src/js/components/Button/Button.js
- src/js/components/Layer/LayerContainer.js
- src/js/components/List/List.js
- src/js/utils/DOM.js
Improve some of the analytics events.
- Makes Layer's with `position="hidden"` not generate open/close events.
- Adds support for events from List `onClickItem`.
- Makes the element returned in the event for Button and Anchor clicks always be the button or anchor element rather than one of it's children.
Button.js
Manual, Jest and Storybook
Add a logging version of onAnalytics callback to `<Grommet>` usages. For example:
```jsx
const onAnalytics = (data) => console.log('onAnalytics', data);
<Grommet onAnalytics={onAnalytics}>
```
#6302 
Not yet
No
> onAnalytics improvements

- src/js/components/Select/EmptySearchOption.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/SelectMultipleValue.js
In NVDA aria-live regions are only read if they have a certain role associated with them. This PR adds `role='alert'` to aria-live regions in the SelectMultiple component so that the region is correctly read when using NVDA.
tested in voiceover on mac and NVDA in windows
no
no, this component isn't released yet
> SelectMultiple - Fix screenreader announcements in NVDA

- src/js/components/Select/SelectContainer.js
- src/js/components/Select/utils.js
Fixes an issue where if a null value is passed to Select the following error appears:
Tested by setting value to null in select storybook stories
Closes https://github.com/grommet/grommet/issues/6323
No
Maybe
> Harden Select against null value

- src/js/components/Notification/__tests__/__snapshots__/Notification-test.js.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Adjusts the notification theme based on comments in https://github.com/grommet/grommet-site/pull/416
One thing I was considering... on the grommet site PR the notification felt more like a page level notification. Right now we only have the option to have global notifications or toast notifications. Would these styling changes make sense to have for page level notifications one we have that option? Or should this styling change be applied to both global and page level notifications?
No
Yes
> Adjust notification theme

- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/SelectionSummary.js
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
Fixes an issue in the `showSelectedInline` version of SelectMultiple the open/close arrow isn't in the same location when the drop is open vs closed.
Current behavior:
https://user-images.githubusercontent.com/54560994/190019309-0e101e74-5078-48d2-af34-2a9e0052e5bf.mp4
Fixed behavior:
https://user-images.githubusercontent.com/54560994/190019436-3faae639-ea79-42e3-859b-15cdb872a6a2.mp4
Note: this PR also fixes an issue where the summary selection content was getting vertically squished when the screen has limited vertical space.
current:
fixed:
No
No, SelectMultiple component has not been released yet
> SelectMultiple - Improve alignment of open/close icon

- src/js/components/Form/__tests__/Form-test-controlled.js
- src/js/components/Select/Select.js
For Select component with multiple selection `nextValue` is an object (array) and we want to trigger change event in this situation to trigger a validation.
Select.js
Manual and unit tests
https://github.com/grommet/grommet/issues/6303
> (Select) fix: trigger a validation for multiple selection

- src/js/components/CheckBoxGroup/CheckBoxGroup.js
- src/js/components/CheckBoxGroup/__tests__/CheckBoxGroup-test.tsx
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.tsx.snap
- src/js/components/CheckBoxGroup/index.d.ts
- src/js/components/CheckBoxGroup/propTypes.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Adds `defaultValue` to CheckBoxGroup, similar to SelectMultiple.
src/js/components/CheckBoxGroup/CheckBoxGroup.js
tested locally in storybook, added jest test.
Yes.
Yes. Added `defaultValue` to CheckBoxGroup.
> Add defaultValue to CheckBoxGroup

- src/js/components/SelectMultiple/SelectMultiple.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/SelectionSummary.js
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
- src/js/components/SelectMultiple/stories/Default.js
- src/js/components/SelectMultiple/stories/LongList.js
When using the `onMore` prop with SelectMultiple we shouldn't show the 'Select All' button, because without all the options loaded we don't have a good way to select all of them. In addition we shouldn't show the total number of options when lazy loading because the total is unknown.
This PR also adjusts the alignment of the close arrow when using `showSelectedInline`.
Added storybook story SelectMultiple/Long list
no
no, component hasn't been released yet
> SelectMultiple - adjust behavior when lazy loading

- src/js/components/Notification/__tests__/__snapshots__/Notification-test.js.snap
- src/js/components/Notification/stories/CustomThemed/ThemedNotification.tsx
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Any notification that is not `global` or `toast` should have both rounding and a background color.
This PR should not affect the appearance of global or toast notifications (besides reverting the changes to the global notification theme from this pr: https://github.com/grommet/grommet/pull/6330)
Tested with existing storybook stories and changed the status of the notifications to confirm all are displaying as expected.
No
Yes
> Change notification theme to have background and rounding for non-global and non-toast notifications

- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/SelectionSummary.js
Fixes issues with the padding in the selection summary area of the SelectMultiple
Before:
After:
existing storybook stories
storybook
No
No, component not released yet
> SelectMultiple - adjust padding on selection summary

- src/js/components/Select/StyledSelect.js
- src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/SelectMultiple/SelectMultipleValue.js
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
Fixes an issue in SelectMultiple where a disabled option has hover styling and the cursor is displayed as a pointer, incorrectly indicating that the option is clickable.
Tested with SelectMultiple/Disabled story
No
No
> SelectMultiple - Fix hover and cursor issue on disabled option

- src/js/components/List/List.js
- src/js/components/List/__tests__/List-test.js
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
When you have a List with both `action` and `onOrder` specified the action and primary/secondary labels end up in a container that is column layout rather than the typical row layout you have with `action` when `onOrder` isn't used.
This change uses the same layout for the non onOrder-related elements as it would have used without `onOrder`. In the case of `action`, this puts the action next to the onOrder controls more like you'd expect.
List.js
Manual, storybook and Jest
Manualy add an action to an onOrder example.
Fixes #6341 
Before:
After:
No
Yes
> Fix List layout when it has action and onOrder defined

- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.tsx.snap
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.tsx.snap
- src/js/components/CheckBoxGroup/__tests__/__snapshots__/CheckBoxGroup-test.tsx.snap
- src/js/components/Clock/__tests__/__snapshots__/Clock-test.tsx.snap
- src/js/components/Collapsible/__tests__/__snapshots__/Collapsible-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/Layer/__tests__/__snapshots__/Layer-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
- src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
- src/js/components/SkipLinks/__tests__/__snapshots__/SkipLink-test.js.snap
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.tsx.snap
- src/js/components/TextInput/__tests__/__snapshots__/TextInput-test.tsx.snap
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.tsx.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.js.snap
- src/js/components/WorldMap/__tests__/__snapshots__/WorldMap-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/utils/styles.js
Adds the ```font-variant``` option to the global font type
```src/js/themes/base.d.ts```
```yarn test```, tests failing
NA
https://github.com/grommet/grommet/issues/6289
> added font-variant to global font type

- src/js/components/SelectMultiple/SelectMultiple.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/stories/Default.js
- src/js/components/SelectMultiple/stories/ObjectOptions.js
Fixes an issue when `options` are objects search doesn't behave as expected.
Also fixes an issue where capital letters in the search were not bolding the matches found. (When searching matching letters should be bolded)
Storybook object options story
Before:
https://user-images.githubusercontent.com/54560994/192879097-a8ca740f-d755-40af-896d-f9e2c1146613.mp4
After:
https://user-images.githubusercontent.com/54560994/192879147-8c66657f-d364-4f57-a588-77011ebb3239.mp4
No
Yes
> SelectMultiple - fix object options search

- src/js/components/Sidebar/stories/Labels.js
Adding aria-labels into Nav components to fix a11y violation in Labels story
Check Sidebar/Labels story in Storybook
yarn test + Storybook manual testing
Through Storybook
Changes don't affect tests
[#6124](https://github.com/grommet/grommet/issues/6124)
No
> Fix aria-label violation for Labels story

- src/js/components/DateInput/DateInput.js
- src/js/components/DateInput/__tests__/DateInput-test.tsx
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Allows theme to control DateInput rounding. Currently it was hardcoded to `xxsmall` which is limiting for themes that want a different value.
src/js/components/DateInput/DateInput.js
Tested in storybook locally and added unit test.
Yes.
Yes. Added `theme.dateInput.container.round`
> Allow DateInput rounding to be controlled via theme

- src/js/components/Notification/index.d.ts
Notification - Revert `title`'s type to be optional. [Related](https://github.com/grommet/grommet/pull/6390#discussion_r989163678)
/Notification/index.d.ts
No
No
> Notification - revert title type to be optional

- src/js/components/DataChart/Detail.js
Changed DataChart to not show detail for missing values.
When data objects are sparsely populated, the `detail` was including properties with no associated values. This would result in either blank content or showing "undefined" when there is a prefix.
This change omits including properties for which the value at the current detail index isn't provided.
DataChart Prediction story detail
^^^
no test changes, hard to test detail interaction in jest tests
This was uncovered via grommet-designer creating designs with sparse data.
Previously:
Subsequently:
no
yes
> Changed DataChart to not show detail for missing values

- src/js/components/Box/__tests__/Box-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
- src/js/utils/background.js
Fixes type error when `global.backgrounds` is defined but Box's `background.image` does not exist in the theme.
src/js/utils/background.js
In storybook and added unit test.
Before, this error would occur:
No. -- `global.backgrounds` is new and I don't believe many themes had leveraged it yet.
> Fix conditional in normalizeBackgroundImage

- package.json
- yarn.lock
Newer version of `grommet-icons` is required since https://github.com/grommet/grommet/pull/6249/files, but version in package.json was overwritten in https://github.com/grommet/grommet/pull/6329/files. 
Fix local build issue: `Failed to resolve 'grommet-icons/icons/FormPin' from './node_modules/grommet/es6/themes/base.js'` 
package.json
Having `grommet-icons` and `grommet` in my package.json will end up with node modules structure like this using yarn
```
node_modules/grommet-icons // v4.8.0
node_modules/grommet/node_modues/grommet-icons // v4.7.0, missing icons
```
Can be fix locally by adding `resolutions` entry, but still 4.8.0 is now min compat version users need.
no
no
> (Deps) update grommet-icons to avoid build issues

- src/js/components/DataChart/DataChart.js
- src/js/components/DataChart/Swatch.js
- src/js/components/DataChart/stories/Legend.js
- src/js/components/DataChart/stories/StackedBars.js
Changed DataChart to better match legend style to chart style.
Previously, opacity wasn't preserved, as can be seen with the legend here:
Now, the legend more accurately aligns to the styling of each property.
This was done by refactoring how the `seriesStyles` are built. That is the essence of these changes. Each chart can set styling, like color and opacity, but also each property can have its own styling for chart types like stacked "bars", "lines", and "areas". In the refactored code, `setPropertyStyle()` is now used across the various permutations and it is passed an object that spreads the chart styles first and then lets any per-property styles supersede them.
DataChart.js where `seriesStyles` are built, about line 324.
Enhanced the Legend and Stacked Bars stories.
DataChart …
> Changed DataChart to better match legend style to chart style

- src/js/components/SkipLinks/SkipLinks.js
- src/js/components/SkipLinks/__tests__/SkipLink-test.js
Fix SkipLinks should automatically filter out undefined children
From this issue #6266 
[SkipLinks/__tests__/SkipLink-test.js](https://github.com/grommet/grommet/compare/master...nidble:grommet:fix_skiplinks_filter_undefined_children?expand=1#diff-556d87db273d0732b0d8eef79133f8a2e0b028c03f76ead8858e45eb6a8fc0a8)
Reproducing https://codesandbox.io/s/grommet-v2-template-forked-dwsdu5?file=/index.js:343-411
No
#6266
No
Yes
> Fix SkipLinks filters out undefined children

- src/js/components/Menu/stories/typescript/Children.tsx
Fixes accessibility violation by updating the background color of the menu in `Menu/Children` storybook
`Menu/Children` storybook
Check the accessibility tab in the `Menu/Children` storybook
#6124
~https://user-images.githubusercontent.com/43496356/194731855-20d0ba78-5fb0-4063-80bf-34de3939a0af.png~
No
No
No
> Fix accessibility violation in Menu/Children storybook

- src/js/components/Table/Table.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Add fowardRef on Table component
Added a ref attribute on Table component, there was no warning on error on ref
https://github.com/grommet/grommet/issues/6370
They are backward compatible
> feat: add fowardRef on Table component

- src/js/components/FileInput/index.d.ts
It corrects types definitions for additional params of `onChange` property of `FileInput` component.
`FileInput` component.
Manual testing with the app that's using TypeScript.
Add `FileInput` with `onChange` property to the render of your component. Try to describe params of `onChange` precisely.
https://github.com/grommet/grommet/pull/6145 (the fix is incomplete).
No.
I think yes.
This change might break an app which has incorrect handling of second parameter of `onChange` (e.g., referring to property of `files` which doesn't actually exist, but TS wouldn't warn about this with current type definition).
> Correct types for onChange() params of FileInput

- src/js/components/FileInput/stories/CustomThemed/Custom.js
- src/js/components/FileInput/stories/MaxFileCount.js
- src/js/components/FileInput/stories/Multiple.js
- src/js/components/FileInput/stories/Simple.js
Hello there,
This should fix up the accessibility violations reported across some of the `FileInput` stories.
It seems like using a `label` element, explicit or implicit, appears to be the preferred way to work around such violations. In the interest of preserving the existing story visuals, I opted for `aria-label`. If the former is more desirable, I can update my changes.
---
Resolve accessibility violations for `FileInput` stories.
Changes are confined to the file input stories reporting violations.
Confirmed the violations no longer appear in the Storybook.
As above.
N/A.
None.
Refer to #6124.
N/A.
Don't think so.
Up to maintainers to decide.
Should have no impact on consumers of the library.
> Fix Storybook accessibility violations for the file input (#6124)

- src/js/components/Chart/stories/Pattern.js
Hello there,
This should fix up the accessibility violation being reported in the "Pattern" story for the `Chart` component.
---
Resolve an accessibility violation for the `Chart` component.
Changes are confined to the "Pattern" story.
Confirmed the violation no longer appears in Storybook.
As above.
N/A.
None.
Refer to #6124.
N/A.
Don't think so.
Up to maintainers to decide.
Should have no impact on consumers of the library.
> Fix Storybook accessibility violations for the chart (#6124)

- src/js/components/Tip/index.d.ts
Allows `dropProps` of Tip to accept inline style.
Tip types
local
Use `style` prop inline with `dropProps` of Tip 
N/A
#types
types
As a TS issue
> fix: dropProps should accept inline style

- src/js/components/Grommet/stories/Messages.js
Fix accessibility violation for Grommet Messages Story
storybook
yarn test + storybook
#6124
> Fix accessibility violation for Grommet Messages Story

- src/js/components/DataTable/stories/rowDetails.js
Fixing an accessibility violation for DataTable rowDetails story
storybook
yarn test + storybook
#6124
> Fix accessibility violation for DataTable rowDetails story

- src/js/components/DataTable/stories/Controlled.js
Fixing an accessibility violation for DataTable Controlled story
Storybook
yarn test + Storybook
#6124
> Fix accessibility violation for DataTable Controlled story

- src/js/components/DropButton/index.d.ts
- src/js/components/MaskedInput/index.d.ts
- src/js/components/Menu/index.d.ts
- src/js/components/Select/index.d.ts
- src/js/components/TextInput/index.d.ts
It's a follow-up to #6431 
The goal is for `dropProps` to accept `style` as a property. This behavior already exists in DateInput, Tip, but also needs alignment for other components as this PR suggests.
Any ts file
local
Use `style` prop with `dropProps` before/after the fix.
N/A
It's a follow-up to #6431 
Any bucket of TS bugs.
nope
Yes, as a TS fix.
Yes. It extends the type of `dropProps`
> Fix types of drop props in components

- package.json
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- yarn.lock
Upgrades the hpe theme dependency
No
No
> Upgrade grommet-theme-hpe

- src/js/components/FileInput/utils/formatBytes.js
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
Adds `?.` notation to formatBytes function for cases where `window` may not be defined yet.
src/js/components/FileInput/utils/formatBytes.js
Related to https://github.com/grommet/grommet/pull/6427
Ran into this error on DS site.
No. Change was only on stable branch not a release.
> Add optional chaining to formatBytes

- src/js/components/Select/SelectContainer.js
Changed Select to fix an issue with null value.
The problem comes from `null` being a javascript object. So, `typeof value === 'object'` is `true` when value is `null`
one line change
changed OrderOptions story to start with a `null` value instead of `''`
^^^
no
#6476 
no
yes
> Changed Select to fix an issue with null value.

- src/js/components/List/List.js
Refactored List key/value handling to reduce code duplication and fix issues with itemKey being a function when ordering.
Without this change, if `itemKey` was a function then the list ordering wouldn't work because it was only treating it as a string:
```
const ordItemKey =
typeof ordItem === 'object' ? ordItem[itemKey] : ordItem;
```
This issue was uncovered within grommet-designer.
List.js
unit tests
various storybook stories
used with grommet-designer to re-order grouped Menu items
storybook
no tests were canged
See above
no issue
no
yes
> Refactored List key/value handling to reduce code duplication and fix issues with itemKey being a function when ordering

- src/js/components/FileInput/utils/formatBytes.js
Follow on work to https://github.com/grommet/grommet/pull/6480. It looks like we need to check that the typeof window is not undefined otherwise we still get the window undefined error.
Tested change on DS site and made sure site built okay
No
No
> Fix window not defined issue

- src/js/components/DateInput/DateInput.js
- src/js/components/DateInput/__tests__/DateInput-test.tsx
- src/js/components/DateInput/utils.js
Fix the issue #6159 
DateInput component
add  
```js
format="mm/dd/yyyy"
```
and 
```js
calendarProps={{
bounds: ['2022-10-10', '2022-10-20'],
}}
``` 
~~I'll need #6424 to be merged first, because I'll need the `setHoursWithOffset` function to solve a issue with dates with wrong offset~~
closes #6159
> fix DateInput format calendar bounds

- src/js/components/DataTable/index.d.ts
Update the TS def for `rowDetails` in DataTable
index.d.ts
locally 
```
rowDetails takes a function as its argument. For example:
rowDetails={(row) => {return I am a box;}}
Typescript throws this error:
TS2769: No overload matches this call.
Overload 1 of 2, '(props: DataTableExtendedProps | Readonly<DataTableExtendedProps>): DataTable<...>', gave the following error.
Type '() => JSX.Element' is not assignable to type 'ReactNode'.
Overload 2 of 2, '(props: DataTableExtendedProps, context: any): DataTable', gave the following error.
Type '() => JSX.Element' is not assignable to type 'ReactNode'.
To fix it, I have updated src/js/components/DataTable/index.d.ts
I replace line 86 with this:
rowDetails?: (row: TRowType) => React.ReactNode;
```
closes #6477 
no
no
> fix ts for datatable

- src/js/components/RangeInput/StyledRangeInput.js
- src/js/components/RangeInput/__tests__/__snapshots__/RangeInput-test.tsx.snap
Fix the bug when using RangeInput in the FormField component.
StyledRangeInput.js
Updated the snapshot for this component
Using storybook via wrapping the RangeInput from the `FormField` or `div`
Yes, the `user-agent-stylesheet` adds the default margin to this component as the Input type of Range.
closes #6487 
added in the issue #6487 
No
No
> fix: RangeInput within formfield off center.

- package.json
- src/js/components/List/__tests__/List-test.js
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Table/__tests__/Table-test.tsx
Added a jest test for the following PRs:
https://github.com/grommet/grommet/pull/6416
https://github.com/grommet/grommet/pull/6424 - note this one is handled by the timezone addition in the package.json rather than an additional jest test
https://github.com/grommet/grommet/pull/6479
https://github.com/grommet/grommet/pull/6478
https://github.com/grommet/hpe-design-system/issues/2949
No
No
> Added tests pre 2.28.0 release

- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
fixes bug when using `border=between` and `gap` with a pixel value
styledBox.js
wrote a test and storybook
storybook
In the If statement for `border="between"` it uses `responsive metric to define `responsiveBorderMetric` which is undefined when a user passes a pixel value. 
closes #6485 
no
no
no
> add metric if responsiveMetric is undefined

- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Pagination/Pagination.js
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
Fixed an issue introduced in #6439 that caused cells to stretch (see screenshots). This PR reverts the change from #6439 but still fixes the original issue https://github.com/grommet/grommet/issues/6333.
Cells are stretching:
Fixed:
Tested with the code from #6333 and tested with the MultiplePins story by adding `step={3}` and `paginate`.
#6333
https://github.com/grommet/hpe-design-system/issues/2949
No
Yes
> Fix DataTable flex and pagination issue

- src/js/components/Drop/Drop.js
It prevent Drop.js Component from creating multiple divs when running App in StrictMode
From Drop.js in src/js/components/Drop/Drop.js
I tested it on a local environment adding Grommet as a library and creating a very simple react App (in StrictMode) with one Tip component that uses the Drop component inside. (I basically reproduced the codebox example of the issue #6371 ). Eventually I ran storybook to see possible regressions and found none.
I was not able to reproduce it without wrapping the App in StrictMode
I encountered this issue on  a personal project by using the Tip Component, I found out that only in a dev-build I was seeing this issue and prod build were bug free.
it closes #6371
it is backwards compatible
> fix:prevent-extra-div-container-in-drop-component

- src/js/components/DataTable/Header.js
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.js.snap
Fix the bug when selecting the search icon within a column header the text 
Header.js
Updated the snapshot for this component
I used the storybook to test this component.
If not passing any align property through the column header, default set to center.
Closes #6493
No
No
> Column Search Causes Jumpy Header Text

- src/js/components/Select/index.d.ts
Select does not currently support `readOnly` functionality. This aligns the typescript definition with the currently supported behavior.
src/js/components/Select/index.d.ts
In local storybook:
Closes #6509 
No.
Yes. Typescript fix.
> Omit readOnly from Select props

- src/js/components/Collapsible/Collapsible.js
- src/js/components/Collapsible/__tests__/__snapshots__/Collapsible-test.tsx.snap
Fixes animation speed value. When component is open on init `nextSpeed` value is `NaN` because sizeRef returns undefined at this point and this value is used in nextSpeed computation.
Collapsible.js
manual
set initial open prop to true
Closes #6523
no
yes
no
> (Collapsible) fix: enable animation when initial open prop is true

- src/js/components/Select/index.d.ts
Fixes Select `value` type definition to include `number` which is documented.
src/js/components/Select/index.d.ts
Tested locally in storybook to make sure `number` is supported.
Set Select value to a number that is included in the options array.
Closes #6522 
No.
Yes. Typescript fix.
> Update Select value type definition

- src/js/components/Form/stories/SolicitedFeedback.js
- src/js/components/StarRating/stories/simple.js
- src/js/components/ThumbsRating/stories/simple.js
adds simple stories for starRating and ThumbRating
takes out `color` prop in old story
StarRating/stories
ThumbsRating/stories
local
storybook
closes #6547 
no
yes
> add simple stories for new rating inputs

- src/js/components/FormField/FormField.js
- src/js/components/RangeSelector/RangeSelector.js
- src/js/components/RangeSelector/__tests__/RangeSelector-test.js
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.js.snap
- src/js/components/RangeSelector/index.d.ts
- src/js/components/RangeSelector/propTypes.js
- src/js/components/RangeSelector/stories/Label.js
- src/js/components/RangeSelector/stories/Simple.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Changed RangeSelector to add `label`. This moves the functionality from being inside DataFilter to be part of RangeSelector directly.
index.d.ts
Added a story and unit tests.
Storybook
No change to existing unit tests for RangeSelector. They should be updated to Typescript at some point.
Follow on from the `<Data />` work.
yes
yes
> Changed RangeSelector to add label

- src/js/components/FormField/FormField.js
- src/js/utils/DOM.js
Enhances certain DOM functions that FormField relies on to ensure that activeElement within a shadow DOM is detected.
Reference: https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode, https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/activeElement
src/js/components/FormField/FormField.js
Tested in local storybook where I set up a FormField in a shadow dom (mirroring the scenario from #6232)
The Box inside the shadow DOM now receives the proper highlighting.
https://user-images.githubusercontent.com/12522275/210661218-34ed2c19-c0b4-4c38-833e-bcc525c223d9.mov
document.activeElement will not look into a shadow root, so getRootNode() needs to be used to determine if root is document or shadow root.
Closes #6232 
Yes.
> Update DOM functions to fix shadow root bug

- src/js/components/DateInput/DateInput.js
- src/js/utils/refs.js
Change the implementation of `useForwardedRef` to not modify the associated ref during render. The preferred method of updating the forwarded ref according to React is its `useImperativeHandle` hook.
See #6551 for details on the issue.
The change to the DateInput-test is basically because the `.focus()` done via a setTimeout() can actually happen after the DOM has gone away (even though the timeout is only 1ms.)
refs.js
jest, manual and storybook
Go to the DateInput "Format" story and click on the icon to open the Calendar. Then click on a date in the calendar and close it.  It should use the ref that the Calendar forwarded from DateInput to set focus on the DateInput input field.
pass a ref into any component that uses `useForwardedRef()` and then display that ref from a `useEffect`. …
> fix useForwardedRef

- src/js/components/List/List.js
When a List allows clicking on items via the `onClickItem`, it sets focus on the List container for various reasons including accessibility and WCAG compliance. However that .focus() causes the the browser to automatically scroll the container in some cases even though it's not necessary in this situation.
This removes the call to set focus() on the List container on item click. It turns out this really doesn't seem to be needed anymore. Without this extra focus() call, clicking on an item does cause the container to get focus, and it does it without causing an extra scroll attempt to make sure it's visible (which isn't needed in this situation.)  
List.js
Manual, jest, existing storybook.
- In storybook go to the List/onClickItem.
- Make the  window sized so that the list has a scrollbar …
> Remove unnecessary focus() on List click

- src/js/components/Data/propTypes.js
Fix the bug when checking the data-controlled story in locally 
components/Data/proptypes.js
I used the storybook to test this component.
Added proptype as array type, object and any type.
Closes #6572 
No
No
> Data - controlled story invalid prop error

- src/js/components/DataTable/index.d.ts
update the type of `onSearch` function in `src/js/components/DataTable/index.d.ts`
`yarn test` was run
https://github.com/grommet/grommet/issues/6555
No
No
Breaking change
> fix: Datatable onSearch argument use object type

- src/js/components/Data/stories/SpaceX.js
- src/js/components/DataFilters/DataFilters.js
- src/js/components/DataSort/DataSort.js
- src/js/components/DataTable/DataTable.js
Integrate DataTable sorting with Data.
Build DataTable's internal `sort` state based on any `view.sort` and pass any `onSort` within DataTable up to `onView` in Data.
DataTable.js
Modified SpaceX story to leverage this.
SpaceX story
no changes to tests
yes
yes
> Integrate DataTable sorting with Data

- src/js/components/FormField/__tests__/FormField-test.js
Adds a test for https://github.com/grommet/grommet/pull/6577 before we release
https://github.com/grommet/hpe-design-system/issues/3100
No
No
> Add test for FormField autoFocus

- src/js/utils/DOM.js
Fixes an issue where if you tab beyond a formField and focus doesn't move to another element the node passed to `withinDropPortal` is undefined, resulting in the following error:
Tested with the following story:
```javascript
import { Box, DateInput, Form, FormField } from 'grommet';
export const Test = () => (
<Box fill align="center" justify="center">
<Form validate="blur">
<FormField label="Enter a date">
<DateInput format="mm/dd/yyyy-mm/dd/yyyy" />
</FormField>
</Form>
</Box>
);
export default {
title: 'Input/Form/Test',
};
```
Using the above story tab past the DateInput
No
Yes
> Check that node is defined in `withinDropPortal` function

- .testcaferc.json
- e2e/src/App.js
- e2e/tests/dateinput-test.js
Adds end to end tests for the issues addressed in https://github.com/grommet/grommet/pull/6436#discussion_r1000999264 and https://github.com/grommet/grommet/pull/6566
https://github.com/grommet/hpe-design-system/issues/2344
No
No
> Add some DateInput tests to testcafe

- src/js/components/Drop/DropContainer.js
- src/js/components/DropButton/DropButton.js
DropButton.js
storybook
```
<Box margin={{ left: 'large', top: '200px' }} direction="row">
<DropButton
badge={badge}
dropAlign={{ left: 'left', top: 'bottom' }}
label='hello'
icon={<Columns />}
dropContent={
<Box pad="medium">
<Button
label="Toggle badge"
onClick={() => setBadge((prev) => !prev)}
/>
</Box>
}
/>
</Box>
```
Re-rendering the Button when adding a badge or tip causes the DropButton's `buttonRef.current` to change. DropButton passes the initial `buttonRef.current` to DropContainer but doesn't pass the new one when the Button re-renders for the badge.
more comments [here](https://github.com/grommet/grommet/issues/6539)
closes #6539 
no
yes
> use `forwardref` and change `buttonref`

- src/js/components/Data/__tests__/Data-test.tsx
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/Pagination/Pagination.js
Changed Pagination to fix an issue with propagating step and page properties to Data view.
Adds a `useEffect()` to pass up the `step` and `page` when they different from the Data's `view`.
Pagination.js
Added a new unit test.
Manually tested a story.
manually
aligned with existing Data unit tests
no
yes
> Changed Pagination to fix an issue with propagating step and page properties to Data view

- src/js/components/DataTableColumns/DataTableColumns.js
- src/js/components/DataView/stories/Simple.js
Changed DataTableColumns to fix an issue when Data doesn't have updateOn=change.
This aligns with DataFilters where the DataForm is set to have `updateOn="change"` when not already in a DataForm context.
DataTableColumns.js
manually tested
no unit tests changed
no
yes
> Changed DataTableColumns to fix an issue when Data doesn't have updateOn=change

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.tsx.snap
- src/js/components/Drop/stories/Overflow.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Changed Drop behavior to flip the drop if part of the drop isn't visible and there is more room in the opposite direction.
I also set the `responsive` prop to true by default. This aligns with what the documentation shows.
Closes https://github.com/grommet/grommet/issues/6495
No
Yes
> Drop - flip drop position if part of the drop isn't visible

- src/js/components/DataTable/GroupedBody.js
This PR makes it possible in `DataTable` to use `rowProps` to target group header rows. The 'key' for a group header is the value of the data member property specified by `groupBy`.
For example, in the code below the data is grouped by the data property `location`. One of the values of `location` is "Fort Collins". By including an member in the `rowProps` object with the key `Fort Collins` we specify row properties for the group header for the "Fort Collins" group. 
GroupedBody.js
Manual and Storybook
I tested this by adding `rowProps` to the DataTable/Grouped storybook example:
```jsx
import { Box, DataTable } from 'grommet';
// Source code for the data can be found here
// https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/stories/data.j …
```
> Make rowProps work on group header rows

- src/js/components/DataTable/StyledDataTable.js
- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
Currently, the DataTable size parameter only allows for a size that is defined in the theme (i.e. small, medium, large, etc.). This PR allows for a custom css string to be provided instead. 
- Checkout the PR branch. 
- Run storybook
- Navigate to http://localhost:9001/?path=/story/visualizations-datatable-sized--sized-data-table
- Update to the [associated story](https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/stories/Sized.js) to test a standard css value (i.e. '200px')
I have not developed test for this PR since it is a pretty simple change.  Let me know if you would like me to do so
I have a use case in which I need to fill a container (Box) with a data table.  Without this PR, I haven't found another way to accomplish this. 
I don't think so. The docs …
> Fix DataTable size parameter to allow for css string

- src/js/components/Layer/LayerContainer.js
This changes the logic of when to `restrictScroll` 
LayerContainer.js
Storybook
```
import { Box, Grommet, Button, Layer, Header, Heading } from 'grommet';
import { hpe } from 'grommet-theme-hpe';
export const TargetLayer = () => {
const [open, setOpen] = React.useState();
const ref = React.useRef();
const onOpen = () => setOpen(true);
return (
// Uncomment <Grommet> lines when using outside of storybook
<Grommet theme={hpe}>
<Box height="xxlarge">
<Box
ref={ref}
height={{ min: 'small' }}
gap="medium"
width="medium"
background="brand"
>
<Button label="Open" onClick={onOpen} />
{open && (
<Layer position="center" target={ref.current}>
<Box
gap="medium"
pad="medium"
width={{ min: 'medium' }}
flex="grow"
>
<Header
flex={false}
align="start"
gap="small" …
```
> Change logic for restrict scroll

- src/js/components/Data/DataForm.js
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
- src/js/components/DataFilters/DataFilters.js
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/DataFilters/stories/Inline.js
- src/js/components/DataFilters/stories/Layer.js
- src/js/components/DataSearch/DataSearch.js
- src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
- src/js/components/DataSort/DataSort.js
- src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
- src/js/components/DataSummary/__tests__/__snapshots__/DataSummary-test.tsx.snap
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
- src/js/components/DataView/DataView.js
- src/js/components/DataView/__tests__/__snapshots__/DataView-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/FormField/FormField.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/StarRating/__tests__/__snapshots__/StarRating-tests.tsx.snap
- src/js/components/ThumbsRating/__tests__/__snapshots__/ThumbsRating.tsx.snap
- src/js/components/Toolbar/__tests__/__snapshots__/Toolbar-test.js.snap
- src/js/languages/default.json
Changed DataFilters to have overflow when using `drop` or `layer`.
The snapshot changes are primarily due to two reasons:
- the restructuring of DataForm
- adding `flex={false}` to FormField
DataForm.js
storys
storys
no tests were changed in the creation of this pull request
#6626 
no
yes
> Changed DataFilters to have overflow

- src/js/components/Form/stories/Controlled.js
- src/js/components/Form/stories/ControlledInput.js
- src/js/components/Form/stories/ControlledInputLazy.js
- src/js/components/Form/stories/ControlledLazy.js
- src/js/components/Form/stories/FieldWithChildren.js
- src/js/components/Form/stories/FieldWithComponentProp.js
- src/js/components/Form/stories/Uncontrolled.js
- src/js/components/Form/stories/ValidateOnChange.js
- src/js/components/Form/stories/ValidateOnMount.js
- src/js/components/Form/stories/typescript/TypedForm.tsx
This PR adds the htmlFor and id's for the form stories that caused the "Form elements must have labels" accessibility warnings. 
Controlled.js
form-test-controlled and form-test-uncontrolled passed.
Storybook
#6542 
No
No
> Issue #6542 Updated form stories to use htmlFor and id.

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- src/js/components/Box/__tests__/__snapshots__/Box-style-test.tsx.snap
- src/js/components/Button/__tests__/Button-kind-test.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Card/__tests__/__snapshots__/Card-test.tsx.snap
- src/js/components/Drop/__tests__/__snapshots__/Drop-test.tsx.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.tsx.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/utils/background.js
- src/js/utils/colors.js
Fixes an issue on dark transparent background where the text is the wrong color.
Just a note about the snapshot changes: for background colors that are opaque the snapshots are changing to use the css property `background-color` instead of `background`. In addition the text color is added in the snapshot, note that in most cases the snapshot already includes the text color so the text color is being duplicated in some cases. I couldn't find a good way around this. Visually I didn't notice any problems from this change but since this code is used across so many components it would be good to get extra eyes here.
Added a unit test and tested with the following story:
```javascript
import {
Box,
Grommet,
Button,
} from 'grommet';
import { deepMerge } from …
```
> Button text color handle dark and transparent backgrounds

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/__tests__/Calendar-test.tsx
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds a new prop `calendar[size].headingSize` to the theme. Specifying this prop will override the `calendar.heading.level` prop and change the calendar to use `<Text>` instead of `<Heading>` to display the date and year. This prop also gives the flexibility to specify different font sizes for each calendar size (small, medium, and large).
In addition to this PR I will file a PR on grommet-theme-hpe to opt into this behavior for the hpe theme.
Added a jest test and tested by adding a custom theme to calendar stories
Related to https://github.com/grommet/grommet/issues/6637
Yes, we need to document the new theme prop as well as mention that using `calendar[size].headingSize` is preferred over `calendar.heading.level`
Yes
> Calendar - add `calendar[size].title` prop to theme

- src/js/components/Data/DataForm.js
- src/js/components/Data/stories/Complex.js
- src/js/components/DataFilter/DataFilter.js
- src/js/components/DataFilters/__tests__/DataFilters-test.tsx
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
Changes Data to handle nested objects in the data as properties.
Now, you can use `properties={ 'location.city': { ...} }` and it will do what you might suspect.
Also, I combined `options` and `range` into a single `useMemo()` in DataFilter to be more efficient.
Take a look at the new Complex story under Data.
Added the Complex story to test interaction with both range and options versions.
Complex story
no jest changes
#6638 
yes
yes
> Changed Data to handle property paths

- src/js/components/Anchor/Anchor.js
- src/js/components/Anchor/__tests__/Anchor-test.tsx
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.tsx.snap
To align with previous behavior, icon color should align with label color. With [recent theme enhancement](https://github.com/grommet/grommet/pull/6643), the theme size-specific styling wasn't coming through on icon. Updating iconColor logic to check for color specification.
src/js/components/Anchor/Anchor.js
Tested in storybook, added a jest test.
Related to #6636 
No.
No.
> Anchor -- Align icon color to label color when theme.anchor.size.color is specified

- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
Adds a test for styling DataTable rowProps on group header rows. (Functionality added in https://github.com/grommet/grommet/pull/6627)
https://github.com/grommet/hpe-design-system/issues/3086
No
No
> Added test for DataTable rowProps on group header rows

- src/js/components/Tabs/Tabs.js
- src/js/components/Tabs/__tests__/Tabs-test.tsx
- src/js/components/Tabs/__tests__/__snapshots__/Tabs-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- src/js/utils/index.d.ts
Adds `theme.tabs.header.alignSelf` to allow theme to drive alignment of Tabs header along axis. This moves where `alignControls` property applies to fix a bug from when responsive tabs was added.
src/js/components/Tabs/Tabs.js
Tested in a storybook, added a test.
Related to https://github.com/grommet/grommet-theme-hpe/issues/308
Yes.
Yes. Added `theme.tabs.header.alignSelf` to theme.
> Allow align of Tab controls to be theme driven

- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
Applies `line-height: 0` for icon-only buttons. This is a required fix for Safari and does not have any visual effects on other browsers. Safari improperly determined a button's dimensions in cases where only icon property was applied, no label.
src/js/components/Button/StyledButtonKind.js
See screenshots below. Tested locally in storybook using NEXT branch of grommet-theme-hpe. This can also be tested directly in a browser (current HPE Design System site exhibits this bug. For example, the "Search" button in main header has 39px height as opposed to 36px). Applying line-height 0 to the button fixes it.
See above notes.
Closes https://github.com/grommet/grommet/issues/6667
BEFORE
AFTER
BEFORE (grommet-theme-hpe NEXT)
AFTER
No.
Yes.
> Apply line-height 0 for iconOnly buttons

- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
- src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/FormField/FormField.js
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.js.snap
- src/js/components/StarRating/__tests__/__snapshots__/StarRating-tests.tsx.snap
- src/js/components/ThumbsRating/__tests__/__snapshots__/ThumbsRating.tsx.snap
- src/js/components/Toolbar/__tests__/__snapshots__/Toolbar-test.js.snap
Reverts FormField `flex={false}`
FormField.js
none
#6669 
no
yes
> Reverted change in FormField to use flex={false}

- src/js/themes/base.d.ts
Adds base.d.ts definition for `theme.icon.disableScaleDown`.
Related to https://github.com/grommet/grommet-icons/pull/301
Yes.
> Add disableScaleDown to base.d.ts

- package.json
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.tsx.snap
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
- src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Notification/__tests__/__snapshots__/Notification-test.js.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
- src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
- src/js/components/Video/__tests__/__snapshots__/Video-test.tsx.snap
- yarn.lock
Upgrade to use the latest version of grommet-icons
https://github.com/grommet/grommet/issues/6658
No
Maybe?
> Updated grommet icons version

- src/js/components/SelectMultiple/SelectMultiple.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
Remove the use of the `FormUp` icon and change SelectMultiple's icon when the drop is open to work better with the new version of the HPE theme.
Before (using NEXT-stable of hpe theme):
After (using NEXT-stable of hpe theme):
Pointed package.json to use NEXT-stable version of the hpe theme, added in changes from https://github.com/grommet/grommet-theme-hpe/pull/328 and tested with SelectMultiple/showSelectedInline story
https://github.com/grommet/grommet-theme-hpe/pull/328
https://github.com/grommet/grommet-theme-hpe/issues/319
No
Yes
> Changed SelectMultiple `showSelectedInline` icon to use icon specified in the theme

- src/js/components/Button/StyledButtonKind.js
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
Applies that same fix in https://github.com/grommet/grommet/pull/6666 to icon only plain buttons.
https://github.com/grommet/grommet-theme-hpe/issues/319
No
Yes
> Add line height 0 to plain icon only buttons

- src/js/components/PageHeader/PageHeader.js
This PR adds functionality that automatically reduces the PageHeader subtitle size to `medium`. This is a reasonable value for HPE theme to ensure the subtitle remains smaller than the Heading (see screenshots below). `large` was not chosen because it would have the same font-size as the heading.
This does not effect Grommet theme which already uses a value of `medium`.
This only applies to the default size of PageHeader which is the main use case in HPE applications currently.
src/js/components/PageHeader/PageHeader.js
Local storybook with HPE next branch.
DESKTOP
MOBILE
No.
Yes.
> Provide default responsive subtitle behavior for PageHeader

- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
- src/js/components/Pagination/StyledPageControl.js
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
Mirrors approach from #6666 on pagination buttons which have a slightly custom button implementation which was overriding the line-height 0 from the underlying button.
Fixes rendering of next/previous icons on Safari.
src/js/components/Pagination/StyledPageControl.js
Tested in storybook with HPE NEXT theme on Safari.
resolved
> Apply line-height 0 to pagination controls

- .eslintrc
- package.json
- src/js/components/Drop/DropContainer.js
- src/js/components/DropButton/DropButton.js
- src/js/components/Layer/Layer.js
- src/js/components/Layer/LayerContainer.js
- storybook/preview.js
- yarn.lock
Addresses some issues with using grommet inside a shadow root context. Specifically, too much reliance on `document` being the root of things.
Also, added a "document" vs. "shadow" toolbar control in storybook to allow testing any story from a shadow root context.
Various stories with the new shadow root context, certainly not all though.
stories with shadow root context
no
yes
> Fixed some issues with using grommet in a shadow root

- src/js/index.d.ts
Adds `export skeleton` to index.d.ts
index.d.ts
closes #6700 
no
no
> add skeleton to ts

- src/js/components/NameValueList/NameValueList.js
- src/js/components/NameValueList/__tests__/NameValueList-test.tsx
- src/js/components/NameValueList/__tests__/__snapshots__/NameValueList-test.tsx.snap
Fixes #6716 by ensuring `align` gets passed to Grid.
`NameValueList.js`
Storybook
Add some Grid props to .../NameValueList/Simple such as:
```
<NameValueList
align="center"
justify="center"
gap={{ row: 'large', column: 'xlarge' }}
>
...
```
#6716 
No
Yes.
> fix NameValueList align

- src/js/components/DataTable/Body.js
- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/DataTable/buildState.js
- src/js/components/DataTableColumns/stories/Simple.js
Changed DataTable to use a primaryKey value as the row key
one line changed
unit tests
storybook?
no change to test structure
#6688 
no
yes
backwards compatible when using primaryKey
if the caller has no column.primary or primaryKey and the first value in the data objects is not unique, the browser will display a warning. This is expected given the inputs.
> Changed DataTable to use a primaryKey value as the row key

- src/js/components/Accordion/Accordion.js
- src/js/components/Accordion/__tests__/Accordion-test.tsx
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- src/js/components/Accordion/index.d.ts
- src/js/components/Accordion/propTypes.js
- src/js/components/AccordionPanel/AccordionPanel.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
Added `level` prop to Accordion to allow caller to control what semantic heading should be rendered in the accordion panel.
src/js/components/Accordion/Accordion.js
Tested locally in a storybook example and added jest test.
Closes #6654 
- Added `level` to Accordion
> Add level prop to Accordion

- src/js/components/Box/__tests__/Box-style-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-style-test.tsx.snap
Adds a jest test for having a Box border array with 'between' as one of the values.
Functionality added in this pr: https://github.com/grommet/grommet/pull/6642
no
no
> Added a test for Box border between in an array

- storybook/preview.js
Fixes the following error when trying to use the shadow dom on storybook.
To replicate this issue go to any storybook story and change root to 'shadow' then switch to a different story.
no
no
> Fix error when switching to the shadow dom in storybook

- src/js/components/Button/Button.js
Fixed an issue where onClick was being set to false resulting in the following error:
no
no - button busy hasn't been released yet
> Set Button onClick to undefined instead of false when busy or success is true

- src/js/components/Data/__tests__/Data-test.tsx
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
Adds tests covering https://github.com/grommet/grommet/issues/6701 and https://github.com/grommet/grommet/pull/6704 by supplying Data with data containing property values as an array.
Data-test.tsx
New Jest test added.
N/A
https://github.com/grommet/hpe-design-system/issues/3164
No.
No.
> Added tests for Data with property values as an array

- src/js/components/Button/BusyAnimation.js
- src/js/components/Button/Button.js
Fixes an issue with Button `busy` where the busy animation was not the right color for non primary buttons.
To fix this I used `background-color: currentColor;` on the busy animation dots so that they would use the same color as the button label text.
Tested by changing the button busy story to use other button kinds
no
no
> Fix Button busy animation color for non primary buttons

- src/js/components/DataFilter/DataFilter.js
- src/js/components/DataFilter/__tests__/DataFilter-test.tsx
Changed DataFilter to handle properties with zero or one values.
Of note, there is a change to the unit test but not a snapshot change. This is because the "blank" and "zero" properties are not rendered by DataFilter. Before the change to DataFilter.js here, the snapshots would have changed to show awkward filter controls that didn't do anything.
DataFilter.js
Manually used a data set provided by @samuelgoff.
Enhanced a unit test to include these cases.
Try with more variations of data.
no change to existing test patterns
See notes above.
no
yes
backwards compatible, since filtering on properties with less than two possible values is meaningless.
> Changed DataFilter to handle properties with zero or one values

- src/js/index.js
For anyone using consuming Grommet with React Server Components, we should specify that Grommet components should be rendered on the client side.
no
yes
> Add use client to index.js

- src/js/utils/refs.js
Solve infinite loop from issue #6792 
Start reading the issue #6792 and go to the associated Codesandbox to see broken code since 2.29.0.
Verified ref callback value on component mount/re-render.
1. Go to codesandbox
2. Change the grommet version to : `npm:@lcdp/grommet@2.32.0-fix-infinite-loop-6792.1`
Codesandbox with version modified available here : https://codesandbox.io/s/grommet-v2-template-forked-clv6l7?file=/CustomComponent.js
3. Everything is working, go to console to see the correct DOM node passed in ref callback
NO TESTS
Issue #6792
No
No
Yes
> Add innerRef as useImperativeHandle dependency to avoid infinite loop (#6792)

- src/js/components/Drop/DropContainer.js
Fixes an issue where the app would crash because we tried to access dropRef.current.style without first checking if dropRef.current is defined.
no
yes
> Check that dropRef is defined before trying to access dropRef style

- src/js/components/Select/index.d.ts
- src/js/components/Select/propTypes.js
update `searchPlaceholder` to take a node as well as a `string`
select/index.d.ts
`searchPlaceholder` functionally takes a node as well as a string so should we support this? 
```
I want search icon and placeholder text in search input field.
But searchPlaceholder accept only string value and I want both search Icon and placeholder both like below screenshot
How to do that? (edited) 
```
https://codesandbox.io/s/competent-merkle-q908cc?file=/src/App.js
none
yes
maybe
> update prop type for select

- src/js/components/CheckBox/StyledCheckBox.js
- src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.js.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.js.snap
Fix issue [6803](https://github.com/grommet/grommet/issues/6803) of check mark exceeding parent bounds when padding applied with fill and reverse styles.
> Fix issue of check mark exceeding parent bounds when padding applied with fill and reverse styles.

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
Resolves an issue where using `valueLabel` on Select and `value={0}` results in the valueLabel not being displayed correctly.
Tested with the following storybook story and added a jest test.
```javascript
import { Box, Select } from 'grommet';
export const Test = () => {
const [value, setValue] = React.useState(0);
return (
<Box fill align="center" justify="start" pad="large" gap="medium">
<Select
options={[0, 1, 2]}
value={value}
valueLabel={(val) => `Value: ${val}`}
onChange={({ option }) => setValue(option)}
/>
</Box>
);
};
export default {
title: 'Input/Select/Test',
};
```
Closes https://github.com/grommet/grommet/issues/6829
no
yes
> Fix issue where valueLabel doesn't show if value is 0

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/themes/base.d.ts
adds `align` part to `menu.item.align`
menu.js
snapshot 
needed an easier way to have the `align` for the Menu 
closes #6830 
yes
yes
> add align for menu item

- src/js/components/Menu/Menu.js
Fixes logic for Menu when `align.bottom === 'top'` so that Menu control is not shown twice.
src/js/components/Menu/Menu.js
Local in storybook with:
```
<Menu
label="Menu"
dropProps={{ align: { bottom: 'top', right: 'right'}}}
items={[
{ label: 'First Action', onClick: () => {} },
{ label: 'Second Action', onClick: () => {} },
]}
/>
```
Storybook locally with above config.
Closes #6778 
Yes. Fixed bug with Menu `dropProps` where control was repeated.
> Fix issue with Menu control showing twice

- src/js/components/DataTable/buildState.js
Update logic of `normalizePrimaryProperty` to treat `null` like `undefined`. Therefore, if a DataTable has `primaryKey={null}` it will first see if any columns have `primary: true` defined and lastly will fallback to the first column.
While primaryKey doesn't technically support `null` as a value (see DataTable index.d.ts), this provides a more useful default behavior since propTypes loosely equates `null` and `undefined`. Having a primary key is important for certain DataTable behaviors such as `onSelect` that needs a primaryKey to identify a record.
To prompt people towards the desired values for `primaryKey`, I have added a console.warn statement with a link to the grommet docs.
Some notes:
- Typescript treats `null` differently than `undefined`. We do not want to extend the Typescript …
> Update DataTable primaryKey behavior to align behavior for undefined and null

- package.json
- src/js/components/Box/Box.js
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/__snapshots__/Box-layout-test.tsx.snap
- src/js/components/Box/__tests__/__snapshots__/Box-style-test.tsx.snap
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
- src/js/utils/styles.js
Converts Box component to use transient props. I updated the snapshots for the Box tests and reviewed the changes there, mostly it was formatting related. Also the snapshot changes cleaned up some duplicated props (for example `display` being defined multiple times)
no
as part of the larger styled components upgrade
> Changed Box to use transient props

- src/js/components/DataTableColumns/DataTableColumns.js
This PR has a fix for the DataTableColumns filter functionality where it will look at the label first to match the searchTerm.
Initially, it was looking at the property and this was causing the search filter to improperly filter the options.
Issue example: https://f4phv2.sse.codesandbox.io/datatable
- Storybook
> Fix DataTableColumns search filter

- src/js/components/Stack/Stack.js
- src/js/components/Stack/StyledStack.js
- src/js/components/Stack/__tests__/__snapshots__/Stack-test.tsx.snap
Converts Stack to use transient props.
> Convert Stack to use transient props

- src/js/components/Layer/Layer.js
Suppress DOMExceptions on hiding `Layer` (see #6888).
Good question. There are only minor code changes which and this should not effect functionality. But maybe suppressing the DOMException unhides other problems. In my manual testing I didn't see this, but maybe I overlooked something.
Rerun automated tests. As well as manual tests.
Since this is hard to reproduce, just hiding a `Layer`.
#6888
This screenshot shows that the error is gone using this PR:
One the left side you can see the header and the menu which proofs that rendering is fine on using this PR.
No
Yes
It is backwards compatible
> Suppress DOMExceptions on hiding Layer (#6888)

- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.js.snap
Fixes an issue where the MaskedInput value shows as `undefined` when the `value` property isn't supplied and an non-matching character is input.
Fixes #6884
MaskedInput.js
Manual, storybook and jest
```jsx
export const Barcode = () => {
const mask = [
{
length: [1, 14],
regexp: /^(3|38|38[0,1]|38[0,1][0-9]{1,11})$/,
},
];
return (
// Uncomment <Grommet> lines when using outside of storybook
// <Grommet theme={...}>
<Box fill align="center" justify="start" pad="large">
<Box width="medium">
<MaskedInput
mask={mask} 
/>
</Box>
</Box>
// </Grommet>
);
};
```
#6884
No
Yes
> Fix 'undefined' value in MaskedInput

- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
Fixes bug where Menu groups were collapsing when Menu had a scroll due to limited vertical space.
Menu.js
Tested in storybook.
BEFORE
AFTER
In GroupedMenu storybook example, reduce the vertical height of the window to introduce a scroll in the Menu items.
N/A No tests were updated.
Closes #6928 
No.
Yes. Fixed bug where grouped Menu items were collapsing when scroll was present in Menu.
> Add flex={false} to Menu item group container

- src/js/components/Data/DataForm.js
- src/js/components/DataFilter/__tests__/DataFilter-test.tsx
- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
Adjust `flatten` function in data form which was only accounting for the first nested property under a given key as opposed to all.
DataForm.js
https://github.com/grommet/grommet/assets/12522275/50895916-2813-4c9e-9d0e-2035ce3ed2a9
Tested in storybook using this code:
```
import { Grid, DataTable, Notification } from 'grommet';
import { Data } from '../Data';
// import { columns, DATA } from '../../DataTable/stories/data';
const data = [
{
id: 0,
location: 'San Francisco',
favorites: {
fruit: 'apple',
candy: 'chocolate',
},
},
{
id: 1,
location: 'Fort Collins',
favorites: {
fruit: 'apple',
candy: 'chocolate',
},
},
{
id: 2,
location: 'San Francisco',
favorites: {
fruit: 'pear',
candy: 'chocolate',
},
},
{
id: 3,
location: 'Fort Collins',
favorites: {
fruit: …
```
> Fix flatten function to allow filtering on multiple sub properties of same parent property

- src/js/components/Data/__tests__/Data-test.tsx
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilters/DataFilters.js
- src/js/components/DataFilters/__tests__/DataFilters-test.tsx
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
Closes https://github.com/grommet/grommet/issues/6940.
Uses `unfilteredData` instead of `data` as source to build up default filter options. Previously, the logic was built up from `data`, however if `data` reached a length of zero, then no object was available to build up the options.
- review issue
- DataFilters.js
- Storybook
- Added unit tests
Use the following stories:
- https://storybook.grommet.io/?path=/story/data-data-simple--simple
- Story 1 - when `properties` is not specified, [data provides default filters](https://v2.grommet.io/data#properties).
- Story 2 - when `properties` is specified, `properties` becomes [the schema definition for which properties are filterable](https://v2.grommet.io/data#properties) by filters.
For each:
1. Use a combination of filters to get zero …
> Fixed DataFilters to show all filter options

- src/js/components/Grommet/index.d.ts
- src/js/components/Grommet/propTypes.js
- src/js/languages/default.json
Fixes type definitions from Grommet `messages` prop.
Closes https://github.com/grommet/grommet/issues/6822
no
yes
> Fix types for Grommet messages

- src/js/components/Tip/Tip.js
Fixes #6926
- Tip stays open when the tip is hovered.
- In the stories
- Ran locally on storybook.
- Previously tooltip was disappearing when hovered 
- #6926 
- yes
> Tip stays open when the tip is hovered

- src/js/components/Box/stories/Round.js
Fix Storybook Accessibility Violations 
- src/js/components/Box/Round.js
- storybook :- `Box/Round`
Check the accessibility tab in the Box/Round storybook
#6124 
NO
NO
NO
> fix: box/round storybook accessibility violation

- src/js/components/Box/stories/Simple.js
Fix Storybook Accessibility Violations
- src/js/components/Box/Simple.js
- storybook :- `Box/Simple`
Check the accessibility tab in the Box/Simple storybook
#6124 
NO
NO
NO
> fix box/simple storybook accessibility violation

- src/js/components/RangeSelector/index.d.ts
Improves event handler type for `RageSelector` component.
Improves event handler type for `RageSelector` component.
index.d.ts of  RangeSelector
Checked the types locally
Verify the typing
Not applicable
#3165 
May be breaking for people using typescript. Because we are now making the type stricter.
> Updates type of onChange of RangeSelector

- .circleci/config.yml
- package.json
- tools/release-styled-components-beta-stable.js
This PR adds a script so anytime something is merged in styled-components-beta branch, it will trigger a CircleCI workflow for a release to `styled-components-beta-stable` branch.
This stable branch will be used to audit the styled components changes in various environments.
> Add release-style-components-beta-stable script

- src/js/components/DataTable/Body.js
Hello there,
This small change is intended to resolve #6719.
As I looked into this, I also discovered a variation to causing the unwanted highlighting of the first row. When keyboard navigation is initiated prior, any subsequent row checkbox click will re-highlight the first row. This is a more broad issue, affecting stories beyond "Controlled".
I did try to add a test, but wasn't able to arrive at a case that covers the unwanted highlighting scenario. The main problem I hit was emulating the keyboard navigation with the tab key in order to get the highlighting style to appear.
Finally, I do recognise this may not be the best remedy for the issue at hand. Hopefully I haven't misunderstood that the active row style should only be tied to the use of `onClickRow`.
---
Resolves unwanted …
> Prevent row focus style for unclickable rows with onSelect (#6719)

- src/js/components/RadioButtonGroup/RadioButtonGroup.js
Resolves an issue with RadioButtonGroup. When using a screenreader and navigating through the RadioButtonGroup options sometimes the focus jumps back to the first radio button.
This PR removes an unnecessary useEffect. The useEffect was added to ensure that when a RadioButtonGroup doesn't have a value and it is focused, the first option will receive focus. This behavior is already covered here: https://github.com/grommet/grommet/blob/master/src/js/components/RadioButtonGroup/RadioButtonGroup.js#L156-L158. The useEffect is unnecessary and introduces the screenreader issue.
Closes https://github.com/grommet/grommet/issues/7002
no
yes
> Fix focus issue on RadioButtonGroup

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Remove suggestion to use UserEvent over FireEvent in the PR template and contributing guide
no
no
> Remove suggestion to use UserEvent over FireEvent

- src/js/components/DataTableColumns/index.d.ts
- src/js/components/DataTableColumns/propTypes.js
Update prop types and typescript types to support `disabled` on DataTableColumns options.
> Update DataTableColumns prop types and typescript types

- src/js/components/DataSummary/DataSummary.js
- src/js/components/DataSummary/__tests__/DataSummary-test.tsx
- src/js/components/DataSummary/__tests__/__snapshots__/DataSummary-test.tsx.snap
- src/js/languages/default.json
Adds `items`, `itemsSingle`, and `totalSingle` to dataSummary messages. Additionally, adjusts logic so it's a little bit smarter to pull the singular "item" when only 1 total.
src/js/languages/default.json
Local storybook.
Local storybook.
Closes https://github.com/grommet/hpe-design-system/issues/3599
Yes.
Yes.
> Update DataSummary messages object

- src/js/components/Box/index.d.ts
- src/js/components/CheckBoxGroup/index.d.ts
`onClick` type is inherited generically from IntrinsicElements and grommet is currently limiting the type.
TS file
local
storybook
N/A
Fix a regression https://github.com/grommet/grommet/pull/6983#issuecomment-1810580064
https://github.com/grommet/grommet/issues/7016
TS
Yes
yes
> [Type] remove `onClick` from types of Box props

- src/js/components/DataSearch/DataSearch.js
- src/js/components/NameValueList/NameValueList.js
- src/js/components/NameValuePair/NameValuePair.js
- src/js/components/Toolbar/Toolbar.js
- src/js/utils/responsive.js
Adjusts the code in NameValueList and NameValuePair to account for both 'xsmall' and 'small' screen sizes instead of just 'small'.
Tested with existing NameValueList/Simple story with the hpe theme
Closes https://github.com/grommet/grommet/issues/6944
no
no (only relevant to hpe theme users)
> Adjust NameValueList to account for xsmall screen size

- src/js/components/Data/Data.js
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
In 80% of use cases where filters are hidden behind a filter button, they should open into a side drawer. More often than not, there are many attributes to be filtered on (especially in the default case before any `properties` have been specified. This ensures that we don't provide a default experience where there are tons of filters displayed in a drop which breaks our design recommendations.
This does not alter the default behavior for use cases not leveraging the `toolbar` prop. In those scenarios, the default behavior remains as inline and can be opted into via `layer`.
src/js/components/Data/Data.js
Local in storybook Data Simple.js
Any storybook that's using `toolbar` on Data.
Closes #7056 
Breaking change, but this is fine because Data + friends are still in beta.
> Change datafilters default presentation within toolbar to `layer`

- src/js/components/DataFilters/__tests__/DataFilters-test.tsx
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
adds test for filtering with RangeSelector and sub objects to support changes [here](https://github.com/grommet/grommet/pull/7049) 
datafilters/tests
the test is written 
adds more protection for us 
none
no
no
yes
> add test for sub objects with rangeselector

- src/js/components/Data/Data.js
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataClearFilters/__tests__/__snapshots__/DataClearFilters-test.tsx.snap
- src/js/components/DataFilters/DataFilters.js
This PR:
- Decouples DataSort from DataFilters. In cases where a view applied "sort", then the sort controls were appearing as part of filters. Now, DataSort will appear as a peer to DataFilters, keeping DataFilters purely focused on filter inputs.
- Aligns default `toolbar` layout with [Figma designs](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260-91540&mode=design&t=ABgPyLwvKbDaPeLj-0). 
- DataView should appear in a separate section and after filter controls.
- Adjusts DataClearFilters behavior to only clear filters and restore dataset to page 1, but does not clear search, sort, step, etc.
Storybook.
Closes #7063 
Backwards compatible, these components are still in beta.
> Decouple DataFilters and DataSort, refine toolbar layout

- src/js/components/DataFilters/DataFilters.js
- src/js/components/DataFilters/DataFiltersContext.js
- src/js/components/RangeSelector/RangeSelector.js
When RangeSelector is reset to its min/max, DataFilters should not "badge" that a filter has been applied. Putting this as a draft to get reactions to the approach.
Prior to this, a badge would apply even if RangeSelector is at its min/max. This is because technically RangeSelector always has a value, so once it was view as "touched" by DataFilters, there was no way to get it to be removed from the "touched" object without clearing all filters.
This is done by:
1. Creating a DataFiltersContext that has a value of a `pendingReset` ref in DataFilters.
2. `pendingReset` ref in DataFilters whose value is a Javascript Set, to track which range selectors should not be included in the "touched" object.
3. on change of its value, RangeSelector will add/remove itself from pendingReset depending on …
> Refine DataFilters badge behavior for RangeSelector reset to min/max

- src/js/components/DataTable/DataTable.js
- src/js/components/DataTable/GroupedBody.js
- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/DataTable/buildState.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/themes/base.js
Hello there,
Another pull request, this time aimed at addressing #6925.
A noteworthy side effect of my proposed fix involved updating existing test snapshots for DataTable. In particular, those which used `groupBy` for row grouping. I can only guess that this was because theme properties relating to `groupHeader` were never fed through properly.
---
Ensures that any theme properties (e.g. https://v2.grommet.io/datatable#dataTable.groupHeader.background) used to customise a DataTable component are incorporated for rendering.
Making sure that the test snapshots I updated are within reason.
I used the available DataTable stories in addition to adding an extra test that covers the provision of `groupHeader` theme properties.
Any DataTable story that involves `groupBy` would be affected by …
> Fix groupHeader theming properties for DataTable (#6925)

- src/js/components/DataFilters/DataFilters.js
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
Sets min-width of medium on DataFilters layer for more reasonable default width. With removal of "undo changes" which previously was holding some space to make the layer wider, the DataFilter layer was rendering quite narrow if the data labels were short. This sets a reasonable default for consistency.
src/js/components/DataFilters/DataFilters.js
BEFORE
AFTER
> Set min-width of DataFilters layer

- src/js/components/Data/DataForm.js
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataClearFilters/__tests__/__snapshots__/DataClearFilters-test.tsx.snap
- src/js/components/DataSearch/DataSearch.js
- src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
- src/js/components/FormField/FormField.js
- src/js/components/Toolbar/__tests__/__snapshots__/Toolbar-test.js.snap
- src/js/utils/index.js
- src/js/utils/use-debounce.js
Remove use of DataForm from DataSearch and instead directly modify the `view`
DataSearch.js
Each of the uses of Data in storybook that have the search ability
Storybook Data examples
No
No need
> DataSearch: Removed dependence on form

- src/js/components/DataClearFilters/stories/Simple.js
When you type into the search field on the DataClearFilters/Simple story the clear filters button is displayed. When the clear filters button is clicked it doesn't clear out the search field. This PR adjusts the logic so the clear filters button is only displayed when DataFilters are applied.
no
no
> Adjust logic in DataClearFilters story

- src/js/components/DataFilter/DataFilter.js
When testing Grommet designer, if DataFilter was added and no `property` had been defined yet, the app would crash.
In a Typescript project, the typings would already flag that `property` is required, so this is a fix for non-Typescript projects.
Tested locally in storybook.
```
<DataFilter />
```
Got this error in Grommet designer:
> Fix undefined case for DataFilter

- src/js/components/DataSearch/DataSearch.js
- src/js/components/DataSearch/__tests__/DataSearch-test.tsx
- src/js/components/DataSearch/index.d.ts
- src/js/components/DataSearch/propTypes.js
- src/js/components/DataSearch/stories/ChangeonEnter.js
- src/js/components/DataSearch/stories/UpdateOnSubmit.js
This is an updated version of PR #7029 originally raised by @anoopadvaitha.
Currently DataSearch filters data as soon as we start typing (onchange). This becomes challenge in scenarios where the data is fetched from API. 
The PR provides updateOn parameter which is passed to DataForm so that developer can leverage to either use change or submit. 
\src\js\components\DataSearch\DataSearch.js
Tested when no value is provided for DataSearch and when submit is provided and works in both scenarios. 
#7024 
Yes, will be raising the PR on that
No.
Yes
> Implement DataSearch updateOn property

- src/js/components/Data/index.d.ts
- src/js/components/Data/propTypes.js
- src/js/components/DataFilters/index.d.ts
- src/js/components/DataFilters/propTypes.js
- src/js/components/Grommet/index.d.ts
- src/js/components/Grommet/propTypes.js
`dataForm.reset` was removed by #7088. This removes the index.d.ts/propTypes support of it.
Additionally, making sure all propTypes/index.d.ts are up to date with latest functionality.
src/js/components/Grommet/index.d.ts
> Align Data+friends propTypes/index.d.ts to latest behavior

- src/js/components/DataTableColumns/DataTableColumns.js
Fixes error when DataTableColumns `options` is undefined. Even though `options` is a required prop, the app should not crash if it's not provided.
src/js/components/DataTableColumns/DataTableColumns.js
Locally in storybook.
Discovered when reviewing https://github.com/grommet/grommet-designer/pull/137
Fixes this where <DataTableColumns /> is used.
No.
No.
> Fix DataTableColumns undefined case

- src/js/components/DataClearFilters/stories/Simple.js
Changes the DataClearFilters story example to check that `view.properties` length before displaying the DataClearFilters button.
no
no
> DataClearFilters story - Check properties length before displaying data clear filters button

- src/js/components/Cards/stories/Simple.js
- src/js/components/Data/stories/Cards.js
- src/js/components/Data/stories/Complex.js
- src/js/components/Data/stories/Controlled.js
- src/js/components/Data/stories/DataTable.js
- src/js/components/Data/stories/Infinite.js
- src/js/components/Data/stories/Inline.js
- src/js/components/Data/stories/List.js
- src/js/components/Data/stories/Properties.js
- src/js/components/Data/stories/Simple.js
- src/js/components/Data/stories/SpaceX.js
- src/js/components/Data/stories/StarWars.js
- src/js/components/Data/stories/Views.js
- src/js/components/DataFilter/stories/Simple.js
- src/js/components/DataFilters/stories/Drop.js
- src/js/components/DataFilters/stories/Inline.js
- src/js/components/DataFilters/stories/Layer.js
- src/js/components/DataFilters/stories/Simple.js
- src/js/components/DataSearch/stories/Drop.js
- src/js/components/DataSearch/stories/Responsive.js
- src/js/components/DataSearch/stories/Simple.js
- src/js/components/DataSort/stories/Drop.js
- src/js/components/DataSort/stories/Simple.js
- src/js/components/DataSummary/stories/Simple.js
- src/js/components/DataTableColumns/stories/Simple.js
- src/js/components/DataTableGroupBy/stories/Simple.js
- src/js/components/DataView/stories/Simple.js
- src/js/components/Toolbar/stories/Simple.js
removes stable flag from data and friends components 
stories
locally 
when we are ready for release we can merge and update our storybook
no
no
> remove stable notification from storybook for data components

- package.json
Removes `engine-strict` true from package.json so that projects running node versions less than what is defined in `engines.node` of package.json don't fail with an error on install. This aligns back with the [default package.json behavior](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines).
We recently changed our package.json to increase our supported node version from >=16 to >=18 since node 16 has already reached its end of life date. That being said, we don't want to cause errors on dependency install for projects that still use node 16.
package.json
> Remove engine-strict: true from package.json

- package.json
In yarn this causes an error when for people using v16 of node, which would break backwards compatibility. Reverting to ensure backwards compatibility.
> revert node version back to 16

- src/js/components/Form/Form.js
- src/js/components/Form/__tests__/Form-test-uncontrolled.js
Fixing bug introduced by https://github.com/grommet/grommet/pull/7005, where if a submit event is fired directly on an input element, the form validations won't run.
This ensures that the event is either being trigged by the form or an input within the form, but still keeps the initial fix to avoid the React portals issue noted in the original issue.
Locally created test and added jest test:
```
test('should validate when submit is fired directly on input', () => {
render(
<Grommet>
<Form>
<FormField
label="My field"
name="my-field"
htmlFor="my-field"
validate={{
regexp: /^some-value/,
message: 'Invalid email address',
status: 'error',
}}
>
<TextInput
name="my-field"
id="my-field"
placeholder="placeholder text"
/>
</FormField>
<Button label="Submit" …
```
> Run form submit validation when submit is fired directly on input

- src/js/components/Box/Box.js
- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/Box-layout-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-layout-test.tsx.snap
- src/js/components/Box/index.d.ts
- src/js/components/Box/propTypes.js
This PR enhances `gap` on Box so a user can pass in {{ row: small, column: 'large' }}
styledBox.js
local storybook also wrote snapshot
yes
yes
> Enhance Box `gap` to accept object with `row` and `column`

- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/List/List.js
- src/js/components/List/__tests__/__snapshots__/List-test.js.snap
fix the bug when the List focus from the keyboard.
component/List/List.js
Updated the snapshot for this component
I used the storybook to test this component.
The list focuses on accepting only from the keyboard.
#6589
No
No
No
> fix: List focus via keyboard

- src/js/components/Grommet/Grommet.js
Adds check to ensure `window` is available when checking for color scheme preference.
Grommet.js
Applied fix to local project's `node_modules/grommet/es6/components/Grommet/Grommet,js`
N/A
NextJS app throws error :
```
node_modules/.pnpm/grommet@2.35.0_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/grommet/es6/components/Grommet/Grommet.js (71:32) @ window
⨯ Internal error: ReferenceError: window is not defined
at eval (./node_modules/.pnpm/grommet@2.35.0_react-dom@18.2.0_react@18.2.0_styled-components@5.3.11/node_modules/grommet/es6/components/Grommet/Grommet.js:110:37)
```
No.
Yes.
> Fixed Grommet ThemeMode "auto" to ensure window is available for server side render

- src/js/components/DataFilter/DataFilter.js
- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
DataFilter SelectMultiple should have a reasonable dropHeight so it doesn't just fill all the available space. Setting to `medium`.
src/js/components/DataFilter/DataFilter.js
BEFORE
AFTER
> Fix dropHeight of DataFilter SelectMultiple

- .eslintrc
- src/js/components/List/List.js
- src/js/components/List/__tests__/List-test.js
Modifies one of the list tests to use the 'space' key on the onOrder buttons. The test covers behavior added in https://github.com/grommet/grommet/pull/7140.
https://github.com/grommet/grommet/pull/7140 introduced a lint error because the dependency array for onSelectOption didn't include everything. I ended up removing the `useCallback` for that function. I don't think we were getting much value from `useCallback` in this case.
I modified our lint rules to flag react-hooks/exhaustive-deps as an error instead of just a warning. I was not able to find a way to have lint fail on warnings (but I didn't spend a ton of time looking, so I could have missed something).
no
no
> List keyboard behavior test and fix lint issues

- .circleci/config.yml
Reverting CI publish job to use NPM_TOKEN instead of NPM_TOKEN_TEST
> Revert npm publish token to existing

- src/js/components/Skeleton/StyledSkeleton.js
- src/js/components/Skeleton/__tests__/Skeleton-test.tsx
- src/js/components/Skeleton/__tests__/__snapshots__/Skeleton-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds `skeleton.extend` to theme to support custom animations or styling.
> Add skeleton.extend to theme

- src/js/utils/DOM.js
Prevents unintentionally matching `data` and `meta` elements, and possibly custom web-components.
- Issue https://github.com/grommet/grommet/issues/6981
- Comments on previous incorrect fix https://github.com/grommet/grommet/pull/6987
Not certain, but I doubt it affects any real-world usecase
> Fix autoFocusingTags regex

- package.json
- yarn.lock
The upgraded chromatic version was not the source of the snapshot changes. Instead, we believe it was the upgrade in Chromatic Cloud of which Chrome version is used.
Restoring our package.json to the latest chromatic version.
> Upgrade chromatic version

- src/js/components/DataFilters/__tests__/DataFilters-test.tsx
changes filters test to use `fireEvent`
DataFilters.tsx
locally run jest test
changed to use `fireEvent` instead of `user.click` so doesn't time out
https://github.com/orgs/grommet/projects/22/views/1?pane=issue&itemId=52570269
no
no
> change filters test to improve run time

- src/js/components/Pagination/Pagination.js
- src/js/components/Pagination/__tests__/Pagination-test.tsx
- src/js/utils/useControlled.js
Fixes a bug where step was not being updated based on `stepProp` 
pagination.js
added a jest test 
```
const [itemsPerPage, setItemsPerPage] = useState(20);
const [totalItems, setTotalItems] = useState(itemsPerPage);
useEffect(() => {
setTotalItems(250);
}, []);
return (
<Grommet theme={theme}>
<Select
testId="rows-per-page-dropdown"
defaultVal={20}
value={itemsPerPage}
options={[10, 20, 50, 100]}
onChange={({ option }) => {
console.log(option);
setItemsPerPage(option);
}}
/>
<Pagination numberItems={totalItems} step={itemsPerPage} />
</Grommet>
);
```
We added a step state then set that value within the PaginationStep so since I changed step from being directly assigned to stepProp to using useState it was only getting the initial value of stepProp during the initial render and was not …
> Fixed Pagination step to allow it to be controlled

- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/DataTable/index.d.ts
Adds unit test for DataTable scenario of `onUpdate` + `groupBy.onSelect` and fixes a Typescript error.
Adding this test to master so we can ensure we don't break backwards compatibility with changes in https://github.com/grommet/grommet/pull/7200
This feature was initially added by https://github.com/grommet/grommet/pull/5716, but there was no unit test for this condition.
src/js/components/DataTable/__tests__/DataTable-test.tsx
Tested locally in storybook
```
import { Box, DataTable } from 'grommet';
// Source code for the data can be found here
// https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/stories/data.js
import { groupColumns, DATA } from './data';
export const Test = () => {
const [groupSelected] = React.useState<{
[key: …
```
> Add unit test for onUpdate with groupBy.onSelect

- src/js/components/Data/__tests__/Data-test.tsx
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataSearch/DataSearch.js
- src/js/components/DataSearch/__tests__/DataSearch-test.tsx
Closes https://github.com/grommet/grommet/issues/7207 by ensuring that a search event returns to page 1 of matched search results.
DataSearch.js
- Storybook
- Added Jest tests
```
import { Data, DataTable, Pagination } from 'grommet';
const data = [
{
name: 'aa',
enabled: true,
rating: 2.3,
sub: { note: 'ZZ' },
tags: ['qa', 'staging', 'prod'],
},
{
name: 'bb',
enabled: false,
rating: 4.3,
sub: { note: 'YY' },
tags: ['qa', 'staging'],
},
{ name: 'cc', sub: {}, tags: ['qa'] },
{ name: 'dd' },
];
const properties = {
name: { label: 'Name' },
};
const view = {
step: 2,
page: 1,
search: '',
};
const columns = [
{ property: 'name', header: 'Name', size: 'small', primary: true },
];
// eslint-disable-next-line arrow-body-style
export const TEMP = () => {
return (
<Data …
```
> Fixed Data with Pagination so that it returns to page 1 on search

- src/js/components/ToggleGroup/ToggleGroup.js
- src/js/components/ToggleGroup/__tests__/ToggleGroup-test.tsx
- src/js/components/ToggleGroup/__tests__/__snapshots__/ToggleGroup-test.tsx.snap
Checks that options is defined before mapping. Error found when testing in Grommet Designer.
ToggleGroup.
Grommet designer locally. Added jest test.
Error from Grommet Designer.
> Ensure ToggleGroup doesn't crash when options is undefined

- src/js/components/DataTableColumns/__tests__/DataTableColumns-test.tsx
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
updates the snap shots for dataTableColumns
DataTableColumns.test
locally
snapshot
there was snap shots being taken but these were not taken correctly of the correct tab panel
> Update DataTableColumns snapshots to include drop

- src/js/components/Button/Button.js
adds the `selected` prop to be passed through to styledButtonResult
button.js
locally
locally
Users can leverage this `selected` prop. This is passed to styledButton but not to styledButtonResult
Related to https://github.com/grommet/grommet-theme-hpe/issues/390
no
yes
> add selected prop to be passed through

- package.json
- yarn.lock
markdown-to-jsx v7.4.5 is causing snapshot changes, I want to look into them a little more. For now I am temporarily freezing the version at 7.4.4 to avoid test failures due to the snapshot changes.
Created an issue to upgrade: https://github.com/grommet/grommet/issues/7233
no
no
> Temporarily freeze markdown-to-jsx

- COPYRIGHT.md
- package.json
Adds copyright information and includes the copyright and license files in the distribution folder
https://github.com/grommet/hpe-design-system/issues/3861
no
no
> Add copyright and include copyright and license in dist folder

- .circleci/config.yml
- package.json
Update circleci config to use newer node version and remove workaround for chrome install
I had to add `chrome --headless=new` to the package.json command until we can upgrade our test cafe version. See https://github.com/DevExpress/testcafe/issues/8145 for more details.
no
no
> Update circleci config

- src/js/components/Data/stories/ComposedToolbar.js
Adds a primary key to the DataTable in the Data/Composed Toolbar story. This prevents issues when the primary key column visibility is toggled off via DataTableColumns. See screenshot:
no
no
> Add primary key to composed toolbar story

- package.json
- yarn.lock
v5 of eslint-plugin-prettier has v3 of prettier as a peer dependency. We are not able to upgrade to v3 of prettier yet, downgrading esline-plugin-prettier so the peer dependency is on the correct version.
no
no
> Downgrade eslint-plugin-prettier version

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/__tests__/Drop-test.tsx
This PR checks to see if the user clicks on the target and then will not invoke the `onClickOutside` func
dropContainer
Added a test 
local story 
```
import React, { useRef, useState } from 'react';
import { Box, Button, Drop, DropButton, Layer, TextInput } from 'grommet';
const alignRight = { left: 'right' };
const alignLeft = { right: 'left' };
const MultipleDrop = () => {
const [showDrop, setShowDrop] = useState(false);
const targetRef = useRef();
return (
// Uncomment <Grommet> lines when using outside of storybook
// <Grommet theme={...}>
<Box gap="medium" fill align="center" justify="center">
<Button
ref={targetRef}
label="button"
onClick={() => setShowDrop(!showDrop)}
/>
{showDrop && (
<Drop
align={alignRight}
target={targetRef.current}
onClickOutside={() => setShowDrop(false)}
> …
```
> add a check to see if target is clicked

- src/js/components/Drop/DropContainer.js
- src/js/components/Drop/__tests__/Drop-test.tsx
This PR provides another option for users to be able to have `restrictFocus` set to true but also have a `autoFocus` in side the drop
dropContainer.js
```
import React, { useRef, useState } from 'react';
import { Drop, Button, Paragraph, Text, Box } from 'grommet';
import { CircleInformation, Close } from 'grommet-icons';
const Popover = ({
a11yTitle,
title,
children,
footer,
target,
onClose,
...rest
}) => {
return (
<Drop
role="dialog"
elevation="medium"
stretch={false}
target={target}
onClose={onClose}
restrictFocus
// need this for drop to control focus
{...rest}
>
<Box
gap="xsmall"
pad={{ vertical: 'small', left: 'small', right: 'xsmall' }}
direction="row"
>
<Box flex gap="small">
{title}
{children}
{footer}
</Box>
<Button
size="small"
icon={<Close size="small" />}
onClick={onClose} …
```
> add a check for is user has something inside of drop set to autofocus

- src/js/components/Drop/DropContainer.js
- src/js/components/Menu/Menu.js
Resolves an issue where drop positioning was not correctly flipping when there was not enough room to display in one direction.
See code comments in DropContainer for a more thorough explanation of what is happening. In cases where the drop has a smaller height than the target and the position is either `top: top` or `bottom: bottom` I decided to not try and flip the drop position. We can change this if we want. I just couldn't think of use cases where we would want this behavior.
This PR covers use cases where the drop doesn't have a scroll within it. Drops that do have a scroll within them don't respond well to the screen size adjusting. The work to address the issues with Drop position when they have a scroll will be handled as a separate issue/PR.
Tested with the existing stories …
> Fix drop positioning

- src/js/components/Box/__tests__/Box-style-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-style-test.tsx.snap
- src/js/components/Box/propTypes.js
- src/js/components/Box/stories/Border.js
- src/js/components/Grid/propTypes.js
- src/js/utils/border.js
- src/js/utils/general-prop-types.js
- src/js/utils/index.d.ts
This PR adds support for `borderImage` 
utilz/border.js
added a test and story
need for DS system
closes #7317 
yes
yes
> add support for border image

- src/js/components/Accordion/__tests__/Accordion-test.tsx
- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- src/js/components/AccordionPanel/AccordionPanel.js
Replaces useId in AccordionPanel because useId is only available in React 18 and we need to support react 16 and 17 as well.
This PR is targeted to merge into the react-compatibility branh so we can do a patch release from that branch
no
yes
> Accordion - Replace useId

- .circleci/config.yml
Update browser tools and temporarily freeze chrome version at 129 because v130 is causing problems with the tests failing on circleci because if a websocket connection issue
no
no
> Update circleci browser tools

- src/js/components/Drop/__tests__/Drop-test.tsx
Adds a test for https://github.com/grommet/grommet/pull/7324
no
no
> Added test for Drop trap focus

- src/js/components/Select/Select.js
- src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/Select/utils.js
- src/js/contexts/MessageContext/MessageContext.js
This PR adds a new function `formatValueForA11y` which uses both the value of the select option(s) and labelKey to extract a Human Readable value for the `aria-label` attribute. [9f986298af444e52777c404e99852fd008f6bd89]
~~Also, as a plus, Button tests were breaking. Updating the snapshot this was properly fixed. [3d5e88750fe4aa53decc992b03b1ba21281634d6]~~
- Start in the context that runs the replacements over at: [src/js/contexts/MessageContext/MessageContext](https://github.com/grommet/grommet/blob/9f986298af444e52777c404e99852fd008f6bd89/src/js/contexts/MessageContext/MessageContext.js)
- Then check `formatValueForA11y` at the [select utils](https://github.com/grommet/grommet/blob/9f986298af444e52777c404e99852fd008f6bd89/src/js/components/Select/utils.js)
- Used npm link to test the …
> Fix a11y aria-label for select

- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/components/List/__tests__/__snapshots__/List-test.tsx.snap
- src/js/components/Pagination/Pagination.js
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
Using the prop `cssGap`, I avoid using the StyledBoxGap element to add gaps between the elements. 
This was as per the Box component comment: 'an internal prop'.
[Pagination Component](https://github.com/grommet/grommet/blob/4a970d1eb0a176e072910d251f300d719e52552b/src/js/components/Pagination/Pagination.js)
Is also worth checking if cssGap should be added to the declarations file and docs.
- Used npm link to test the components in a test project
- Used Snapshots/Jest to test the output of the components
- Measure Pagination before/after pulling the branch. **Shouldn't have changed.**
- Avoid any extra customization to the component to get a proper measurement
- Fixes https://github.com/grommet/grommet/issues/7375
|![before](https://github.com/user-attachments/assets/852d0a2c-175c-4bd7-9bf …
> Fix using div gaps inside pagination lists

- src/js/components/DataTable/Body.js
- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
* It fixes the space key interaction for clickable Datatable rows.
* `src/js/components/DataTable/Body.js`
* Press `Space` key when row is selected.
* Closes #7335
* No.
* May be.
* It's backwards compatible.
> GH-7335: Fix space key interaction for clickable Datatable rows

- src/js/components/Box/StyledBox.js
- src/js/components/Button/StyledButton.js
- src/js/components/Button/__tests__/Button-kind-test.js
- src/js/components/Button/__tests__/Button-test.tsx
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.tsx.snap
- src/js/components/Tip/__tests__/__snapshots__/Tip-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
- src/js/utils/styles.js
This PR enhances Button theme to allow for `elevation` of a Button to be themed. This enhancement is specific to enabling the styling of the "bookend" within a "selected option" in a Select. Use of box-shadow to implement this styling is to avoid having to recalculate padding when this bookend is rendered (which would be necessary if implemented as a border).
Additionally, this will allow us to introduce a new elevation within grommet-theme-hpe called `inset-selected` (or something similar) which can be applied in the theme to `button.selected.option` as well as used by teams if they are composing custom Select option render via children or custom List items where one item might need to be indicated as "selected" (see screenshots and code examples below).
NOTE: With List, there is an …
> Enhance button theme with elevation

- src/js/components/Accordion/__tests__/__snapshots__/Accordion-test.tsx.snap
- src/js/components/AccordionPanel/AccordionPanel.js
- src/js/utils/index.js
- src/js/utils/useId.js
UPDATE: Tested with React 17.
The change we made to avoid React 18's `useId` #7351 has the downside that it makes test snapshots involving Accordions change randomly due to the randomly generated button ids. It also has a downside in that the id for an Accordion button changes every render.
This change instead creates a polyfill for React 18's `useId` which works much like their `useId` and stays consistent for tests and renders. If React 18 is being used, it will simply use the React `useId` implementation instead.
utils/useId.js
Basic testing with storybook and simulating React 18 being available. It could use a little more testing with the actual React 17 or 16.
Storybook accordion stories.
Backwards compatible although it can change existing snapshots.
> Polyfill useId rather than random id

- src/js/components/Accordion/__tests__/Accordion-test.tsx
Remove unnecessary date.now and random mocks in the Accordion tests
Remove unnecessary date.now and random mocks in the Accordion tests
With the addition of the useId() polyfill, Accordion no longer needs the mocks for Date.now() and random().
> Remove unused date/random mocks in the Accordion tests

- src/js/components/List/List.js
_Prevents_ `event.preventDefault();` from running in `List` component events if `onClickItem` or `onOrder` isn't defined.
- [List](https://github.com/grommet/grommet/blob/07811588d21e0be78dc89e5ec1a574e5c1b04ae5/src/js/components/List/List.js) component and the issues provided below. 
- Used npm link to test the components in a test project
- Used Snapshots/Jest to test the output of the components
- Fixes https://github.com/grommet/grommet/issues/7414
- Fixes https://github.com/grommet/grommet/issues/7362
- Shouldn't
> fix: check onClickItem or onOrder is defined before preventing event in List component

- src/js/components/Notification/Notification.js
- src/js/components/Notification/__tests__/Notification-test.tsx
- src/js/components/Notification/__tests__/__snapshots__/Notification-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Enhances Notification theme to allow status/kind-specific `message` and `title` colors. This will us to leverage our token color system where there will be specific `on` colors for text colors on status backgrounds. We won't need to leverage all of these combinations (the background/text colors for our global and inline notifications are the same-- only toast differs), but introducing them for consistency.
src/js/components/Notification/Notification.js
Locally, adjusted preview.js with the following:
```
import React, { useState, useEffect } from 'react';
import Root from 'react-shadow';
import { StyleSheetManager } from 'styled-components';
import { hpe } from 'grommet-theme-hpe';
import isChromatic from 'chromatic/isChromatic';
import { Grommet, grommet, hacktoberfest2022, Box, Text } …
```
> Enhance Notification theme for status/kind-specific `message` and `title` colors

- src/js/components/CheckBox/CheckBox.js
- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/SelectMultiple/SelectMultiple.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/SelectMultipleValue.js
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
Follow on to https://github.com/grommet/grommet/pull/7420, fixes the nested interactive issue for SelectMultiple
In addition to adding `inert` to the inputs within the drop button we also needed to add `inert` to the CheckBoxes because they are nested within a Button element. I also added `pointerEvents: 'none'` to the CheckBoxes to prevent an issue in FireFox where the click event was swallowed by the CheckBox instead of triggering the click event on the Button.
To add the `pointerEvents: 'none'` style onto the StyledCheckBoxContainer I needed to add containerProps onto CheckBox, for now leaving this as an internal only prop.
Normally we avoid inline styles but in this case it was the solution that felt like it was the most readable and least intrusive to the CheckBox component.
Check …
> Fix nested interactive issue for SelectMultiple

- src/js/components/DataTableColumns/__tests__/DataTableColumns-test.tsx
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
- src/js/components/List/List.js
- src/js/components/List/__tests__/List-test.tsx
- src/js/components/List/__tests__/__snapshots__/List-test.tsx.snap
Resolves the following accessibility issues with the List `onOrder` prop
Tested with existing List onOrder story and tested with voiceover
Check the accessibility tab on the List/onOrder story
Closes https://github.com/grommet/grommet/issues/7425
no
yes
> List - Fixed accessibility violations with `onOrder`

- src/js/components/Pagination/stories/CustomThemed/Custom.tsx
- src/js/components/Pagination/stories/NumberEdgePages.js
- src/js/components/Pagination/stories/NumberMiddlePages.js
- src/js/components/Pagination/stories/Simple.js
- src/js/components/Pagination/stories/Size.js
- src/js/components/Pagination/stories/Steps.js
adds an `aria-label` to the pagination
pagination/stories
yes storybook
storybook
The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable
no
no
yes
> fix pagination accessibility stories

- src/js/components/Tabs/stories/Scrollable.js
This PR fixes the scroll tabs story that was giving an accessibility error
scrollable.js
storybook
storybook
```
Serious
Element should have focusable content
Serious
Element should be focusable
```
fixes #7434 
no
no
> fix the scroll tab story for accessibility

- src/js/components/FormField/FormField.js
- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButton/stories/Children.js
- src/js/components/RadioButtonGroup/stories/Children.js
Added focus indicator to the radio button component.
I also changed the RadioButton/Children story to show how focus indicator could be implemented with custom children.
Closes https://github.com/grommet/grommet/issues/6328
no
yes
> Added focus indicator to RadioButton

- tools/release-stable.js
Remove git silent because it is deprecated
no
no
> remove git().silent because it is deprecated

- src/js/components/Box/__tests__/__snapshots__/Box-style-test.tsx.snap
- src/js/components/Button/__tests__/__snapshots__/Button-kind-test.js.snap
- src/js/components/Button/__tests__/__snapshots__/Button-test.tsx.snap
- src/js/components/Chart/__tests__/__snapshots__/Chart-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.tsx.snap
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.tsx.snap
- src/js/components/Grommet/__tests__/__snapshots__/Grommet-test.js.snap
- src/js/components/Notification/__tests__/__snapshots__/Notification-test.tsx.snap
- src/js/components/Text/__tests__/__snapshots__/Text-test.tsx.snap
- src/js/themes/__tests__/__snapshots__/theme-test.js.snap
- src/js/themes/base.js
This PR updates the `status` colors in our base theme.
| Color name | Previous value | Recommended value | Rationale |
|----|----|----|--|
| `status-ok` | `#00C781` | `#009E67` | Previous value had a contrast ratio of `2.02:1`. New value has `3.06:1`  and `5.5:1` in dark mode|
| `status-warning` | `#FFAA15` | `#C27B00` | Previous value had a contrast ratio of `1.77:1`. New value has `3.07:1` and `5.67:1` in dark mode |
| `status-unknown` | `#CCCCCC` | `#919191` | Previous value had a contrast ratio of `1.53:1`. New value has `3.01:1` and `5.84:1` in dark mode|
| `status-critical` | `#FF4040` | `#EB0000`* | No change proposed to this color in this Issue, as previous value had a passing contrast ratio of `3.06:1`. However, this color is proposed to be changed to meet 4,5:1 on white …
> update status colors to meet wcag

- src/js/components/Calendar/Calendar.js
- src/js/components/Calendar/StyledCalendar.js
- src/js/components/Calendar/__tests__/__snapshots__/Calendar-test.tsx.snap
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Updates the Calendar styling to meet accessibility requirements. Based on work done in https://github.com/grommet/grommet/issues/7423.
The `calendar.day.adjacent.color` theme prop was added because in the HPE theme we want the calendar dates outside of the month to be `text-weak` instead of `text-xweak`.
Open to naming suggestions on the theme prop. I went with the `adjacent` naming because this aligns with the `showAdjacentDays` prop on the Calendar component which controls if days outside of the month should be displayed or not.
https://github.com/grommet/grommet/issues/7467
yes
yes
backwards compatible because previously we weren't meeting WCAG AA contrast requirements
> Calendar style a11y updates

- package.json
- yarn.lock
Point to latest grommet-icons patch version.
> Update grommet-icons dependency

- src/js/components/Select/StyledSelect.js
- src/js/components/Select/__tests__/Select-test.js
- src/js/components/Select/__tests__/__snapshots__/Select-multiple-test.js.snap
- src/js/components/Select/__tests__/__snapshots__/Select-test.js.snap
- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/__tests__/SelectMultiple-test.tsx
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
This PR adds an extend to the theme for the "listbox" container directly surrounding the options. Open to naming suggestions, but things like "option.container" etc were already taken and apply to different things. "Listbox" is because this is the container with role="listbox".
Had to pass through `selectMultiple` as a prop on OptionsContainer so that the extend could differentiate between desired styling for Select vs SelectMultiple
src/js/components/Select/StyledSelect.js
Locally. Also added jest tests.
```
theme: {
select: {
listbox: {
extend: `padding: 24px;`,
},
},
selectMultiple: {
listbox: {
extend: `padding: 12px;`,
},
},
}
```
Yes.
Yes.
> Select, SelectMultiple -- Add extend to listbox

- src/js/components/Menu/Menu.js
- src/js/components/Menu/__tests__/Menu-test.js
- src/js/components/Menu/__tests__/__snapshots__/Menu-test.js.snap
- src/js/components/Menu/stories/CustomThemed/Themed.tsx
- src/js/themes/base.d.ts
- src/js/themes/base.js
This PR adds `theme.menu.container` which styles the Box directly surrounding the menu items. If menu groups are provided, then `theme.menu.group.container` will override theme.menu.container where appropriate.
src/js/components/Menu/Menu.js
Adjusted Custom Themed menu storybook.
Added jest test.
Yes.
Yes.
> Add `theme.menu.container`

- src/js/utils/styles.js
In https://github.com/grommet/grommet/pull/7479, the twoColor focus strategy was added to focusStyles but the mirrored adjustments were not made in unfocusStyles. This adds the necessary code to ensure focus styles are removed appropriately in the case of twoColor focus approach.
Locally
BEFORE (part of the two color focus still remained when interacting with mouse)
https://github.com/user-attachments/assets/ac7fd563-d22c-41c9-a40c-645968fb30bf
AFTER (focus does not appear when interacting with mouse)
https://github.com/user-attachments/assets/f7f53a9d-e481-492d-be0a-9589c79af4dc
twoColor focus still appears when interacting with keyboard
> Fix unFocusStyle for twoColor focus

- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilter/__tests__/__snapshots__/DataFilter-test.tsx.snap
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/DataSearch/__tests__/__snapshots__/DataSearch-test.tsx.snap
- src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-controlled.tsx.snap
- src/js/components/Form/__tests__/__snapshots__/Form-test-uncontrolled.tsx.snap
- src/js/components/FormField/FormField.js
- src/js/components/FormField/__tests__/FormField-test.tsx
- src/js/components/FormField/__tests__/__snapshots__/FormField-test.tsx.snap
- src/js/components/StarRating/__tests__/__snapshots__/StarRating-tests.tsx.snap
- src/js/components/ThumbsRating/__tests__/__snapshots__/ThumbsRating.tsx.snap
- src/js/components/Toolbar/__tests__/__snapshots__/Toolbar-test.js.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds an extend to the FormField container to style it differently based on the kind of child element (TextInput, TextArea, etc.).
Marking as a draft because I need to add the TS types and a jest test
Closes https://github.com/grommet/grommet/issues/7495
Yes
Yes
> Add extend to formfield container based on child input kind

- src/js/components/Box/__tests__/Box-test.tsx
- src/js/components/Box/__tests__/__snapshots__/Box-test.tsx.snap
- src/js/components/Layer/StyledLayer.js
- src/js/components/Meter/StyledMeter.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
- src/js/utils/responsive.js
- src/js/utils/styles.js
Adds `theme.global.radius` and `theme.global.breakpoint[size].radius` to allow for radius values to be styled independently from "edgeSize" (which controls gap, margin, pad).
Adjusts logic to fallback to "edgeSize" if theme.global.radius is not provided.
Add theme.global.radius and theme.global.breakpoint[size].radius
Locally by modifying base theme.
```
theme: {
global: {
breakpoint: {
small: {
radius: {
small: '2px',
},
},
},
radius: {
small: '38px',
},
}
```
Yes.
Yes.
> Add theme.global.radius and theme.global.breakpoint[size].radius

- package.json
- yarn.lock
Bumps grommet-icons dependency to 4.12.4 because 4.12.2 and 4.12.3 have a bug in them
no
yes
> Upgraded version of grommet-icons

- package.json
- yarn.lock
The hoist-non-react-statistics dependency was added in https://github.com/grommet/grommet/pull/2498 but we are no longer using it, so I removed it from package.json
no
maybe
> Remove unused dependency hoist-non-react-statics

- src/js/components/DateInput/DateInput.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
Fix disabled container style of DateInput
now
without additional
pass disabled props and check styles changed
closes #7527
no
yes
> DateInput apply disabled styles

- src/js/components/Menu/Menu.js
- src/js/components/Select/SelectContainer.js
- src/js/components/SelectMultiple/SelectMultipleContainer.js
In [this eslint upgrade PR](https://github.com/grommet/grommet/pull/7508) I removed comments that were disabling a lint rule in places where the rule wasn't being triggered. There were a few places I removed `eslint-disable-next-line react/no-array-index-key`. This PR adds comments to those places so we don't lose track of them even through they are not triggering eslint. See https://github.com/grommet/grommet/pull/7508/files#r1956535695 for more details.
> Add no array index as a key comments

- src/js/components/FileInput/__tests__/FileInput-test.tsx
- src/js/components/FileInput/__tests__/__snapshots__/FileInput-test.tsx.snap
Adds a test for the fix in https://github.com/grommet/grommet/pull/7512 to ensure the remove button is styled as disabled when the fileinput is disabled
no
no
> Add test for FileInput disabled when a file is already uploaded

- src/js/components/Box/StyledBox.js
- src/js/components/Box/__tests__/__snapshots__/Box-layout-test.tsx.snap
- src/js/components/Pagination/__tests__/__snapshots__/Pagination-test.tsx.snap
This PR fixes Box gap's which have been specified as an object to correctly have `@media` or `@container` styles which modify the gap at the small breakpoint like it would for a non-object gap.
StyledBox.js
Storybook
Storybook Layout/Box/Responsive Container
Fixes #7543 
No
Yes
> Fix css gap responsiveness

- src/js/components/Tip/Tip.js
- src/js/components/Tip/__tests__/Tip-test.tsx
This PR adds an event listener to the tooltip so that when a user clicks `escape` the tooltip will close
tip.js
storybook
open storybook of any of the tip stories and open in a new window then hover over tip and press `escape`
Tip is currently not passing these WCAG points for WCAG 1.4.13:
Dismissible
A [mechanism](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#dfn-mechanism) is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an [input error](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#dfn-input-error) or does not obscure or replace other content;
Part 1 of #7552 
no
yes
> add event listener to close tip on escape

- src/js/components/Avatar/Avatar.js
- src/js/components/Avatar/index.d.ts
- src/js/components/Avatar/propTypes.js
adds the `imageProps` prop to `Avatar` to add missing props for the `Image` used internally by `Avatar`
`Avatar.js`
manually tested with Storybook
Storybook
#6530
Yes
Yes
> add `imageProps` prop to `Avatar`

- src/js/components/MaskedInput/MaskedInput.js
- src/js/components/MaskedInput/__tests__/MaskedInput-test.tsx
- src/js/components/MaskedInput/__tests__/__snapshots__/MaskedInput-test.tsx.snap
- src/js/components/MaskedInput/stories/CustomBox.stories.js
- src/js/components/MaskedInput/stories/Date.stories.js
- src/js/components/MaskedInput/stories/DateRange.stories.js
- src/js/components/MaskedInput/stories/DateTimeDrop.stories.js
- src/js/components/MaskedInput/stories/Filtered.stories.js
- src/js/components/MaskedInput/stories/SizeUnits.stories.js
- src/js/components/MaskedInput/stories/Time.stories.js
- src/js/components/TextInput/stories/CustomThemed/CustomSuggestions.stories.tsx
- src/js/components/TextInput/stories/CustomThemed/Themed.stories.js
- src/js/components/TextInput/stories/OnSelect.stories.js
- src/js/components/TextInput/stories/WithTags.stories.js
Adds [`combobox`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/combobox_role) props to MaskedInput (similar to TextInput logic).
Slight modifications to the logic so that each mask section can appropriately inform screen reader if it's expanded.
According to ARIA documentation, an "id" is needed to associate the input with the combobox, so added "id" to the stories in MaskedInput and TextInput that involve the suggestions.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Roles/combobox_role
Locally in SizeUnits story with VoiceOver.
Same as above.
Closes #7573 
Yes. Fixed MaskedInput to support `combobox` aria properties for dropdown options.
> Add combobox props to MaskedInput with suggestions

- src/js/components/Drop/StyledDrop.js
This PR address that `tip.drop.margin` should take priority over `global.drop.margin` currently in our hpe theme we have `global.drop.margin` set as well as `intelligentMargin` so whats happening is those are being applied to Tip even though we have `tip.drop.margin` set to "none"
I have add the check that if `marginProp` is set to something then that should come before the adjustedMargin in the `marginStyle` function in Drop. 
styledDrop
locally 
locally 
in hpe theme you will see that the only margin being applied is the `theme.tip.content.margin` in which we will update this value in the hpe them to either `6px` or `9px` depending on discussion with designers. 
`margin` on the drop was causing the tooltip not to stay open as a user hovered from the target to the tooltip
closes #7552 …
> look at marginProp before setting adjustedMargin

- src/js/components/Data/__tests__/__snapshots__/Data-test.tsx.snap
- src/js/components/DataFilter/DataFilter.js
- src/js/components/DataSort/DataSort.js
- src/js/components/DataSort/__tests__/__snapshots__/DataSort-test.tsx.snap
- src/js/components/Select/Select.js
- src/js/components/Select/utils.js
- src/js/components/SelectMultiple/SelectMultiple.js
Ensures for Grommet components, we are properly associating form label + select input.
src/js/components/Select/utils.js
Locally in storybook
DataFilter before
DataFilter after
Related to #7646 
Yes.
Yes.
> Ensure DataSort and DataFilter properly associate form label + Select

- src/js/components/Data/index.d.ts
- src/js/components/Data/propTypes.js
- src/js/components/DataTableColumns/DataTableColumns.js
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
- src/js/components/Grommet/index.d.ts
- src/js/components/Grommet/propTypes.js
- src/js/components/List/List.js
- src/js/components/List/__tests__/List-test.tsx
- src/js/components/List/__tests__/__snapshots__/List-test.tsx.snap
- src/js/components/List/index.d.ts
- src/js/components/List/propTypes.js
- src/js/components/__tests__/__snapshots__/components-test.js.snap
- src/js/languages/default.json
Add `message` support for pinned List item. The use case the spurred this was for `pinned` columns in DataTableColumns, but since that is built with List it seemed appropriate to solve for it at the root component.
src/js/components/List/List.js
Locally in storybook.
Locally in storybook.
Closes #7644 
Yes.
Yes.
> Add `message` support for pinned List and DataTableColumns item

- src/js/components/SelectMultiple/SelectMultipleContainer.js
- src/js/components/SelectMultiple/__tests__/SelectMultiple-test.tsx
- src/js/components/SelectMultiple/__tests__/__snapshots__/SelectMultiple-test.tsx.snap
This PR resolves focus visibility bug on SelectMultiple by:
- Removing nested interactive elements (previously we had tabIndex="0" on the listbox and on any selected option inside the listbox).
- Switching to a roving tab index approach to ensure there's still only one-ish tab stop (see sub-bullets here) for the listbox and arrow keys are used to navigate among options)
- listbox has tabIndex="-1" (not in tab order)
- If nothing is selected, the first option has tabIndex="0"
- Using arrow keys updates the "active" option to tabIndex="0" and the rest to tabIndex="-1"
- NOTE: If an option is selected, it also remains part of the tab order. This is existing behavior that I didn't change, but it does mean that it's possible for the listbox to have more than one tab stop (which goes against …
> Update SelectMultiple to use roving tab index

- src/js/components/RangeSelector/EdgeControl.js
- src/js/components/RangeSelector/__tests__/RangeSelector-test.tsx
- src/js/components/RangeSelector/__tests__/__snapshots__/RangeSelector-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
This PR adds a theme value for the theme to allow users to pass a value for `edge` size
EdgeControl.js
locally and wrote a test 
pass in a value for `theme.rangeSelector?.edge?.size;`
The size needs to be at least 24X24 
right now we have it at 12X12 so we dont break the current size I have added a theme option for us to use in the hpe theme 
closes #7669 
yes
yes
> RangeSelector - add theme value for the edge size

- src/js/components/Box/Box.js
- src/js/components/Box/StyledBox.js
- src/js/components/DataFilters/__tests__/__snapshots__/DataFilters-test.tsx.snap
- src/js/components/DataTableColumns/__tests__/__snapshots__/DataTableColumns-test.tsx.snap
- src/js/components/List/List.js
- src/js/components/List/__tests__/List-test.tsx
- src/js/components/List/__tests__/__snapshots__/List-test.tsx.snap
This follows generally the same approach as https://github.com/grommet/grommet/pull/7682 with regards to making the mouse and keyboard navigation more independent and aligned to the WCAG APG pattern.
That said it also retains backwards compatible behavior for how `onActive` is documented on List component/how `active` would be passed to List with children. This required introducing a new state variable internal to List (`focused`, `setFocused`) to manage DOM focus.
List.js
Various list storybook examples
https://github.com/user-attachments/assets/4897762d-756e-4770-9101-97c92084b825
https://github.com/user-attachments/assets/8b41cd5a-b61e-40ea-ad61-03ee99ca89b5
https://github.com/user-attachments/assets/707c7880-4038-4f7c-bab2-f8c12fb48838
Storybook examples or locally.
Closes #7648 …
> List -- roving tab index approach 2

- src/js/components/Data/stories/StarWars.stories.js
- src/js/components/DataTable/stories/rowDetails.stories.js
This PR switches the two stories that use the StarWars api to use a more supported one.
The original `https://swapi.dev` we originally used no longer maintained and has an invalid certificate, preventing it from working in storybook. There is a `https://swapi.info` version of the API now available that is more supported. Unfortunately it doesn't support search or pagination. The examples still to search and pagination locally.
Storybook->Data->Data->StarWars
Storybook->Visualizations->DataTable->rowDetails
No
No
> switch to available star wars api

- src/js/components/Anchor/Anchor.js
- src/js/components/FileInput/FileInput.js
- src/js/components/FileInput/__tests__/__snapshots__/FileInput-test.tsx.snap
When FileInput is `disabled`, the internal "Browse" button/anchor should also be `disabled`. Currently, the functionality of the container disables them, but their visual and cursor styling isn't disabled. This fixes that.
Closes #7528
> Ensure all buttons and anchors in FileInput are disabled when input is

- src/js/components/DateInput/DateInput.js
- src/js/components/DateInput/__tests__/__snapshots__/DateInput-test.tsx.snap
- src/js/components/TextInput/CopyButton.js
- src/js/components/TextInput/TextInput.js
When DateInput is disabled, the calendar button in the input should also be `disabled` to avoid making it seem like the user can change the date.
Closes #7526
> DateInput — Ensure disabled applies to calendar button

- src/js/components/Layer/Layer.js
- src/js/components/Layer/__tests__/Layer-test.js
adds a test for this PR https://github.com/grommet/grommet/pull/7727
layer test
local testing
jest test 
the focus should be placed back on the trigger button when the layer is closed
none
no
no
> add test for pressing escape on layer

- src/js/components/Notification/Notification.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Notification component.
notification.js
yes
yes
> add notification theme object

- src/js/components/DataFilter/DataFilter.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the DataFilter component. Based on changes in https://github.com/grommet/grommet/pull/7591
> Add DataFilter theme objects

- src/js/components/Video/Video.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Video component. 
video.js
video.js
yes
yes
> add theme object for video

- src/js/components/DataSearch/DataSearch.js
- src/js/components/DataSort/DataSort.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the DataSearch and DataSort component. Based on changes in https://github.com/grommet/grommet/pull/7591
> add DataSearch and DataSort theme objects

- src/js/components/Paragraph/ParagraphSkeleton.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Paragraph component.
paragraph.js
yes
yes
> add paragraph theme object

- src/js/components/Nav/Nav.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Nav component.
nav.js
yes
yes
> add nav theme object

- src/js/components/Distribution/Distribution.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Distribution component. Based on changes in https://github.com/grommet/grommet/pull/7591
> Add Distribution theme objects

- src/js/components/DataTableColumns/DataTableColumns.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the DataTableColumns component. Based on changes in https://github.com/grommet/grommet/pull/7591
Note I removed `theme.dataTableColumns.tabs.justify` because i felt like we didn't need to add the justify prop to the theme for the t-shirt size changes
> Add DataTableColumns theme objects

- src/js/components/DataSummary/DataSummary.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the DataSummary component. Based on changes in https://github.com/grommet/grommet/pull/7591
> Add DataSummary theme objects

- src/js/components/Menu/Menu.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Menu component.
menu.js
yes
yes
> add menu theme object

- src/js/components/RadioButton/RadioButton.js
- src/js/components/RadioButtonGroup/RadioButtonGroup.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the RadioButton and RadioButtonGroup component. Based on changes in https://github.com/grommet/grommet/pull/7591
RadioButton.js
RadioButtonGroup.js
yes
yes
> add theme object radiobutton radiobuttongroup

- src/js/components/Sidebar/Sidebar.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Sidebar component.
sidebar.js
yes
yes
> add sidebar theme object

- src/js/components/DataFilters/DataFilters.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the dataFilters component.
dataFilters.js
yes
yes
> add datafilters theme object

- src/js/components/Pagination/Pagination.js
- src/js/components/Pagination/PaginationStep.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Pagination component. Based on changes in https://github.com/grommet/grommet/pull/7591
> Add Pagination theme objects

- src/js/components/Anchor/StyledAnchor.js
- src/js/components/Anchor/__tests__/__snapshots__/Anchor-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the Anchor component.
anchor.js
yes
yes
> add anchor theme object

- src/js/components/DataChart/DataChart.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Since grommet-theme-hpe is expanding the range of t-shirt sizes, need a way to redefine our desired granularities.
> Add theme support for `theme.dataChart.granularity.y`

- src/js/components/Tag/StyledTag.js
- src/js/components/Tag/stories/OnClick.stories.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Add theme support for `theme.tag.hover` (background and border) when `onClick` is applied.
There have been some design discussions around potential Tag style changes for HPE theme. This won't be part of the initial landmark release, but might be a modification in future once more discussion has been had.
So while nothing has been "settled", I wanted to make sure Grommet was in a place to support the style updates if needed (and not require a peerDependency bump again in the theme).
Included a storybook example with the potential desired styles.
https://github.com/user-attachments/assets/0fed83ca-e98c-4a0e-b0cb-21cd921bdffe
Yes.
Yes.
> Add `theme.tag.hover` support

- src/js/components/Box/StyledBox.js
- src/js/themes/base.d.ts
- src/js/themes/base.js
Change `box.border.size` to `box.border.offset` because this naming more accurately reflects it's usage
Backwards compatible (this hasn't been released yet)
> Rename box.border.size to box.border.offset

- src/js/components/DataTable/Resizer.js
- src/js/components/DataTable/__tests__/DataTable-test.tsx
- src/js/components/DataTable/__tests__/__snapshots__/DataTable-test.tsx.snap
- src/js/themes/base.d.ts
- src/js/themes/base.js
Adds theme objects for the DataTable resizer margin and padding.
I adjusted the margin from -12px to -11px because the border was sometimes getting cut off since the resizer has 24px width and the border is 1px. We want the center of the resizer to align with the edge of the cell. So we divide the resizer width by 2 and subtract 1 to account for the border width. The -11px margin-right value means that the border ends up at the edge of the cell and doesn't get cut off.
Yes, theme props should be marked as beta
> DataTable - add resizer theme objects for t-shirt values
